"""ABConnect API models package.

Auto-generated from swagger.json specification.
Contains Pydantic models for all API schemas.
"""

# Import base and enums first as they don't have dependencies
from .base import *
from .enums import *

# Lazy loading function to avoid circular imports
_MODELS = {}

def __getattr__(name):
    """Lazy load models to avoid circular imports."""
    if name in _MODELS:
        return _MODELS[name]

    # Map of model names to their modules (auto-generated from swagger.json)
    module_map = {
        'AcceptModel': 'rfq',
        'AccesorialCharges': 'shared',
        'Address': 'address',
        'AddressData': 'address',
        'AddressDetails': 'address',
        'AddressDetailsMergePreviewDataItem': 'address',
        'AddressIsValidResult': 'address',
        'AdvancedSettingsEntitySaveModel': 'advancedsettings',
        'AttachCustomerBankModel': 'jobpayment',
        'AutoCompleteValue': 'shared',
        'Base64File': 'shared',
        'BaseContactDetails': 'contacts',
        'BaseInfoCalendar': 'calendar',
        'BaseInfoCalendarJob': 'job',
        'BaseTask': 'shared',
        'BaseTaskModel': 'jobtimeline',
        'BookShipmentRequest': 'jobshipment',
        'BookShipmentSpecificParams': 'shared',
        'Calendar': 'calendar',
        'CalendarAddress': 'address',
        'CalendarContact': 'contacts',
        'CalendarItem': 'shared',
        'CalendarJob': 'job',
        'CalendarNotes': 'shared',
        'CalendarTask': 'shared',
        'CarrierAccountInfo': 'shared',
        'CarrierErrorMessage': 'carriererrormessage',
        'CarrierInfo': 'shared',
        'CarrierProviderMessage': 'shared',
        'CarrierRateModel': 'shared',
        'CarrierTask': 'jobtimeline',
        'CarrierTaskModel': 'shared',
        'ChangeJobAgentRequest': 'job',
        'ChangePasswordModel': 'account',
        'Commodity': 'shared',
        'Company': 'companies',
        'CompanyAddressInfo': 'companies',
        'CompanyDetails': 'companies',
        'CompanyDetailsBaseInfo': 'companies',
        'CompanyDetailsFinalMileTariffItem': 'companies',
        'CompanyDetailsInsurancePricing': 'companies',
        'CompanyDetailsPreferences': 'companies',
        'CompanyDetailsServicePricings': 'companies',
        'CompanyDetailsTaxPricing': 'companies',
        'CompanyHierarchyInfo': 'globalsettings',
        'CompanyImageData': 'companies',
        'CompanyInfo': 'companies',
        'CompanyInsurancePricing': 'companies',
        'CompanyListItem': 'jobtimeline',
        'CompanyServicePricing': 'companies',
        'CompanySetupData': 'companysettings',
        'CompanyTaxPricing': 'companies',
        'ConfirmEmailModel': 'account',
        'Contact': 'contacts',
        'ContactAddressDetails': 'contacts',
        'ContactAddressEditDetails': 'contacts',
        'ContactDetailedInfo': 'contacts',
        'ContactDetails': 'contacts',
        'ContactDetailsCompanyInfo': 'companies',
        'ContactEmailDetails': 'contacts',
        'ContactEmailEditDetails': 'contacts',
        'ContactHistoryAggregatedCost': 'contacthistory',
        'ContactHistoryDataSourceLoadOptions': 'contacthistory',
        'ContactHistoryGraphData': 'contacthistory',
        'ContactHistoryInfo': 'contacthistory',
        'ContactHistoryPricePerPound': 'contacts',
        'ContactHistoryRevenueSum': 'contacts',
        'ContactPhoneDetails': 'contacts',
        'ContactPhoneEditDetails': 'contacts',
        'ContactPrimaryDetails': 'contacts',
        'ContactTypeEntity': 'lookup',
        'ContainerThickness': 'containerthicknessinches',
        'CountryCodeDto': 'lookup',
        'CreateJobIntacctModel': 'jobintacct',
        'CreateScheduledJobEmailResponse': 'job',
        'CreateUserModel': 'users',
        'CreatedTask': 'shared',
        'CustomerInfo': 'shared',
        'DeleteShipRequestModel': 'jobshipment',
        'DeleteTaskResponse': 'jobtimeline',
        'Details': 'shared',
        'DocumentDetails': 'shared',
        'DocumentUpdateModel': 'documents',
        'EmailDetails': 'shared',
        'EstesAccountData': 'shared',
        'ExportPackingInfo': 'shared',
        'ExportTotalCosts': 'shared',
        'ExpressFreightDetail': 'shared',
        'ExtendedOnHoldInfo': 'jobonhold',
        'FedExAccountData': 'shared',
        'FedExRestApiAccount': 'shared',
        'FedExSpecific': 'shared',
        'FeedbackSaveModel': 'job',
        'ForgotLoginModel': 'account',
        'FormsShipmentPlan': 'jobform',
        'ForwardAirAccountData': 'shared',
        'FranchiseeCarrierAccounts': 'shared',
        'FreightRateRequestAddressDetails': 'address',
        'FreightShimpment': 'job',
        'GlobalTranzAccountData': 'shared',
        'GridSettingsEntity': 'dashboard',
        'GridViewAccess': 'gridviews',
        'GridViewDetails': 'gridviews',
        'GroupingInfo': 'shared',
        'HandlingUnitModel': 'shared',
        'InTheFieldTaskModel': 'shared',
        'InboundNewDashboardItem': 'dashboard',
        'IncrementJobStatusInputModel': 'dashboard',
        'IncrementJobStatusResponseModel': 'dashboard',
        'InhouseNewDashboardItem': 'dashboard',
        'InitialNoteModel': 'shared',
        'InsuranceOption': 'shared',
        'InsuranceReport': 'reports',
        'InsuranceReportRequest': 'reports',
        'InternationalParams': 'jobshipment',
        'ItemPhotoUploadRequest': 'document_upload',
        'ItemPhotoUploadResponse': 'document_upload',
        'ItemTotals': 'shared',
        'Items': 'shared',
        'JToken': 'shared',
        'JobCarrierRatesModel': 'jobshipment',
        'JobContactDetails': 'job',
        'JobExportData': 'job',
        'JobItemNotesData': 'job',
        'JobParcelAddOn': 'jobshipment',
        'JobSaveRequest': 'job',
        'JobSaveRequestModel': 'job',
        'JobTaskNote': 'jobnote',
        'JobTrackingResponseV3': 'jobtrackingv3',
        'LaborCharges': 'shared',
        'LastObtainNFM': 'shared',
        'LatLng': 'shared',
        'LocalDeliveriesNewDashboardItem': 'dashboard',
        'LookupItem': 'shared',
        'LookupKeys': 'lookup',
        'LookupValue': 'lookup',
        'MasterMaterials': 'shared',
        'MergeContactsPreviewInfo': 'contactmerge',
        'MergeContactsPreviewRequestModel': 'contactmerge',
        'MergeContactsRequestModel': 'contactmerge',
        'MergeContactsSearchRequestModel': 'contacts',
        'MergeContactsSearchRequestParameters': 'contacts',
        'NameValueEntity': 'shared',
        'NoteModel': 'note',
        'Notes': 'note',
        'ObtainNFMParcelItem': 'shared',
        'ObtainNFMParcelService': 'shared',
        'OnHoldDetails': 'jobonhold',
        'OnHoldNoteDetails': 'jobonhold',
        'OnHoldUser': 'jobonhold',
        'OnlinePaymentSettings': 'shared',
        'OutboundNewDashboardItem': 'dashboard',
        'OverridableAddressData': 'address',
        'PackagingLaborHours': 'shared',
        'PackagingLaborSettings': 'companies',
        'PackagingTariffSettings': 'companies',
        'PageOrderedRequestModel': 'shared',
        'ParcelItem': 'jobparcelitems',
        'ParcelItemWithPackage': 'jobparcelitems',
        'PaymentSourceDetails': 'jobpayment',
        'PhoneDetails': 'shared',
        'PickupLaborHoursRule': 'shared',
        'PilotAccountData': 'shared',
        'PlannerAddress': 'address',
        'PlannerContact': 'contacts',
        'PlannerLabor': 'shared',
        'PlannerTask': 'planner',
        'PricedFreightProvider': 'jobfreightproviders',
        'QuoteRequestComment': 'shared',
        'QuoteRequestDisplayInfo': 'jobrfq',
        'RecentEstimatesNewDashboardItem': 'dashboard',
        'ReferredByReport': 'reports',
        'ReferredByReportRequest': 'reports',
        'RegistrationModel': 'account',
        'RequestedParcelPackaging': 'shared',
        'ResetPasswordModel': 'account',
        'ResolveJobOnHoldResponse': 'jobonhold',
        'RevenueCustomer': 'reports',
        'RoadRunnerAccountData': 'shared',
        'RoyaltiesCharges': 'shared',
        'SalesForecastReport': 'reports',
        'SalesForecastReportRequest': 'reports',
        'SalesForecastSummary': 'reports',
        'SalesForecastSummaryRequest': 'reports',
        'SaveEntityResponse': 'truck',
        'SaveGeoSettingModel': 'companies',
        'SaveGridSettingsModel': 'dashboard',
        'SaveOnHoldDatesModel': 'jobonhold',
        'SaveOnHoldRequest': 'jobonhold',
        'SaveOnHoldResponse': 'jobonhold',
        'SaveResponseModel': 'jobtimeline',
        'SaveTruckRequest': 'truck',
        'SaveValidatedRequest': 'address',
        'SearchAddress': 'address',
        'SearchCompanyDataSourceLoadOptions': 'companies',
        'SearchCompanyModel': 'companies',
        'SearchCompanyResponse': 'companies',
        'SearchContactEntityResult': 'contacts',
        'SearchContactRequest': 'contacts',
        'SearchCustomerInfo': 'shared',
        'SearchJobFilter': 'job',
        'SearchJobInfo': 'job',
        'SelectApproveInsuranceResult': 'globalsettings',
        'SendDocumentEmailModel': 'jobemail',
        'SendSMSModel': 'jobsms',
        'ServiceBaseResponse': 'jobfreightproviders',
        'ServiceInfo': 'shared',
        'ServicePricingsMarkup': 'shared',
        'ServiceWarningResponse': 'truck',
        'SetRateModel': 'jobfreightproviders',
        'ShipmentContactAddressDetails': 'contacts',
        'ShipmentContactDetails': 'contacts',
        'ShipmentDetails': 'shipment',
        'ShipmentOriginDestination': 'jobshipment',
        'ShipmentPlanProvider': 'jobfreightproviders',
        'ShipmentTrackingDetails': 'jobtracking',
        'ShipmentTrackingDocument': 'shared',
        'ShippingDocument': 'shipment',
        'ShippingHistoryStatus': 'shared',
        'ShippingPackageInfo': 'shared',
        'SimplePriceTariff': 'shared',
        'SimpleTaskModel': 'shared',
        'SmsTemplateModel': 'jobsmstemplate',
        'SoldToAddress': 'address',
        'SoldToDetails': 'shared',
        'SortBy': 'shared',
        'SortByModel': 'shared',
        'SortingInfo': 'shared',
        'StoredProcedureColumn': 'shared',
        'StringMergePreviewDataItem': 'shared',
        'StringOverridable': 'shared',
        'SuggestedContactEntity': 'note',
        'SummaryInfo': 'shared',
        'TagBoxDataSourceLoadOptions': 'companies',
        'TaskNoteModel': 'jobnote',
        'TaskTruckInfo': 'shared',
        'TaxOption': 'shared',
        'TeamWWAccountData': 'shared',
        'TimeLog': 'shared',
        'TimeLogModel': 'shared',
        'TimeLogPause': 'shared',
        'TimeLogPauseModel': 'shared',
        'TimeSpan': 'shared',
        'TimelineResponse': 'jobtimeline',
        'TrackingCarrierProps': 'shared',
        'TrackingStatusV2': 'shared',
        'TransferModel': 'job',
        'TransportationCharges': 'shared',
        'TransportationRatesRequest': 'shared',
        'TransportationRatesRequestModel': 'jobshipment',
        'Truck': 'truck',
        'TwilioSmsStatusCallback': 'twiliowebhook',
        'UPSAccountData': 'shared',
        'UPSSpecific': 'shared',
        'USPSAccountData': 'shared',
        'USPSSpecific': 'shared',
        'UndoIncrementJobStatusInputModel': 'dashboard',
        'UpdateCarrierAccountsModel': 'companies',
        'UpdateDateModel': 'shared',
        'UpdateTaskModel': 'jobtimeline',
        'UpdateTruckModel': 'shared',
        'UploadedFile': 'document_upload',
        'UserInfo': 'users',
        'Users': 'users',
        'VerifyBankAccountRequest': 'jobpayment',
        'Web2LeadReport': 'reports',
        'Web2LeadRevenueFilter': 'reports',
        'Web2LeadV2RequestModel': 'reports',
        'WebApiDataSourceLoadOptions': 'companies',
        'WeightInfo': 'shared',
        'WorkTimeLog': 'shared',
        'WorkTimeLogModel': 'shared',
    }

    if name in module_map:
        module_name = module_map[name]
        # Import the module
        import importlib
        module = importlib.import_module(f'.{module_name}', package='ABConnect.api.models')
        # Get the model from the module
        model = getattr(module, name)
        # Cache it
        _MODELS[name] = model
        return model

    raise AttributeError(f"module 'ABConnect.api.models' has no attribute '{name}'")

# Rebuild models after all are defined (called when needed)
def rebuild_models():
    """Rebuild all Pydantic models to resolve forward references."""
    # Import all model modules
    import importlib
    modules_to_rebuild = [
        'account', 'address', 'companies', 'contacts', 'job',
        'jobform', 'jobpayment', 'jobshipment', 'documents',
        'users', 'dashboard', 'reports', 'lookup'
    ]

    for module_name in modules_to_rebuild:
        try:
            module = importlib.import_module(f'.{module_name}', package='ABConnect.api.models')
            # Call model_rebuild on all Pydantic models in the module
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if hasattr(attr, 'model_rebuild'):
                    try:
                        attr.model_rebuild()
                    except:
                        pass  # Some models might not need rebuilding
        except ImportError:
            pass  # Module might not exist