# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AggregationScheduleEnum(object):

    """Implementation of the 'aggregationSchedule' enum.

    Attributes:
        HOURS: Hourly schedule.
        DAYS: Daily schedule.
        WEEKS: Weekly schedule.
        MONTHS: Monthly schedule.
        YEARS: Annual schedule.

    """
    _all_values = ['hours', 'days', 'weeks', 'months', 'years']
    HOURS = 'hours'

    DAYS = 'days'

    WEEKS = 'weeks'

    MONTHS = 'months'

    YEARS = 'years'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   