# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper
from payrix.models.alert_actions_post_request import AlertActionsPostRequest
from payrix.models.alert_triggers_post_request import AlertTriggersPostRequest


class AlertsPostRequest(object):

    """Implementation of the 'alertsPostRequest' model.

    Attributes:
        login (str): The Login that owns this resource.
        forlogin (str): The identifier of the Login that this Alert relates
            to.  The Alert is triggered based on the activity of this Login.
        team (str | TeamsPostRequest | None): The model property of type str |
            TeamsPostRequest | None.
        division (str): The division for which this Alerts applies.
        partition (str): The partition for which this Alerts applies.
        name (str): The name of this Alert.  This field is stored as a text
            string and must be between 1 and 100 characters long.
        description (str): Description of Alerts.
        alert_actions (List[AlertActionsPostRequest]): The model property of
            type List[AlertActionsPostRequest].
        alert_triggers (List[AlertTriggersPostRequest]): The model property of
            type List[AlertTriggersPostRequest].
        inactive (InactiveEnum): Whether this resource is marked as inactive. 
            <details> <summary>Valid Values</summary>  - `0` - **Active** -
            `1` - **Inactive**  </details>
        frozen (FrozenEnum): Whether this resource is marked as frozen. 
            <details> <summary>Valid Values</summary>  - `0` - **Not Frozen**
            - `1` - **Frozen**  </details>

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "login": 'login',
        "forlogin": 'forlogin',
        "team": 'team',
        "division": 'division',
        "partition": 'partition',
        "name": 'name',
        "description": 'description',
        "alert_actions": 'alertActions',
        "alert_triggers": 'alertTriggers',
        "inactive": 'inactive',
        "frozen": 'frozen'
    }

    _optionals = [
        'forlogin',
        'team',
        'division',
        'partition',
        'name',
        'description',
        'alert_actions',
        'alert_triggers',
        'inactive',
        'frozen',
    ]

    def __init__(self,
                 login=None,
                 forlogin=APIHelper.SKIP,
                 team=APIHelper.SKIP,
                 division=APIHelper.SKIP,
                 partition=APIHelper.SKIP,
                 name=APIHelper.SKIP,
                 description=APIHelper.SKIP,
                 alert_actions=APIHelper.SKIP,
                 alert_triggers=APIHelper.SKIP,
                 inactive=0,
                 frozen=0):
        """Constructor for the AlertsPostRequest class"""

        # Initialize members of the class
        self.login = login 
        if forlogin is not APIHelper.SKIP:
            self.forlogin = forlogin 
        if team is not APIHelper.SKIP:
            self.team = team 
        if division is not APIHelper.SKIP:
            self.division = division 
        if partition is not APIHelper.SKIP:
            self.partition = partition 
        if name is not APIHelper.SKIP:
            self.name = name 
        if description is not APIHelper.SKIP:
            self.description = description 
        if alert_actions is not APIHelper.SKIP:
            self.alert_actions = alert_actions 
        if alert_triggers is not APIHelper.SKIP:
            self.alert_triggers = alert_triggers 
        self.inactive = inactive 
        self.frozen = frozen 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from payrix.utilities.union_type_lookup import UnionTypeLookUp

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        login = dictionary.get("login") if dictionary.get("login") else None
        forlogin = dictionary.get("forlogin") if dictionary.get("forlogin") else APIHelper.SKIP
        team = APIHelper.deserialize_union_type(UnionTypeLookUp.get('AlertsPostRequestTeam'), dictionary.get('team'), False) if dictionary.get('team') is not None else APIHelper.SKIP
        division = dictionary.get("division") if dictionary.get("division") else APIHelper.SKIP
        partition = dictionary.get("partition") if dictionary.get("partition") else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        alert_actions = None
        if dictionary.get('alertActions') is not None:
            alert_actions = [AlertActionsPostRequest.from_dictionary(x) for x in dictionary.get('alertActions')]
        else:
            alert_actions = APIHelper.SKIP
        alert_triggers = None
        if dictionary.get('alertTriggers') is not None:
            alert_triggers = [AlertTriggersPostRequest.from_dictionary(x) for x in dictionary.get('alertTriggers')]
        else:
            alert_triggers = APIHelper.SKIP
        inactive = dictionary.get("inactive") if dictionary.get("inactive") else 0
        frozen = dictionary.get("frozen") if dictionary.get("frozen") else 0
        # Return an object of this model
        return cls(login,
                   forlogin,
                   team,
                   division,
                   partition,
                   name,
                   description,
                   alert_actions,
                   alert_triggers,
                   inactive,
                   frozen)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(value=dictionary.login,
                                           type_callable=lambda value: isinstance(value, str))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(value=dictionary.get('login'),
                                       type_callable=lambda value: isinstance(value, str))

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'login={self.login!r}, '
                f'forlogin={(self.forlogin if hasattr(self, "forlogin") else None)!r}, '
                f'team={(self.team if hasattr(self, "team") else None)!r}, '
                f'division={(self.division if hasattr(self, "division") else None)!r}, '
                f'partition={(self.partition if hasattr(self, "partition") else None)!r}, '
                f'name={(self.name if hasattr(self, "name") else None)!r}, '
                f'description={(self.description if hasattr(self, "description") else None)!r}, '
                f'alert_actions={(self.alert_actions if hasattr(self, "alert_actions") else None)!r}, '
                f'alert_triggers={(self.alert_triggers if hasattr(self, "alert_triggers") else None)!r}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!r}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'login={self.login!s}, '
                f'forlogin={(self.forlogin if hasattr(self, "forlogin") else None)!s}, '
                f'team={(self.team if hasattr(self, "team") else None)!s}, '
                f'division={(self.division if hasattr(self, "division") else None)!s}, '
                f'partition={(self.partition if hasattr(self, "partition") else None)!s}, '
                f'name={(self.name if hasattr(self, "name") else None)!s}, '
                f'description={(self.description if hasattr(self, "description") else None)!s}, '
                f'alert_actions={(self.alert_actions if hasattr(self, "alert_actions") else None)!s}, '
                f'alert_triggers={(self.alert_triggers if hasattr(self, "alert_triggers") else None)!s}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!s}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!s})')
