# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AutoCloseEnum(object):

    """Implementation of the 'AutoClose' enum.

    Attributes:
        AUTOMATIC: The terminal is automatically closed for the day.
        MANUAL: The terminal is manually closed for the day.
        NONE: No auto-close behavior is set for the terminal.

    """
    _all_values = [0, 1, 2]
    AUTOMATIC = 0

    MANUAL = 1

    ENUM_NONE = 2

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   