# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CollectionFactorEnum(object):

    """Implementation of the 'CollectionFactor' enum.

    Attributes:
        DAYS: Multiplier based on days.
        WEEKS: Multiplier based on weeks.
        MONTHS: Multiplier based on months.
        YEARS: Multiplier based on years.

    """
    _all_values = ['days', 'weeks', 'months', 'years']
    DAYS = 'days'

    WEEKS = 'weeks'

    MONTHS = 'months'

    YEARS = 'years'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   