# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ConfigurationStageMethodEnum(object):

    """Implementation of the 'configurationStageMethod' enum.

    Attributes:
        SFTPUPLOAD: SFtpUpload. Use sftp to Upload.
        SFTPDOWNLOAD: sftpDownload. Use sftp to Download.
        POST: POST. Use a post request.
        GET: GET. Use a get request.
        PUT: PUT. Use a put request.
        DELETE: DELETE. Use a delete request.
        TCP: TCP. Use tcp protocol.

    """
    _all_values = ['sftpUpload', 'sftpDownload', 'post', 'get', 'put', 'delete', 'tcp']
    SFTPUPLOAD = 'sftpUpload'

    SFTPDOWNLOAD = 'sftpDownload'

    POST = 'post'

    GET = 'get'

    PUT = 'put'

    DELETE = 'delete'

    TCP = 'tcp'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   