# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CvvStatusEnum(object):

    """Implementation of the 'CvvStatus' enum.

    Attributes:
        NOTPRESENT: CVV is not present.
        ILLEGIBLE: CVV is illegible.
        NOTPROVIDED: CVV was not provided.

    """
    _all_values = ['notPresent', 'illegible', 'notProvided']
    NOTPRESENT = 'notPresent'

    ILLEGIBLE = 'illegible'

    NOTPROVIDED = 'notProvided'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   