# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FeeCollectionEnum(object):

    """Implementation of the 'feeCollection' enum.

    Attributes:
        TXN: The total amount of all transactions.
        TXNTAXID: The total amount of all transactions per entity EIN/tax ID.
        TXNMERCHANT: The total amount of all transactions per entity.

    """
    _all_values = [1, 2, 3]
    TXN = 1

    TXNTAXID = 2

    TXNMERCHANT = 3

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   