# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper
from payrix.models.entity_reserves_response import EntityReservesResponse
from payrix.models.entries_response import EntriesResponse
from payrix.models.fund_origins_response import FundOriginsResponse
from payrix.models.reserve_entries_response import ReserveEntriesResponse


class FundsResponse(object):

    """Implementation of the 'fundsResponse' model.

    Attributes:
        id (str): The ID of this resource.
        created (str): The date and time at which this resource was created.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        modified (str): The date and time at which this resource was modified.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        creator (str | LoginsResponse | None): The model property of type str
            | LoginsResponse | None.
        modifier (str): The identifier of the Login that last modified this
            resource.
        entity (str | EntitiesResponse | None): The model property of type str
            | EntitiesResponse | None.
        currency (CurrencyEnum): The currency of the Fund.
        reserved (float): The amount held in this Fund that is marked as
            reserved, This field is specified in cents(up to three decimal
            points). See <a href="https://www.iban.com/currency-codes"
            target="_blank">Currency codes</a>  for all valid values.
        pending (float): The current funds pending for the entity, This field
            is specified in cents(up to three decimal points)
        available (float): The amount held in this Fund that is currently
            available for disbursement, This field is specified in cents(up to
            three decimal points).
        total (float): The total amount held in this Fund, This field is
            specified in cents(up to three decimal points).
        inactive (InactiveEnum): Whether this resource is marked as inactive. 
            <details> <summary>Valid Values</summary>  - `0` - **Active** -
            `1` - **Inactive**  </details>
        frozen (FrozenEnum): Whether this resource is marked as frozen. 
            <details> <summary>Valid Values</summary>  - `0` - **Not Frozen**
            - `1` - **Frozen**  </details>
        entity_reserves (List[EntityReservesResponse]): The model property of
            type List[EntityReservesResponse].
        entries (List[EntriesResponse]): The model property of type
            List[EntriesResponse].
        reserve_entries (List[ReserveEntriesResponse]): The model property of
            type List[ReserveEntriesResponse].
        fund_origins (List[FundOriginsResponse]): The model property of type
            List[FundOriginsResponse].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "created": 'created',
        "modified": 'modified',
        "creator": 'creator',
        "modifier": 'modifier',
        "entity": 'entity',
        "currency": 'currency',
        "reserved": 'reserved',
        "pending": 'pending',
        "available": 'available',
        "total": 'total',
        "inactive": 'inactive',
        "frozen": 'frozen',
        "entity_reserves": 'entityReserves',
        "entries": 'entries',
        "reserve_entries": 'reserveEntries',
        "fund_origins": 'fundOrigins'
    }

    _optionals = [
        'id',
        'created',
        'modified',
        'creator',
        'modifier',
        'entity',
        'currency',
        'reserved',
        'pending',
        'available',
        'total',
        'inactive',
        'frozen',
        'entity_reserves',
        'entries',
        'reserve_entries',
        'fund_origins',
    ]

    _nullables = [
        'currency',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 created=APIHelper.SKIP,
                 modified=APIHelper.SKIP,
                 creator=APIHelper.SKIP,
                 modifier=APIHelper.SKIP,
                 entity=APIHelper.SKIP,
                 currency=APIHelper.SKIP,
                 reserved=APIHelper.SKIP,
                 pending=APIHelper.SKIP,
                 available=APIHelper.SKIP,
                 total=APIHelper.SKIP,
                 inactive=0,
                 frozen=0,
                 entity_reserves=APIHelper.SKIP,
                 entries=APIHelper.SKIP,
                 reserve_entries=APIHelper.SKIP,
                 fund_origins=APIHelper.SKIP):
        """Constructor for the FundsResponse class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if created is not APIHelper.SKIP:
            self.created = created 
        if modified is not APIHelper.SKIP:
            self.modified = modified 
        if creator is not APIHelper.SKIP:
            self.creator = creator 
        if modifier is not APIHelper.SKIP:
            self.modifier = modifier 
        if entity is not APIHelper.SKIP:
            self.entity = entity 
        if currency is not APIHelper.SKIP:
            self.currency = currency 
        if reserved is not APIHelper.SKIP:
            self.reserved = reserved 
        if pending is not APIHelper.SKIP:
            self.pending = pending 
        if available is not APIHelper.SKIP:
            self.available = available 
        if total is not APIHelper.SKIP:
            self.total = total 
        self.inactive = inactive 
        self.frozen = frozen 
        if entity_reserves is not APIHelper.SKIP:
            self.entity_reserves = entity_reserves 
        if entries is not APIHelper.SKIP:
            self.entries = entries 
        if reserve_entries is not APIHelper.SKIP:
            self.reserve_entries = reserve_entries 
        if fund_origins is not APIHelper.SKIP:
            self.fund_origins = fund_origins 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from payrix.utilities.union_type_lookup import UnionTypeLookUp

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        created = dictionary.get("created") if dictionary.get("created") else APIHelper.SKIP
        modified = dictionary.get("modified") if dictionary.get("modified") else APIHelper.SKIP
        creator = APIHelper.deserialize_union_type(UnionTypeLookUp.get('FundsResponseCreator'), dictionary.get('creator'), False) if dictionary.get('creator') is not None else APIHelper.SKIP
        modifier = dictionary.get("modifier") if dictionary.get("modifier") else APIHelper.SKIP
        entity = APIHelper.deserialize_union_type(UnionTypeLookUp.get('FundsResponseEntity'), dictionary.get('entity'), False) if dictionary.get('entity') is not None else APIHelper.SKIP
        currency = dictionary.get("currency") if "currency" in dictionary.keys() else APIHelper.SKIP
        reserved = dictionary.get("reserved") if dictionary.get("reserved") else APIHelper.SKIP
        pending = dictionary.get("pending") if dictionary.get("pending") else APIHelper.SKIP
        available = dictionary.get("available") if dictionary.get("available") else APIHelper.SKIP
        total = dictionary.get("total") if dictionary.get("total") else APIHelper.SKIP
        inactive = dictionary.get("inactive") if dictionary.get("inactive") else 0
        frozen = dictionary.get("frozen") if dictionary.get("frozen") else 0
        entity_reserves = None
        if dictionary.get('entityReserves') is not None:
            entity_reserves = [EntityReservesResponse.from_dictionary(x) for x in dictionary.get('entityReserves')]
        else:
            entity_reserves = APIHelper.SKIP
        entries = None
        if dictionary.get('entries') is not None:
            entries = [EntriesResponse.from_dictionary(x) for x in dictionary.get('entries')]
        else:
            entries = APIHelper.SKIP
        reserve_entries = None
        if dictionary.get('reserveEntries') is not None:
            reserve_entries = [ReserveEntriesResponse.from_dictionary(x) for x in dictionary.get('reserveEntries')]
        else:
            reserve_entries = APIHelper.SKIP
        fund_origins = None
        if dictionary.get('fundOrigins') is not None:
            fund_origins = [FundOriginsResponse.from_dictionary(x) for x in dictionary.get('fundOrigins')]
        else:
            fund_origins = APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   created,
                   modified,
                   creator,
                   modifier,
                   entity,
                   currency,
                   reserved,
                   pending,
                   available,
                   total,
                   inactive,
                   frozen,
                   entity_reserves,
                   entries,
                   reserve_entries,
                   fund_origins)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'created={(self.created if hasattr(self, "created") else None)!r}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!r}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!r}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!r}, '
                f'entity={(self.entity if hasattr(self, "entity") else None)!r}, '
                f'currency={(self.currency if hasattr(self, "currency") else None)!r}, '
                f'reserved={(self.reserved if hasattr(self, "reserved") else None)!r}, '
                f'pending={(self.pending if hasattr(self, "pending") else None)!r}, '
                f'available={(self.available if hasattr(self, "available") else None)!r}, '
                f'total={(self.total if hasattr(self, "total") else None)!r}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!r}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!r}, '
                f'entity_reserves={(self.entity_reserves if hasattr(self, "entity_reserves") else None)!r}, '
                f'entries={(self.entries if hasattr(self, "entries") else None)!r}, '
                f'reserve_entries={(self.reserve_entries if hasattr(self, "reserve_entries") else None)!r}, '
                f'fund_origins={(self.fund_origins if hasattr(self, "fund_origins") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'created={(self.created if hasattr(self, "created") else None)!s}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!s}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!s}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!s}, '
                f'entity={(self.entity if hasattr(self, "entity") else None)!s}, '
                f'currency={(self.currency if hasattr(self, "currency") else None)!s}, '
                f'reserved={(self.reserved if hasattr(self, "reserved") else None)!s}, '
                f'pending={(self.pending if hasattr(self, "pending") else None)!s}, '
                f'available={(self.available if hasattr(self, "available") else None)!s}, '
                f'total={(self.total if hasattr(self, "total") else None)!s}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!s}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!s}, '
                f'entity_reserves={(self.entity_reserves if hasattr(self, "entity_reserves") else None)!s}, '
                f'entries={(self.entries if hasattr(self, "entries") else None)!s}, '
                f'reserve_entries={(self.reserve_entries if hasattr(self, "reserve_entries") else None)!s}, '
                f'fund_origins={(self.fund_origins if hasattr(self, "fund_origins") else None)!s})')
