# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Product3Enum(object):

    """Implementation of the 'Product3' enum.

    Attributes:
        MERCHANTWORKINGCAPITAL: Merchant Working Capital

    """
    _all_values = ['merchantWorkingCapital']
    MERCHANTWORKINGCAPITAL = 'merchantWorkingCapital'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   