# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SaqTypeEnum(object):

    """Implementation of the 'SaqType' enum.

    Attributes:
        SAQA: Card-not-present merchants (e-commerce or mail/telephone-order)
            with PCI DSS-validated third-party payments service provider(s)
            and does not store cardholder data.
        SAQAEP: E-commerce merchants with PCI DSS-validated third-party
            payments service provider(s) with a website that doesn't directly
            collect cardholder data, but may impact it in some way, and does
            not store cardholder data.
        SAQB: Merchants with imprint machines or standalone, dial-out
            terminals that do not store cardholder data.
        SAQBIP: Merchants with standalone, PTS-approved payment terminals that
            have an IP connection to the payment processor, but do not store
            cardholder data.
        SAQCVT: Merchants that enter single transactions manually into an
            internet-based terminal hosted by PCI DSS-validated third-party
            payments service provider(s) and does not store cardholder data.
        SAQC: Merchants with payment application systems connected to the
            internet that do not store cardholder data.
        SAQP2PEHW: Merchants with hardware-only payment terminals managed by a
            PCI SSC-listed P2PE solution, and does not store cardholder data.
        SAQD: Generic field for all Merchants that do not fall under the
            requirements for any above SAQ types.

    """
    _all_values = ['SAQ-A', 'SAQ-A-EP', 'SAQ-B', 'SAQ-B-IP', 'SAQ-C-VT', 'SAQ-C', 'SAQ-P2PE-HW', 'SAQ-D']
    SAQA = 'SAQ-A'

    SAQAEP = 'SAQ-A-EP'

    SAQB = 'SAQ-B'

    SAQBIP = 'SAQ-B-IP'

    SAQCVT = 'SAQ-C-VT'

    SAQC = 'SAQ-C'

    SAQP2PEHW = 'SAQ-P2PE-HW'

    SAQD = 'SAQ-D'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   