# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper


class UpdateApplePayDomainPostRequest(object):

    """Implementation of the 'updateApplePayDomainPostRequest' model.

    Attributes:
        domain (str): The Fully Qualified Domain Name (FQDN) associated with
            the registered Merchant.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "domain": 'domain'
    }

    _optionals = [
        'domain',
    ]

    def __init__(self,
                 domain=APIHelper.SKIP):
        """Constructor for the UpdateApplePayDomainPostRequest class"""

        # Initialize members of the class
        if domain is not APIHelper.SKIP:
            self.domain = domain 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        domain = dictionary.get("domain") if dictionary.get("domain") else APIHelper.SKIP
        # Return an object of this model
        return cls(domain)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'domain={(self.domain if hasattr(self, "domain") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'domain={(self.domain if hasattr(self, "domain") else None)!s})')
