COMMON_BONE_NAMES = [
    ['pelvis', 'Hips', 'mixamorig:Hips'],
    ['spine', 'Spine', 'mixamorig:Spine', 'spine1'],
    ['spine.001', 'Spine1', 'mixamorig:Spine1', 'spine3'],
    ['neck', 'Neck', 'mixamorig:Neck', 'neck1'],
    ['head', 'Head', 'mixamorig:Head', 'face', 'head'],
    ['shoulder.R', 'r_shoulder'],
    ['shoulder.L', 'l_shoulder'],
    ['upper_arm.R', 'RightArm', 'mixamorig:RightArm', 'r_upperarm'],
    ['upper_arm.L', 'LeftArm', 'mixamorig:LeftArm', 'l_upperarm'],
    ['forearm.R', 'RightForeArm', 'mixamorig:RightForeArm', 'r_forearm'],
    ['forearm.L', 'LeftForeArm', 'mixamorig:LeftForeArm', 'l_forearm'],
    ['hand.R', 'RightHand', 'mixamorig:RightHand', 'r_hand'],
    ['hand.L', 'LeftHand', 'mixamorig:LeftHand', 'l_hand'],
    ['thigh.R', 'RightUpLeg', 'mixamorig:RightUpLeg', 'r_thigh'],
    ['thigh.L', 'LeftUpLeg', 'mixamorig:LeftUpLeg', 'l_thigh'],
    ['shin.R', 'RightLeg', 'mixamorig:RightLeg', 'r_shin'],
    ['shin.L', 'LeftLeg', 'mixamorig:LeftLeg', 'l_shin'],
    ['foot.R', 'RightFoot', 'mixamorig:RightFoot', 'r_foot'],
    ['foot.L', 'LeftFoot', 'mixamorig:LeftFoot', 'l_foot'],
    ['thumb.01.R', 'RightHandThumb1', 'mixamorig:RightHandThumb1', 'r_thumb1'],
    ['thumb.02.R', 'RightHandThumb2', 'mixamorig:RightHandThumb2', 'r_thumb2'],
    ['thumb.03.R', 'RightHandThumb3', 'mixamorig:RightHandThumb3', 'r_thumb3'],
    ['f_index.01.R', 'RightHandIndex1', 'mixamorig:RightHandIndex1', 'r_index1'],
    ['f_index.02.R', 'RightHandIndex2', 'mixamorig:RightHandIndex2', 'r_index2'],
    ['f_index.03.R', 'RightHandIndex3', 'mixamorig:RightHandIndex3', 'r_index3'],
    ['f_middle.01.R', 'RightHandMiddle1', 'mixamorig:RightHandMiddle1', 'r_mid1'],
    ['f_middle.02.R', 'RightHandMiddle2', 'mixamorig:RightHandMiddle2', 'r_mid2'],
    ['f_middle.03.R', 'RightHandMiddle3', 'mixamorig:RightHandMiddle3', 'r_mid3'],
    ['f_ring.01.R', 'RightHandRing1', 'mixamorig:RightHandRing1', 'r_ring1'],
    ['f_ring.02.R', 'RightHandRing2', 'mixamorig:RightHandRing2', 'r_ring2'],
    ['f_ring.03.R', 'RightHandRing3', 'mixamorig:RightHandRing3', 'r_ring3'],
    ['f_pinky.01.R', 'RightHandPinky1', 'mixamorig:RightHandPinky1', 'r_pinky1'],
    ['f_pinky.02.R', 'RightHandPinky2', 'mixamorig:RightHandPinky2', 'r_pinky2'],
    ['f_pinky.03.R', 'RightHandPinky3', 'mixamorig:RightHandPinky3', 'r_pinky3'],
    ['thumb.01.L', 'LeftHandThumb1', 'mixamorig:LeftHandThumb1', 'l_thumb1'],
    ['thumb.02.L', 'LeftHandThumb2', 'mixamorig:LeftHandThumb2', 'l_thumb2'],
    ['thumb.03.L', 'LeftHandThumb3', 'mixamorig:LeftHandThumb3', 'l_thumb3'],
    ['f_index.01.L', 'LeftHandIndex1', 'mixamorig:LeftHandIndex1', 'l_index1'],
    ['f_index.02.L', 'LeftHandIndex2', 'mixamorig:LeftHandIndex2', 'l_index2'],
    ['f_index.03.L', 'LeftHandIndex3', 'mixamorig:LeftHandIndex3', 'l_index3'],
    ['f_middle.01.L', 'LeftHandMiddle1', 'mixamorig:LeftHandMiddle1', 'l_mid1'],
    ['f_middle.02.L', 'LeftHandMiddle2', 'mixamorig:LeftHandMiddle2', 'l_mid2'],
    ['f_middle.03.L', 'LeftHandMiddle3', 'mixamorig:LeftHandMiddle3', 'l_mid3'],
    ['f_ring.01.L', 'LeftHandRing1', 'mixamorig:LeftHandRing1', 'l_ring1'],
    ['f_ring.02.L', 'LeftHandRing2', 'mixamorig:LeftHandRing2', 'l_ring2'],
    ['f_ring.03.L', 'LeftHandRing3', 'mixamorig:LeftHandRing3', 'l_ring3'],
    ['f_pinky.01.L', 'LeftHandPinky1', 'mixamorig:LeftHandPinky1', 'l_pinky1'],
    ['f_pinky.02.L', 'LeftHandPinky2', 'mixamorig:LeftHandPinky2', 'l_pinky2'],
    ['f_pinky.03.L', 'LeftHandPinky3', 'mixamorig:LeftHandPinky3', 'l_pinky3'],
]
