"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from herobrain_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PostAPIV1IntelligenceRunTieringDataTypedDict(TypedDict):
    evaluated: NotRequired[float]
    moved: NotRequired[float]
    timestamp: NotRequired[float]


class PostAPIV1IntelligenceRunTieringData(BaseModel):
    evaluated: Optional[float] = None

    moved: Optional[float] = None

    timestamp: Optional[float] = None


class PostAPIV1IntelligenceRunTieringResponseBodyTypedDict(TypedDict):
    r"""Tiering processing results"""

    success: NotRequired[bool]
    data: NotRequired[PostAPIV1IntelligenceRunTieringDataTypedDict]


class PostAPIV1IntelligenceRunTieringResponseBody(BaseModel):
    r"""Tiering processing results"""

    success: Optional[bool] = None

    data: Optional[PostAPIV1IntelligenceRunTieringData] = None
