// DebGenParam.cpp
// Build: g++ -std=c++17 -O2 DebGenParam.cpp -o DebGenParam
// Usage: ./DebGenParam input.json "PRESET1;PRESET2;..." output.hpp

#include <filesystem>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "DebPreComputeUtils.hpp"

int main(int argc, char **argv) {
    if (argc < 4) {
        std::cerr << "Usage: " << argv[0]
                  << " <INPUT_JSON> <PRESET_LIST> <OUTPUT_HPP>\n";
        return 1;
    }
    const std::string in_json = argv[1];
    std::unordered_set<std::string> preset_list;
    std::stringstream preset_ss(argv[2]);
    std::string preset;
    while (std::getline(preset_ss, preset, ';')) {
        preset_list.insert(preset);
    }
    const std::string out_hpp = argv[3];

    std::ifstream is(in_json);
    if (!is) {
        std::cerr << "Failed to open input: " << in_json << "\n";
        return 1;
    }

    json root;
    is >> root;
    if (!root.is_array()) {
        std::cerr << "Top-level JSON must be an array\n";
        return 1;
    }

    std::unordered_map<std::string, RawPreset> raw_by_name;
    for (const auto &item : root) {
        if (!item.is_object())
            continue;
        if (!item.contains("NAME")) {
            // comment object or non-preset, skip
            continue;
        }
        RawPreset r = parse_raw_preset(item);
        if (r.NAME.empty())
            continue;
        if (raw_by_name.count(r.NAME)) {
            std::cerr << "Duplicate NAME: " << r.NAME << "\n";
            return 1;
        }
        // If PARENT missing, spec says default is Self
        if (!r.has_PARENT) {
            r.PARENT = r.NAME;
            r.has_PARENT = true;
        }
        raw_by_name.emplace(r.NAME, std::move(r));
    }

    // Resolve all
    std::unordered_map<std::string, FinalPreset> memo;
    std::unordered_set<std::string> visiting;
    std::vector<FinalPreset> finals;
    std::unordered_set<std::string> parent_presets;
    // finals.reserve(raw_by_name.size());

    for (const auto &kv : raw_by_name) {
        const std::string &name = kv.first;
        if (!preset_list.count("ALL") && !preset_list.count(name))
            continue;
        FinalPreset p = resolve_one(name, raw_by_name, memo, visiting);
        finals.push_back(std::move(p));
        parent_presets.insert(memo[name].PARENT);
    }
    for (const auto &pname : parent_presets) {
        if (!pname.empty() && !memo.count(pname)) {
            // ensure all parents are also included
            FinalPreset p = resolve_one(pname, raw_by_name, memo, visiting);
            finals.push_back(std::move(p));
        }
    }

    // sort by NAME for deterministic header
    std::sort(finals.begin(), finals.end(),
              [](const FinalPreset &a, const FinalPreset &b) {
                  return a.NAME < b.NAME;
              });

    try {
        write_header(out_hpp, finals);
    } catch (const std::exception &e) {
        std::cerr << "Error writing header: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Generated: " << out_hpp << " (" << finals.size()
              << " presets)\n";

    std::filesystem::path p(out_hpp);
    std::string deb_type_h_path =
        p.parent_path().string() + "/../include/deb/deb_type.h";
    replace_codegen_block(
        deb_type_h_path, "    // <DEB_CODEGEN:BEGIN>",
        "    // <DEB_CODEGEN:END>", [](const std::vector<FinalPreset> &finals) {
            std::ostringstream ss;
            ss << " Auto-generated by DebGenParam.cpp — DO NOT EDIT\n";
            for (const auto &final : finals) {
                ss << "    DEB_PRESET_" << final.NAME << ",\n";
            }
            ss << "    DEB_PRESET_EMPTY,\n";
            return ss.str();
        }(finals));
    return 0;
}
