import json
import setuptools

kwargs = json.loads(
    """
{
    "name": "cdktf-cdktf-provider-ionoscloud",
    "version": "12.0.12",
    "description": "Prebuilt ionoscloud Provider for Terraform CDK (cdktf)",
    "license": "MPL-2.0",
    "url": "https://github.com/cdktf/cdktf-provider-ionoscloud.git",
    "long_description_content_type": "text/markdown",
    "author": "HashiCorp",
    "bdist_wheel": {
        "universal": true
    },
    "project_urls": {
        "Source": "https://github.com/cdktf/cdktf-provider-ionoscloud.git"
    },
    "package_dir": {
        "": "src"
    },
    "packages": [
        "cdktf_cdktf_provider_ionoscloud",
        "cdktf_cdktf_provider_ionoscloud._jsii",
        "cdktf_cdktf_provider_ionoscloud.apigateway",
        "cdktf_cdktf_provider_ionoscloud.apigateway_route",
        "cdktf_cdktf_provider_ionoscloud.application_loadbalancer",
        "cdktf_cdktf_provider_ionoscloud.application_loadbalancer_forwardingrule",
        "cdktf_cdktf_provider_ionoscloud.auto_certificate",
        "cdktf_cdktf_provider_ionoscloud.auto_certificate_provider",
        "cdktf_cdktf_provider_ionoscloud.autoscaling_group",
        "cdktf_cdktf_provider_ionoscloud.backup_unit",
        "cdktf_cdktf_provider_ionoscloud.cdn_distribution",
        "cdktf_cdktf_provider_ionoscloud.certificate",
        "cdktf_cdktf_provider_ionoscloud.container_registry",
        "cdktf_cdktf_provider_ionoscloud.container_registry_token",
        "cdktf_cdktf_provider_ionoscloud.cube_server",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_apigateway",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_apigateway_route",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_application_loadbalancer",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_application_loadbalancer_forwardingrule",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_auto_certificate",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_auto_certificate_provider",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_autoscaling_group",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_autoscaling_group_servers",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_backup_unit",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_cdn_distribution",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_certificate",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_container_registry",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_container_registry_locations",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_container_registry_token",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_contracts",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_cube_server",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_datacenter",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_dns_record",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_dns_zone",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_firewall",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_group",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_image",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_inmemorydb_replicaset",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_inmemorydb_snapshot",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_ipblock",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_ipfailover",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_k8_s_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_k8_s_clusters",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_k8_s_node_pool",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_k8_s_node_pool_nodes",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_kafka_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_kafka_cluster_topic",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_lan",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_location",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_logging_pipeline",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_mariadb_backups",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_mariadb_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_mongo_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_mongo_template",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_mongo_user",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_monitoring_pipeline",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_natgateway",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_natgateway_rule",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_networkloadbalancer",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_networkloadbalancer_forwardingrule",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_nfs_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_nfs_share",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_nic",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_nsg",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_object_storage_accesskey",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_object_storage_region",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_backups",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_cluster",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_database",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_databases",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_user",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_pg_versions",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_private_crossconnect",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_resource",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_s3_bucket",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_s3_bucket_policy",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_s3_key",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_s3_object",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_s3_objects",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_server",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_servers",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_share",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_snapshot",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_target_group",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_template",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_user",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_vcpu_server",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_volume",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_vpn_ipsec_gateway",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_vpn_ipsec_tunnel",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_vpn_wireguard_gateway",
        "cdktf_cdktf_provider_ionoscloud.data_ionoscloud_vpn_wireguard_peer",
        "cdktf_cdktf_provider_ionoscloud.datacenter",
        "cdktf_cdktf_provider_ionoscloud.datacenter_nsg_selection",
        "cdktf_cdktf_provider_ionoscloud.dns_record",
        "cdktf_cdktf_provider_ionoscloud.dns_zone",
        "cdktf_cdktf_provider_ionoscloud.firewall",
        "cdktf_cdktf_provider_ionoscloud.group",
        "cdktf_cdktf_provider_ionoscloud.inmemorydb_replicaset",
        "cdktf_cdktf_provider_ionoscloud.ipblock",
        "cdktf_cdktf_provider_ionoscloud.ipfailover",
        "cdktf_cdktf_provider_ionoscloud.k8_s_cluster",
        "cdktf_cdktf_provider_ionoscloud.k8_s_node_pool",
        "cdktf_cdktf_provider_ionoscloud.kafka_cluster",
        "cdktf_cdktf_provider_ionoscloud.kafka_cluster_topic",
        "cdktf_cdktf_provider_ionoscloud.lan",
        "cdktf_cdktf_provider_ionoscloud.loadbalancer",
        "cdktf_cdktf_provider_ionoscloud.logging_pipeline",
        "cdktf_cdktf_provider_ionoscloud.mariadb_cluster",
        "cdktf_cdktf_provider_ionoscloud.mongo_cluster",
        "cdktf_cdktf_provider_ionoscloud.mongo_user",
        "cdktf_cdktf_provider_ionoscloud.monitoring_pipeline",
        "cdktf_cdktf_provider_ionoscloud.natgateway",
        "cdktf_cdktf_provider_ionoscloud.natgateway_rule",
        "cdktf_cdktf_provider_ionoscloud.networkloadbalancer",
        "cdktf_cdktf_provider_ionoscloud.networkloadbalancer_forwardingrule",
        "cdktf_cdktf_provider_ionoscloud.nfs_cluster",
        "cdktf_cdktf_provider_ionoscloud.nfs_share",
        "cdktf_cdktf_provider_ionoscloud.nic",
        "cdktf_cdktf_provider_ionoscloud.nsg",
        "cdktf_cdktf_provider_ionoscloud.nsg_firewallrule",
        "cdktf_cdktf_provider_ionoscloud.object_storage_accesskey",
        "cdktf_cdktf_provider_ionoscloud.pg_cluster",
        "cdktf_cdktf_provider_ionoscloud.pg_database",
        "cdktf_cdktf_provider_ionoscloud.pg_user",
        "cdktf_cdktf_provider_ionoscloud.private_crossconnect",
        "cdktf_cdktf_provider_ionoscloud.provider",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_cors_configuration",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_lifecycle_configuration",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_object_lock_configuration",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_policy",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_public_access_block",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_server_side_encryption_configuration",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_versioning",
        "cdktf_cdktf_provider_ionoscloud.s3_bucket_website_configuration",
        "cdktf_cdktf_provider_ionoscloud.s3_key",
        "cdktf_cdktf_provider_ionoscloud.s3_object",
        "cdktf_cdktf_provider_ionoscloud.s3_object_copy",
        "cdktf_cdktf_provider_ionoscloud.server",
        "cdktf_cdktf_provider_ionoscloud.server_boot_device_selection",
        "cdktf_cdktf_provider_ionoscloud.share",
        "cdktf_cdktf_provider_ionoscloud.snapshot",
        "cdktf_cdktf_provider_ionoscloud.target_group",
        "cdktf_cdktf_provider_ionoscloud.user",
        "cdktf_cdktf_provider_ionoscloud.vcpu_server",
        "cdktf_cdktf_provider_ionoscloud.volume",
        "cdktf_cdktf_provider_ionoscloud.vpn_ipsec_gateway",
        "cdktf_cdktf_provider_ionoscloud.vpn_ipsec_tunnel",
        "cdktf_cdktf_provider_ionoscloud.vpn_wireguard_gateway",
        "cdktf_cdktf_provider_ionoscloud.vpn_wireguard_peer"
    ],
    "package_data": {
        "cdktf_cdktf_provider_ionoscloud._jsii": [
            "provider-ionoscloud@12.0.12.jsii.tgz"
        ],
        "cdktf_cdktf_provider_ionoscloud": [
            "py.typed"
        ]
    },
    "python_requires": "~=3.9",
    "install_requires": [
        "cdktf>=0.21.0, <0.22.0",
        "constructs>=10.4.2, <11.0.0",
        "jsii>=1.118.0, <2.0.0",
        "publication>=0.0.3",
        "typeguard>=2.13.3,<4.3.0"
    ],
    "classifiers": [
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: JavaScript",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Typing :: Typed",
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved"
    ],
    "scripts": []
}
"""
)

with open("README.md", encoding="utf8") as fp:
    kwargs["long_description"] = fp.read()


setuptools.setup(**kwargs)
