VERSION = "1.0.0"

# fmt: off
MAPPING = {
    "autosemver": "https://autosemver.readthedocs.io/en/latest/",
    "autosemver.api": "https://autosemver.readthedocs.io/en/latest/api.html",
    "autosemver.api.get_authors": "https://autosemver.readthedocs.io/en/latest/api.html#autosemver.api.get_authors",
    "autosemver.api.get_changelog": "https://autosemver.readthedocs.io/en/latest/api.html#autosemver.api.get_changelog",
    "autosemver.api.get_current_version": "https://autosemver.readthedocs.io/en/latest/api.html#autosemver.api.get_current_version",
    "autosemver.api.get_releasenotes": "https://autosemver.readthedocs.io/en/latest/api.html#autosemver.api.get_releasenotes",
    "autosemver.api.tag_versions": "https://autosemver.readthedocs.io/en/latest/api.html#autosemver.api.tag_versions",
    "autosemver.distutils": "https://autosemver.readthedocs.io/en/latest/autosemver.html#autosemver.distutils",
    "autosemver.distutils_autosemver_case": "https://autosemver.readthedocs.io/en/latest/autosemver.html#autosemver.distutils_autosemver_case",
    "autosemver.distutils_default_case": "https://autosemver.readthedocs.io/en/latest/autosemver.html#autosemver.distutils_default_case",
    "autosemver.distutils_old_autosemver_case": "https://autosemver.readthedocs.io/en/latest/autosemver.html#autosemver.distutils_old_autosemver_case",
    "autosemver.git": "https://autosemver.readthedocs.io/en/latest/git.html",
    "autosemver.git.fit_to_cols": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.fit_to_cols",
    "autosemver.git.fuzzy_matches_ref": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.fuzzy_matches_ref",
    "autosemver.git.fuzzy_matches_refs": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.fuzzy_matches_refs",
    "autosemver.git.get_bugs_from_commit_msg": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_bugs_from_commit_msg",
    "autosemver.git.get_children_per_first_parent": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_children_per_first_parent",
    "autosemver.git.get_children_per_parent": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_children_per_parent",
    "autosemver.git.get_commit_type": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_commit_type",
    "autosemver.git.get_first_parents": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_first_parents",
    "autosemver.git.get_merged_commits": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_merged_commits",
    "autosemver.git.get_refs": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_refs",
    "autosemver.git.get_repo_object": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_repo_object",
    "autosemver.git.get_tags": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_tags",
    "autosemver.git.get_version": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.get_version",
    "autosemver.git.has_firstparent_child": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.has_firstparent_child",
    "autosemver.git.is_api_break": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.is_api_break",
    "autosemver.git.is_feature": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.is_feature",
    "autosemver.git.pretty_commit": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.pretty_commit",
    "autosemver.git.split_line": "https://autosemver.readthedocs.io/en/latest/git.html#autosemver.git.split_line",
    "autosemver.main": "https://autosemver.readthedocs.io/en/latest/autosemver.html#autosemver.main",
    "autosemver.packaging": "https://autosemver.readthedocs.io/en/latest/packaging.html",
    "autosemver.packaging.create_authors": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.create_authors",
    "autosemver.packaging.create_changelog": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.create_changelog",
    "autosemver.packaging.create_releasenotes": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.create_releasenotes",
    "autosemver.packaging.get_authors": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.get_authors",
    "autosemver.packaging.get_changelog": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.get_changelog",
    "autosemver.packaging.get_current_version": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.get_current_version",
    "autosemver.packaging.get_releasenotes": "https://autosemver.readthedocs.io/en/latest/packaging.html#autosemver.packaging.get_releasenotes",
}
