VERSION = "1.11.4"

# fmt: off
MAPPING = {
    "deep_translator": "https://deep-translator.readthedocs.io/en/latest/",
    "deep_translator.constants": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#module-deep_translator.constants",
    "deep_translator.deepl": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#module-deep_translator.deepl",
    "deep_translator.deepl.deepltranslator": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.deepl.DeeplTranslator",
    "deep_translator.deepl.deepltranslator.translate": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.deepl.DeeplTranslator.translate",
    "deep_translator.deepl.deepltranslator.translate_batch": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.deepl.DeeplTranslator.translate_batch",
    "deep_translator.deepl.deepltranslator.translate_file": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.deepl.DeeplTranslator.translate_file",
    "deep_translator.detection": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#module-deep_translator.detection",
    "deep_translator.detection.batch_detection": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.detection.batch_detection",
    "deep_translator.detection.get_request_body": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.detection.get_request_body",
    "deep_translator.detection.single_detection": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.detection.single_detection",
    "deep_translator.exceptions": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#module-deep_translator.exceptions",
    "deep_translator.exceptions.apikeyexception": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.ApiKeyException",
    "deep_translator.exceptions.authorizationexception": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.AuthorizationException",
    "deep_translator.exceptions.baiduapierror": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.BaiduAPIerror",
    "deep_translator.exceptions.baseerror": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.BaseError",
    "deep_translator.exceptions.elementnotfoundingetrequest": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.ElementNotFoundInGetRequest",
    "deep_translator.exceptions.invalidsourceortargetlanguage": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.InvalidSourceOrTargetLanguage",
    "deep_translator.exceptions.languagenotsupportedexception": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.LanguageNotSupportedException",
    "deep_translator.exceptions.microsoftapierror": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.MicrosoftAPIerror",
    "deep_translator.exceptions.notvalidlength": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.NotValidLength",
    "deep_translator.exceptions.notvalidpayload": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.NotValidPayload",
    "deep_translator.exceptions.requesterror": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.RequestError",
    "deep_translator.exceptions.serverexception": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.ServerException",
    "deep_translator.exceptions.serverexception.errors": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.ServerException.errors",
    "deep_translator.exceptions.tencentapierror": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.TencentAPIerror",
    "deep_translator.exceptions.toomanyrequests": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.TooManyRequests",
    "deep_translator.exceptions.translationnotfound": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.exceptions.TranslationNotFound",
    "deep_translator.validate": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#module-deep_translator.validate",
    "deep_translator.validate.is_empty": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.validate.is_empty",
    "deep_translator.validate.is_input_valid": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.validate.is_input_valid",
    "deep_translator.validate.request_failed": "https://deep-translator.readthedocs.io/en/latest/deep_translator.html#deep_translator.validate.request_failed",
}
