VERSION = "1.9.0"

# fmt: off
MAPPING = {
    "distro": "https://distro.readthedocs.io/en/latest/",
    "distro.build_number": "https://distro.readthedocs.io/en/latest/index.html#distro.build_number",
    "distro.codename": "https://distro.readthedocs.io/en/latest/index.html#distro.codename",
    "distro.distro_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.distro_release_attr",
    "distro.distro_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.distro_release_info",
    "distro.id": "https://distro.readthedocs.io/en/latest/index.html#distro.id",
    "distro.info": "https://distro.readthedocs.io/en/latest/index.html#distro.info",
    "distro.like": "https://distro.readthedocs.io/en/latest/index.html#distro.like",
    "distro.linux_distribution": "https://distro.readthedocs.io/en/latest/index.html#distro.linux_distribution",
    "distro.linuxdistribution": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution",
    "distro.linuxdistribution.build_number": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.build_number",
    "distro.linuxdistribution.codename": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.codename",
    "distro.linuxdistribution.distro_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.distro_release_attr",
    "distro.linuxdistribution.distro_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.distro_release_info",
    "distro.linuxdistribution.id": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.id",
    "distro.linuxdistribution.info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.info",
    "distro.linuxdistribution.like": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.like",
    "distro.linuxdistribution.linux_distribution": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.linux_distribution",
    "distro.linuxdistribution.lsb_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.lsb_release_attr",
    "distro.linuxdistribution.lsb_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.lsb_release_info",
    "distro.linuxdistribution.major_version": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.major_version",
    "distro.linuxdistribution.minor_version": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.minor_version",
    "distro.linuxdistribution.name": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.name",
    "distro.linuxdistribution.os_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.os_release_attr",
    "distro.linuxdistribution.os_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.os_release_info",
    "distro.linuxdistribution.oslevel_info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.oslevel_info",
    "distro.linuxdistribution.uname_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.uname_attr",
    "distro.linuxdistribution.uname_info": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.uname_info",
    "distro.linuxdistribution.version": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.version",
    "distro.linuxdistribution.version_parts": "https://distro.readthedocs.io/en/latest/index.html#distro.LinuxDistribution.version_parts",
    "distro.lsb_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.lsb_release_attr",
    "distro.lsb_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.lsb_release_info",
    "distro.major_version": "https://distro.readthedocs.io/en/latest/index.html#distro.major_version",
    "distro.minor_version": "https://distro.readthedocs.io/en/latest/index.html#distro.minor_version",
    "distro.name": "https://distro.readthedocs.io/en/latest/index.html#distro.name",
    "distro.normalized_distro_id": "https://distro.readthedocs.io/en/latest/index.html#distro.NORMALIZED_DISTRO_ID",
    "distro.normalized_lsb_id": "https://distro.readthedocs.io/en/latest/index.html#distro.NORMALIZED_LSB_ID",
    "distro.normalized_os_id": "https://distro.readthedocs.io/en/latest/index.html#distro.NORMALIZED_OS_ID",
    "distro.os_release_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.os_release_attr",
    "distro.os_release_info": "https://distro.readthedocs.io/en/latest/index.html#distro.os_release_info",
    "distro.uname_attr": "https://distro.readthedocs.io/en/latest/index.html#distro.uname_attr",
    "distro.uname_info": "https://distro.readthedocs.io/en/latest/index.html#distro.uname_info",
    "distro.version": "https://distro.readthedocs.io/en/latest/index.html#distro.version",
    "distro.version_parts": "https://distro.readthedocs.io/en/latest/index.html#distro.version_parts",
}
