VERSION = "4.0.1"

# fmt: off
MAPPING = {
    "flatdict": "https://flatdict.readthedocs.io/en/stable/",
    "flatdict.flatdict": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict",
    "flatdict.flatdict.as_dict": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.as_dict",
    "flatdict.flatdict.clear": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.clear",
    "flatdict.flatdict.copy": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.copy",
    "flatdict.flatdict.get": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.get",
    "flatdict.flatdict.items": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.items",
    "flatdict.flatdict.iteritems": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.iteritems",
    "flatdict.flatdict.iterkeys": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.iterkeys",
    "flatdict.flatdict.itervalues": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.itervalues",
    "flatdict.flatdict.keys": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.keys",
    "flatdict.flatdict.pop": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.pop",
    "flatdict.flatdict.popitem": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.popitem",
    "flatdict.flatdict.set_delimiter": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.set_delimiter",
    "flatdict.flatdict.setdefault": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.setdefault",
    "flatdict.flatdict.update": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.update",
    "flatdict.flatdict.values": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatDict.values",
    "flatdict.flatterdict": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict",
    "flatdict.flatterdict.as_dict": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.as_dict",
    "flatdict.flatterdict.clear": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.clear",
    "flatdict.flatterdict.copy": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.copy",
    "flatdict.flatterdict.get": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.get",
    "flatdict.flatterdict.items": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.items",
    "flatdict.flatterdict.iteritems": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.iteritems",
    "flatdict.flatterdict.iterkeys": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.iterkeys",
    "flatdict.flatterdict.itervalues": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.itervalues",
    "flatdict.flatterdict.keys": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.keys",
    "flatdict.flatterdict.pop": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.pop",
    "flatdict.flatterdict.popitem": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.popitem",
    "flatdict.flatterdict.set_delimiter": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.set_delimiter",
    "flatdict.flatterdict.setdefault": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.setdefault",
    "flatdict.flatterdict.update": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.update",
    "flatdict.flatterdict.values": "https://flatdict.readthedocs.io/en/stable/index.html#flatdict.FlatterDict.values",
}
