VERSION = "2.5.4"

# fmt: off
MAPPING = {
    "gtts": "https://gtts.readthedocs.io/en/latest/",
    "gtts.lang": "https://gtts.readthedocs.io/en/latest/module.html#module-gtts.lang",
    "gtts.lang.tts_langs": "https://gtts.readthedocs.io/en/latest/module.html#gtts.lang.tts_langs",
    "gtts.tokenizer": "https://gtts.readthedocs.io/en/latest/tokenizer.html#module-gtts.tokenizer",
    "gtts.tokenizer.core": "https://gtts.readthedocs.io/en/latest/tokenizer.html",
    "gtts.tokenizer.core.preprocessorregex": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.PreProcessorRegex",
    "gtts.tokenizer.core.preprocessorregex.run": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.PreProcessorRegex.run",
    "gtts.tokenizer.core.preprocessorsub": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.PreProcessorSub",
    "gtts.tokenizer.core.preprocessorsub.run": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.PreProcessorSub.run",
    "gtts.tokenizer.core.regexbuilder": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.RegexBuilder",
    "gtts.tokenizer.core.tokenizer": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.Tokenizer",
    "gtts.tokenizer.core.tokenizer.run": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.core.Tokenizer.run",
    "gtts.tokenizer.pre_processors": "https://gtts.readthedocs.io/en/latest/tokenizer.html#module-gtts.tokenizer.pre_processors",
    "gtts.tokenizer.pre_processors.abbreviations": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.pre_processors.abbreviations",
    "gtts.tokenizer.pre_processors.end_of_line": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.pre_processors.end_of_line",
    "gtts.tokenizer.pre_processors.tone_marks": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.pre_processors.tone_marks",
    "gtts.tokenizer.pre_processors.word_sub": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.pre_processors.word_sub",
    "gtts.tokenizer.symbols": "https://gtts.readthedocs.io/en/latest/tokenizer.html",
    "gtts.tokenizer.symbols.abbreviations": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.symbols.ABBREVIATIONS",
    "gtts.tokenizer.symbols.all_punc": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.symbols.ALL_PUNC",
    "gtts.tokenizer.symbols.sub_pairs": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.symbols.SUB_PAIRS",
    "gtts.tokenizer.symbols.tone_marks": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.symbols.TONE_MARKS",
    "gtts.tokenizer.tokenizer_cases": "https://gtts.readthedocs.io/en/latest/tokenizer.html#module-gtts.tokenizer.tokenizer_cases",
    "gtts.tokenizer.tokenizer_cases.colon": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.tokenizer_cases.colon",
    "gtts.tokenizer.tokenizer_cases.legacy_all_punctuation": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.tokenizer_cases.legacy_all_punctuation",
    "gtts.tokenizer.tokenizer_cases.other_punctuation": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.tokenizer_cases.other_punctuation",
    "gtts.tokenizer.tokenizer_cases.period_comma": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.tokenizer_cases.period_comma",
    "gtts.tokenizer.tokenizer_cases.tone_marks": "https://gtts.readthedocs.io/en/latest/tokenizer.html#gtts.tokenizer.tokenizer_cases.tone_marks",
    "gtts.tts": "https://gtts.readthedocs.io/en/latest/module.html#module-gtts.tts",
    "gtts.tts.gtts": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTS",
    "gtts.tts.gtts.get_bodies": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTS.get_bodies",
    "gtts.tts.gtts.save": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTS.save",
    "gtts.tts.gtts.stream": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTS.stream",
    "gtts.tts.gtts.write_to_fp": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTS.write_to_fp",
    "gtts.tts.gttserror": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTSError",
    "gtts.tts.gttserror.infer_msg": "https://gtts.readthedocs.io/en/latest/module.html#gtts.tts.gTTSError.infer_msg",
}
