VERSION = "2.3.1"

# fmt: off
MAPPING = {
    "hijri_converter": "https://hijri-converter.readthedocs.io/en/stable/",
    "hijri_converter.convert": "https://hijri-converter.readthedocs.io/en/stable/api.html",
    "hijri_converter.convert.gregorian": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian",
    "hijri_converter.convert.gregorian.datetuple": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.datetuple",
    "hijri_converter.convert.gregorian.day_name": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.day_name",
    "hijri_converter.convert.gregorian.dmyformat": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.dmyformat",
    "hijri_converter.convert.gregorian.fromdate": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.fromdate",
    "hijri_converter.convert.gregorian.month_name": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.month_name",
    "hijri_converter.convert.gregorian.notation": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.notation",
    "hijri_converter.convert.gregorian.to_hijri": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.to_hijri",
    "hijri_converter.convert.gregorian.to_julian": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian.to_julian",
    "hijri_converter.convert.hijri": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri",
    "hijri_converter.convert.hijri.datetuple": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.datetuple",
    "hijri_converter.convert.hijri.day": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.day",
    "hijri_converter.convert.hijri.day_name": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.day_name",
    "hijri_converter.convert.hijri.dmyformat": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.dmyformat",
    "hijri_converter.convert.hijri.fromisoformat": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.fromisoformat",
    "hijri_converter.convert.hijri.isoformat": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.isoformat",
    "hijri_converter.convert.hijri.isoweekday": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.isoweekday",
    "hijri_converter.convert.hijri.month": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.month",
    "hijri_converter.convert.hijri.month_length": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.month_length",
    "hijri_converter.convert.hijri.month_name": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.month_name",
    "hijri_converter.convert.hijri.notation": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.notation",
    "hijri_converter.convert.hijri.to_gregorian": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.to_gregorian",
    "hijri_converter.convert.hijri.to_julian": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.to_julian",
    "hijri_converter.convert.hijri.today": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.today",
    "hijri_converter.convert.hijri.weekday": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.weekday",
    "hijri_converter.convert.hijri.year": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Hijri.year",
    "hijri_converter.ummalqura": "https://hijri-converter.readthedocs.io/en/stable/api.html",
    "hijri_converter.ummalqura.gregorian_range": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.ummalqura.GREGORIAN_RANGE",
    "hijri_converter.ummalqura.hijri_range": "https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.ummalqura.HIJRI_RANGE",
}
