VERSION = "0.22.0"

# fmt: off
MAPPING = {
    "injector": "https://injector.readthedocs.io/en/latest/",
    "injector.binder": "https://injector.readthedocs.io/en/latest/api.html#injector.Binder",
    "injector.binder.bind": "https://injector.readthedocs.io/en/latest/api.html#injector.Binder.bind",
    "injector.binder.install": "https://injector.readthedocs.io/en/latest/api.html#injector.Binder.install",
    "injector.binder.multibind": "https://injector.readthedocs.io/en/latest/api.html#injector.Binder.multibind",
    "injector.boundkey": "https://injector.readthedocs.io/en/latest/api.html#injector.BoundKey",
    "injector.callableprovider": "https://injector.readthedocs.io/en/latest/api.html#injector.CallableProvider",
    "injector.callerror": "https://injector.readthedocs.io/en/latest/api.html#injector.CallError",
    "injector.circulardependency": "https://injector.readthedocs.io/en/latest/api.html#injector.CircularDependency",
    "injector.classprovider": "https://injector.readthedocs.io/en/latest/api.html#injector.ClassProvider",
    "injector.error": "https://injector.readthedocs.io/en/latest/api.html#injector.Error",
    "injector.get_bindings": "https://injector.readthedocs.io/en/latest/api.html#injector.get_bindings",
    "injector.Inject": "https://injector.readthedocs.io/en/latest/api.html#injector.Inject",
    "injector.inject": "https://injector.readthedocs.io/en/latest/api.html#injector.inject",
    "injector.injector": "https://injector.readthedocs.io/en/latest/api.html#injector.Injector",
    "injector.injector.binder": "https://injector.readthedocs.io/en/latest/api.html#injector.Injector.binder",
    "injector.injector.call_with_injection": "https://injector.readthedocs.io/en/latest/api.html#injector.Injector.call_with_injection",
    "injector.injector.create_object": "https://injector.readthedocs.io/en/latest/api.html#injector.Injector.create_object",
    "injector.injector.get": "https://injector.readthedocs.io/en/latest/api.html#injector.Injector.get",
    "injector.instanceprovider": "https://injector.readthedocs.io/en/latest/api.html#injector.InstanceProvider",
    "injector.is_decorated_with_inject": "https://injector.readthedocs.io/en/latest/api.html#injector.is_decorated_with_inject",
    "injector.module": "https://injector.readthedocs.io/en/latest/api.html#injector.Module",
    "injector.module.configure": "https://injector.readthedocs.io/en/latest/api.html#injector.Module.configure",
    "injector.multiprovider": "https://injector.readthedocs.io/en/latest/api.html#injector.multiprovider",
    "injector.noinject": "https://injector.readthedocs.io/en/latest/api.html#injector.NoInject",
    "injector.noninjectable": "https://injector.readthedocs.io/en/latest/api.html#injector.noninjectable",
    "injector.noscope": "https://injector.readthedocs.io/en/latest/api.html#injector.NoScope",
    "injector.Provider": "https://injector.readthedocs.io/en/latest/api.html#injector.Provider",
    "injector.provider": "https://injector.readthedocs.io/en/latest/api.html#injector.provider",
    "injector.providerof": "https://injector.readthedocs.io/en/latest/api.html#injector.ProviderOf",
    "injector.providerof.get": "https://injector.readthedocs.io/en/latest/api.html#injector.ProviderOf.get",
    "injector.scope": "https://injector.readthedocs.io/en/latest/api.html#injector.Scope",
    "injector.scope.configure": "https://injector.readthedocs.io/en/latest/api.html#injector.Scope.configure",
    "injector.scope.get": "https://injector.readthedocs.io/en/latest/api.html#injector.Scope.get",
    "injector.singletonscope": "https://injector.readthedocs.io/en/latest/api.html#injector.SingletonScope",
    "injector.threadlocalscope": "https://injector.readthedocs.io/en/latest/api.html#injector.ThreadLocalScope",
    "injector.unknownargument": "https://injector.readthedocs.io/en/latest/api.html#injector.UnknownArgument",
    "injector.unknownprovider": "https://injector.readthedocs.io/en/latest/api.html#injector.UnknownProvider",
    "injector.unsatisfiedrequirement": "https://injector.readthedocs.io/en/latest/api.html#injector.UnsatisfiedRequirement",
}
