VERSION = "1.5.1"

# fmt: off
MAPPING = {
    "joblib": "https://joblib.readthedocs.io/en/stable/",
    "joblib.cpu_count": "https://joblib.readthedocs.io/en/stable/generated/joblib.cpu_count.html#joblib.cpu_count",
    "joblib.delayed": "https://joblib.readthedocs.io/en/stable/parallel.html#joblib.delayed",
    "joblib.dump": "https://joblib.readthedocs.io/en/stable/generated/joblib.dump.html#joblib.dump",
    "joblib.expires_after": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.expires_after",
    "joblib.hash": "https://joblib.readthedocs.io/en/stable/generated/joblib.hash.html#joblib.hash",
    "joblib.load": "https://joblib.readthedocs.io/en/stable/generated/joblib.load.html#joblib.load",
    "joblib.Memory": "https://joblib.readthedocs.io/en/stable/generated/joblib.Memory.html#joblib.Memory",
    "joblib.memory": "https://joblib.readthedocs.io/en/stable/memory.html",
    "joblib.memory.cache": "https://joblib.readthedocs.io/en/stable/generated/joblib.Memory.html#joblib.Memory.cache",
    "joblib.memory.clear": "https://joblib.readthedocs.io/en/stable/generated/joblib.Memory.html#joblib.Memory.clear",
    "joblib.memory.eval": "https://joblib.readthedocs.io/en/stable/generated/joblib.Memory.html#joblib.Memory.eval",
    "joblib.memory.memorizedfunc": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.memory.MemorizedFunc",
    "joblib.memory.memorizedfunc.__init__": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.memory.MemorizedFunc.__init__",
    "joblib.memory.memorizedfunc.call": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.memory.MemorizedFunc.call",
    "joblib.memory.memorizedfunc.check_call_in_cache": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.memory.MemorizedFunc.check_call_in_cache",
    "joblib.memory.memorizedfunc.clear": "https://joblib.readthedocs.io/en/stable/memory.html#joblib.memory.MemorizedFunc.clear",
    "joblib.memory.reduce_size": "https://joblib.readthedocs.io/en/stable/generated/joblib.Memory.html#joblib.Memory.reduce_size",
    "joblib.Parallel": "https://joblib.readthedocs.io/en/stable/generated/joblib.Parallel.html#joblib.Parallel",
    "joblib.parallel": "https://joblib.readthedocs.io/en/stable/parallel.html",
    "joblib.parallel.autobatchingmixin": "https://joblib.readthedocs.io/en/stable/parallel.html#joblib.parallel.AutoBatchingMixin",
    "joblib.parallel.dispatch_next": "https://joblib.readthedocs.io/en/stable/generated/joblib.Parallel.html#joblib.Parallel.dispatch_next",
    "joblib.parallel.dispatch_one_batch": "https://joblib.readthedocs.io/en/stable/generated/joblib.Parallel.html#joblib.Parallel.dispatch_one_batch",
    "joblib.parallel.parallelbackendbase": "https://joblib.readthedocs.io/en/stable/parallel.html#joblib.parallel.ParallelBackendBase",
    "joblib.parallel.print_progress": "https://joblib.readthedocs.io/en/stable/generated/joblib.Parallel.html#joblib.Parallel.print_progress",
    "joblib.parallel_backend": "https://joblib.readthedocs.io/en/stable/generated/joblib.parallel_backend.html#joblib.parallel_backend",
    "joblib.parallel_config": "https://joblib.readthedocs.io/en/stable/generated/joblib.parallel_config.html#joblib.parallel_config",
    "joblib.register_compressor": "https://joblib.readthedocs.io/en/stable/generated/joblib.register_compressor.html#joblib.register_compressor",
    "joblib.register_parallel_backend": "https://joblib.readthedocs.io/en/stable/parallel.html#joblib.register_parallel_backend",
    "joblib.wrap_non_picklable_objects": "https://joblib.readthedocs.io/en/stable/parallel.html#joblib.wrap_non_picklable_objects",
}
