VERSION = "0.6"

# fmt: off
MAPPING = {
    "mplcursors": "https://mplcursors.readthedocs.io/en/stable/",
    "mplcursors.compute_pick": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.compute_pick",
    "mplcursors.Cursor": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor",
    "mplcursors.cursor": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.cursor",
    "mplcursors.cursor.__init__": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.__init__",
    "mplcursors.cursor.add_highlight": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.add_highlight",
    "mplcursors.cursor.add_selection": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.add_selection",
    "mplcursors.cursor.annotation_kwargs": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.annotation_kwargs",
    "mplcursors.cursor.annotation_positions": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.annotation_positions",
    "mplcursors.cursor.artists": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.artists",
    "mplcursors.cursor.bindings": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.bindings",
    "mplcursors.cursor.connect": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.connect",
    "mplcursors.cursor.disconnect": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.disconnect",
    "mplcursors.cursor.enabled": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.enabled",
    "mplcursors.cursor.highlight_kwargs": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.highlight_kwargs",
    "mplcursors.cursor.remove": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.remove",
    "mplcursors.cursor.remove_selection": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.remove_selection",
    "mplcursors.cursor.selections": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.selections",
    "mplcursors.cursor.visible": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.visible",
    "mplcursors.get_ann_text": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.get_ann_text",
    "mplcursors.hovermode": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.HoverMode",
    "mplcursors.hovermode.nohover": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.HoverMode.NoHover",
    "mplcursors.hovermode.persistent": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.HoverMode.Persistent",
    "mplcursors.hovermode.transient": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.HoverMode.Transient",
    "mplcursors.make_highlight": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.make_highlight",
    "mplcursors.move": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.move",
    "mplcursors.selection": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection",
    "mplcursors.selection.annotation": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.annotation",
    "mplcursors.selection.artist": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.artist",
    "mplcursors.selection.dist": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.dist",
    "mplcursors.selection.extras": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.extras",
    "mplcursors.selection.index": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.index",
    "mplcursors.selection.target": "https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Selection.target",
}
