VERSION = "0.61.2"

# fmt: off
MAPPING = {
    "numba": "https://numba.readthedocs.io/en/stable/reference/index.html",
    "numba.carray": "https://numba.readthedocs.io/en/stable/reference/utils.html#numba.carray",
    "numba.cfunc": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.cfunc",
    "numba.core": "https://numba.readthedocs.io/en/stable/reference/pysupported.html",
    "numba.core.typing": "https://numba.readthedocs.io/en/stable/reference/pysupported.html",
    "numba.core.typing.cffi_utils": "https://numba.readthedocs.io/en/stable/reference/pysupported.html",
    "numba.core.typing.cffi_utils.register_module": "https://numba.readthedocs.io/en/stable/reference/pysupported.html#numba.core.typing.cffi_utils.register_module",
    "numba.core.typing.cffi_utils.register_type": "https://numba.readthedocs.io/en/stable/reference/pysupported.html#numba.core.typing.cffi_utils.register_type",
    "numba.dufunc": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc",
    "numba.dufunc.accumulate": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.accumulate",
    "numba.dufunc.at": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.at",
    "numba.dufunc.identity": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.identity",
    "numba.dufunc.nargs": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.nargs",
    "numba.dufunc.nin": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.nin",
    "numba.dufunc.nout": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.nout",
    "numba.dufunc.ntypes": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.ntypes",
    "numba.dufunc.outer": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.outer",
    "numba.dufunc.reduce": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.reduce",
    "numba.dufunc.reduceat": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.reduceat",
    "numba.dufunc.types": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.types",
    "numba.dufunc.ufunc": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.DUFunc.ufunc",
    "numba.extending": "https://numba.readthedocs.io/en/stable/reference/types.html",
    "numba.extending.as_numba_type": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.extending.as_numba_type",
    "numba.farray": "https://numba.readthedocs.io/en/stable/reference/utils.html#numba.farray",
    "numba.from_dtype": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.from_dtype",
    "numba.guvectorize": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.guvectorize",
    "numba.jit": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.jit",
    "numba.optional": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.optional",
    "numba.pycc": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html",
    "numba.pycc.cc": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC",
    "numba.pycc.cc.compile": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.compile",
    "numba.pycc.cc.distutils_extension": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.distutils_extension",
    "numba.pycc.cc.export": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.export",
    "numba.pycc.cc.name": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.name",
    "numba.pycc.cc.output_dir": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.output_dir",
    "numba.pycc.cc.output_file": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.output_file",
    "numba.pycc.cc.target_cpu": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.target_cpu",
    "numba.pycc.cc.verbose": "https://numba.readthedocs.io/en/stable/reference/aot-compilation.html#numba.pycc.CC.verbose",
    "numba.typeof": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.typeof",
    "numba.types": "https://numba.readthedocs.io/en/stable/reference/types.html",
    "numba.types.array": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.types.Array",
    "numba.types.npdatetime": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.types.NPDatetime",
    "numba.types.nptimedelta": "https://numba.readthedocs.io/en/stable/reference/types.html#numba.types.NPTimedelta",
    "numba.vectorize": "https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.vectorize",
}
