VERSION = "0.5"

# fmt: off
MAPPING = {
    "parver": "https://parver.readthedocs.io/en/stable/",
    "parver.parseerror": "https://parver.readthedocs.io/en/stable/api.html#parver.ParseError",
    "parver.version": "https://parver.readthedocs.io/en/stable/api.html#parver.Version",
    "parver.version.base_version": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.base_version",
    "parver.version.bump_dev": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_dev",
    "parver.version.bump_epoch": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_epoch",
    "parver.version.bump_post": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_post",
    "parver.version.bump_pre": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_pre",
    "parver.version.bump_release": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_release",
    "parver.version.bump_release_to": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.bump_release_to",
    "parver.version.dev": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.dev",
    "parver.version.dev_sep": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.dev_sep",
    "parver.version.epoch": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.epoch",
    "parver.version.is_alpha": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_alpha",
    "parver.version.is_beta": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_beta",
    "parver.version.is_devrelease": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_devrelease",
    "parver.version.is_postrelease": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_postrelease",
    "parver.version.is_prerelease": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_prerelease",
    "parver.version.is_release_candidate": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.is_release_candidate",
    "parver.version.local": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.local",
    "parver.version.parse": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.parse",
    "parver.version.post": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.post",
    "parver.version.post_sep1": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.post_sep1",
    "parver.version.post_sep2": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.post_sep2",
    "parver.version.post_tag": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.post_tag",
    "parver.version.pre": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.pre",
    "parver.version.pre_sep1": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.pre_sep1",
    "parver.version.pre_sep2": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.pre_sep2",
    "parver.version.pre_tag": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.pre_tag",
    "parver.version.public": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.public",
    "parver.version.release": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.release",
    "parver.version.replace": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.replace",
    "parver.version.set_release": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.set_release",
    "parver.version.truncate": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.truncate",
    "parver.version.v": "https://parver.readthedocs.io/en/stable/api.html#parver.Version.v",
}
