VERSION = "0.4.3"

# fmt: off
MAPPING = {
    "pathlib_abc": "https://pathlib-abc.readthedocs.io/en/latest/",
    "pathlib_abc.joinablepath": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath",
    "pathlib_abc.joinablepath.__rtruediv__": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.__rtruediv__",
    "pathlib_abc.joinablepath.__str__": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.__str__",
    "pathlib_abc.joinablepath.__truediv__": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.__truediv__",
    "pathlib_abc.joinablepath.anchor": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.anchor",
    "pathlib_abc.joinablepath.full_match": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.full_match",
    "pathlib_abc.joinablepath.joinpath": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.joinpath",
    "pathlib_abc.joinablepath.name": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.name",
    "pathlib_abc.joinablepath.parent": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.parent",
    "pathlib_abc.joinablepath.parents": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.parents",
    "pathlib_abc.joinablepath.parser": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.parser",
    "pathlib_abc.joinablepath.parts": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.parts",
    "pathlib_abc.joinablepath.stem": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.stem",
    "pathlib_abc.joinablepath.suffix": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.suffix",
    "pathlib_abc.joinablepath.suffixes": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.suffixes",
    "pathlib_abc.joinablepath.with_name": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.with_name",
    "pathlib_abc.joinablepath.with_segments": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.with_segments",
    "pathlib_abc.joinablepath.with_stem": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.with_stem",
    "pathlib_abc.joinablepath.with_suffix": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.JoinablePath.with_suffix",
    "pathlib_abc.magic_open": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.magic_open",
    "pathlib_abc.pathinfo": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathInfo",
    "pathlib_abc.pathinfo.exists": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathInfo.exists",
    "pathlib_abc.pathinfo.is_dir": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathInfo.is_dir",
    "pathlib_abc.pathinfo.is_file": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathInfo.is_file",
    "pathlib_abc.pathinfo.is_symlink": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathInfo.is_symlink",
    "pathlib_abc.pathparser": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser",
    "pathlib_abc.pathparser.altsep": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser.altsep",
    "pathlib_abc.pathparser.normcase": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser.normcase",
    "pathlib_abc.pathparser.sep": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser.sep",
    "pathlib_abc.pathparser.split": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser.split",
    "pathlib_abc.pathparser.splitext": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.PathParser.splitext",
    "pathlib_abc.readablepath": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath",
    "pathlib_abc.readablepath.__open_rb__": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.__open_rb__",
    "pathlib_abc.readablepath.copy": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.copy",
    "pathlib_abc.readablepath.copy_into": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.copy_into",
    "pathlib_abc.readablepath.glob": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.glob",
    "pathlib_abc.readablepath.info": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.info",
    "pathlib_abc.readablepath.iterdir": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.iterdir",
    "pathlib_abc.readablepath.read_bytes": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.read_bytes",
    "pathlib_abc.readablepath.read_text": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.read_text",
    "pathlib_abc.readablepath.readlink": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.readlink",
    "pathlib_abc.readablepath.walk": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.ReadablePath.walk",
    "pathlib_abc.writablepath": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath",
    "pathlib_abc.writablepath.__open_wb__": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath.__open_wb__",
    "pathlib_abc.writablepath._copy_from": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath._copy_from",
    "pathlib_abc.writablepath.mkdir": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath.mkdir",
    "pathlib_abc.writablepath.symlink_to": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath.symlink_to",
    "pathlib_abc.writablepath.write_bytes": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath.write_bytes",
    "pathlib_abc.writablepath.write_text": "https://pathlib-abc.readthedocs.io/en/latest/api.html#pathlib_abc.WritablePath.write_text",
}
