VERSION = "5.1.1"

# fmt: off
MAPPING = {
    "pebble": "https://pebble.readthedocs.io/en/latest/",
    "pebble.mapfuture": "https://pebble.readthedocs.io/en/latest/#pebble.MapFuture",
    "pebble.mapfuture.cancel": "https://pebble.readthedocs.io/en/latest/#pebble.MapFuture.cancel",
    "pebble.mapfuture.result": "https://pebble.readthedocs.io/en/latest/#pebble.MapFuture.result",
    "pebble.processexpired": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessExpired",
    "pebble.processexpired.exitcode": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessExpired.exitcode",
    "pebble.processexpired.pid": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessExpired.pid",
    "pebble.processfuture": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessFuture",
    "pebble.processfuture.cancel": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessFuture.cancel",
    "pebble.processmapfuture": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessMapFuture",
    "pebble.processmapfuture.cancel": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessMapFuture.cancel",
    "pebble.processmapfuture.result": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessMapFuture.result",
    "pebble.processpool": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool",
    "pebble.processpool.active": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.active",
    "pebble.processpool.close": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.close",
    "pebble.processpool.join": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.join",
    "pebble.processpool.map": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.map",
    "pebble.processpool.schedule": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.schedule",
    "pebble.processpool.stop": "https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.stop",
    "pebble.sighandler": "https://pebble.readthedocs.io/en/latest/#pebble.sighandler",
    "pebble.synchronized": "https://pebble.readthedocs.io/en/latest/#pebble.synchronized",
    "pebble.threadpool": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool",
    "pebble.threadpool.active": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.active",
    "pebble.threadpool.close": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.close",
    "pebble.threadpool.join": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.join",
    "pebble.threadpool.map": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.map",
    "pebble.threadpool.schedule": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.schedule",
    "pebble.threadpool.stop": "https://pebble.readthedocs.io/en/latest/#pebble.ThreadPool.stop",
    "pebble.waitforqueues": "https://pebble.readthedocs.io/en/latest/#pebble.waitforqueues",
    "pebble.waitforthreads": "https://pebble.readthedocs.io/en/latest/#pebble.waitforthreads",
}
