VERSION = "0.16.1"

# fmt: off
MAPPING = {
    "pydata_sphinx_theme": "https://pydata-sphinx-theme.readthedocs.io/en/stable/",
    "pydata_sphinx_theme.__version__": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/index.html#pydata_sphinx_theme.__version__",
    "pydata_sphinx_theme._fix_canonical_url": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/index.html#pydata_sphinx_theme._fix_canonical_url",
    "pydata_sphinx_theme.edit_this_page": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/edit_this_page/index.html",
    "pydata_sphinx_theme.edit_this_page.setup_edit_url": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/edit_this_page/index.html#pydata_sphinx_theme.edit_this_page.setup_edit_url",
    "pydata_sphinx_theme.logo": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/logo/index.html",
    "pydata_sphinx_theme.logo.copy_logo_images": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/logo/index.html#pydata_sphinx_theme.logo.copy_logo_images",
    "pydata_sphinx_theme.logo.setup_logo_path": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/logo/index.html#pydata_sphinx_theme.logo.setup_logo_path",
    "pydata_sphinx_theme.pygments": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/pygments/index.html",
    "pydata_sphinx_theme.pygments._get_styles": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/pygments/index.html#pydata_sphinx_theme.pygments._get_styles",
    "pydata_sphinx_theme.pygments.get_pygments_stylesheet": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/pygments/index.html#pydata_sphinx_theme.pygments.get_pygments_stylesheet",
    "pydata_sphinx_theme.pygments.overwrite_pygments_css": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/pygments/index.html#pydata_sphinx_theme.pygments.overwrite_pygments_css",
    "pydata_sphinx_theme.setup": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/index.html#pydata_sphinx_theme.setup",
    "pydata_sphinx_theme.short_link": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html",
    "pydata_sphinx_theme.short_link.shortenlinktransform": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform",
    "pydata_sphinx_theme.short_link.shortenlinktransform.default_priority": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.default_priority",
    "pydata_sphinx_theme.short_link.shortenlinktransform.formats": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.formats",
    "pydata_sphinx_theme.short_link.shortenlinktransform.parse_url": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.parse_url",
    "pydata_sphinx_theme.short_link.shortenlinktransform.platform": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.platform",
    "pydata_sphinx_theme.short_link.shortenlinktransform.run": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.run",
    "pydata_sphinx_theme.short_link.shortenlinktransform.supported_platform": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/short_link/index.html#pydata_sphinx_theme.short_link.ShortenLinkTransform.supported_platform",
    "pydata_sphinx_theme.toctree": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html",
    "pydata_sphinx_theme.toctree._get_ancestor_pagename": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree._get_ancestor_pagename",
    "pydata_sphinx_theme.toctree.add_collapse_checkboxes": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.add_collapse_checkboxes",
    "pydata_sphinx_theme.toctree.add_inline_math": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.add_inline_math",
    "pydata_sphinx_theme.toctree.add_toctree_functions": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.add_toctree_functions",
    "pydata_sphinx_theme.toctree.get_nonroot_toctree": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.get_nonroot_toctree",
    "pydata_sphinx_theme.toctree.linkinfo": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.LinkInfo",
    "pydata_sphinx_theme.toctree.linkinfo.href": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.LinkInfo.href",
    "pydata_sphinx_theme.toctree.linkinfo.is_current": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.LinkInfo.is_current",
    "pydata_sphinx_theme.toctree.linkinfo.is_external": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.LinkInfo.is_external",
    "pydata_sphinx_theme.toctree.linkinfo.title": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/toctree/index.html#pydata_sphinx_theme.toctree.LinkInfo.title",
    "pydata_sphinx_theme.translator": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html",
    "pydata_sphinx_theme.translator.bootstraphtml5translatormixin": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.BootstrapHTML5TranslatorMixin",
    "pydata_sphinx_theme.translator.bootstraphtml5translatormixin.depart_table": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.BootstrapHTML5TranslatorMixin.depart_table",
    "pydata_sphinx_theme.translator.bootstraphtml5translatormixin.starttag": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.BootstrapHTML5TranslatorMixin.starttag",
    "pydata_sphinx_theme.translator.bootstraphtml5translatormixin.visit_table": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.BootstrapHTML5TranslatorMixin.visit_table",
    "pydata_sphinx_theme.translator.logger": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.logger",
    "pydata_sphinx_theme.translator.setup_translators": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/translator/index.html#pydata_sphinx_theme.translator.setup_translators",
    "pydata_sphinx_theme.update_and_remove_templates": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/index.html#pydata_sphinx_theme.update_and_remove_templates",
    "pydata_sphinx_theme.update_config": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/index.html#pydata_sphinx_theme.update_config",
    "pydata_sphinx_theme.utils": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html",
    "pydata_sphinx_theme.utils._get_matching_sidebar_items": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils._get_matching_sidebar_items",
    "pydata_sphinx_theme.utils._has_wildcard": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils._has_wildcard",
    "pydata_sphinx_theme.utils._update_and_remove_templates": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils._update_and_remove_templates",
    "pydata_sphinx_theme.utils.config_provided_by_user": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.config_provided_by_user",
    "pydata_sphinx_theme.utils.escape_ansi": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.escape_ansi",
    "pydata_sphinx_theme.utils.get_theme_options_dict": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.get_theme_options_dict",
    "pydata_sphinx_theme.utils.maybe_warn": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.maybe_warn",
    "pydata_sphinx_theme.utils.set_secondary_sidebar_items": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.set_secondary_sidebar_items",
    "pydata_sphinx_theme.utils.sphinx_logger": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.SPHINX_LOGGER",
    "pydata_sphinx_theme.utils.traverse_or_findall": "https://pydata-sphinx-theme.readthedocs.io/en/stable/api/pydata_sphinx_theme/utils/index.html#pydata_sphinx_theme.utils.traverse_or_findall",
}
