VERSION = "2.1.0"

# fmt: off
MAPPING = {
    "questionary": "https://questionary.readthedocs.io/en/stable/",
    "questionary.autocomplete": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.autocomplete",
    "questionary.checkbox": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.checkbox",
    "questionary.choice": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice",
    "questionary.choice.build": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.build",
    "questionary.choice.checked": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.checked",
    "questionary.choice.disabled": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.disabled",
    "questionary.choice.shortcut_key": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.shortcut_key",
    "questionary.choice.title": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.title",
    "questionary.choice.value": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice.value",
    "questionary.confirm": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.confirm",
    "questionary.Form": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Form",
    "questionary.form": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.form",
    "questionary.form.ask": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Form.ask",
    "questionary.form.ask_async": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Form.ask_async",
    "questionary.form.unsafe_ask": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Form.unsafe_ask",
    "questionary.form.unsafe_ask_async": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Form.unsafe_ask_async",
    "questionary.formfield": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.FormField",
    "questionary.formfield.key": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.FormField.key",
    "questionary.formfield.question": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.FormField.question",
    "questionary.password": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.password",
    "questionary.path": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.path",
    "questionary.press_any_key_to_continue": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.press_any_key_to_continue",
    "questionary.print": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.print",
    "questionary.prompt": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.prompt",
    "questionary.question": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question",
    "questionary.question.ask": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question.ask",
    "questionary.question.ask_async": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question.ask_async",
    "questionary.question.skip_if": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question.skip_if",
    "questionary.question.unsafe_ask": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question.unsafe_ask",
    "questionary.question.unsafe_ask_async": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Question.unsafe_ask_async",
    "questionary.rawselect": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.rawselect",
    "questionary.select": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.select",
    "questionary.separator": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Separator",
    "questionary.separator.default_separator": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Separator.default_separator",
    "questionary.separator.line": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Separator.line",
    "questionary.text": "https://questionary.readthedocs.io/en/stable/pages/types.html#questionary.text",
    "questionary.unsafe_prompt": "https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.unsafe_prompt",
}
