VERSION = "0.25.1"

# fmt: off
MAPPING = {
    "rpds": "https://rpds.readthedocs.io/en/latest/",
    "rpds.hashtriemap": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap",
    "rpds.hashtriemap.__getitem__": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.__getitem__",
    "rpds.hashtriemap.__iter__": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.__iter__",
    "rpds.hashtriemap.__len__": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.__len__",
    "rpds.hashtriemap.convert": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.convert",
    "rpds.hashtriemap.discard": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.discard",
    "rpds.hashtriemap.fromkeys": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.fromkeys",
    "rpds.hashtriemap.get": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.get",
    "rpds.hashtriemap.insert": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.insert",
    "rpds.hashtriemap.items": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.items",
    "rpds.hashtriemap.keys": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.keys",
    "rpds.hashtriemap.remove": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.remove",
    "rpds.hashtriemap.update": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.update",
    "rpds.hashtriemap.values": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap.values",
    "rpds.hashtrieset": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet",
    "rpds.hashtrieset.__iter__": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.__iter__",
    "rpds.hashtrieset.__len__": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.__len__",
    "rpds.hashtrieset.difference": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.difference",
    "rpds.hashtrieset.discard": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.discard",
    "rpds.hashtrieset.insert": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.insert",
    "rpds.hashtrieset.intersection": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.intersection",
    "rpds.hashtrieset.remove": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.remove",
    "rpds.hashtrieset.symmetric_difference": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.symmetric_difference",
    "rpds.hashtrieset.union": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.union",
    "rpds.hashtrieset.update": "https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieSet.update",
    "rpds.list": "https://rpds.readthedocs.io/en/latest/api/#rpds.List",
    "rpds.list.__iter__": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.__iter__",
    "rpds.list.__len__": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.__len__",
    "rpds.list.drop_first": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.drop_first",
    "rpds.list.first": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.first",
    "rpds.list.push_front": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.push_front",
    "rpds.list.rest": "https://rpds.readthedocs.io/en/latest/api/#rpds.List.rest",
    "rpds.queue": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue",
    "rpds.queue.__iter__": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.__iter__",
    "rpds.queue.__len__": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.__len__",
    "rpds.queue.dequeue": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.dequeue",
    "rpds.queue.enqueue": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.enqueue",
    "rpds.queue.is_empty": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.is_empty",
    "rpds.queue.peek": "https://rpds.readthedocs.io/en/latest/api/#rpds.Queue.peek",
}
