VERSION = "1.2.2"

# fmt: off
MAPPING = {
    "schedule": "https://schedule.readthedocs.io/en/stable/",
    "schedule.cancel_job": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.cancel_job",
    "schedule.canceljob": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.CancelJob",
    "schedule.clear": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.clear",
    "schedule.default_scheduler": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.default_scheduler",
    "schedule.every": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.every",
    "schedule.get_jobs": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.get_jobs",
    "schedule.idle_seconds": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.idle_seconds",
    "schedule.job": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job",
    "schedule.job.at": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.at",
    "schedule.job.day": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.day",
    "schedule.job.days": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.days",
    "schedule.job.do": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.do",
    "schedule.job.friday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.friday",
    "schedule.job.hour": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.hour",
    "schedule.job.hours": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.hours",
    "schedule.job.minute": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.minute",
    "schedule.job.minutes": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.minutes",
    "schedule.job.monday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.monday",
    "schedule.job.run": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.run",
    "schedule.job.saturday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.saturday",
    "schedule.job.second": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.second",
    "schedule.job.seconds": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.seconds",
    "schedule.job.should_run": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.should_run",
    "schedule.job.sunday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.sunday",
    "schedule.job.tag": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.tag",
    "schedule.job.thursday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.thursday",
    "schedule.job.to": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.to",
    "schedule.job.tuesday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.tuesday",
    "schedule.job.until": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.until",
    "schedule.job.wednesday": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.wednesday",
    "schedule.job.week": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.week",
    "schedule.job.weeks": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Job.weeks",
    "schedule.jobs": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.jobs",
    "schedule.next_run": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.next_run",
    "schedule.run_all": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.run_all",
    "schedule.run_pending": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.run_pending",
    "schedule.scheduler": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler",
    "schedule.scheduler.cancel_job": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.cancel_job",
    "schedule.scheduler.clear": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.clear",
    "schedule.scheduler.every": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.every",
    "schedule.scheduler.get_jobs": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.get_jobs",
    "schedule.scheduler.get_next_run": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.get_next_run",
    "schedule.scheduler.idle_seconds": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.idle_seconds",
    "schedule.scheduler.next_run": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.next_run",
    "schedule.scheduler.run_all": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.run_all",
    "schedule.scheduler.run_pending": "https://schedule.readthedocs.io/en/stable/reference.html#schedule.Scheduler.run_pending",
}
