VERSION = "1.1.0"

# fmt: off
MAPPING = {
    "simple_websocket": "https://simple-websocket.readthedocs.io/en/latest/",
    "simple_websocket.aioclient": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient",
    "simple_websocket.aioclient.close": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient.close",
    "simple_websocket.aioclient.connect": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient.connect",
    "simple_websocket.aioclient.receive": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient.receive",
    "simple_websocket.aioclient.send": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient.send",
    "simple_websocket.aioclient.subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioClient.subprotocol",
    "simple_websocket.aioserver": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer",
    "simple_websocket.aioserver.accept": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.accept",
    "simple_websocket.aioserver.choose_subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.choose_subprotocol",
    "simple_websocket.aioserver.close": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.close",
    "simple_websocket.aioserver.receive": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.receive",
    "simple_websocket.aioserver.send": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.send",
    "simple_websocket.aioserver.subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.AioServer.subprotocol",
    "simple_websocket.client": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client",
    "simple_websocket.client.close": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client.close",
    "simple_websocket.client.connect": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client.connect",
    "simple_websocket.client.receive": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client.receive",
    "simple_websocket.client.send": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client.send",
    "simple_websocket.client.subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Client.subprotocol",
    "simple_websocket.connectionclosed": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.ConnectionClosed",
    "simple_websocket.connectionerror": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.ConnectionError",
    "simple_websocket.server": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server",
    "simple_websocket.server.accept": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.accept",
    "simple_websocket.server.choose_subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.choose_subprotocol",
    "simple_websocket.server.close": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.close",
    "simple_websocket.server.receive": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.receive",
    "simple_websocket.server.send": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.send",
    "simple_websocket.server.subprotocol": "https://simple-websocket.readthedocs.io/en/latest/api.html#simple_websocket.Server.subprotocol",
}
