VERSION = "0.5.3"

# fmt: off
MAPPING = {
    "sqlparse": "https://sqlparse.readthedocs.io/en/latest/",
    "sqlparse.format": "https://sqlparse.readthedocs.io/en/latest/api.html#sqlparse.format",
    "sqlparse.parse": "https://sqlparse.readthedocs.io/en/latest/api.html#sqlparse.parse",
    "sqlparse.split": "https://sqlparse.readthedocs.io/en/latest/api.html#sqlparse.split",
    "sqlparse.sql": "https://sqlparse.readthedocs.io/en/latest/analyzing.html",
    "sqlparse.sql.assignment": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Assignment",
    "sqlparse.sql.case": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Case",
    "sqlparse.sql.case.get_cases": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Case.get_cases",
    "sqlparse.sql.comment": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Comment",
    "sqlparse.sql.comparison": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Comparison",
    "sqlparse.sql.for": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.For",
    "sqlparse.sql.identifier": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Identifier",
    "sqlparse.sql.identifier.get_array_indices": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Identifier.get_array_indices",
    "sqlparse.sql.identifier.get_ordering": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Identifier.get_ordering",
    "sqlparse.sql.identifier.get_typecast": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Identifier.get_typecast",
    "sqlparse.sql.identifier.is_wildcard": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Identifier.is_wildcard",
    "sqlparse.sql.identifierlist": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.IdentifierList",
    "sqlparse.sql.identifierlist.get_identifiers": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.IdentifierList.get_identifiers",
    "sqlparse.sql.if": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.If",
    "sqlparse.sql.parenthesis": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Parenthesis",
    "sqlparse.sql.statement": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Statement",
    "sqlparse.sql.statement.get_type": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Statement.get_type",
    "sqlparse.sql.token": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token",
    "sqlparse.sql.token.flatten": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token.flatten",
    "sqlparse.sql.token.has_ancestor": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token.has_ancestor",
    "sqlparse.sql.token.is_child_of": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token.is_child_of",
    "sqlparse.sql.token.match": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token.match",
    "sqlparse.sql.token.within": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Token.within",
    "sqlparse.sql.tokenlist": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList",
    "sqlparse.sql.tokenlist.flatten": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.flatten",
    "sqlparse.sql.tokenlist.get_alias": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.get_alias",
    "sqlparse.sql.tokenlist.get_name": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.get_name",
    "sqlparse.sql.tokenlist.get_parent_name": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.get_parent_name",
    "sqlparse.sql.tokenlist.get_real_name": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.get_real_name",
    "sqlparse.sql.tokenlist.get_token_at_offset": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.get_token_at_offset",
    "sqlparse.sql.tokenlist.group_tokens": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.group_tokens",
    "sqlparse.sql.tokenlist.has_alias": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.has_alias",
    "sqlparse.sql.tokenlist.insert_after": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.insert_after",
    "sqlparse.sql.tokenlist.insert_before": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.insert_before",
    "sqlparse.sql.tokenlist.token_first": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.token_first",
    "sqlparse.sql.tokenlist.token_index": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.token_index",
    "sqlparse.sql.tokenlist.token_next": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.token_next",
    "sqlparse.sql.tokenlist.token_prev": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.TokenList.token_prev",
    "sqlparse.sql.where": "https://sqlparse.readthedocs.io/en/latest/analyzing.html#sqlparse.sql.Where",
}
