VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "sshtunnel": "https://sshtunnel.readthedocs.io/en/latest/",
    "sshtunnel.basesshtunnelforwardererror": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.BaseSSHTunnelForwarderError",
    "sshtunnel.check_address": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.check_address",
    "sshtunnel.check_addresses": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.check_addresses",
    "sshtunnel.create_logger": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.create_logger",
    "sshtunnel.default_loglevel": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.DEFAULT_LOGLEVEL",
    "sshtunnel.default_ssh_directory": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.DEFAULT_SSH_DIRECTORY",
    "sshtunnel.handlersshtunnelforwardererror": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.HandlerSSHTunnelForwarderError",
    "sshtunnel.open_tunnel": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.open_tunnel",
    "sshtunnel.ssh_timeout": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSH_TIMEOUT",
    "sshtunnel.sshtunnelforwarder": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder",
    "sshtunnel.sshtunnelforwarder.check_tunnels": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.check_tunnels",
    "sshtunnel.sshtunnelforwarder.close": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.close",
    "sshtunnel.sshtunnelforwarder.daemon_forward_servers": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.daemon_forward_servers",
    "sshtunnel.sshtunnelforwarder.daemon_transport": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.daemon_transport",
    "sshtunnel.sshtunnelforwarder.get_agent_keys": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.get_agent_keys",
    "sshtunnel.sshtunnelforwarder.get_keys": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.get_keys",
    "sshtunnel.sshtunnelforwarder.is_active": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.is_active",
    "sshtunnel.sshtunnelforwarder.local_bind_addresses": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.local_bind_addresses",
    "sshtunnel.sshtunnelforwarder.local_bind_hosts": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.local_bind_hosts",
    "sshtunnel.sshtunnelforwarder.local_bind_ports": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.local_bind_ports",
    "sshtunnel.sshtunnelforwarder.local_is_up": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.local_is_up",
    "sshtunnel.sshtunnelforwarder.read_private_key_file": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.read_private_key_file",
    "sshtunnel.sshtunnelforwarder.restart": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.restart",
    "sshtunnel.sshtunnelforwarder.skip_tunnel_checkup": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.skip_tunnel_checkup",
    "sshtunnel.sshtunnelforwarder.start": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.start",
    "sshtunnel.sshtunnelforwarder.stop": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.stop",
    "sshtunnel.sshtunnelforwarder.tunnel_bindings": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.tunnel_bindings",
    "sshtunnel.sshtunnelforwarder.tunnel_is_up": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.SSHTunnelForwarder.tunnel_is_up",
    "sshtunnel.tunnel_timeout": "https://sshtunnel.readthedocs.io/en/latest/#sshtunnel.TUNNEL_TIMEOUT",
}
