VERSION = "1.0.8.post1"

# fmt: off
MAPPING = {
    "usort": "https://usort.readthedocs.io/en/stable/",
    "usort.config": "https://usort.readthedocs.io/en/stable/api.html#usort.Config",
    "usort.config.categories": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.categories",
    "usort.config.category": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.category",
    "usort.config.default_category": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.default_category",
    "usort.config.excludes": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.excludes",
    "usort.config.find": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.find",
    "usort.config.first_party_detection": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.first_party_detection",
    "usort.config.is_side_effect_import": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.is_side_effect_import",
    "usort.config.known": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.known",
    "usort.config.line_length": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.line_length",
    "usort.config.merge_imports": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.merge_imports",
    "usort.config.side_effect_modules": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.side_effect_modules",
    "usort.config.side_effect_re": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.side_effect_re",
    "usort.config.update_from_config": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.update_from_config",
    "usort.config.with_first_party": "https://usort.readthedocs.io/en/stable/api.html#usort.Config.with_first_party",
    "usort.result": "https://usort.readthedocs.io/en/stable/api.html#usort.Result",
    "usort.result.content": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.content",
    "usort.result.encoding": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.encoding",
    "usort.result.error": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.error",
    "usort.result.output": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.output",
    "usort.result.path": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.path",
    "usort.result.timings": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.timings",
    "usort.result.trace": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.trace",
    "usort.result.warnings": "https://usort.readthedocs.io/en/stable/api.html#usort.Result.warnings",
    "usort.sortwarning": "https://usort.readthedocs.io/en/stable/api.html#usort.SortWarning",
    "usort.sortwarning.line": "https://usort.readthedocs.io/en/stable/api.html#usort.SortWarning.line",
    "usort.sortwarning.message": "https://usort.readthedocs.io/en/stable/api.html#usort.SortWarning.message",
    "usort.usort": "https://usort.readthedocs.io/en/stable/api.html#usort.usort",
    "usort.usort_file": "https://usort.readthedocs.io/en/stable/api.html#usort.usort_file",
    "usort.usort_path": "https://usort.readthedocs.io/en/stable/api.html#usort.usort_path",
    "usort.usort_stdin": "https://usort.readthedocs.io/en/stable/api.html#usort.usort_stdin",
}
