VERSION = "1.37.1"

# fmt: off
MAPPING = {
    "yamllint": "https://yamllint.readthedocs.io/en/stable/",
    "yamllint.linter": "https://yamllint.readthedocs.io/en/stable/development.html",
    "yamllint.linter.lintproblem": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.LintProblem",
    "yamllint.linter.lintproblem.column": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.LintProblem.column",
    "yamllint.linter.lintproblem.desc": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.LintProblem.desc",
    "yamllint.linter.lintproblem.line": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.LintProblem.line",
    "yamllint.linter.lintproblem.rule": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.LintProblem.rule",
    "yamllint.linter.run": "https://yamllint.readthedocs.io/en/stable/development.html#yamllint.linter.run",
    "yamllint.rules": "https://yamllint.readthedocs.io/en/stable/rules.html",
    "yamllint.rules.anchors": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.anchors",
    "yamllint.rules.braces": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.braces",
    "yamllint.rules.brackets": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.brackets",
    "yamllint.rules.colons": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons",
    "yamllint.rules.commas": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.commas",
    "yamllint.rules.comments": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments",
    "yamllint.rules.comments_indentation": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation",
    "yamllint.rules.document_end": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_end",
    "yamllint.rules.document_start": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start",
    "yamllint.rules.empty_lines": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.empty_lines",
    "yamllint.rules.empty_values": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.empty_values",
    "yamllint.rules.float_values": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.float_values",
    "yamllint.rules.hyphens": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.hyphens",
    "yamllint.rules.indentation": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation",
    "yamllint.rules.key_duplicates": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.key_duplicates",
    "yamllint.rules.key_ordering": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.key_ordering",
    "yamllint.rules.line_length": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length",
    "yamllint.rules.new_line_at_end_of_file": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.new_line_at_end_of_file",
    "yamllint.rules.new_lines": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.new_lines",
    "yamllint.rules.octal_values": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.octal_values",
    "yamllint.rules.quoted_strings": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings",
    "yamllint.rules.trailing_spaces": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.trailing_spaces",
    "yamllint.rules.truthy": "https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy",
}
