from pathlib import Path
from typing import Any, Optional, Tuple, Type, Union

import numpy as np
import numpy.typing as npt

from . import affines as affines
from . import orientations as orientations

__all__ = [
    "Nifti1Header",
    "Nifti1Image",
    "FileBasedImage",
    "load",
    "save",
    "affines",
    "orientations",
]

class Nifti1Header:
    def get_zooms(self) -> Tuple[float, ...]: ...
    def set_zooms(self, zooms: Tuple[float, ...]) -> None: ...
    def set_qform(self, affine: npt.NDArray[np.float64], code: int) -> None: ...
    def set_sform(self, affine: npt.NDArray[np.float64], code: int) -> None: ...
    def set_xyzt_units(self, xyz: str = "unknown", t: str = "unknown") -> None: ...
    def set_data_dtype(self, dtype: Union[np.dtype, Type[np.uint8]]) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

class Nifti1Image:
    def __init__(self, dataobj: npt.NDArray[Any], affine: npt.NDArray[np.float64], header: Optional[Nifti1Header] = None) -> None: ...
    header: Nifti1Header
    affine: npt.NDArray[np.float64]
    shape: Tuple[int, ...]

    def get_fdata(self) -> npt.NDArray[Any]: ...
    def get_data(self) -> npt.NDArray[Any]: ...
    def to_bytes(self) -> bytes: ...
    def to_filename(self, filename: Union[str, Path]) -> None: ...

# FileBasedImage is what load() actually returns - it's compatible with Nifti1Image
class FileBasedImage(Nifti1Image):
    pass

def load(filename: Union[str, Path]) -> FileBasedImage: ...
def save(img: Nifti1Image, filename: Union[str, Path]) -> None: ...
