from typing import Any, Tuple
import numpy as np
import numpy.typing as npt

def io_orientation(affine: npt.NDArray[np.float64]) -> npt.NDArray[Any]: ...
def axcodes2ornt(axcodes: Tuple[str, ...]) -> npt.NDArray[Any]: ...
def ornt_transform(ornt1: npt.NDArray[Any], ornt2: npt.NDArray[Any]) -> npt.NDArray[Any]: ...
def apply_orientation(arr: npt.NDArray[Any], ornt: npt.NDArray[Any]) -> npt.NDArray[Any]: ...
def inv_ornt_aff(ornt: npt.NDArray[Any], shape: Tuple[int, ...]) -> npt.NDArray[np.float64]: ...

