HEALTH = {
    "bluebell jar": 24,
    "blue dye": 6,
    "bluebell": 10,
    "bluebell grown": 14,
    "bookshelf": 8,
    "bowl": 6,
    "brick": 12,
    "brick floor": 8,
    "burner drill": 20,
    "campfire": 8,
    "carrot grown": 8,
    "carrot": 4,
    "clay": 12,
    "coal ore": 20,
    "coal": 8,
    "coal block": 32,
    "composter": 8,
    "copper anvil": 16,
    "copper axe": 12,
    "copper block": 24,
    "copper boiler": 40,
    "copper brick": 12,
    "copper brick floor": 8,
    "copper constructor": 32,
    "copper door": 8,
    "copper door open": 8,
    "copper gear": 10,
    "copper hammer": 12,
    "copper ingot": 16,
    "copper needle": 12,
    "copper ore": 30,
    "copper pickaxe": 12,
    "copper pipe": 12,
    "copper pit grown": 20,
    "copper press": 24,
    "copper pump": 20,
    "copper sapling": 8,
    "copper shaft": 12,
    "copper sheet": 12,
    "copper shovel": 12,
    "copper sword": 12,
    "copper tank": 20,
    "copper tree": 16,
    "copper treeling": 12,
    "copper wrench": 12,
    "corpse": 1,
    "dirt": 5,
    "fertilizer": 5,
    "flint axe": 8,
    "flint hammer": 8,
    "flint pickaxe": 8,
    "flint shovel": 8,
    "flint sword": 8,
    "flint": 16,
    "furnace": 32,
    "glass": 8,
    "glass key": 1,
    "ice": 12,
    "junk": 1,
    "life crystal": 16,
    "log floor": 12,
    "log": 8,
    "manual press": 12,
    "masonry bench": 12,
    "moist dirt": 8,
    "mushroom block": 5,
    "mushroom door": 10,
    "mushroom door open": 10,
    "mushroom floor": 8,
    "mushroom shaper": 13,
    "mushroom stew": 6,
    "mushroom table": 10,
    "mushroom": 10,
    "paper": 8,
    "pebble": 8,
    "plant bouquet": 6,
    "potato": 6,
    "potato grown": 10,
    "rabbit adult": 10,
    "rabbit child": 6,
    "rabbit fur": 8,
    "rabbit meat": 6,
    "rail 0": 8,
    "rail 1": 8,
    "rail 2": 8,
    "rail 3": 8,
    "rail 4": 8,
    "rail 5": 8,
    "raw copper": 12,
    "raw tin": 16,
    "roasted mushroom": 8,
    "roasted rabbit meat": 10,
    "rock": 20,
    "rock axe": 10,
    "rock hammer": 10,
    "rock pickaxe": 10,
    "rock shovel": 10,
    "rock sword": 10,
    "sand": 6,
    "sapling": 4,
    "sawbench": 12,
    "sewbench": 12,
    "skeleton": 16,
    "slife crystal": 20,
    "slime": 20,
    "slime ball": 6,
    "slime block": 5,
    "slime crystal": 8,
    "slime door": 10,
    "slime door open": 10,
    "slime floor": 8,
    "slime prince": 100,
    "slime shaper": 20,
    "slime table": 10,
    "small backpack": 16,
    "small barrel": 10,
    "small crate": 10,
    "spore": 4,
    "stick": 4,
    "stone brick": 16,
    "stone brick floor": 12,
    "stone": 16,
    "stone floor": 12,
    "thread": 12,
    "tin ingot": 20,
    "tin ore": 40,
    "tin treeling": 16,
    "tin tree": 20,
    "torch": 12,
    "tree": 10,
    "treeling": 9,
    "tree constructor": 16,
    "water": 8,
    "water axe": 10,
    "water hammer": 10,
    "water pickaxe": 10,
    "water shovel": 10,
    "water sword": 10,
    "wood crucible": 10,
    "wood door": 8,
    "wood door open": 8,
    "wood fence": 8,
    "wood fence pole": 6,
    "wood fence vertical": 8,
    "wood floor": 6,
    "wood": 4,
    "wooden bed": 12,
    "wooden sieve": 12,
    "wooden table": 8,
    "workbench": 5,
}
