# Generated by Django 3.0.3 on 2021-01-12 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mutationlog_client_mutation_details'),
        ('contribution_plan', '0004_auto_20201217_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPlanMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='contribution_plan.ContributionPlan')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contribution_plan', to='core.MutationLog')),
            ],
            options={
                'db_table': 'contribution_plan_ContributionPlanMutation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContributionPlanBundleMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_plan_bundle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='contribution_plan.ContributionPlanBundle')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contribution_plan_bundle', to='core.MutationLog')),
            ],
            options={
                'db_table': 'contribution_plan_bundle_ContributionPlanBundleMutation',
                'managed': True,
            },
        ),
    ]
