scrape_cal = {
    "currentStadiumsTitle": "list of current stadiums",
    "currentStadiumsTitleInfo": "The title of the section on wikipedia page https://en.wikipedia.org/wiki/List_of_current_NFL_stadiums pertaining to the current stadiums utilized by current NFL teams.",
    "currentStadiumsNumFromHeading": 2,
    "currentStadiumsNumFromHeadingInfo": "E.g., if current stadiums is the 2nd table in the section, 2. If it is the 1st, then 1.",
    "additionalStadiumsTitle": "special event stadiums",
    "additionalStadiumsTitleInfo": "The title of the section on wikipedia page https://en.wikipedia.org/wiki/List_of_current_NFL_stadiums pertaining to neutral fields that teams utilize for special events (e.g., global or hall of fame game)",
    "additionalStadiumsNumFromHeading": 1,
    "additionalStadiumsNumFromHeadingInfo": "E.g., if additional stadiums is the 2nd table in the section, 2. If it is the 1st, then 1."
}

city_short = \
    [
            "ARI",
            "ATL",
            "BAL",
            "BUF",
            "CAR",
            "CHI",
            "CIN",
            "CLE",
            "DAL",
            "DEN",
            "DET",
            "GB",
            "HOU",
            "IND",
            "JAX",
            "KC",
            "LV",
            "LAC",
            "LAR",
            "MIA",
            "MIN",
            "NE",
            "NO",
            "NYG",
            "NYJ",
            "PHI",
            "PIT",
            "SF",
            "SEA",
            "TB",
            "TEN",
            "WAS"
        ]

long = \
    [
            "Arizona Cardinals",
            "Atlanta Falcons",
            "Baltimore Ravens",
            "Buffalo Bills",
            "Carolina Panthers",
            "Chicago Bears",
            "Cincinnati Bengals",
            "Cleveland Browns",
            "Dallas Cowboys",
            "Denver Broncos",
            "Detroit Lions",
            "Green Bay Packers",
            "Houston Texans",
            "Indianapolis Colts",
            "Jacksonville Jaguars",
            "Kansas City Chiefs",
            "Las Vegas Raiders",
            "Los Angeles Chargers",
            "Los Angeles Rams",
            "Miami Dolphins",
            "Minnesota Vikings",
            "New England Patriots",
            "New Orleans Saints",
            "New York Giants",
            "New York Jets",
            "Philadelphia Eagles",
            "Pittsburgh Steelers",
            "San Francisco 49ers",
            "Seattle Seahawks",
            "Tampa Bay Buccaneers",
            "Tennessee Titans",
            "Washington Commanders"
        ]

mascots = \
    [
            "Cardinals",
            "Falcons",
            "Ravens",
            "Bills",
            "Panthers",
            "Bears",
            "Bengals",
            "Browns",
            "Cowboys",
            "Broncos",
            "Lions",
            "Packers",
            "Texans",
            "Colts",
            "Jaguars",
            "Chiefs",
            "Raiders",
            "Chargers",
            "Rams",
            "Dolphins",
            "Vikings",
            "Patriots",
            "Saints",
            "Giants",
            "Jets",
            "Eagles",
            "Steelers",
            "49ers",
            "Seahawks",
            "Buccaneers",
            "Titans",
            "Commanders"
        ]

alt_city_short = \
    [
            "ARZ",
            "ATL",
            "BAL",
            "BUF",
            "CAR",
            "CHI",
            "CIN",
            "CLE",
            "DAL",
            "DEN",
            "DET",
            "GB",
            "HOU",
            "IND",
            "JAC",
            "KC",
            "LV",
            "LAC",
            "LAR",
            "MIA",
            "MIN",
            "NE",
            "NOR",
            "NYG",
            "NYJ",
            "PHI",
            "PIT",
            "SF",
            "SEA",
            "TB",
            "TEN",
            "WSH"
        ]

mascots_short = \
    [
            "Cards",
            "Falcons",
            "Ravens",
            "Bills",
            "Panthers",
            "Bears",
            "Bengals",
            "Browns",
            "Cowboys",
            "Broncos",
            "Lions",
            "Packers",
            "Texans",
            "Colts",
            "Jags",
            "Chiefs",
            "Raiders",
            "Chargers",
            "Rams",
            "Dolphins",
            "Vikings",
            "Pats",
            "Saints",
            "Giants",
            "Jets",
            "Eagles",
            "Steelers",
            "49ers",
            "Hawks",
            "Bucs",
            "Titans",
            "Commanders"
        ]
