from typing import Protocol


class LoggerType(Protocol):
    def log(self, *_, **__): ...

    def debug(self, *_, **__): ...

    def info(self, *_, **__): ...

    def warning(self, *_, **__): ...

    def warn(self, *_, **__): ...

    def error(self, *_, **__): ...

    def critical(self, *_, **__): ...

    def exception(self, *_, **__): ...