#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2506-31-ga34e6d60"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2506
#define NETGEN_VERSION_TWEAK 31
#define NETGEN_VERSION_HASH "ga34e6d60"
#endif // NETGEN_VERSION_HPP_INCLUDED
