
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-07T12:33:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b24cb8877205a775f00bad6e8bcd6b5433ef784",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
