from typing import Any, Callable, Optional


class Library():

    def __init__(self):
        ...

    parents: tuple[Library, ...] = ...
    gates: dict = ...
    opaques: dict = ...

    def gate(self, qnum: int = 1, name: Optional[str] = ...):
        ...

    def opaque(self, name: str, type: str = ..., params: Optional[dict] = ...):
        ...

    def getGate(self, name: str) -> Callable:
        ...

    def getOpaque(self, name: str, type: str = ...) -> tuple[Callable, dict]:
        ...

    def __getstate__(self) -> dict[str, Any]:
        ...

    def __setstate__(self, state: dict[str, Any]):
        ...


def libraries(*libs: Library) -> Library:
    ...
