from typing import Protocol, AsyncIterator, List
from cuea.models import OrderRequest, Order, Ticker, Balance, OptionsChain, OptionsOrder, MarginBalance, MarginPosition

class BaseMarketAdapter(Protocol):
    name: str
    async def fetch_ticker(self, symbol: str) -> Ticker: ...
    async def fetch_orderbook(self, symbol: str): ...
    async def create_order(self, req: OrderRequest) -> Order: ...
    async def cancel_order(self, order_id: str, symbol: str) -> bool: ...
    async def fetch_order(self, order_id: str, symbol: str) -> Order: ...
    async def fetch_balances(self) -> List[Balance]: ...
    async def ws_subscribe_trades(self, symbol: str) -> AsyncIterator: ...

    # options (optional)
    async def fetch_options_chain(self, underlying: str) -> OptionsChain: ...
    async def create_options_order(self, req: OrderRequest) -> OptionsOrder: ...

    # margin (optional)
    async def fetch_margin_balances(self) -> List[MarginBalance]: ...
    async def fetch_margin_positions(self) -> List[MarginPosition]: ...
