from enum import Enum

class FlowActionKind(str, Enum):
    Http = "Http",
    PowerApp = "PowerApp",
    PowerAppV2 = "PowerAppV2",
    Button = "Button",
    ApiConnection = "ApiConnection",
    Alert = "Alert",
    EventGrid = "EventGrid",
    CurrentTime = "CurrentTime",
    ConvertTimeZone = "ConvertTimeZone",
    GetFutureTime = "GetFutureTime",
    GetPastTime = "GetPastTime",
    AddToTime = "AddToTime",
    SubtractFromTime = "SubtractFromTime",
    AzureMonitorAlert = "AzureMonitorAlert",
    SecurityCenterAlert = "SecurityCenterAlert",
    JsonToJson = "JsonToJson",
    JsonToText = "JsonToText",
    XmlToJson = "XmlToJson",
    XmlToText = "XmlToText",
    Geofence = "Geofence",
    ODataOpenApiConnection = "ODataOpenApiConnection",
    IndexOf = "IndexOf",
    Substring = "Substring",
    VirtualAgent = "VirtualAgent",
    FormatNumber = "FormatNumber",
    Skills = "Skills",
    PowerPages = "PowerPages",
    TeamsWebhook = "TeamsWebhook",

