"""Fix small issues in FIT files generated by Tymewear

Author: Dominik Rappaport
eMail: dominik@rappaport.at
"""

__version__ = "0.1.0"
__author__ = "Dominik Rappaport"
__email__ = "dominik@rappaport.at"
__license__ = "MIT"
__url__ = "https://github.com/dominikrappaport/FITFixer"
__description__ = "Fixes small issues of FIT files generated by Tymewear"
__keywords__ = "fit tymewear"
__package_name__ = "fitfix"
__readme_name__ = "README.md"
