"""Type stubs for all generated components."""

from .animated_image import animated_image as animated_image
from .animation import animation as animation
from .avatar import avatar as avatar
from .badge import badge as badge
from .breadcrumb import breadcrumb as breadcrumb
from .breadcrumb_item import breadcrumb_item as breadcrumb_item
from .button import button as button
from .button_group import button_group as button_group
from .callout import callout as callout
from .card import card as card
from .carousel import carousel as carousel
from .carousel_item import carousel_item as carousel_item
from .checkbox import checkbox as checkbox
from .color_picker import color_picker as color_picker
from .comparison import comparison as comparison
from .copy_button import copy_button as copy_button
from .details import details as details
from .dialog import dialog as dialog
from .divider import divider as divider
from .drawer import drawer as drawer
from .dropdown import dropdown as dropdown
from .dropdown_item import dropdown_item as dropdown_item
from .format_bytes import format_bytes as format_bytes
from .format_date import format_date as format_date
from .format_number import format_number as format_number
from .icon import icon as icon
from .include import include as include
from .input import input as input
from .intersection_observer import intersection_observer as intersection_observer
from .mutation_observer import mutation_observer as mutation_observer
from .option import option as option
from .popover import popover as popover
from .popup import popup as popup
from .progress_bar import progress_bar as progress_bar
from .progress_ring import progress_ring as progress_ring
from .qr_code import qr_code as qr_code
from .radio import radio as radio
from .radio_group import radio_group as radio_group
from .rating import rating as rating
from .relative_time import relative_time as relative_time
from .resize_observer import resize_observer as resize_observer
from .scroller import scroller as scroller
from .select import select as select
from .skeleton import skeleton as skeleton
from .slider import slider as slider
from .spinner import spinner as spinner
from .split_panel import split_panel as split_panel
from .switch import switch as switch
from .tab import tab as tab
from .tab_group import tab_group as tab_group
from .tab_panel import tab_panel as tab_panel
from .tag import tag as tag
from .textarea import textarea as textarea
from .tooltip import tooltip as tooltip
from .tree import tree as tree
from .tree_item import tree_item as tree_item
from .zoomable_frame import zoomable_frame as zoomable_frame

__all__: list[str]