"""
Schemas module for Acerta SDK
"""

from .agreement import AgreementGet, AgreementRemunerationBankAccountCreate, AgreementRemunerationBankAccountUpdate
from .family import (
    FamilyMemberGet,
    FamilySituationGet,
    FamilySituationUpdate,
    FamilyMemberCreate,
    FamilyMemberPersonalia,
    FamilyMemberName,
    FamilyMemberOther,
    CivilStatus,
    Partner,
    DependantsChildren,
    DependantsOver65,
    DependantsOthers,
    Dependants,
    FiscalDetails
)
from .bank_account import BankAccountUpdate, BankOwner, OwnerName, BankDetails
from .employee import (
    AdditionalInformationGet,
    AdditionalInformationUpdate,
    PersonalDetailsGet,
    PersonalDetailsUpdate,
    EmployeeName,
    EmployeeBirth,
    AddressBase,
    ContactBase,
    EmergencyContactBase,
    EmployeePersonalDetails,
    EmployeeAddressDetails,
    EmployeeAdditionalInformation,
    EmployeeContactInformation,
    EmployeeCivilStatus,
    EmployeePartner,
    EmployeeDependants,
    EmployeeDependantsChildren,
    EmployeeDependantsOver65,
    EmployeeDependantsOthers,
    EmployeeFiscalDetails,
    EmployeeFamilySituation,
    EmployeeBankDetails,
    EmployeeForeignBankAccount,
    EmployeeBankAccountOwner,
    EmployeeBankAccount,
    EmployeeCreate
)
from .contact_information import ContactInformationGet, ContactInformationUpdate, Contact, EmergencyContact
from .address import AddressGet, AddressUpdate, Address, OfficialAddressUpdate, CorrespondenceAddressUpdate
from .planning import CountryGet, BelgianCityGet
from .employer import JointCommitteeGet, FunctionGet, SalaryCodeGet
from .in_service import EmploymentCreate, EmploymentRehire
from .cost_center import CostCenterGet, CostCenterCreate, CostCenterDescription, CostCenterPeriod
from .salaries import BasicSalaryGet, PatchBasicSalariesRequest
from .company_car import CompanyCarGet, CompanyCarCreate, CompanyCarUpdate

__all__ = [
    'AgreementGet',
    'AgreementRemunerationBankAccountCreate',
    'AgreementRemunerationBankAccountUpdate',
    'FamilyMemberGet',
    'FamilySituationGet',
    'FamilySituationUpdate',
    'FamilyMemberCreate',
    'FamilyMemberPersonalia',
    'FamilyMemberName',
    'FamilyMemberOther',
    'CivilStatus',
    'Partner',
    'DependantsChildren',
    'DependantsOver65',
    'DependantsOthers',
    'Dependants',
    'FiscalDetails',
    'BankAccountLinkGet',
    'BankAccountUpdate',
    'BankOwner',
    'OwnerName',
    'BankDetails',
    'EmployeeGet',
    'ContactInformationGet',
    'ContactInformationUpdate',
    'Contact',
    'EmergencyContact',
    'AddressGet',
    'AddressUpdate',
    'Address',
    'OfficialAddressUpdate',
    'CorrespondenceAddressUpdate',
    'AdditionalInformationGet',
    'AdditionalInformationUpdate',
    'PersonalDetailsGet',
    'PersonalDetailsUpdate',
    'EmployeeName',
    'EmployeeBirth',
    'AddressBase',
    'ContactBase',
    'EmergencyContactBase',
    'EmployeePersonalDetails',
    'EmployeeAddressDetails',
    'EmployeeAdditionalInformation',
    'EmployeeContactInformation',
    'EmployeeCivilStatus',
    'EmployeePartner',
    'EmployeeDependants',
    'EmployeeDependantsChildren',
    'EmployeeDependantsOver65',
    'EmployeeDependantsOthers',
    'EmployeeFiscalDetails',
    'EmployeeFamilySituation',
    'EmployeeBankDetails',
    'EmployeeForeignBankAccount',
    'EmployeeBankAccountOwner',
    'EmployeeBankAccount',
    'EmployeeCreate',
    'CountryGet',
    'BelgianCityGet',
    'JointCommitteeGet',
    'FunctionGet',
    'SalaryCodeGet',
    'EmploymentCreate',
    'EmploymentRehire',
    'CostCenterGet',
    'CostCenterCreate',
    'CostCenterDescription',
    'CostCenterPeriod',
    'BasicSalaryGet',
    'PatchBasicSalariesRequest',
    'CompanyCarGet',
    'CompanyCarCreate',
    'CompanyCarUpdate'
]
