from enum import Enum

class CapacityStatusMessageCode(str, Enum):
    AllCapacityAvailable = "AllCapacityAvailable",
    DBCapacityOver = "DBCapacityOver",
    LogOverDBCover = "LogOverDBCover",
    LogCapacityOver = "LogCapacityOver",
    FileOverDBCover = "FileOverDBCover",
    FileOverLogCover = "FileOverLogCover",
    FileOverDBAndLogCover = "FileOverDBAndLogCover",
    FileCapacityOver = "FileCapacityOver",
    DBAndLogOver = "DBAndLogOver",
    DBAndFileOver = "DBAndFileOver",
    LogAndFileOverDBCover = "LogAndFileOverDBCover",
    LogAndFileOver = "LogAndFileOver",
    AllCapacityOver = "AllCapacityOver",
    LegacyCapacityAvailable = "LegacyCapacityAvailable",
    LegacyCapacityOver = "LegacyCapacityOver",
    FinOpsAllCapacityAvailable = "FinOpsAllCapacityAvailable",
    FinOpsNotAvailable = "FinOpsNotAvailable",
    FinOpsAllCapacityOver = "FinOpsAllCapacityOver",
    FinOpsDBCapacityOver = "FinOpsDBCapacityOver",
    FinOpsFileCapacityOver = "FinOpsFileCapacityOver",
    LegacyCapacityMoreThanEightyFive = "LegacyCapacityMoreThanEightyFive",
    DBCapacityMoreThanEightyFive = "DBCapacityMoreThanEightyFive",
    LogCapacityMoreThanEightyFive = "LogCapacityMoreThanEightyFive",
    FileCapacityMoreThanEightyFive = "FileCapacityMoreThanEightyFive",
    DBAndFileCapacityMoreThanEightyFive = "DBAndFileCapacityMoreThanEightyFive",
    DBAndLogCapacityMoreThanEightyFive = "DBAndLogCapacityMoreThanEightyFive",
    LogAndFileCapacityMoreThanEightyFive = "LogAndFileCapacityMoreThanEightyFive",
    AllCapacityMoreThanEightyFive = "AllCapacityMoreThanEightyFive",

