from enum import Enum

class CapacityEntitlementType(str, Enum):
    None_ = "None",
    DatabaseBase = "DatabaseBase",
    DatabaseIncremental = "DatabaseIncremental",
    DatabaseAddOn = "DatabaseAddOn",
    FileBase = "FileBase",
    FileIncremental = "FileIncremental",
    FileAddOn = "FileAddOn",
    LogBase = "LogBase",
    LogAddOn = "LogAddOn",
    SubscriptionTrialDatabaseBase = "SubscriptionTrialDatabaseBase",
    SubscriptionTrialFileBase = "SubscriptionTrialFileBase",
    SubscriptionTrialLogBase = "SubscriptionTrialLogBase",
    SubscriptionTrialEnvironmentCountBase = "SubscriptionTrialEnvironmentCountBase",
    SubscriptionTrialEnvironmentCountIncremental = "SubscriptionTrialEnvironmentCountIncremental",
    TrialDatabaseBase = "TrialDatabaseBase",
    TrialFileBase = "TrialFileBase",
    TrialLogBase = "TrialLogBase",
    M365DatabaseBase = "M365DatabaseBase",
    M365DatabaseIncremental = "M365DatabaseIncremental",
    M365EnvironmentCountBase = "M365EnvironmentCountBase",
    M365EnvironmentCountIncremental = "M365EnvironmentCountIncremental",
    ApiCallCountIncremental = "ApiCallCountIncremental",
    ApiCallCountBase = "ApiCallCountBase",
    CapacityPassBase = "CapacityPassBase",
    FinOpsDatabaseBase = "FinOpsDatabaseBase",
    FinOpsDatabaseIncremental = "FinOpsDatabaseIncremental",
    FinOpsFileBase = "FinOpsFileBase",
    FinOpsFileIncremental = "FinOpsFileIncremental",

