# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.identity.v1 import auto_service_account_pb2 as spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2


class AutoServiceAccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list = channel.unary_unary(
                '/spaceone.api.identity.v1.AutoServiceAccount/list',
                request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountQuery.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsLists.FromString,
                )
        self.create = channel.unary_unary(
                '/spaceone.api.identity.v1.AutoServiceAccount/create',
                request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.FromString,
                )
        self.delete = channel.unary_unary(
                '/spaceone.api.identity.v1.AutoServiceAccount/delete',
                request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.renewal_get = channel.unary_unary(
                '/spaceone.api.identity.v1.AutoServiceAccount/renewal_get',
                request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountAsIsToBeList.FromString,
                )
        self.renewal_update = channel.unary_unary(
                '/spaceone.api.identity.v1.AutoServiceAccount/renewal_update',
                request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.FromString,
                )


class AutoServiceAccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def renewal_get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def renewal_update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoServiceAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountQuery.FromString,
                    response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsLists.SerializeToString,
            ),
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.FromString,
                    response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'renewal_get': grpc.unary_unary_rpc_method_handler(
                    servicer.renewal_get,
                    request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.FromString,
                    response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountAsIsToBeList.SerializeToString,
            ),
            'renewal_update': grpc.unary_unary_rpc_method_handler(
                    servicer.renewal_update,
                    request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.FromString,
                    response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.identity.v1.AutoServiceAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoServiceAccount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.identity.v1.AutoServiceAccount/list',
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountQuery.SerializeToString,
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsLists.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.identity.v1.AutoServiceAccount/create',
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.identity.v1.AutoServiceAccount/delete',
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def renewal_get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.identity.v1.AutoServiceAccount/renewal_get',
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountAsIsToBeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def renewal_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.identity.v1.AutoServiceAccount/renewal_update',
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountTargets.SerializeToString,
            spaceone_dot_api_dot_identity_dot_v1_dot_auto__service__account__pb2.AutoServiceAccountsInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
