bone_naming_mapping = {
    "metahuman": {
        'pelvis': 'pelvis',
        'pelvis.R': 'pelvis_r',
        'pelvis.L': 'pelvis_l',
        'spine': 'spine_01',
        'spine.001': 'spine_04',
        'neck': 'neck_01',
        'face': 'head',
        'shoulder.R': 'clavicle_r',
        'shoulder.L': 'clavicle_l',
        'upper_arm.R': 'upperarm_r',
        'upper_arm.L': 'upperarm_l',
        'forearm.R': 'lowerarm_r',
        'forearm.L': 'lowerarm_l',
        'hand.R': 'hand_r',
        'hand.L': 'hand_l',
        'thumb.carpal.R': 'thumb_metacarpal_r',
        'palm.01.R': 'index_mcarpal_r', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.02.R': 'middle_mcarpal_r', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.03.R': 'ring_mcarpal_r', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.04.R': 'pinky_mcarpal_r', # Changed name so the automatic retargeting in UE does not detect this bone
        'thumb.carpal.L': 'thumb_metacarpal_l',
        'palm.01.L': 'index_mcarpal_l', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.02.L': 'middle_mcarpal_l', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.03.L': 'ring_mcarpal_l', # Changed name so the automatic retargeting in UE does not detect this bone
        'palm.04.L': 'pinky_mcarpal_l', # Changed name so the automatic retargeting in UE does not detect this bone
        'thumb.01.R': 'thumb_01_r',
        'thumb.01.L': 'thumb_01_l',
        'thumb.02.R': 'thumb_02_r',
        'thumb.02.L': 'thumb_02_l',
        'thumb.03.R': 'thumb_03_r',
        'thumb.03.L': 'thumb_03_l',
        'f_index.01.R': 'index_01_r',
        'f_index.01.L': 'index_01_l',
        'f_index.02.R': 'index_02_r',
        'f_index.02.L': 'index_02_l',
        'f_index.03.R': 'index_03_r',
        'f_index.03.L': 'index_03_l',
        'f_middle.01.R': 'middle_01_r',
        'f_middle.01.L': 'middle_01_l',
        'f_middle.02.R': 'middle_02_r',
        'f_middle.02.L': 'middle_02_l',
        'f_middle.03.R': 'middle_03_r',
        'f_middle.03.L': 'middle_03_l',
        'f_ring.01.R': 'ring_01_r',
        'f_ring.01.L': 'ring_01_l',
        'f_ring.02.R': 'ring_02_r',
        'f_ring.02.L': 'ring_02_l',
        'f_ring.03.R': 'ring_03_r',
        'f_ring.03.L': 'ring_03_l',
        'f_pinky.01.R': 'pinky_01_r',
        'f_pinky.01.L': 'pinky_01_l',
        'f_pinky.02.R': 'pinky_02_r',
        'f_pinky.02.L': 'pinky_02_l',
        'f_pinky.03.R': 'pinky_03_r',
        'f_pinky.03.L': 'pinky_03_l',
        'thigh.R': 'thigh_r',
        'thigh.L': 'thigh_l',
        'shin.R': 'calf_r',
        'shin.L': 'calf_l',
        'foot.R': 'foot_r',
        'foot.L': 'foot_l',
        'heel.02.R': 'heel_r',
        'heel.02.L': 'heel_l',
    },
    "daz_g8.1": {
        'pelvis': 'hip',
        'spine': 'abdomenLower',
        'spine.001': 'chestLower',
        'neck': 'neckUpper',
        'face': 'head',
        'shoulder.R': 'rCollar',
        'shoulder.L': 'lCollar',
        'upper_arm.R': 'rShldrBend',
        'upper_arm.L': 'lShldrBend',
        'forearm.R': 'rForearmBend',
        'forearm.L': 'lForearmBend',
        'forearm_twist.R': 'rForearmTwist',
        'forearm_twist.L': 'lForearmTwist',
        'hand.R': 'rHand',
        'hand.L': 'lHand',
        'palm.01.R': 'rCarpal1',
        'palm.02.R': 'rCarpal2',
        'palm.03.R': 'rCarpal3',
        'palm.04.R': 'rCarpal4',
        'palm.01.L': 'lCarpal1',
        'palm.02.L': 'lCarpal2',
        'palm.03.L': 'lCarpal3',
        'palm.04.L': 'lCarpal4',
        'thumb.01.R': 'rThumb1',
        'thumb.01.L': 'lThumb1',
        'thumb.02.R': 'rThumb2',
        'thumb.02.L': 'lThumb2',
        'thumb.03.R': 'rThumb3',
        'thumb.03.L': 'lThumb3',
        'f_index.01.R': 'rIndex1',
        'f_index.01.L': 'lIndex1',
        'f_index.02.R': 'rIndex2',
        'f_index.02.L': 'lIndex2',
        'f_index.03.R': 'rIndex3',
        'f_index.03.L': 'lIndex3',
        'f_middle.01.R': 'rMid1',
        'f_middle.01.L': 'lMid1',
        'f_middle.02.R': 'rMid2',
        'f_middle.02.L': 'lMid2',
        'f_middle.03.R': 'rMid3',
        'f_middle.03.L': 'lMid3',
        'f_ring.01.R': 'rRing1',
        'f_ring.01.L': 'lRing1',
        'f_ring.02.R': 'rRing2',
        'f_ring.02.L': 'lRing2',
        'f_ring.03.R': 'rRing3',
        'f_ring.03.L': 'lRing3',
        'f_pinky.01.R': 'rPinky1',
        'f_pinky.01.L': 'lPinky1',
        'f_pinky.02.R': 'rPinky2',
        'f_pinky.02.L': 'lPinky2',
        'f_pinky.03.R': 'rPinky3',
        'f_pinky.03.L': 'lPinky3',
        'thigh.R': 'rThighBend',
        'thigh.L': 'lThighBend',
        'shin.R': 'rShin',
        'shin.L': 'lShin',
        'foot.R': 'rFoot',
        'foot.L': 'lFoot',
    }
}