

TIMEZONES_DICT = {
    'ACDT': {'name': 'Australia/Yancowinna', 'utc_offset': 10},
    'ACST': {'name': 'Australia/North', 'utc_offset': 9},
    'ADT': {'name': 'Canada/Atlantic', 'utc_offset': -3},
    'AEDT': {'name': 'Australia/Victoria', 'utc_offset': 11},
    'AEST': {'name': 'Australia/Queensland', 'utc_offset': 10},
    'AKDT': {'name': 'US/Alaska', 'utc_offset': -8},
    'AST': {'name': 'America/Virgin', 'utc_offset': -4},
    'AWST': {'name': 'Australia/West', 'utc_offset': 8},
    'CAT': {'name': 'Africa/Windhoek', 'utc_offset': 2},
    'CDT': {'name': 'US/Indiana-Starke', 'utc_offset': -5},
    'CET': {'name': 'Poland', 'utc_offset': 1},
    'CST': {'name': 'ROC', 'utc_offset': 8},
    'ChST': {'name': 'Pacific/Saipan', 'utc_offset': 10},
    'EAT': {'name': 'Indian/Mayotte', 'utc_offset': 3},
    'EDT': {'name': 'US/Michigan', 'utc_offset': -4},
    'EET': {'name': 'Libya', 'utc_offset': 2},
    'EST': {'name': 'Jamaica', 'utc_offset': -5},
    'GMT': {'name': 'GMT', 'utc_offset': 0},
    'HDT': {'name': 'US/Aleutian', 'utc_offset': -9},
    'HKT': {'name': 'Hongkong', 'utc_offset': 8},
    'HST': {'name': 'US/Hawaii', 'utc_offset': -10},
    'IST': {'name': 'Israel', 'utc_offset': 3},
    'JST': {'name': 'Japan', 'utc_offset': 9},
    'KST': {'name': 'ROK', 'utc_offset': 9},
    'MDT': {'name': 'US/Mountain', 'utc_offset': -6},
    'MET': {'name': 'MET', 'utc_offset': 1},
    'MSK': {'name': 'W-SU', 'utc_offset': 3},
    'MST': {'name': 'US/Arizona', 'utc_offset': -7},
    'NDT': {'name': 'Canada/Newfoundland', 'utc_offset': -2},
    'NZDT': {'name': 'Pacific/Auckland', 'utc_offset': 13},
    'PDT': {'name': 'US/Pacific', 'utc_offset': -7},
    'PKT': {'name': 'Asia/Karachi', 'utc_offset': 5},
    'PST': {'name': 'Asia/Manila', 'utc_offset': 8},
    'SAST': {'name': 'Africa/Mbabane', 'utc_offset': 2},
    'SST': {'name': 'US/Samoa', 'utc_offset': -11},
    'UTC': {'name': 'UTC', 'utc_offset': 0},
    'WAT': {'name': 'Africa/Porto-Novo', 'utc_offset': 1},
    'WET': {'name': 'WET', 'utc_offset': 0},
    'WIB': {'name': 'Asia/Pontianak', 'utc_offset': 7},
    'WIT': {'name': 'Asia/Jayapura', 'utc_offset': 9},
    'WITA': {'name': 'Asia/Ujung_Pandang', 'utc_offset': 8}
}
