# sleep
SLEEP_TIME = 5
LONG_SLEEP_TIME = 2
MONITOR_TIME_DEFAULT = "150"
# ENV VARIABLES
MONITOR_TIME_ENV = "MONITOR_TIME_ENV"
PROPHECY_PAT = "PROPHECY_PAT"

PROPHECY_URL = "PROPHECY_URL"

PROJECT_ID = "PROJECT_ID"
PIPELINE_ID = "PIPELINE_ID"
SEND_EMAIL = "SEND_EMAIL"
BRANCH = "BRANCH"
OUTPUT_DIR = "OUTPUT_DIR"
RECURSIVE_EXTRACT = "RECURSIVE_EXTRACT"
RUN_FOR_ALL_PIPELINES= "RUN_FOR_ALL_PIPELINES"
FMT = "FORMAT"

# EXCEL COLUMN NAMES
CATALOG_COL = "Target Catalog"
DB_COL = "Target Database"
TABLE_COL = "Target Table"
COLNAME_COL = "Column Name"
COLTYPE_COL = "Column Type"
COL_DESCRIPTION_COL = "Column Description"
PROCESS_NAME_COL = "Process Name"
PROCESS_DESCRIPTION = "Process Description"
PIPELINE_NAME_COL = "Pipeline Name"
INBOUND_COL = "Inbound/Outbound Connection"
UPSTREAM_TRANSFORMATION_COL = "Upstream Lineage"
DATASET_SOURCE_COL = "Source Full Path"
IS_OUTBOUND = "OUTBOUND"
IS_INBOUND = "INBOUND"
