"""Core functionality for WNote."""

from .database import (
    init_db,
    get_connection,
    create_note,
    get_notes,
    update_note,
    delete_note,
    get_all_tags,
    add_attachment,
    get_attachments,
    remove_attachment,
    add_reminder,
    get_reminders,
    complete_reminder,
    delete_reminder,
    get_notes_statistics,
    delete_tag,
    create_template,
    get_templates,
    link_notes,
    get_linked_notes,
)

from .config import (
    load_config,
    save_config,
    get_config,
    CONFIG_DIR,
    DB_PATH,
    CONFIG_PATH,
    ATTACHMENTS_DIR,
    BACKUP_DIR,
    TEMPLATES_DIR,
    ARCHIVE_DIR,
)

__all__ = [
    "init_db",
    "get_connection",
    "create_note",
    "get_notes",
    "update_note",
    "delete_note",
    "get_all_tags",
    "add_attachment",
    "get_attachments",
    "remove_attachment",
    "add_reminder",
    "get_reminders",
    "complete_reminder",
    "delete_reminder",
    "get_notes_statistics",
    "delete_tag",
    "create_template",
    "get_templates",
    "link_notes",
    "get_linked_notes",
    "load_config",
    "save_config",
    "get_config",
    "CONFIG_DIR",
    "DB_PATH",
    "CONFIG_PATH",
    "ATTACHMENTS_DIR",
    "BACKUP_DIR",
    "TEMPLATES_DIR",
    "ARCHIVE_DIR",
]

