from __future__ import annotations

SINGLE_TARGET_SUPPORTED_COUNT = 1
# Audio Processing Constants
SAMPLE_RATE_DEFAULT = 48000
SAMPLE_RATE_HALF = 24000

CHANNELS_MONO = 1
OUTPUT_DEVICE_BLOCK_SIZE = 1024
AUDIO_CHUNK_SECONDS = 0.5
AUDIO_CHUNK_DURATION_SECONDS = 2
BYTES_PER_SAMPLE = 2

# Audio Streaming Constants
DECODE_TIMEOUT = 10.0
MAX_FRAMES_PER_READ = 10

# Timing Constants
BOOT_TIMEOUT = 30.0
SHUTDOWN_TIMEOUT = 5.0
SLEEP_INTERVAL_SHORT = 0.01
SLEEP_INTERVAL_DEFAULT = 0.1
SLEEP_INTERVAL_MEDIUM = 0.3
SLEEP_INTERVAL_LONG = 1.0
QUEUE_READ_TIMEOUT = 1.0
DEBUG_TASK_CHECK_INTERVAL = 30.0

RT_DEFAULT_DURATION = 60.0

# Buffer and Queue Constants
AUDIO_BUFFER_PADDING_SEC = 60  # Extra buffer time in seconds
THREADPOOL_MAX_WORKERS = 32
DEVICE_ID_HASH_LENGTH = 8
MONITOR_MESSAGE_PREVIEW_LENGTH = 100
AUDIO_PROGRESS_LOG_INTERVAL = 100000

# EOF and Completion Constants
EMPTY_MESSAGE_THRESHOLD = 10
STATS_LOG_INTERVAL = 5.0

# Preprocessing Constants
FORCE_SPLIT_MIN_CHARACTERS_DEFAULT = 100
FORCE_SPLIT_MIN_SECONDS_DEFAULT = 6.0
MIN_SENTENCE_CHARACTERS_DEFAULT = 80
MIN_SENTENCE_SECONDS_DEFAULT = 4
MIN_SPLIT_INTERVAL_DEFAULT = 0.6
CONTEXT_SIZE_DEFAULT = 30
SEGMENTS_AFTER_RESTART_DEFAULT = 15
STEP_SIZE_DEFAULT = 5
MAX_STEPS_WITHOUT_EOS_DEFAULT = 3
FORCE_END_OF_SEGMENT_DEFAULT = 0.5

# Filler Phrases Constants
MIN_TRANSCRIPTION_LEN_DEFAULT = 40
MIN_TRANSCRIPTION_TIME_DEFAULT = 3
PHRASE_CHANCE_DEFAULT = 0.5

# TTS Constants
F0_VARIANCE_FACTOR_DEFAULT = 1.2
ENERGY_VARIANCE_FACTOR_DEFAULT = 1.5
SPEECH_TEMPO_ADJUSTMENT_FACTOR_DEFAULT = 0.75

# Queue Config Constants
DESIRED_QUEUE_LEVEL_MS_DEFAULT = 5000
MAX_QUEUE_LEVEL_MS_DEFAULT = 20000
QUEUE_MIN_TEMPO = 1.15
QUEUE_MAX_TEMPO = 1.45
AUTO_TEMPO_MAX_DELAY_MS_DEFAULT = 250
TEMPO_DECAY_DEFAULT = 0.35
TEMPO_SMOOTHING_DEFAULT = 0.005

# TranscriptionMessage Constants
MIN_ALIGNMENT_SCORE_DEFAULT = 0.2
MAX_ALIGNMENT_CER_DEFAULT = 0.8
SEGMENT_CONFIRMATION_SILENCE_THRESHOLD_DEFAULT = 0.7

# VAD Constants
VAD_THRESHOLD_DEFAULT = 0.5
VAD_LEFT_PADDING_DEFAULT = 1
VAD_RIGHT_PADDING_DEFAULT = 1


WS_MODE_INPUT_SAMPLE_RATE = 16000
WS_MODE_OUTPUT_SAMPLE_RATE = 24000
WS_MODE_CHANNELS = 1
WS_MODE_CHUNK_DURATION_MS = 320

WEBRTC_MODE_INPUT_SAMPLE_RATE = 48000
WEBRTC_MODE_OUTPUT_SAMPLE_RATE = 48000
WEBRTC_MODE_CHANNELS = 1
WEBRTC_MODE_CHUNK_DURATION_MS = 320

EOS_SILENCE_S = 10.0
