# from .alias_multi import run_module as alias_multi
# from .alias_purge import run_module as alias_purge
from .alias import run_module as alias
from .bind_acl import run_module as bind_acl
from .bind_blocklist import run_module as bind_blocklist
from .bind_domain import run_module as bind_domain
from .bind_general import run_module as bind_general
# from .bind_record_multi import run_module as bind_record_multi
from .bind_record import run_module as bind_record
from .cron import run_module as cron
from .dhcp_reservation import run_module as dhcp_reservation
from .dhcrelay_destination import run_module as dhcrelay_destination
from .dhcrelay_relay import run_module as dhcrelay_relay
from .frr_bfd_general import run_module as frr_bfd_general
from .frr_bfd_neighbor import run_module as frr_bfd_neighbor
from .frr_bgp_as_path import run_module as frr_bgp_as_path
from .frr_bgp_community_list import run_module as frr_bgp_community_list
from .frr_bgp_general import run_module as frr_bgp_general
from .frr_bgp_neighbor import run_module as frr_bgp_neighbor
from .frr_bgp_prefix_list import run_module as frr_bgp_prefix_list
from .frr_bgp_route_map import run_module as frr_bgp_route_map
from .frr_diagnostic import run_module as frr_diagnostic
from .frr_general import run_module as frr_general
from .frr_ospf3_general import run_module as frr_ospf3_general
from .frr_ospf3_interface import run_module as frr_ospf3_interface
from .frr_ospf_general import run_module as frr_ospf_general
from .frr_ospf_interface import run_module as frr_ospf_interface
from .frr_ospf_network import run_module as frr_ospf_network
from .frr_ospf_prefix_list import run_module as frr_ospf_prefix_list
from .frr_ospf_route_map import run_module as frr_ospf_route_map
from .frr_rip import run_module as frr_rip
from .gateway import run_module as gateway
from .ids_action import run_module as ids_action
from .ids_general import run_module as ids_general
from .ids_policy import run_module as ids_policy
from .ids_policy_rule import run_module as ids_policy_rule
from .ids_rule import run_module as ids_rule
from .ids_ruleset import run_module as ids_ruleset
from .ids_user_rule import run_module as ids_user_rule
from .interface_lagg import run_module as interface_lagg
from .interface_loopback import run_module as interface_loopback
from .interface_vip import run_module as interface_vip
from .interface_vlan import run_module as interface_vlan
from .interface_vxlan import run_module as interface_vxlan
from .ipsec_auth_local import run_module as ipsec_auth_local
from .ipsec_auth_remote import run_module as ipsec_auth_remote
from .ipsec_cert import run_module as ipsec_cert
from .ipsec_child import run_module as ipsec_child
from .ipsec_connection import run_module as ipsec_connection
from .ipsec_pool import run_module as ipsec_pool
from .ipsec_psk import run_module as ipsec_psk
from .ipsec_vti import run_module as ipsec_vti
from .meta_list import run_module as meta_list
from .meta_reload import run_module as meta_reload
from .monit_alert import run_module as monit_alert
from .monit_service import run_module as monit_service
from .monit_test import run_module as monit_test
from .nginx_general import run_module as nginx_general
from .nginx_upstream_server import run_module as nginx_upstream_server
from .openvpn_client_override import run_module as openvpn_client_override
from .openvpn_client import run_module as openvpn_client
from .openvpn_server import run_module as openvpn_server
from .openvpn_static_key import run_module as openvpn_static_key
from .openvpn_status import run_module as openvpn_status
from .package import run_module as package
from .route import run_module as route
from .rule_interface_group import run_module as rule_interface_group
# from .rule_multi import run_module as rule_multi
# from .rule_purge import run_module as rule_purge
from .rule import run_module as rule
from .savepoint import run_module as savepoint
from .service import run_module as service
from .shaper_pipe import run_module as shaper_pipe
from .shaper_queue import run_module as shaper_queue
from .shaper_rule import run_module as shaper_rule
from .source_nat import run_module as source_nat
from .syslog import run_module as syslog
from .system import run_module as system
from .unbound_acl import run_module as unbound_acl
from .unbound_dnsbl import run_module as unbound_dnsbl
from .unbound_domain import run_module as unbound_domain
from .unbound_dot import run_module as unbound_dot
from .unbound_forward import run_module as unbound_forward
from .unbound_general import run_module as unbound_general
from .unbound_host_alias import run_module as unbound_host_alias
from .unbound_host import run_module as unbound_host
from .webproxy_acl import run_module as webproxy_acl
from .webproxy_auth import run_module as webproxy_auth
from .webproxy_cache import run_module as webproxy_cache
from .webproxy_forward import run_module as webproxy_forward
from .webproxy_general import run_module as webproxy_general
from .webproxy_icap import run_module as webproxy_ica
from .webproxy_pac_match import run_module as webproxy_ac_match
from .webproxy_pac_proxy import run_module as webproxy_pac_proxy
from .webproxy_pac_rule import run_module as webproxy_pac_rule
from .webproxy_parent import run_module as webproxy_parent
from .webproxy_remote_acl import run_module as webproxy_remote_acl
from .webproxy_traffic import run_module as webproxy_traffic
from .wireguard_general import run_module as wireguard_general
from .wireguard_peer import run_module as wireguard_eer
from .wireguard_server import run_module as wireguard_server
from .wireguard_show import run_module as wireguard_show
