from canaerospace.datatypes import DataType
from canaerospace.units import unit_map as units


#  @TODO Replace the norms unit with the correct unit per parameter
def get_electric_system_data_parameters():
    """Electric System data 5.6"""
    return [{"name": "ac_system_1_voltage", "can_id": 900, "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_2_voltage", "can_id": 901,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_3_voltage", "can_id": 902,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_4_voltage", "can_id": 903,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_5_voltage", "can_id": 904,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_6_voltage", "can_id": 905,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_7_voltage", "can_id": 906,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_8_voltage", "can_id": 907,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_9_voltage", "can_id": 908,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "ac_system_10_voltage", "can_id": 909,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},

            {"name": "ac_system_1_current", "can_id": 910,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_2_current", "can_id": 911,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_3_current", "can_id": 912,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_4_current", "can_id": 913,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_5_current", "can_id": 914,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_6_current", "can_id": 915,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_7_current", "can_id": 916,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_8_current", "can_id": 917,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_9_current", "can_id": 918,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "ac_system_10_current", "can_id": 919,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},

            {"name": "dc_system_1_voltage", "can_id": 920,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_2_voltage", "can_id": 921,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_3_voltage", "can_id": 922,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_4_voltage", "can_id": 923,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_5_voltage", "can_id": 924,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_6_voltage", "can_id": 925,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_7_voltage", "can_id": 926,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_8_voltage", "can_id": 927,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_9_voltage", "can_id": 928,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},
            {"name": "dc_system_10_voltage", "can_id": 929,
                "data_type": DataType.FLOAT, "unit": units.get("volt")},

            {"name": "dc_system_1_current", "can_id": 930,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_2_current", "can_id": 931,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_3_current", "can_id": 932,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_4_current", "can_id": 933,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_5_current", "can_id": 934,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_6_current", "can_id": 935,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_7_current", "can_id": 936,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_8_current", "can_id": 937,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_9_current", "can_id": 938,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},
            {"name": "dc_system_10_current", "can_id": 939,
                "data_type": DataType.FLOAT, "unit": units.get("ampere")},

            {"name": "prop_1_iceguard_dc_current", "can_id": 940, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_2_iceguard_dc_current", "can_id": 941, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_3_iceguard_dc_current", "can_id": 942, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_4_iceguard_dc_current", "can_id": 943, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_5_iceguard_dc_current", "can_id": 944, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_6_iceguard_dc_current", "can_id": 945, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_7_iceguard_dc_current", "can_id": 946, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_8_iceguard_dc_current", "can_id": 947, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_9_iceguard_dc_current", "can_id": 948, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")},
            {"name": "prop_10_iceguard_dc_current", "can_id": 949, "data_type": DataType.FLOAT,
             "unit": units.get("ampere")}, ]
