ATTRIBUTES = {
    "burner drill": {"open", "machine", "drill"},
    "campfire": {"open", "craft"},
    "composter": {"open", "machine"},
    "copper anvil": {"open", "craft"},
    "copper boiler": {"open", "machine"},
    "copper constructor": {"open", "machine"},
    "copper press": {"open", "machine"},
    "furnace": {"open", "machine"},
    "left": {"point"},
    "manual press": {"open", "craft"},
    "masonry bench": {"open", "craft"},
    "mushroom shaper": {"open", "craft"},
    "mushroom table": {"store", "table"},
    "player": {"open", "craft"},
    "rabbit adult": {"animal"},
    "rabbit child": {"animal"},
    "sawbench": {"open", "craft"},
    "sewbench": {"open", "craft"},
    "skeleton": {"enemy"},
    "slime": {"enemy"},
    "slime prince": {"enemy"},
    "slime shaper": {"open", "craft"},
    "slime table": {"store", "table"},
    "small barrel": {"open", "store"},
    "small crate": {"open", "store"},
    "tree constructor": {"open", "craft"},
    "up": {"point"},
    "void convertor": {"open", "machine"},
    "void crate": {"open", "store"},
    "wood crucible": {"open", "machine"},
    "wooden bed": {"sleep"},
    "wooden sieve": {"open", "machine"},
    "wooden table": {"store", "table"},
    "workbench": {"open", "craft"},
}
