"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import SiLAFramework_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EchoBinaryValue_Parameters(google.protobuf.message.Message):
    """Parameters for EchoBinaryValue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARYVALUE_FIELD_NUMBER: builtins.int
    @property
    def BinaryValue(self) -> SiLAFramework_pb2.Binary:
        """The Binary value to be returned."""

    def __init__(
        self,
        *,
        BinaryValue: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["BinaryValue", b"BinaryValue"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["BinaryValue", b"BinaryValue"]) -> None: ...

global___EchoBinaryValue_Parameters = EchoBinaryValue_Parameters

@typing.final
class EchoBinaryValue_Responses(google.protobuf.message.Message):
    """Responses of EchoBinaryValue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECEIVEDVALUE_FIELD_NUMBER: builtins.int
    @property
    def ReceivedValue(self) -> SiLAFramework_pb2.Binary:
        """The received Binary value transmitted in the same way it has been received."""

    def __init__(
        self,
        *,
        ReceivedValue: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ReceivedValue", b"ReceivedValue"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ReceivedValue", b"ReceivedValue"]) -> None: ...

global___EchoBinaryValue_Responses = EchoBinaryValue_Responses

@typing.final
class EchoBinariesObservably_Parameters(google.protobuf.message.Message):
    """Parameters for EchoBinariesObservably"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARIES_FIELD_NUMBER: builtins.int
    @property
    def Binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[SiLAFramework_pb2.Binary]:
        """List of binaries to echo"""

    def __init__(
        self,
        *,
        Binaries: collections.abc.Iterable[SiLAFramework_pb2.Binary] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Binaries", b"Binaries"]) -> None: ...

global___EchoBinariesObservably_Parameters = EchoBinariesObservably_Parameters

@typing.final
class EchoBinariesObservably_Responses(google.protobuf.message.Message):
    """Responses of EchoBinariesObservably"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINTBINARY_FIELD_NUMBER: builtins.int
    @property
    def JointBinary(self) -> SiLAFramework_pb2.Binary:
        """A single binary comprised of binaries received as parameter"""

    def __init__(
        self,
        *,
        JointBinary: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["JointBinary", b"JointBinary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["JointBinary", b"JointBinary"]) -> None: ...

global___EchoBinariesObservably_Responses = EchoBinariesObservably_Responses

@typing.final
class EchoBinariesObservably_IntermediateResponses(google.protobuf.message.Message):
    """Intermediate responses of EchoBinariesObservably"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARY_FIELD_NUMBER: builtins.int
    @property
    def Binary(self) -> SiLAFramework_pb2.Binary:
        """Single binary from the parameter list"""

    def __init__(
        self,
        *,
        Binary: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Binary", b"Binary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Binary", b"Binary"]) -> None: ...

global___EchoBinariesObservably_IntermediateResponses = EchoBinariesObservably_IntermediateResponses

@typing.final
class EchoBinaryAndMetadataString_Parameters(google.protobuf.message.Message):
    """Parameters for EchoBinaryAndMetadataString"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARY_FIELD_NUMBER: builtins.int
    @property
    def Binary(self) -> SiLAFramework_pb2.Binary:
        """The binary to echo"""

    def __init__(
        self,
        *,
        Binary: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Binary", b"Binary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Binary", b"Binary"]) -> None: ...

global___EchoBinaryAndMetadataString_Parameters = EchoBinaryAndMetadataString_Parameters

@typing.final
class EchoBinaryAndMetadataString_Responses(google.protobuf.message.Message):
    """Responses of EchoBinaryAndMetadataString"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARY_FIELD_NUMBER: builtins.int
    STRINGMETADATA_FIELD_NUMBER: builtins.int
    @property
    def Binary(self) -> SiLAFramework_pb2.Binary:
        """The received binary"""

    @property
    def StringMetadata(self) -> SiLAFramework_pb2.String:
        """The received String Metadata"""

    def __init__(
        self,
        *,
        Binary: SiLAFramework_pb2.Binary | None = ...,
        StringMetadata: SiLAFramework_pb2.String | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Binary", b"Binary", "StringMetadata", b"StringMetadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Binary", b"Binary", "StringMetadata", b"StringMetadata"]) -> None: ...

global___EchoBinaryAndMetadataString_Responses = EchoBinaryAndMetadataString_Responses

@typing.final
class Get_BinaryValueDirectly_Parameters(google.protobuf.message.Message):
    """Parameters for BinaryValueDirectly"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Get_BinaryValueDirectly_Parameters = Get_BinaryValueDirectly_Parameters

@typing.final
class Get_BinaryValueDirectly_Responses(google.protobuf.message.Message):
    """Responses of BinaryValueDirectly"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARYVALUEDIRECTLY_FIELD_NUMBER: builtins.int
    @property
    def BinaryValueDirectly(self) -> SiLAFramework_pb2.Binary:
        """Returns the UTF-8 encoded string 'SiLA2_Test_String_Value' directly transmitted as Binary value."""

    def __init__(
        self,
        *,
        BinaryValueDirectly: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["BinaryValueDirectly", b"BinaryValueDirectly"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["BinaryValueDirectly", b"BinaryValueDirectly"]) -> None: ...

global___Get_BinaryValueDirectly_Responses = Get_BinaryValueDirectly_Responses

@typing.final
class Get_BinaryValueDownload_Parameters(google.protobuf.message.Message):
    """Parameters for BinaryValueDownload"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Get_BinaryValueDownload_Parameters = Get_BinaryValueDownload_Parameters

@typing.final
class Get_BinaryValueDownload_Responses(google.protobuf.message.Message):
    """Responses of BinaryValueDownload"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARYVALUEDOWNLOAD_FIELD_NUMBER: builtins.int
    @property
    def BinaryValueDownload(self) -> SiLAFramework_pb2.Binary:
        """Returns the Binary Transfer UUID to be used to download the binary data which is the UTF-8 encoded string 'A_slightly_longer_SiLA2_Test_String_Value_used_to_demonstrate_the_binary_download', repeated 100,000 times."""

    def __init__(
        self,
        *,
        BinaryValueDownload: SiLAFramework_pb2.Binary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["BinaryValueDownload", b"BinaryValueDownload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["BinaryValueDownload", b"BinaryValueDownload"]) -> None: ...

global___Get_BinaryValueDownload_Responses = Get_BinaryValueDownload_Responses

@typing.final
class Get_FCPAffectedByMetadata_String_Parameters(google.protobuf.message.Message):
    """Parameters for Get_FCPAffectedByMetadata_String"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Get_FCPAffectedByMetadata_String_Parameters = Get_FCPAffectedByMetadata_String_Parameters

@typing.final
class Get_FCPAffectedByMetadata_String_Responses(google.protobuf.message.Message):
    """Responses of Get_FCPAffectedByMetadata_String"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AFFECTEDCALLS_FIELD_NUMBER: builtins.int
    @property
    def AffectedCalls(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[SiLAFramework_pb2.String]:
        """Fully qualified identifiers of all features, commands and properties affected by String"""

    def __init__(
        self,
        *,
        AffectedCalls: collections.abc.Iterable[SiLAFramework_pb2.String] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AffectedCalls", b"AffectedCalls"]) -> None: ...

global___Get_FCPAffectedByMetadata_String_Responses = Get_FCPAffectedByMetadata_String_Responses

@typing.final
class Metadata_String(google.protobuf.message.Message):
    """A string"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRING_FIELD_NUMBER: builtins.int
    @property
    def String(self) -> SiLAFramework_pb2.String:
        """A string"""

    def __init__(
        self,
        *,
        String: SiLAFramework_pb2.String | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["String", b"String"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["String", b"String"]) -> None: ...

global___Metadata_String = Metadata_String
