from setuptools import setup, find_packages

# Common dependencies
common_dependencies = [
    "aiohttp",
    "anthropic",
    "beautifulsoup4",
    "boto3",
    "botocore",
    "brui-core==1.0.9",
    "certifi==2025.4.26",
    "cryptography",
    "google-api-python-client",
    "google-genai==1.38.0",
    "httpx",
    "Jinja2",
    "mcp[cli]",
    "mistral_common",
    "mistralai",
    'numpy',
    "ollama",
    "openai",
    "requests",
    "rich",
    "textual",
    "tiktoken",
    "tokenizers",
]

setup(
    name="autobyteus",
    version="1.2.1",
    packages=find_packages(exclude=["tests", "tests.*"]),
    include_package_data=True,
    install_requires=[
        *common_dependencies,
    ],
    extras_require={
        "dev": [
            "coverage",
            "flake8",
            "numpy",
            "pre-commit",
            "black",
            "isort",
            "gitpython==3.1.31",
            "auto-gpt-plugin-template",
            "mkdocs",
            "pytest",
            "asynctest",
            "pytest-asyncio",
            "pytest-benchmark",
            "pytest-cov",
            "pytest-integration",
            "pytest-mock",
            "vcrpy",
            "pytest-vcr",
            "load_dotenv",
        ],
    },
    python_requires=">=3.8",
    author="Ryan Zheng",
    author_email="ryan.zheng.work@gmail.com",
    description="Multi-Agent framework",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/AutoByteus/autobyteus",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    package_data={
        "autobyteus": ["py.typed", "clients/certificates/cert.pem"],
    },
)
