from typing_extensions import TypedDict, Required, NotRequired, Callable, Literal, Any


class RouterSettings(TypedDict, total=False):
    handlers: Required[str]
    protobufs: NotRequired[str]
    base_path: NotRequired[str]
    host: NotRequired[str]
    port: NotRequired[int]
    reload: NotRequired[bool]
    verbose: NotRequired[bool]
    api_type: NotRequired[Literal['rest', 'grpc', 'graphql']]
    before_all: NotRequired[Callable]
    after_all: NotRequired[Callable]
    when_auth_required: NotRequired[Callable]
    on_error: NotRequired[Callable]
    on_timeout: NotRequired[Callable]
    cors: NotRequired[bool]
    cache_size: NotRequired[int]
    cache_mode: NotRequired[Literal['all', 'static-only', 'dynamic-only']]
    timeout: NotRequired[int]
    output_error: NotRequired[bool]
    openapi: NotRequired[str]
    openapi_validate_request: NotRequired[bool]
    openapi_validate_response: NotRequired[bool]
    openapi_validate_spec: NotRequired[bool]
    is_grpc: NotRequired[bool]
    grpc_endpoint: NotRequired[Any]
    default_error_message: NotRequired[str]
    reflection: NotRequired[bool]
    private_key: NotRequired[str]
    certificate: NotRequired[str]
