# Generated by Django 4.2.25 on 2025-11-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowApp', '0005_alter_order_response_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='response_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший заявку'),
        ),
        migrations.DeleteModel(
            name='Responsible',
        ),
    ]
