# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flexlogger/automation/proto/Application.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flexlogger/automation/proto/Application.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-flexlogger/automation/proto/Application.proto\x12.national_instruments.core.automation.protocols\"\x10\n\x0e\x43onnectRequest\"\x11\n\x0f\x43onnectResponse\"-\n\x11\x44isconnectRequest\x12\x18\n\x10\x65xit_application\x18\x01 \x01(\x08\"\x14\n\x12\x44isconnectResponse\" \n\x1eGetPreferencesDirectoryRequest\"@\n\x1fGetPreferencesDirectoryResponse\x12\x1d\n\x15preferences_directory\x18\x01 \x01(\t2\xf3\x03\n\x0b\x41pplication\x12\x8c\x01\n\x07\x43onnect\x12>.national_instruments.core.automation.protocols.ConnectRequest\x1a?.national_instruments.core.automation.protocols.ConnectResponse\"\x00\x12\x95\x01\n\nDisconnect\x12\x41.national_instruments.core.automation.protocols.DisconnectRequest\x1a\x42.national_instruments.core.automation.protocols.DisconnectResponse\"\x00\x12\xbc\x01\n\x17GetPreferencesDirectory\x12N.national_instruments.core.automation.protocols.GetPreferencesDirectoryRequest\x1aO.national_instruments.core.automation.protocols.GetPreferencesDirectoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flexlogger.automation.proto.Application_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=97
  _globals['_CONNECTREQUEST']._serialized_end=113
  _globals['_CONNECTRESPONSE']._serialized_start=115
  _globals['_CONNECTRESPONSE']._serialized_end=132
  _globals['_DISCONNECTREQUEST']._serialized_start=134
  _globals['_DISCONNECTREQUEST']._serialized_end=179
  _globals['_DISCONNECTRESPONSE']._serialized_start=181
  _globals['_DISCONNECTRESPONSE']._serialized_end=201
  _globals['_GETPREFERENCESDIRECTORYREQUEST']._serialized_start=203
  _globals['_GETPREFERENCESDIRECTORYREQUEST']._serialized_end=235
  _globals['_GETPREFERENCESDIRECTORYRESPONSE']._serialized_start=237
  _globals['_GETPREFERENCESDIRECTORYRESPONSE']._serialized_end=301
  _globals['_APPLICATION']._serialized_start=304
  _globals['_APPLICATION']._serialized_end=803
# @@protoc_insertion_point(module_scope)
