# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flexlogger.automation.proto import Events_pb2 as flexlogger_dot_automation_dot_proto_dot_Events__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flexlogger/automation/proto/Events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlexLoggerEventsStub(object):
    """Service interface for the FlexLogger events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvent = channel.unary_unary(
                '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/SendEvent',
                request_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeToEvents = channel.unary_stream(
                '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/SubscribeToEvents',
                request_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.SerializeToString,
                response_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.FromString,
                _registered_method=True)
        self.UnsubscribeFromEvents = channel.unary_unary(
                '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/UnsubscribeFromEvents',
                request_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.UnsubscribeFromEventsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterEvents = channel.unary_unary(
                '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/RegisterEvents',
                request_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRegisteredEvents = channel.unary_unary(
                '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/GetRegisteredEvents',
                request_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsRequest.SerializeToString,
                response_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsResponse.FromString,
                _registered_method=True)


class FlexLoggerEventsServicer(object):
    """Service interface for the FlexLogger events.
    """

    def SendEvent(self, request, context):
        """RPC call to send an event for test purposes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToEvents(self, request, context):
        """RPC call to subscribe to FlexLogger events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeFromEvents(self, request, context):
        """RPC call to unsubscribe from events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEvents(self, request, context):
        """RPC call to specify which events to subscribe to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisteredEvents(self, request, context):
        """RPC call to get which events are currently registered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlexLoggerEventsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvent,
                    request_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeToEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToEvents,
                    request_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.FromString,
                    response_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.SerializeToString,
            ),
            'UnsubscribeFromEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeFromEvents,
                    request_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.UnsubscribeFromEventsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegisterEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEvents,
                    request_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRegisteredEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisteredEvents,
                    request_deserializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsRequest.FromString,
                    response_serializer=flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_instruments.flex_logger.automation.protocols.FlexLoggerEvents', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_instruments.flex_logger.automation.protocols.FlexLoggerEvents', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlexLoggerEvents(object):
    """Service interface for the FlexLogger events.
    """

    @staticmethod
    def SendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/SendEvent',
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/SubscribeToEvents',
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.SerializeToString,
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeFromEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/UnsubscribeFromEvents',
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.UnsubscribeFromEventsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/RegisterEvents',
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.SubscribeToEventsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegisteredEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_instruments.flex_logger.automation.protocols.FlexLoggerEvents/GetRegisteredEvents',
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsRequest.SerializeToString,
            flexlogger_dot_automation_dot_proto_dot_Events__pb2.GetRegisteredEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
