#+title: bisos.crypt:  BPO Based Encryption/Decryption Facilities that provide vault, symetric and PKCS encryption, decryption, and hashing capabilities.


* Overview
bisos.crypt is a python package that uses the PyCS-Framework for NOTYET.
It is a BISOS-Capability and a Standalone-BISOS-Package.

/bisos.crypt/ is based on PyCS-Foundation and can be used both as a Command and
as a Service (invoke/perform model of remote operations) using RPYC for central
management of multiple systems.


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#part-of-bisos-----bystar-internet-services-operating-system][Part of BISOS --- ByStar Internet Services Operating System]]
- [[#bisoscrypt-is-a-command-services-pycs-facility][bisos.crypt is a Command Services (PyCS) Facility]]
-  [[#uses-of-bisoscrypt][Uses of bisos.crypt]]
- [[#bisoscrypt-as-a-standalone-piece-of-bisos][bisos.crypt as a Standalone Piece of BISOS]]
- [[#installation][Installation]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
- [[#usage][Usage]]
  - [[#locally-system-command-line][Locally (system command-line)]]
  - [[#remotely-as-a-service----performerinvoker][Remotely (as a service -- Performer+Invoker)]]
    - [[#performer][Performer]]
    - [[#invoker][Invoker]]
  - [[#use-by-python-script][Use by Python script]]
    - [[#bisoscrypt-source-code-is-in-writen-in-comeega-collaborative-org-mode-enhanced-emacs-generalized-authorship----httpsgithubcombx-bleecomeega][bisos.crypt Source Code is in writen in COMEEGA (Collaborative Org-Mode Enhanced Emacs Generalized Authorship) -- https://github.com/bx-blee/comeega.]]
    - [[#the-primary-api-for-bisoscrypt-is-bisoscryptcrypt-csupy-it-is-self-documented-in-comeega][The primary API for bisos.crypt is ./bisos/crypt/crypt-csu.py. It is self documented in COMEEGA.]]
- [[#documentation-and-blee-panels][Documentation and Blee-Panels]]
  - [[#bisoscrypt-blee-panels][bisos.crypt Blee-Panels]]
- [[#support][Support]]

* Part of BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.\\
*BISOS* is a foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is
described as a cure for losses of autonomy and privacy in a book titled: [[https://github.com/bxplpc/120033][Nature
of Polyexistentials]]

/bisos.crypt/ is part of BISOS.

* bisos.crypt is a Command Services (PyCS) Facility

bisos.crypt can be used locally on command-line or remotely as a service.
bisos.crypt is a PyCS multi-unit command-service.
PyCS is a framework that converges developement of CLI and Services.
PyCS is an alternative to FastAPI, Typer and Click.

bisos.crypt uses the PyCS Framework to:

1) Provide access to crypt facilities through native python.
2) Provide local access to crypt facilities on CLI.
3) Provide remote access to crypt facilities through remote invocation of
   python Expection Complete Operations using [[https://github.com/tomerfiliba-org/rpyc][rpyc]].
4) Provide remote access to crypt facilities on CLI.

What is unique in the PyCS-Framework is that these four models are all
a single abstraction.

The core of PyCS-Framework is the /bisos.b/ package (the PyCS-Foundation).
See https://github.com/bisos-pip/b for an overview.

*  Uses of bisos.crypt

Within BISOS,  bisos.crypt is used as a common facility.


* bisos.crypt as a Standalone Piece of BISOS

bisos.crypt is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installtion and usage
instructions below for your own use.

* Installation

The sources for the  bisos.crypt pip package is maintained at:
https://github.com/bisos-pip/crypt.

The bisos.crypt pip package is available at PYPI as
https://pypi.org/project/bisos.crypt

You can install bisos.crypt with pip or pipx.

** Installation With pip

If you need access to bisos.crypt as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.crypt
#+end_src

** Installation With pipx

If you only need access to bisos.crypt as a command on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.crypt
#+end_src

The following commands are made available:
- crypt.cs
- roInv-crypt.cs
- roPerf-crypt.cs

These are all one file with 3 names. _roInv-crypt.cs_ and _roPerf-crypt.cs_ are sym-links to _crypt.cs_

* Usage

** Locally (system command-line)

=crypt.cs= can be invoked directly as

#+begin_src bash
bin/crypt.cs
#+end_src

** Remotely (as a service -- Performer+Invoker)

You can also  run


*** Performer

Run performer as:

#+begin_src bash
bin/roPerf-crypt.cs
#+end_src

*** Invoker

Run invoker as:

#+begin_src bash
bin/roInv-crypt.cs
#+end_src

** Use by Python script

*** bisos.crypt Source Code is in writen in COMEEGA (Collaborative Org-Mode Enhanced Emacs Generalized Authorship) -- https://github.com/bx-blee/comeega.

*** The primary API for bisos.crypt is ./bisos/crypt/crypt-csu.py. It is self documented in COMEEGA.

* Documentation and Blee-Panels

bisos.crypt is part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in the form of Blee-Panels.
Additional information is also available in: [[http://www.by-star.net/PLPC/180047]]

** bisos.crypt Blee-Panels

bisos.crypt Blee-Panles are in ./panels directory.
From within Blee and BISOS these panles are accessible under the
Blee "Panels" menu.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


