# Generated by Django 3.2.20 on 2023-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_protection', '0009_add_schema_admin_and_schema_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitplan',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='historicalbenefitplan',
            name='holder',
        ),
        migrations.AddField(
            model_name='benefitplan',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenefitplan',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
