# Generated by Django 4.2.20 on 2025-06-27 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_protection', '0019_project_status_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiaries', to='social_protection.project'),
        ),
        migrations.AddField(
            model_name='groupbeneficiary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_beneficiaries', to='social_protection.project'),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='social_protection.project'),
        ),
        migrations.AddField(
            model_name='historicalgroupbeneficiary',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='social_protection.project'),
        ),
    ]
