SLANG_MAP = {
    "u": "you",
    "r": "are",
    "idk": "I do not know",
    "brb": "be right back",
    "finna": "going to",
    "gonna": "going to",
    "wanna": "want to",
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "imo": "in my opinion",
    "imho": "in my honest opinion",
    "btw": "by the way",
    "fwiw": "for what it's worth",
    "thx": "thanks",
    "ty": "thank you",
    "np": "no problem",
    "smh": "shaking my head",
    "tldr": "too long didn't read",
    "ngl": "not gonna lie",
    "fr": "for real",
    "rn": "right now",
    "on fleek": "perfectly executed",
    "goat": "greatest of all time",
    "af": "as fuck",
    "asap": "as soon as possible",
    "b-day": "birthday",
    "bday": "birthday",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "bff": "best friends forever",
    "cya": "see you",
    "dm": "direct message",
    "fomo": "fear of missing out",
    "gr8": "great",
    "idc": "I do not care",
    "ily": "I love you",
    "irl": "in real life",
    "jk": "just kidding",
    "l8r": "later",
    "omg": "oh my god",
    "omw": "on my way",
    "pls": "please",
    "plz": "please",
    "ppl": "people",
    "rip": "rest in peace",
    "sus": "suspicious",
    "tmi": "too much information",
    "ttyl": "talk to you later",
    "wyd": "what are you doing",
    "wya": "where are you at",
    "tbh": "to be honest",
    "fyi": "for your information",
    "hmu": "hit me up",
    "gucci": "good",
    "lit": "amazing",
    "fam": "family",
    "bet": "okay",
    "cap": "lie",
    "no cap": "no lie",
    "periodt": "end of discussion",
    "simp": "overly affectionate",
    "tea": "gossip",
    "yeet": "throw",
    "yolo": "you only live once",
    "basic": "common",
    "cringe": "embarrassing",
    "salty": "upset",
    "savage": "ruthless",
    "shook": "shocked",
    "slay": "did well",
    "stan": "obsessed fan",
    "vibe": "feeling",
    "woke": "aware",
    "hbu": "how about you",
    "gn": "good night",
    "gm": "good morning",
    "gtg": "got to go",
    "g2g": "got to go",
    "ilyk": "I'll let you know",
    "nvm": "nevermind",
    "ofc": "of course",
    "tbf": "to be fair"
}
