# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.inventory.v1 import finops_query_set_pb2 as spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2


class FinOpsQuerySetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/spaceone.api.inventory.v1.FinOpsQuerySet/create',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.CreateFinOpsQuerySetRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
                )
        self.update = channel.unary_unary(
                '/spaceone.api.inventory.v1.FinOpsQuerySet/update',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.UpdateFinOpsQuerySetRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
                )
        self.delete = channel.unary_unary(
                '/spaceone.api.inventory.v1.FinOpsQuerySet/delete',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get = channel.unary_unary(
                '/spaceone.api.inventory.v1.FinOpsQuerySet/get',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.GetFinOpsQuerySetRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
                )
        self.list = channel.unary_unary(
                '/spaceone.api.inventory.v1.FinOpsQuerySet/list',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetQuery.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetsInfo.FromString,
                )


class FinOpsQuerySetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinOpsQuerySetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.CreateFinOpsQuerySetRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.UpdateFinOpsQuerySetRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.GetFinOpsQuerySetRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.SerializeToString,
            ),
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetQuery.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetsInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.inventory.v1.FinOpsQuerySet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FinOpsQuerySet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.FinOpsQuerySet/create',
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.CreateFinOpsQuerySetRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.FinOpsQuerySet/update',
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.UpdateFinOpsQuerySetRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.FinOpsQuerySet/delete',
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.FinOpsQuerySet/get',
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.GetFinOpsQuerySetRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.FinOpsQuerySet/list',
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetQuery.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_finops__query__set__pb2.FinOpsQuerySetsInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
