# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from payrix.api_helper import APIHelper
from payrix.configuration import Server
from payrix.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from payrix.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from apimatic_core.authentication.multiple.or_auth_group import Or
from payrix.models.orgs_vas_tax_form_enablements_response_result import OrgsVASTaxFormEnablementsResponseResult
from payrix.exceptions.error_four_hundred_exception import ErrorFourHundredException


class OrgsVASTaxFormEnablementsController(BaseController):

    """A Controller to access Endpoints in the payrix API."""
    def __init__(self, config):
        super(OrgsVASTaxFormEnablementsController, self).__init__(config)

    def get_orgs_vas_tax_form_enablements_id(self,
                                             org_id,
                                             id,
                                             request_token=None):
        """Does a GET request to /orgs/{OrgId}/taxForms/{id}.

        Returns the details of a specific Orgs Tax Form Enablement
        configuration for an Org.

        Args:
            org_id (str): The Org ID this tax form enablement belongs to.
            id (str): The ID of this OrgsVASTaxFormEnablements.
            request_token (str, optional): A custom, one-time identifier for
                any API request (GET, PUT, POST, or DELETE). Blocks future
                requests with the same token for 48 hours, ensuring only the
                first request is processed. Valid values can contain 1-100
                alphanumeric and special characters. See <a
                href="/apis/payrix/dev-int-guide/references/request-tokens"
                target="_blank">Request Tokens</a>  for more information.

        Returns:
            OrgsVASTaxFormEnablementsResponseResult: Response from the API.
                Successfully retrieved the Tax Form Enablement configuration
                for an Org.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.PAYRIX)
            .path('/orgs/{OrgId}/taxForms/{id}')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('OrgId')
                            .value(org_id)
                            .should_encode(True))
            .template_param(Parameter()
                            .key('id')
                            .value(id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('request-token')
                          .value(request_token))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .auth(Or(Single('apiKey'), Single('sessionKey'), Single('txnSessionKey')))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(OrgsVASTaxFormEnablementsResponseResult.from_dictionary)
            .local_error('400', 'Error', ErrorFourHundredException)
        ).execute()

    def put_orgs_vas_tax_form_enablements_id(self,
                                             org_id,
                                             id,
                                             body):
        """Does a PUT request to /orgs/{OrgId}/taxForms/{id}.

        Update Orgs VAS Tax Form Enablements.

        Args:
            org_id (str): The Org ID this tax form enablement belongs to.
            id (str): The ID of this OrgsVASTaxFormEnablements.
            body (OrgsVASTaxFormEnablementsPutRequest): Request payload for
                updating Tax Form for an Org.

        Returns:
            OrgsVASTaxFormEnablementsResponseResult: Response from the API.
                Successfully updated the Tax Form Enablement configuration for
                the Org.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.PAYRIX)
            .path('/orgs/{OrgId}/taxForms/{id}')
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                            .key('OrgId')
                            .value(org_id)
                            .should_encode(True))
            .template_param(Parameter()
                            .key('id')
                            .value(id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Or(Single('apiKey'), Single('sessionKey'), Single('txnSessionKey')))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(OrgsVASTaxFormEnablementsResponseResult.from_dictionary)
            .local_error('400', 'Error', ErrorFourHundredException)
        ).execute()

    def delete_orgs_vas_tax_form_enablements_id(self,
                                                org_id,
                                                id):
        """Does a DELETE request to /orgs/{OrgId}/taxForms/{id}.

        Delete Tax form for an Org by ID.

        Args:
            org_id (str): The Org ID this tax form enablement belongs to.
            id (str): The ID of this Orgs VAS Tax Form Enablements.

        Returns:
            OrgsVASTaxFormEnablementsResponseResult: Response from the API.
                Successfully deleted the Tax Form Enablement configuration for
                the Org.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.PAYRIX)
            .path('/orgs/{OrgId}/taxForms/{id}')
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                            .key('OrgId')
                            .value(org_id)
                            .should_encode(True))
            .template_param(Parameter()
                            .key('id')
                            .value(id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .auth(Or(Single('apiKey'), Single('sessionKey'), Single('txnSessionKey')))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(OrgsVASTaxFormEnablementsResponseResult.from_dictionary)
            .local_error('400', 'Error', ErrorFourHundredException)
        ).execute()

    def get_orgs_vas_tax_form_enablements(self,
                                          org_id,
                                          request_token=None,
                                          search=None,
                                          totals=None,
                                          page_number=None,
                                          page_limit=None):
        """Does a GET request to /orgs/{OrgId}/taxForms.

        Returns a paginated list of Orgs Tax Form Enablements associated with
        a specific Org ID.

        Args:
            org_id (str): The Org ID this tax form enablement belongs to.
            request_token (str, optional): A custom, one-time identifier for
                any API request (GET, PUT, POST, or DELETE). Blocks future
                requests with the same token for 48 hours, ensuring only the
                first request is processed. Valid values can contain 1-100
                alphanumeric and special characters. See <a
                href="/apis/payrix/dev-int-guide/references/request-tokens"
                target="_blank">Request Tokens</a>  for more information.
            search (str, optional): Set this header to filter or sort the list
                of resources that the method returns.  See
                [Searches](page:welcome#searches) for detailed information and
                examples on how to use search header.
            totals (str, optional): To configure a request to return a total
                for all instances of a field in a result set,  use the totals
                header in the format `totals={operator}[]={key}`.  This will
                calculate the desired total and return it in the `details >
                totals` object of the response.  For instance, if you want to
                sum the `total` field of all transactions,  you would use the
                `sum` operator. The response will include the result set, 
                along with the calculated total in the `details` section. See
                [Collection Operators](page:welcome#collection-operators) for
                detailed information and examples on how to use totals header.
            page_number (int, optional): Set this path parameter to request a
                specific page of records.  For example, set `?page[number]=2`
                to retrieve the second page of records for this request.
            page_limit (int, optional): Set this path parameter to request up
                to a specific amount of records. By default 30 records are
                retrieved per page. The maximum limit that can be set is 100.
                For example, set `?page[limit]=50` to retrieve up to 50
                records for this request.

        Returns:
            OrgsVASTaxFormEnablementsResponseResult: Response from the API.
                Successfully retrieved Orgs Tax Form Enablements for an Org.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.PAYRIX)
            .path('/orgs/{OrgId}/taxForms')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('OrgId')
                            .value(org_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('request-token')
                          .value(request_token))
            .header_param(Parameter()
                          .key('search')
                          .value(search))
            .header_param(Parameter()
                          .key('totals')
                          .value(totals))
            .query_param(Parameter()
                         .key('page[number]')
                         .value(page_number))
            .query_param(Parameter()
                         .key('page[limit]')
                         .value(page_limit))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .auth(Or(Single('apiKey'), Single('sessionKey'), Single('txnSessionKey')))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(OrgsVASTaxFormEnablementsResponseResult.from_dictionary)
            .local_error('400', 'Error', ErrorFourHundredException)
        ).execute()

    def post_orgs_vas_tax_form_enablements(self,
                                           org_id,
                                           body,
                                           request_token=None):
        """Does a POST request to /orgs/{OrgId}/taxForms.

        Creates a new Orgs Tax Form Enablement for a specific Org. This allows
        you to assign rule groups and enable Tax Form decisioning across
        Merchants under the Org.

        Args:
            org_id (str): The Org ID this tax form enablement belongs to.
            body (OrgsVASTaxFormEnablementsPostRequest): Request payload for
                enabling Tax Form for an Org.
            request_token (str, optional): A custom, one-time identifier for
                any API request (GET, PUT, POST, or DELETE). Blocks future
                requests with the same token for 48 hours, ensuring only the
                first request is processed. Valid values can contain 1-100
                alphanumeric and special characters. See <a
                href="/apis/payrix/dev-int-guide/references/request-tokens"
                target="_blank">Request Tokens</a>  for more information.

        Returns:
            OrgsVASTaxFormEnablementsResponseResult: Response from the API.
                Successful response for enabling Tax Form for an Org.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.PAYRIX)
            .path('/orgs/{OrgId}/taxForms')
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                            .key('OrgId')
                            .value(org_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('request-token')
                          .value(request_token))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Or(Single('apiKey'), Single('sessionKey'), Single('txnSessionKey')))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(OrgsVASTaxFormEnablementsResponseResult.from_dictionary)
            .local_error('400', 'Error', ErrorFourHundredException)
        ).execute()
