import shlex
from pathlib import Path
from typing import Tuple


def generate_run_script(wasm_file: Path, project_path: Path) -> Path:
    script_path = project_path / "run.sh"

    wasm_type = "standalone" if wasm_file.suffix == ".wasm" else "component"

    if wasm_type == "standalone":
        run_cmd = 'wasmtime run "$WASM_FILE" "$@"'
        description = "run your WebAssembly binary (standalone)"
    else:
        run_cmd = 'wasmtime run "$WASM_FILE" "$@"'
        description = "run your WebAssembly component"

    # Properly escape filename for shell to prevent command injection
    escaped_wasm_name = shlex.quote(wasm_file.name)

    script_content = f"""#!/bin/bash
# Auto-generated by wasm-kit - {description}

set -e

WASM_FILE={escaped_wasm_name}

# Check if wasmtime is installed
if ! command -v wasmtime &> /dev/null; then
    echo "wasmtime not found"
    echo "Install: curl https://wasmtime.dev/install.sh -sSf | bash"
    exit 1
fi

# Run the WASM file
echo "Running $WASM_FILE..."
{run_cmd}
"""

    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return script_path


def generate_serve_script(wasm_file: Path, project_path: Path, port: int = 8080) -> Path:
    script_path = project_path / "serve.sh"

    # Properly escape filename for shell to prevent command injection
    escaped_wasm_name = shlex.quote(wasm_file.name)

    script_content = f"""#!/bin/bash
# Auto-generated by wasm-kit - serve your WebAssembly component via HTTP

set -e

WASM_FILE={escaped_wasm_name}
PORT={port}

# Check if wasmtime is installed
if ! command -v wasmtime &> /dev/null; then
    echo "wasmtime not found"
    echo "Install: curl https://wasmtime.dev/install.sh -sSf | bash"
    exit 1
fi

# Serve the component
echo "Serving $WASM_FILE on http://localhost:$PORT..."
echo "Press Ctrl+C to stop"
wasmtime serve "$WASM_FILE" --addr 0.0.0.0:$PORT
"""

    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return script_path


def generate_both_scripts(wasm_file: Path, project_path: Path) -> Tuple[Path, Path]:
    run_script = generate_run_script(wasm_file, project_path)
    serve_script = generate_serve_script(wasm_file, project_path)

    return run_script, serve_script
