from yaml.scanner import ScannerError


class YamlFormatFileError(ScannerError): ...

class EmptyFileError(Exception): ...

class SyntaxValidationError(Exception): ...

class NotSerializable(Exception): ...

