# Field Length Limits
MAX_TITLE_LENGTH = 1024
MAX_NOTES_LENGTH = 8192

# Task Status Options
TASK_STATUS_NEEDS_ACTION = "needsAction"
TASK_STATUS_COMPLETED = "completed"

VALID_TASK_STATUSES = [
    TASK_STATUS_NEEDS_ACTION,
    TASK_STATUS_COMPLETED
]

DEFAULT_TASK_LIST_ID = "@default"
