# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/v1/file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta/v1/file.proto\"U\n\x1f\x43reateUploadPresignedUrlRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileSize\x18\x03 \x01(\x03\"q\n CreateUploadPresignedUrlResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12.\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x1e.CreateUploadPresignedUrlField\";\n\x1d\x43reateUploadPresignedUrlField\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"i\n$CreateManyUploadPresignedUrlsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x31\n\x05\x66iles\x18\x02 \x03(\x0b\x32\".CreateManyUploadPresignedUrlsFile\"?\n!CreateManyUploadPresignedUrlsFile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\"Y\n%CreateManyUploadPresignedUrlsResponse\x12\x30\n\x05\x66iles\x18\x01 \x03(\x0b\x32!.CreateUploadPresignedUrlResponse2\xde\x01\n\x0b\x46ileService\x12_\n\x18\x43reateUploadPresignedUrl\x12 .CreateUploadPresignedUrlRequest\x1a!.CreateUploadPresignedUrlResponse\x12n\n\x1d\x43reateManyUploadPresignedUrls\x12%.CreateManyUploadPresignedUrlsRequest\x1a&.CreateManyUploadPresignedUrlsResponseB\rZ\x0b.;dataprotob\x06proto3')



_CREATEUPLOADPRESIGNEDURLREQUEST = DESCRIPTOR.message_types_by_name['CreateUploadPresignedUrlRequest']
_CREATEUPLOADPRESIGNEDURLRESPONSE = DESCRIPTOR.message_types_by_name['CreateUploadPresignedUrlResponse']
_CREATEUPLOADPRESIGNEDURLFIELD = DESCRIPTOR.message_types_by_name['CreateUploadPresignedUrlField']
_CREATEMANYUPLOADPRESIGNEDURLSREQUEST = DESCRIPTOR.message_types_by_name['CreateManyUploadPresignedUrlsRequest']
_CREATEMANYUPLOADPRESIGNEDURLSFILE = DESCRIPTOR.message_types_by_name['CreateManyUploadPresignedUrlsFile']
_CREATEMANYUPLOADPRESIGNEDURLSRESPONSE = DESCRIPTOR.message_types_by_name['CreateManyUploadPresignedUrlsResponse']
CreateUploadPresignedUrlRequest = _reflection.GeneratedProtocolMessageType('CreateUploadPresignedUrlRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUPLOADPRESIGNEDURLREQUEST,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateUploadPresignedUrlRequest)
  })
_sym_db.RegisterMessage(CreateUploadPresignedUrlRequest)

CreateUploadPresignedUrlResponse = _reflection.GeneratedProtocolMessageType('CreateUploadPresignedUrlResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUPLOADPRESIGNEDURLRESPONSE,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateUploadPresignedUrlResponse)
  })
_sym_db.RegisterMessage(CreateUploadPresignedUrlResponse)

CreateUploadPresignedUrlField = _reflection.GeneratedProtocolMessageType('CreateUploadPresignedUrlField', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUPLOADPRESIGNEDURLFIELD,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateUploadPresignedUrlField)
  })
_sym_db.RegisterMessage(CreateUploadPresignedUrlField)

CreateManyUploadPresignedUrlsRequest = _reflection.GeneratedProtocolMessageType('CreateManyUploadPresignedUrlsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMANYUPLOADPRESIGNEDURLSREQUEST,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateManyUploadPresignedUrlsRequest)
  })
_sym_db.RegisterMessage(CreateManyUploadPresignedUrlsRequest)

CreateManyUploadPresignedUrlsFile = _reflection.GeneratedProtocolMessageType('CreateManyUploadPresignedUrlsFile', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMANYUPLOADPRESIGNEDURLSFILE,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateManyUploadPresignedUrlsFile)
  })
_sym_db.RegisterMessage(CreateManyUploadPresignedUrlsFile)

CreateManyUploadPresignedUrlsResponse = _reflection.GeneratedProtocolMessageType('CreateManyUploadPresignedUrlsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMANYUPLOADPRESIGNEDURLSRESPONSE,
  '__module__' : 'data.v1.file_pb2'
  # @@protoc_insertion_point(class_scope:CreateManyUploadPresignedUrlsResponse)
  })
_sym_db.RegisterMessage(CreateManyUploadPresignedUrlsResponse)

_FILESERVICE = DESCRIPTOR.services_by_name['FileService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013.;dataproto'
  _CREATEUPLOADPRESIGNEDURLREQUEST._serialized_start=22
  _CREATEUPLOADPRESIGNEDURLREQUEST._serialized_end=107
  _CREATEUPLOADPRESIGNEDURLRESPONSE._serialized_start=109
  _CREATEUPLOADPRESIGNEDURLRESPONSE._serialized_end=222
  _CREATEUPLOADPRESIGNEDURLFIELD._serialized_start=224
  _CREATEUPLOADPRESIGNEDURLFIELD._serialized_end=283
  _CREATEMANYUPLOADPRESIGNEDURLSREQUEST._serialized_start=285
  _CREATEMANYUPLOADPRESIGNEDURLSREQUEST._serialized_end=390
  _CREATEMANYUPLOADPRESIGNEDURLSFILE._serialized_start=392
  _CREATEMANYUPLOADPRESIGNEDURLSFILE._serialized_end=455
  _CREATEMANYUPLOADPRESIGNEDURLSRESPONSE._serialized_start=457
  _CREATEMANYUPLOADPRESIGNEDURLSRESPONSE._serialized_end=546
  _FILESERVICE._serialized_start=549
  _FILESERVICE._serialized_end=771
# @@protoc_insertion_point(module_scope)
