# coding: utf-8

# flake8: noqa
"""
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

The version of the OpenAPI document: 1001.0.0-SNAPSHOT-f79806309100f55b79091ff1d6ea3c2c90b46ad9
Contact: ecosystem@atlassian.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
