"""Common metadata for TailorKey specs."""

from glove80.layouts.common import _build_common_fields

COMMON_FIELDS = _build_common_fields(creator="moosy")

LAYER_NAME_MAP = {
    "windows": [
        "HRM_WinLinx",
        "Typing",
        "Autoshift",
        "Cursor",
        "Symbol",
        "Gaming",
        "Lower",
        "Mouse",
        "MouseSlow",
        "MouseFast",
        "MouseWarp",
        "Magic",
    ],
    "mac": [
        "HRM_macOS",
        "Typing",
        "Autoshift",
        "Cursor",
        "Symbol",
        "Gaming",
        "Lower",
        "Mouse",
        "MouseSlow",
        "MouseFast",
        "MouseWarp",
        "Magic",
    ],
    "dual": [
        "HRM_macOS",
        "HRM_WinLinx",
        "Typing",
        "Autoshift",
        "Cursor_macOS",
        "Cursor",
        "Symbol",
        "Mouse",
        "MouseSlow",
        "MouseFast",
        "MouseWarp",
        "Gaming",
        "Lower",
        "Magic",
    ],
    "bilateral_windows": [
        "HRM_WinLinx",
        "Typing",
        "Autoshift",
        "Cursor",
        "Symbol",
        "Gaming",
        "Lower",
        "LeftIndex",
        "LeftMiddy",
        "LeftRingy",
        "LeftPinky",
        "RightIndex",
        "RightMiddy",
        "RightRingy",
        "RightPinky",
        "Mouse",
        "MouseSlow",
        "MouseFast",
        "MouseWarp",
        "Magic",
    ],
    "bilateral_mac": [
        "HRM_macOS",
        "Typing",
        "Autoshift",
        "Cursor",
        "Symbol",
        "Gaming",
        "Lower",
        "LeftIndex",
        "LeftMiddy",
        "LeftRingy",
        "LeftPinky",
        "RightIndex",
        "RightMiddy",
        "RightRingy",
        "RightPinky",
        "Mouse",
        "MouseSlow",
        "MouseFast",
        "MouseWarp",
        "Magic",
    ],
}


__all__ = ["COMMON_FIELDS", "LAYER_NAME_MAP"]
