# Generated by Django 5.2.7 on 2025-11-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('age', models.IntegerField()),
                ('score', models.FloatField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('followers', models.BigIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('wake_time', models.TimeField()),
                ('is_active', models.BooleanField()),
                ('json', models.JSONField()),
            ],
            options={
                'db_table': 'test_user',
            },
        ),
        migrations.CreateModel(
            name='TestChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('age', models.IntegerField()),
                ('score', models.FloatField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('followers', models.BigIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('wake_time', models.TimeField()),
                ('is_active', models.BooleanField()),
                ('json', models.JSONField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tests.testparent')),
                ('parents', models.ManyToManyField(related_name='many_children', to='tests.testparent')),
            ],
            options={
                'db_table': 'test_child',
            },
        ),
    ]
