from _typeshed import StrPath

def get_steam_path() -> str: ...
def load_library_folders(steam_path: StrPath) -> dict[str, dict[str, str | dict[str, str]]]: ...
def get_app_path(steam_path: StrPath, app_id: object) -> str: ...
def get_game_path(steam_path: StrPath, app_id: object, game_name: StrPath) -> str: ...
