from _typeshed import Incomplete
from cezzis_kafka.kafka_producer_settings import KafkaProducerSettings as KafkaProducerSettings
from typing import Any

logger: Incomplete

class KafkaProducer:
    settings: Incomplete
    def __init__(self, settings: KafkaProducerSettings) -> None: ...
    @property
    def broker_url(self) -> str: ...
    def send(self, topic: str, message: str | bytes, key: str | None = None, headers: dict[str, str | bytes] | None = None, message_id: str | None = None, metadata: dict[str, Any] | None = None) -> str: ...
    def flush(self, timeout: float = 10.0) -> None: ...
    def close(self) -> None: ...
