VERSION = "0.12.0"

# fmt: off
MAPPING = {
    "aioitertools": "https://aioitertools.omnilib.dev/en/stable/",
    "aioitertools.asyncio": "https://aioitertools.omnilib.dev/en/stable/api.html#module-aioitertools.asyncio",
    "aioitertools.asyncio.as_completed": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.asyncio.as_completed",
    "aioitertools.asyncio.as_generated": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.asyncio.as_generated",
    "aioitertools.asyncio.gather": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.asyncio.gather",
    "aioitertools.asyncio.gather_iter": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.asyncio.gather_iter",
    "aioitertools.builtins": "https://aioitertools.omnilib.dev/en/stable/api.html#module-aioitertools.builtins",
    "aioitertools.builtins.all": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.all",
    "aioitertools.builtins.any": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.any",
    "aioitertools.builtins.enumerate": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.enumerate",
    "aioitertools.builtins.iter": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.iter",
    "aioitertools.builtins.list": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.list",
    "aioitertools.builtins.map": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.map",
    "aioitertools.builtins.max": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.max",
    "aioitertools.builtins.min": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.min",
    "aioitertools.builtins.next": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.next",
    "aioitertools.builtins.set": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.set",
    "aioitertools.builtins.sum": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.sum",
    "aioitertools.builtins.tuple": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.tuple",
    "aioitertools.builtins.zip": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.builtins.zip",
    "aioitertools.itertools": "https://aioitertools.omnilib.dev/en/stable/api.html#module-aioitertools.itertools",
    "aioitertools.itertools.accumulate": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.accumulate",
    "aioitertools.itertools.batched": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.batched",
    "aioitertools.itertools.combinations": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.combinations",
    "aioitertools.itertools.combinations_with_replacement": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.combinations_with_replacement",
    "aioitertools.itertools.compress": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.compress",
    "aioitertools.itertools.count": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.count",
    "aioitertools.itertools.cycle": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.cycle",
    "aioitertools.itertools.dropwhile": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.dropwhile",
    "aioitertools.itertools.filterfalse": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.filterfalse",
    "aioitertools.itertools.groupby": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.groupby",
    "aioitertools.itertools.islice": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.islice",
    "aioitertools.itertools.permutations": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.permutations",
    "aioitertools.itertools.product": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.product",
    "aioitertools.itertools.repeat": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.repeat",
    "aioitertools.itertools.starmap": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.starmap",
    "aioitertools.itertools.takewhile": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.takewhile",
    "aioitertools.itertools.tee": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.tee",
    "aioitertools.itertools.zip_longest": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.itertools.zip_longest",
    "aioitertools.more_itertools": "https://aioitertools.omnilib.dev/en/stable/api.html#module-aioitertools.more_itertools",
    "aioitertools.more_itertools.before_and_after": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.more_itertools.before_and_after",
    "aioitertools.more_itertools.chunked": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.more_itertools.chunked",
    "aioitertools.more_itertools.take": "https://aioitertools.omnilib.dev/en/stable/api.html#aioitertools.more_itertools.take",
}
