VERSION = "2.1.2"

# fmt: off
MAPPING = {
    "class_registry": "https://class-registry.readthedocs.io/en/latest/",
    "class_registry.base": "https://class-registry.readthedocs.io/en/latest/api.html#module-class_registry.base",
    "class_registry.base.autoregister": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.AutoRegister",
    "class_registry.base.basemutableregistry": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry",
    "class_registry.base.basemutableregistry.items": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry.items",
    "class_registry.base.basemutableregistry.keys": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry.keys",
    "class_registry.base.basemutableregistry.register": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry.register",
    "class_registry.base.basemutableregistry.unregister": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry.unregister",
    "class_registry.base.basemutableregistry.values": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseMutableRegistry.values",
    "class_registry.base.baseregistry": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry",
    "class_registry.base.baseregistry.classes": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.classes",
    "class_registry.base.baseregistry.create_instance": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.create_instance",
    "class_registry.base.baseregistry.gen_lookup_key": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.gen_lookup_key",
    "class_registry.base.baseregistry.get": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.get",
    "class_registry.base.baseregistry.get_class": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.get_class",
    "class_registry.base.baseregistry.keys": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.BaseRegistry.keys",
    "class_registry.base.registrykeyerror": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.base.RegistryKeyError",
    "class_registry.cache": "https://class-registry.readthedocs.io/en/latest/api.html#module-class_registry.cache",
    "class_registry.cache.classregistryinstancecache": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.cache.ClassRegistryInstanceCache",
    "class_registry.cache.classregistryinstancecache.get_class_key": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.cache.ClassRegistryInstanceCache.get_class_key",
    "class_registry.cache.classregistryinstancecache.get_instance_key": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.cache.ClassRegistryInstanceCache.get_instance_key",
    "class_registry.cache.classregistryinstancecache.warm_cache": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.cache.ClassRegistryInstanceCache.warm_cache",
    "class_registry.entry_points": "https://class-registry.readthedocs.io/en/latest/api.html#module-class_registry.entry_points",
    "class_registry.entry_points.entrypointclassregistry": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.entry_points.EntryPointClassRegistry",
    "class_registry.entry_points.entrypointclassregistry.get": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.entry_points.EntryPointClassRegistry.get",
    "class_registry.entry_points.entrypointclassregistry.get_class": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.entry_points.EntryPointClassRegistry.get_class",
    "class_registry.entry_points.entrypointclassregistry.keys": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.entry_points.EntryPointClassRegistry.keys",
    "class_registry.entry_points.entrypointclassregistry.refresh": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.entry_points.EntryPointClassRegistry.refresh",
    "class_registry.patcher": "https://class-registry.readthedocs.io/en/latest/api.html#module-class_registry.patcher",
    "class_registry.patcher.registrypatcher": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.patcher.RegistryPatcher",
    "class_registry.patcher.registrypatcher.apply": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.patcher.RegistryPatcher.apply",
    "class_registry.patcher.registrypatcher.doesnotexist": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.patcher.RegistryPatcher.DoesNotExist",
    "class_registry.patcher.registrypatcher.restore": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.patcher.RegistryPatcher.restore",
    "class_registry.registry": "https://class-registry.readthedocs.io/en/latest/api.html#module-class_registry.registry",
    "class_registry.registry.classregistry": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.registry.ClassRegistry",
    "class_registry.registry.classregistry.get_class": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.registry.ClassRegistry.get_class",
    "class_registry.registry.sortedclassregistry": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.registry.SortedClassRegistry",
    "class_registry.registry.sortedclassregistry.create_sorter": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.registry.SortedClassRegistry.create_sorter",
    "class_registry.registry.sortedclassregistry.keys": "https://class-registry.readthedocs.io/en/latest/api.html#class_registry.registry.SortedClassRegistry.keys",
}
