VERSION = "0.5.7"

# fmt: off
MAPPING = {
    "click_option_group": "https://click-option-group.readthedocs.io/en/latest/",
    "click_option_group.alloptiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.AllOptionGroup",
    "click_option_group.alloptiongroup.forbidden_option_attrs": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.AllOptionGroup.forbidden_option_attrs",
    "click_option_group.alloptiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.AllOptionGroup.handle_parse_result",
    "click_option_group.alloptiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.AllOptionGroup.name_extra",
    "click_option_group.groupedoption": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.GroupedOption",
    "click_option_group.groupedoption.group": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.GroupedOption.group",
    "click_option_group.mutuallyexclusiveoptiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.MutuallyExclusiveOptionGroup",
    "click_option_group.mutuallyexclusiveoptiongroup.forbidden_option_attrs": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.MutuallyExclusiveOptionGroup.forbidden_option_attrs",
    "click_option_group.mutuallyexclusiveoptiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.MutuallyExclusiveOptionGroup.handle_parse_result",
    "click_option_group.mutuallyexclusiveoptiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.MutuallyExclusiveOptionGroup.name_extra",
    "click_option_group.optgroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.optgroup",
    "click_option_group.optgroup.group": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.optgroup.group",
    "click_option_group.optgroup.option": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.optgroup.option",
    "click_option_group.optiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup",
    "click_option_group.optiongroup.forbidden_option_attrs": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.forbidden_option_attrs",
    "click_option_group.optiongroup.get_help_record": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.get_help_record",
    "click_option_group.optiongroup.get_option_names": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.get_option_names",
    "click_option_group.optiongroup.get_options": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.get_options",
    "click_option_group.optiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.handle_parse_result",
    "click_option_group.optiongroup.help": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.help",
    "click_option_group.optiongroup.name": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.name",
    "click_option_group.optiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.name_extra",
    "click_option_group.optiongroup.option": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.OptionGroup.option",
    "click_option_group.requiredalloptiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAllOptionGroup",
    "click_option_group.requiredalloptiongroup.forbidden_option_attrs": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAllOptionGroup.forbidden_option_attrs",
    "click_option_group.requiredalloptiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAllOptionGroup.handle_parse_result",
    "click_option_group.requiredalloptiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAllOptionGroup.name_extra",
    "click_option_group.requiredanyoptiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAnyOptionGroup",
    "click_option_group.requiredanyoptiongroup.forbidden_option_attrs": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAnyOptionGroup.forbidden_option_attrs",
    "click_option_group.requiredanyoptiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAnyOptionGroup.handle_parse_result",
    "click_option_group.requiredanyoptiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredAnyOptionGroup.name_extra",
    "click_option_group.requiredmutuallyexclusiveoptiongroup": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredMutuallyExclusiveOptionGroup",
    "click_option_group.requiredmutuallyexclusiveoptiongroup.handle_parse_result": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredMutuallyExclusiveOptionGroup.handle_parse_result",
    "click_option_group.requiredmutuallyexclusiveoptiongroup.name_extra": "https://click-option-group.readthedocs.io/en/latest/api.html#click_option_group.RequiredMutuallyExclusiveOptionGroup.name_extra",
}
