VERSION = "2.0"

# fmt: off
MAPPING = {
    "deepmerge": "https://deepmerge.readthedocs.io/en/latest/",
    "deepmerge.exception": "https://deepmerge.readthedocs.io/en/latest/api.html",
    "deepmerge.exception.deepmergeexception": "https://deepmerge.readthedocs.io/en/latest/api.html#deepmerge.exception.DeepMergeException",
    "deepmerge.exception.invalidmerge": "https://deepmerge.readthedocs.io/en/latest/api.html#deepmerge.exception.InvalidMerge",
    "deepmerge.exception.strategynotfound": "https://deepmerge.readthedocs.io/en/latest/api.html#deepmerge.exception.StrategyNotFound",
    "deepmerge.merger": "https://deepmerge.readthedocs.io/en/latest/api.html",
    "deepmerge.merger.merger": "https://deepmerge.readthedocs.io/en/latest/api.html#deepmerge.merger.Merger",
    "deepmerge.strategy": "https://deepmerge.readthedocs.io/en/latest/strategies.html",
    "deepmerge.strategy.dict": "https://deepmerge.readthedocs.io/en/latest/strategies.html",
    "deepmerge.strategy.dict.dictstrategies": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.dict.DictStrategies",
    "deepmerge.strategy.dict.dictstrategies.name": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.dict.DictStrategies.NAME",
    "deepmerge.strategy.dict.dictstrategies.strategy_merge": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.dict.DictStrategies.strategy_merge",
    "deepmerge.strategy.dict.dictstrategies.strategy_override": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.dict.DictStrategies.strategy_override",
    "deepmerge.strategy.fallback": "https://deepmerge.readthedocs.io/en/latest/strategies.html",
    "deepmerge.strategy.fallback.fallbackstrategies": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.fallback.FallbackStrategies",
    "deepmerge.strategy.fallback.fallbackstrategies.name": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.fallback.FallbackStrategies.NAME",
    "deepmerge.strategy.fallback.fallbackstrategies.strategy_override": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.fallback.FallbackStrategies.strategy_override",
    "deepmerge.strategy.fallback.fallbackstrategies.strategy_use_existing": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.fallback.FallbackStrategies.strategy_use_existing",
    "deepmerge.strategy.list": "https://deepmerge.readthedocs.io/en/latest/strategies.html",
    "deepmerge.strategy.list.liststrategies": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.list.ListStrategies",
    "deepmerge.strategy.list.liststrategies.name": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.list.ListStrategies.NAME",
    "deepmerge.strategy.list.liststrategies.strategy_append": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.list.ListStrategies.strategy_append",
    "deepmerge.strategy.list.liststrategies.strategy_override": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.list.ListStrategies.strategy_override",
    "deepmerge.strategy.list.liststrategies.strategy_prepend": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.list.ListStrategies.strategy_prepend",
    "deepmerge.strategy.type_conflict": "https://deepmerge.readthedocs.io/en/latest/strategies.html",
    "deepmerge.strategy.type_conflict.typeconflictstrategies": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.type_conflict.TypeConflictStrategies",
    "deepmerge.strategy.type_conflict.typeconflictstrategies.name": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.type_conflict.TypeConflictStrategies.NAME",
    "deepmerge.strategy.type_conflict.typeconflictstrategies.strategy_override": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.type_conflict.TypeConflictStrategies.strategy_override",
    "deepmerge.strategy.type_conflict.typeconflictstrategies.strategy_override_if_not_empty": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.type_conflict.TypeConflictStrategies.strategy_override_if_not_empty",
    "deepmerge.strategy.type_conflict.typeconflictstrategies.strategy_use_existing": "https://deepmerge.readthedocs.io/en/latest/strategies.html#deepmerge.strategy.type_conflict.TypeConflictStrategies.strategy_use_existing",
}
