VERSION = "1.0.1"

# fmt: off
MAPPING = {
    "diceware": "https://diceware.readthedocs.io/en/stable/",
    "diceware.config": "https://diceware.readthedocs.io/en/stable/api.html#module-diceware.config",
    "diceware.config.get_config_dict": "https://diceware.readthedocs.io/en/stable/api.html#diceware.config.get_config_dict",
    "diceware.config.get_configparser": "https://diceware.readthedocs.io/en/stable/api.html#diceware.config.get_configparser",
    "diceware.config.re_wlist_name": "https://diceware.readthedocs.io/en/stable/api.html#diceware.config.RE_WLIST_NAME",
    "diceware.config.string_to_wlist_list": "https://diceware.readthedocs.io/en/stable/api.html#diceware.config.string_to_wlist_list",
    "diceware.config.valid_locations": "https://diceware.readthedocs.io/en/stable/api.html#diceware.config.valid_locations",
    "diceware.get_passphrase": "https://diceware.readthedocs.io/en/stable/api.html#diceware.get_passphrase",
    "diceware.get_random_sources": "https://diceware.readthedocs.io/en/stable/api.html#diceware.get_random_sources",
    "diceware.handle_options": "https://diceware.readthedocs.io/en/stable/api.html#diceware.handle_options",
    "diceware.insert_special_char": "https://diceware.readthedocs.io/en/stable/api.html#diceware.insert_special_char",
    "diceware.logger": "https://diceware.readthedocs.io/en/stable/api.html#module-diceware.logger",
    "diceware.logger.configure": "https://diceware.readthedocs.io/en/stable/api.html#diceware.logger.configure",
    "diceware.logger.logger": "https://diceware.readthedocs.io/en/stable/api.html#diceware.logger.logger",
    "diceware.main": "https://diceware.readthedocs.io/en/stable/api.html#diceware.main",
    "diceware.print_version": "https://diceware.readthedocs.io/en/stable/api.html#diceware.print_version",
    "diceware.random_sources": "https://diceware.readthedocs.io/en/stable/api.html#module-diceware.random_sources",
    "diceware.random_sources.realdicerandomsource": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.RealDiceRandomSource",
    "diceware.random_sources.realdicerandomsource.choice": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.RealDiceRandomSource.choice",
    "diceware.random_sources.realdicerandomsource.get_num_rolls": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.RealDiceRandomSource.get_num_rolls",
    "diceware.random_sources.realdicerandomsource.pre_check": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.RealDiceRandomSource.pre_check",
    "diceware.random_sources.systemrandomsource": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.SystemRandomSource",
    "diceware.random_sources.systemrandomsource.choice": "https://diceware.readthedocs.io/en/stable/api.html#diceware.random_sources.SystemRandomSource.choice",
    "diceware.special_chars": "https://diceware.readthedocs.io/en/stable/api.html#diceware.SPECIAL_CHARS",
    "diceware.wordlist": "https://diceware.readthedocs.io/en/stable/api.html#module-diceware.wordlist",
    "diceware.wordlist.get_wordlist_names": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.get_wordlist_names",
    "diceware.wordlist.get_wordlist_path": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.get_wordlist_path",
    "diceware.wordlist.get_wordlists_dir": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.get_wordlists_dir",
    "diceware.wordlist.max_in_mem_size": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.MAX_IN_MEM_SIZE",
    "diceware.wordlist.re_numbered_wordlist_entry": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.RE_NUMBERED_WORDLIST_ENTRY",
    "diceware.wordlist.re_valid_wordlist_filename": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.RE_VALID_WORDLIST_FILENAME",
    "diceware.wordlist.re_wordlist_name": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.RE_WORDLIST_NAME",
    "diceware.wordlist.wordlist": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.WordList",
    "diceware.wordlist.wordlist.is_signed": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.WordList.is_signed",
    "diceware.wordlist.wordlist.refine_entry": "https://diceware.readthedocs.io/en/stable/api.html#diceware.wordlist.WordList.refine_entry",
}
