VERSION = "8.0.0"

# fmt: off
MAPPING = {
    "axes": "https://django-axes.readthedocs.io/en/latest/",
    "axes.backends": "https://django-axes.readthedocs.io/en/latest/8_reference.html#module-axes.backends",
    "axes.backends.axesbackend": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.backends.AxesBackend",
    "axes.backends.axesstandalonebackend": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.backends.AxesStandaloneBackend",
    "axes.handlers": "https://django-axes.readthedocs.io/en/latest/8_reference.html",
    "axes.handlers.base": "https://django-axes.readthedocs.io/en/latest/8_reference.html#module-axes.handlers.base",
    "axes.handlers.base.abstractaxeshandler": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AbstractAxesHandler",
    "axes.handlers.base.abstractaxeshandler.get_failures": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AbstractAxesHandler.get_failures",
    "axes.handlers.base.abstractaxeshandler.user_logged_in": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AbstractAxesHandler.user_logged_in",
    "axes.handlers.base.abstractaxeshandler.user_logged_out": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AbstractAxesHandler.user_logged_out",
    "axes.handlers.base.abstractaxeshandler.user_login_failed": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AbstractAxesHandler.user_login_failed",
    "axes.handlers.base.axesbasehandler": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler",
    "axes.handlers.base.axesbasehandler.get_admin_url": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.get_admin_url",
    "axes.handlers.base.axesbasehandler.is_admin_request": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_admin_request",
    "axes.handlers.base.axesbasehandler.is_admin_site": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_admin_site",
    "axes.handlers.base.axesbasehandler.is_allowed": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_allowed",
    "axes.handlers.base.axesbasehandler.is_blacklisted": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_blacklisted",
    "axes.handlers.base.axesbasehandler.is_locked": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_locked",
    "axes.handlers.base.axesbasehandler.is_whitelisted": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.is_whitelisted",
    "axes.handlers.base.axesbasehandler.remove_out_of_limit_failure_logs": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.remove_out_of_limit_failure_logs",
    "axes.handlers.base.axesbasehandler.reset_attempts": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.reset_attempts",
    "axes.handlers.base.axesbasehandler.reset_failure_logs": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.reset_failure_logs",
    "axes.handlers.base.axesbasehandler.reset_logs": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesBaseHandler.reset_logs",
    "axes.handlers.base.axeshandler": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesHandler",
    "axes.handlers.base.axeshandler.get_failures": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesHandler.get_failures",
    "axes.handlers.base.axeshandler.user_logged_in": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesHandler.user_logged_in",
    "axes.handlers.base.axeshandler.user_logged_out": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesHandler.user_logged_out",
    "axes.handlers.base.axeshandler.user_login_failed": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.handlers.base.AxesHandler.user_login_failed",
    "axes.middleware": "https://django-axes.readthedocs.io/en/latest/8_reference.html#module-axes.middleware",
    "axes.middleware.axesmiddleware": "https://django-axes.readthedocs.io/en/latest/8_reference.html#axes.middleware.AxesMiddleware",
}
