VERSION = "8.1.0"

# fmt: off
MAPPING = {
    "phonenumber_field": "https://django-phonenumber-field.readthedocs.io/en/latest/",
    "phonenumber_field.formfields": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.formfields.phonenumberfield": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.PhoneNumberField",
    "phonenumber_field.formfields.phonenumberfield.__init__": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.PhoneNumberField.__init__",
    "phonenumber_field.formfields.splitphonenumberfield": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.SplitPhoneNumberField",
    "phonenumber_field.formfields.splitphonenumberfield.__init__": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.SplitPhoneNumberField.__init__",
    "phonenumber_field.formfields.splitphonenumberfield.invalid_error_message": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.SplitPhoneNumberField.invalid_error_message",
    "phonenumber_field.formfields.splitphonenumberfield.number_field": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.SplitPhoneNumberField.number_field",
    "phonenumber_field.formfields.splitphonenumberfield.prefix_field": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.formfields.SplitPhoneNumberField.prefix_field",
    "phonenumber_field.modelfields": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.modelfields.phonenumberfield": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.modelfields.PhoneNumberField",
    "phonenumber_field.modelfields.phonenumberfield.__init__": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.modelfields.PhoneNumberField.__init__",
    "phonenumber_field.phonenumber": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.phonenumber.phonenumber": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber",
    "phonenumber_field.phonenumber.phonenumber.as_e164": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_e164",
    "phonenumber_field.phonenumber.phonenumber.as_international": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_international",
    "phonenumber_field.phonenumber.phonenumber.as_national": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_national",
    "phonenumber_field.phonenumber.phonenumber.as_rfc3966": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_rfc3966",
    "phonenumber_field.phonenumber.phonenumber.from_string": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.from_string",
    "phonenumber_field.phonenumber.phonenumber.is_valid": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.is_valid",
    "phonenumber_field.serializerfields": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.serializerfields.phonenumberfield": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.serializerfields.PhoneNumberField",
    "phonenumber_field.serializerfields.phonenumberfield.__init__": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.serializerfields.PhoneNumberField.__init__",
    "phonenumber_field.validators": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.validators.validate_international_phonenumber": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.validators.validate_international_phonenumber",
    "phonenumber_field.widgets": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html",
    "phonenumber_field.widgets.phonenumberprefixwidget": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.widgets.PhoneNumberPrefixWidget",
    "phonenumber_field.widgets.regionalphonenumberwidget": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.widgets.RegionalPhoneNumberWidget",
    "phonenumber_field.widgets.regionalphonenumberwidget.__init__": "https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.widgets.RegionalPhoneNumberWidget.__init__",
}
