VERSION = "3.18.0"

# fmt: off
MAPPING = {
    "filelock": "https://py-filelock.readthedocs.io/en/latest/",
    "filelock.__version__": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.__version__",
    "filelock.acquirereturnproxy": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AcquireReturnProxy",
    "filelock.asyncacquirereturnproxy": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AsyncAcquireReturnProxy",
    "filelock.asyncfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AsyncFileLock",
    "filelock.asyncsoftfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AsyncSoftFileLock",
    "filelock.asyncunixfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AsyncUnixFileLock",
    "filelock.asyncwindowsfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.AsyncWindowsFileLock",
    "filelock.baseasyncfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock",
    "filelock.baseasyncfilelock.acquire": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock.acquire",
    "filelock.baseasyncfilelock.executor": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock.executor",
    "filelock.baseasyncfilelock.loop": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock.loop",
    "filelock.baseasyncfilelock.release": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock.release",
    "filelock.baseasyncfilelock.run_in_executor": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseAsyncFileLock.run_in_executor",
    "filelock.basefilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock",
    "filelock.basefilelock.acquire": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.acquire",
    "filelock.basefilelock.blocking": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.blocking",
    "filelock.basefilelock.is_locked": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.is_locked",
    "filelock.basefilelock.is_singleton": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.is_singleton",
    "filelock.basefilelock.is_thread_local": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.is_thread_local",
    "filelock.basefilelock.lock_counter": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.lock_counter",
    "filelock.basefilelock.lock_file": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.lock_file",
    "filelock.basefilelock.mode": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.mode",
    "filelock.basefilelock.release": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.release",
    "filelock.basefilelock.timeout": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.BaseFileLock.timeout",
    "filelock.filelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.FileLock",
    "filelock.softfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.SoftFileLock",
    "filelock.timeout": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.Timeout",
    "filelock.timeout.lock_file": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.Timeout.lock_file",
    "filelock.unixfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.UnixFileLock",
    "filelock.windowsfilelock": "https://py-filelock.readthedocs.io/en/latest/api.html#filelock.WindowsFileLock",
}
