VERSION = "4.8.0"

# fmt: off
MAPPING = {
    "flask_httpauth": "https://flask-httpauth.readthedocs.io/en/latest/",
    "flask_httpauth.httpbasicauth": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth",
    "flask_httpauth.httpbasicauth.__init__": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.__init__",
    "flask_httpauth.httpbasicauth.current_user": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.current_user",
    "flask_httpauth.httpbasicauth.error_handler": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.error_handler",
    "flask_httpauth.httpbasicauth.get_password": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.get_password",
    "flask_httpauth.httpbasicauth.get_user_roles": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.get_user_roles",
    "flask_httpauth.httpbasicauth.hash_password": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.hash_password",
    "flask_httpauth.httpbasicauth.login_required": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.login_required",
    "flask_httpauth.httpbasicauth.username": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.username",
    "flask_httpauth.httpbasicauth.verify_password": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.verify_password",
    "flask_httpauth.httpdigestauth": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth",
    "flask_httpauth.httpdigestauth.__init__": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.__init__",
    "flask_httpauth.httpdigestauth.current_user": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.current_user",
    "flask_httpauth.httpdigestauth.error_handler": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.error_handler",
    "flask_httpauth.httpdigestauth.generate_ha1": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.generate_ha1",
    "flask_httpauth.httpdigestauth.generate_nonce": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.generate_nonce",
    "flask_httpauth.httpdigestauth.generate_opaque": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.generate_opaque",
    "flask_httpauth.httpdigestauth.get_password": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.get_password",
    "flask_httpauth.httpdigestauth.get_user_roles": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.get_user_roles",
    "flask_httpauth.httpdigestauth.login_required": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.login_required",
    "flask_httpauth.httpdigestauth.username": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.username",
    "flask_httpauth.httpdigestauth.verify_nonce": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.verify_nonce",
    "flask_httpauth.httpdigestauth.verify_opaque": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPDigestAuth.verify_opaque",
    "flask_httpauth.httpmultiauth": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPMultiAuth",
    "flask_httpauth.httpmultiauth.__init__": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPMultiAuth.__init__",
    "flask_httpauth.httpmultiauth.current_user": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPMultiAuth.current_user",
    "flask_httpauth.httpmultiauth.login_required": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPMultiAuth.login_required",
    "flask_httpauth.httptokenauth": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth",
    "flask_httpauth.httptokenauth.__init__": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.__init__",
    "flask_httpauth.httptokenauth.current_user": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.current_user",
    "flask_httpauth.httptokenauth.error_handler": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.error_handler",
    "flask_httpauth.httptokenauth.get_user_roles": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.get_user_roles",
    "flask_httpauth.httptokenauth.login_required": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.login_required",
    "flask_httpauth.httptokenauth.verify_token": "https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPTokenAuth.verify_token",
}
