VERSION = "5.5.1"

# fmt: off
MAPPING = {
    "flask_socketio": "https://flask-socketio.readthedocs.io/en/latest/",
    "flask_socketio.close_room": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.close_room",
    "flask_socketio.disconnect": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.disconnect",
    "flask_socketio.emit": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.emit",
    "flask_socketio.join_room": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.join_room",
    "flask_socketio.leave_room": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.leave_room",
    "flask_socketio.namespace": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.Namespace",
    "flask_socketio.namespace.close_room": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.Namespace.close_room",
    "flask_socketio.namespace.emit": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.Namespace.emit",
    "flask_socketio.namespace.send": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.Namespace.send",
    "flask_socketio.namespace.trigger_event": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.Namespace.trigger_event",
    "flask_socketio.rooms": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.rooms",
    "flask_socketio.send": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.send",
    "flask_socketio.socketio": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO",
    "flask_socketio.socketio.call": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.call",
    "flask_socketio.socketio.close_room": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.close_room",
    "flask_socketio.socketio.emit": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.emit",
    "flask_socketio.socketio.event": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.event",
    "flask_socketio.socketio.on": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.on",
    "flask_socketio.socketio.on_error": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.on_error",
    "flask_socketio.socketio.on_error_default": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.on_error_default",
    "flask_socketio.socketio.on_event": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.on_event",
    "flask_socketio.socketio.reason": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason",
    "flask_socketio.socketio.reason.client_disconnect": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason.CLIENT_DISCONNECT",
    "flask_socketio.socketio.reason.ping_timeout": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason.PING_TIMEOUT",
    "flask_socketio.socketio.reason.server_disconnect": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason.SERVER_DISCONNECT",
    "flask_socketio.socketio.reason.transport_close": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason.TRANSPORT_CLOSE",
    "flask_socketio.socketio.reason.transport_error": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.reason.TRANSPORT_ERROR",
    "flask_socketio.socketio.run": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.run",
    "flask_socketio.socketio.send": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.send",
    "flask_socketio.socketio.sleep": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.sleep",
    "flask_socketio.socketio.start_background_task": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.start_background_task",
    "flask_socketio.socketio.stop": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.stop",
    "flask_socketio.socketio.test_client": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.test_client",
    "flask_socketio.socketiotestclient": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient",
    "flask_socketio.socketiotestclient.connect": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.connect",
    "flask_socketio.socketiotestclient.disconnect": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.disconnect",
    "flask_socketio.socketiotestclient.emit": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.emit",
    "flask_socketio.socketiotestclient.get_received": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.get_received",
    "flask_socketio.socketiotestclient.is_connected": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.is_connected",
    "flask_socketio.socketiotestclient.send": "https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient.send",
}
