VERSION = "4.7.1"

# fmt: off
MAPPING = {
    "flask_jwt_extended": "https://flask-jwt-extended.readthedocs.io/en/stable/",
    "flask_jwt_extended.create_access_token": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.create_access_token",
    "flask_jwt_extended.create_refresh_token": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.create_refresh_token",
    "flask_jwt_extended.current_user": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.current_user",
    "flask_jwt_extended.decode_token": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.decode_token",
    "flask_jwt_extended.get_csrf_token": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_csrf_token",
    "flask_jwt_extended.get_current_user": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_current_user",
    "flask_jwt_extended.get_jti": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_jti",
    "flask_jwt_extended.get_jwt": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_jwt",
    "flask_jwt_extended.get_jwt_header": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_jwt_header",
    "flask_jwt_extended.get_jwt_identity": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_jwt_identity",
    "flask_jwt_extended.get_unverified_jwt_headers": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.get_unverified_jwt_headers",
    "flask_jwt_extended.jwt_required": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.jwt_required",
    "flask_jwt_extended.jwtmanager": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager",
    "flask_jwt_extended.jwtmanager.additional_claims_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.additional_claims_loader",
    "flask_jwt_extended.jwtmanager.additional_headers_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.additional_headers_loader",
    "flask_jwt_extended.jwtmanager.decode_key_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.decode_key_loader",
    "flask_jwt_extended.jwtmanager.encode_key_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.encode_key_loader",
    "flask_jwt_extended.jwtmanager.expired_token_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.expired_token_loader",
    "flask_jwt_extended.jwtmanager.init_app": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.init_app",
    "flask_jwt_extended.jwtmanager.invalid_token_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.invalid_token_loader",
    "flask_jwt_extended.jwtmanager.needs_fresh_token_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.needs_fresh_token_loader",
    "flask_jwt_extended.jwtmanager.revoked_token_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.revoked_token_loader",
    "flask_jwt_extended.jwtmanager.token_in_blocklist_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.token_in_blocklist_loader",
    "flask_jwt_extended.jwtmanager.token_verification_failed_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.token_verification_failed_loader",
    "flask_jwt_extended.jwtmanager.token_verification_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.token_verification_loader",
    "flask_jwt_extended.jwtmanager.unauthorized_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.unauthorized_loader",
    "flask_jwt_extended.jwtmanager.user_identity_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.user_identity_loader",
    "flask_jwt_extended.jwtmanager.user_lookup_error_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.user_lookup_error_loader",
    "flask_jwt_extended.jwtmanager.user_lookup_loader": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.user_lookup_loader",
    "flask_jwt_extended.set_access_cookies": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.set_access_cookies",
    "flask_jwt_extended.set_refresh_cookies": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.set_refresh_cookies",
    "flask_jwt_extended.unset_access_cookies": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.unset_access_cookies",
    "flask_jwt_extended.unset_jwt_cookies": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.unset_jwt_cookies",
    "flask_jwt_extended.unset_refresh_cookies": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.unset_refresh_cookies",
    "flask_jwt_extended.verify_jwt_in_request": "https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.verify_jwt_in_request",
}
