VERSION = "1.2.3"

# fmt: off
MAPPING = {
    "flupy": "https://flupy.readthedocs.io/en/latest/",
    "flupy.flu": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu",
    "flupy.flu.chunk": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.chunk",
    "flupy.flu.collect": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.collect",
    "flupy.flu.count": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.count",
    "flupy.flu.denormalize": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.denormalize",
    "flupy.flu.drop_while": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.drop_while",
    "flupy.flu.enumerate": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.enumerate",
    "flupy.flu.filter": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.filter",
    "flupy.flu.first": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.first",
    "flupy.flu.flatten": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.flatten",
    "flupy.flu.fold_left": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.fold_left",
    "flupy.flu.group_by": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.group_by",
    "flupy.flu.head": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.head",
    "flupy.flu.join_full": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.join_full",
    "flupy.flu.join_inner": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.join_inner",
    "flupy.flu.join_left": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.join_left",
    "flupy.flu.last": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.last",
    "flupy.flu.map": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.map",
    "flupy.flu.map_attr": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.map_attr",
    "flupy.flu.map_item": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.map_item",
    "flupy.flu.max": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.max",
    "flupy.flu.min": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.min",
    "flupy.flu.rate_limit": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.rate_limit",
    "flupy.flu.reduce": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.reduce",
    "flupy.flu.shuffle": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.shuffle",
    "flupy.flu.side_effect": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.side_effect",
    "flupy.flu.sort": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.sort",
    "flupy.flu.sum": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.sum",
    "flupy.flu.tail": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.tail",
    "flupy.flu.take": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.take",
    "flupy.flu.take_while": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.take_while",
    "flupy.flu.tee": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.tee",
    "flupy.flu.to_list": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.to_list",
    "flupy.flu.unique": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.unique",
    "flupy.flu.window": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.window",
    "flupy.flu.zip": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.zip",
    "flupy.flu.zip_longest": "https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.zip_longest",
}
