VERSION = "2.1.0"

# fmt: off
MAPPING = {
    "graypy": "https://graypy.readthedocs.io/en/latest/",
    "graypy.handler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html",
    "graypy.handler.basegelfhandler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.BaseGELFHandler",
    "graypy.handler.basegelfhandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.BaseGELFHandler.__init__",
    "graypy.handler.basegelfhandler.makepickle": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.BaseGELFHandler.makePickle",
    "graypy.handler.chunkedgelf": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.ChunkedGELF",
    "graypy.handler.chunkedgelf.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.ChunkedGELF.__init__",
    "graypy.handler.chunkedgelf.encode": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.ChunkedGELF.encode",
    "graypy.handler.chunkedgelf.message_chunks": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.ChunkedGELF.message_chunks",
    "graypy.handler.gelfhttphandler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFHTTPHandler",
    "graypy.handler.gelfhttphandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFHTTPHandler.__init__",
    "graypy.handler.gelfhttphandler.emit": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFHTTPHandler.emit",
    "graypy.handler.gelftcphandler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTCPHandler",
    "graypy.handler.gelftcphandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTCPHandler.__init__",
    "graypy.handler.gelftcphandler.makepickle": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTCPHandler.makePickle",
    "graypy.handler.gelftlshandler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTLSHandler",
    "graypy.handler.gelftlshandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTLSHandler.__init__",
    "graypy.handler.gelftlshandler.makesocket": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFTLSHandler.makeSocket",
    "graypy.handler.gelfudphandler": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFUDPHandler",
    "graypy.handler.gelfudphandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFUDPHandler.__init__",
    "graypy.handler.gelfudphandler.send": "https://graypy.readthedocs.io/en/latest/api/graypy.handler.html#graypy.handler.GELFUDPHandler.send",
    "graypy.rabbitmq": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html",
    "graypy.rabbitmq.excludefilter": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.ExcludeFilter",
    "graypy.rabbitmq.excludefilter.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.ExcludeFilter.__init__",
    "graypy.rabbitmq.excludefilter.filter": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.ExcludeFilter.filter",
    "graypy.rabbitmq.gelfrabbithandler": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.GELFRabbitHandler",
    "graypy.rabbitmq.gelfrabbithandler.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.GELFRabbitHandler.__init__",
    "graypy.rabbitmq.gelfrabbithandler.makepickle": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.GELFRabbitHandler.makePickle",
    "graypy.rabbitmq.gelfrabbithandler.makesocket": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.GELFRabbitHandler.makeSocket",
    "graypy.rabbitmq.rabbitsocket": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.RabbitSocket",
    "graypy.rabbitmq.rabbitsocket.__init__": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.RabbitSocket.__init__",
    "graypy.rabbitmq.rabbitsocket.close": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.RabbitSocket.close",
    "graypy.rabbitmq.rabbitsocket.sendall": "https://graypy.readthedocs.io/en/latest/api/graypy.rabbitmq.html#graypy.rabbitmq.RabbitSocket.sendall",
}
