VERSION = "2.0.0"

# fmt: off
MAPPING = {
    "honcho": "https://honcho.readthedocs.io/en/latest/",
    "honcho.environ": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.environ",
    "honcho.environ.env": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Env",
    "honcho.environ.env.load_procfile": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Env.load_procfile",
    "honcho.environ.env.port": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Env.port",
    "honcho.environ.env.procfile": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Env.procfile",
    "honcho.environ.expand_processes": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.expand_processes",
    "honcho.environ.parse": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.parse",
    "honcho.environ.parse_procfile": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.parse_procfile",
    "honcho.environ.processparams": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.ProcessParams",
    "honcho.environ.processparams.cmd": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.ProcessParams.cmd",
    "honcho.environ.processparams.env": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.ProcessParams.env",
    "honcho.environ.processparams.name": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.ProcessParams.name",
    "honcho.environ.processparams.quiet": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.ProcessParams.quiet",
    "honcho.environ.procfile": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Procfile",
    "honcho.environ.procfile.add_process": "https://honcho.readthedocs.io/en/latest/api.html#honcho.environ.Procfile.add_process",
    "honcho.export": "https://honcho.readthedocs.io/en/latest/api.html",
    "honcho.export.base": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.export.base",
    "honcho.export.base.baseexport": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.BaseExport",
    "honcho.export.base.baseexport.get_template": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.BaseExport.get_template",
    "honcho.export.base.baseexport.get_template_loader": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.BaseExport.get_template_loader",
    "honcho.export.base.baseexport.render": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.BaseExport.render",
    "honcho.export.base.dashrepl": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.dashrepl",
    "honcho.export.base.file": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.File",
    "honcho.export.base.percentescape": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.base.percentescape",
    "honcho.export.supervisord": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.export.supervisord",
    "honcho.export.supervisord.export": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.supervisord.Export",
    "honcho.export.supervisord.export.get_template_loader": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.supervisord.Export.get_template_loader",
    "honcho.export.supervisord.export.render": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.supervisord.Export.render",
    "honcho.export.upstart": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.export.upstart",
    "honcho.export.upstart.export": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.upstart.Export",
    "honcho.export.upstart.export.get_template_loader": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.upstart.Export.get_template_loader",
    "honcho.export.upstart.export.render": "https://honcho.readthedocs.io/en/latest/api.html#honcho.export.upstart.Export.render",
    "honcho.manager": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.manager",
    "honcho.manager.manager": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager",
    "honcho.manager.manager.add_process": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.add_process",
    "honcho.manager.manager.kill": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.kill",
    "honcho.manager.manager.loop": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.loop",
    "honcho.manager.manager.returncode": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.returncode",
    "honcho.manager.manager.terminate": "https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.terminate",
    "honcho.process": "https://honcho.readthedocs.io/en/latest/api.html#module-honcho.process",
    "honcho.process.popen": "https://honcho.readthedocs.io/en/latest/api.html#honcho.process.Popen",
    "honcho.process.process": "https://honcho.readthedocs.io/en/latest/api.html#honcho.process.Process",
    "honcho.process.process.run": "https://honcho.readthedocs.io/en/latest/api.html#honcho.process.Process.run",
}
