VERSION = "0.22.0"

# fmt: off
MAPPING = {
    "httplib2": "https://httplib2.readthedocs.io/en/latest/",
    "httplib2.cache": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html",
    "httplib2.cache.delete": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Cache.delete",
    "httplib2.cache.get": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Cache.get",
    "httplib2.cache.set": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Cache.set",
    "httplib2.debuglevel": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.debuglevel",
    "httplib2.failedtodecompresscontent": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.FailedToDecompressContent",
    "httplib2.filecache": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.FileCache",
    "httplib2.http": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http",
    "httplib2.http.add_certificate": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.add_certificate",
    "httplib2.http.add_credentials": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.add_credentials",
    "httplib2.http.clear_credentials": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.clear_credentials",
    "httplib2.http.follow_all_redirects": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.follow_all_redirects",
    "httplib2.http.follow_redirects": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.follow_redirects",
    "httplib2.http.force_exception_to_status_code": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.force_exception_to_status_code",
    "httplib2.http.forward_authorization_headers": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.forward_authorization_headers",
    "httplib2.http.ignore_etag": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.ignore_etag",
    "httplib2.http.optimistic_concurrency_methods": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.optimistic_concurrency_methods",
    "httplib2.http.request": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.request",
    "httplib2.httplib2error": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.HttpLib2Error",
    "httplib2.proxyinfo": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.ProxyInfo",
    "httplib2.redirectlimit": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.RedirectLimit",
    "httplib2.redirectmissinglocation": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.RedirectMissingLocation",
    "httplib2.relativeurierror": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.RelativeURIError",
    "httplib2.response": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response",
    "httplib2.response.fromcache": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response.fromcache",
    "httplib2.response.previous": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response.previous",
    "httplib2.response.reason": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response.reason",
    "httplib2.response.status": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response.status",
    "httplib2.response.version": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Response.version",
    "httplib2.retries": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.RETRIES",
    "httplib2.servernotfounderror": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.ServerNotFoundError",
    "httplib2.unimplementeddigestauthoptionerror": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.UnimplementedDigestAuthOptionError",
    "httplib2.unimplementedhmacdigestauthoptionerror": "https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.UnimplementedHmacDigestAuthOptionError",
}
