VERSION = "21.0.0"

# fmt: off
MAPPING = {
    "hyperlink": "https://hyperlink.readthedocs.io/en/latest/",
    "hyperlink._url": "https://hyperlink.readthedocs.io/en/latest/api.html",
    "hyperlink.decodedurl": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.DecodedURL",
    "hyperlink.decodedurl.from_text": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.DecodedURL.from_text",
    "hyperlink.parse": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.parse",
    "hyperlink.register_scheme": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.register_scheme",
    "hyperlink.url": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL",
    "hyperlink.url.absolute": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.absolute",
    "hyperlink.url.add": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.add",
    "hyperlink.url.child": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.child",
    "hyperlink.url.click": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.click",
    "hyperlink.url.fragment": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.fragment",
    "hyperlink.url.from_text": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.from_text",
    "hyperlink.url.get": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.get",
    "hyperlink.url.host": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.host",
    "hyperlink.url.normalize": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.normalize",
    "hyperlink.url.path": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.path",
    "hyperlink.url.port": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.port",
    "hyperlink.url.query": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.query",
    "hyperlink.url.remove": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.remove",
    "hyperlink.url.replace": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.replace",
    "hyperlink.url.rooted": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.rooted",
    "hyperlink.url.scheme": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.scheme",
    "hyperlink.url.set": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.set",
    "hyperlink.url.sibling": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.sibling",
    "hyperlink.url.to_iri": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.to_iri",
    "hyperlink.url.to_text": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.to_text",
    "hyperlink.url.to_uri": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.to_uri",
    "hyperlink.url.user": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.user",
    "hyperlink.url.userinfo": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URL.userinfo",
    "hyperlink.urlparseerror": "https://hyperlink.readthedocs.io/en/latest/api.html#hyperlink.URLParseError",
}
