VERSION = "1.3.2"

# fmt: off
MAPPING = {
    "itemloaders": "https://itemloaders.readthedocs.io/en/latest/",
    "itemloaders.itemloader": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader",
    "itemloaders.itemloader.add_css": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.add_css",
    "itemloaders.itemloader.add_jmes": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.add_jmes",
    "itemloaders.itemloader.add_value": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.add_value",
    "itemloaders.itemloader.add_xpath": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.add_xpath",
    "itemloaders.itemloader.context": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.context",
    "itemloaders.itemloader.default_input_processor": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.default_input_processor",
    "itemloaders.itemloader.default_item_class": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.default_item_class",
    "itemloaders.itemloader.default_output_processor": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.default_output_processor",
    "itemloaders.itemloader.get_collected_values": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_collected_values",
    "itemloaders.itemloader.get_css": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_css",
    "itemloaders.itemloader.get_jmes": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_jmes",
    "itemloaders.itemloader.get_output_value": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_output_value",
    "itemloaders.itemloader.get_value": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_value",
    "itemloaders.itemloader.get_xpath": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.get_xpath",
    "itemloaders.itemloader.item": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.item",
    "itemloaders.itemloader.load_item": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.load_item",
    "itemloaders.itemloader.nested_css": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.nested_css",
    "itemloaders.itemloader.nested_xpath": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.nested_xpath",
    "itemloaders.itemloader.replace_css": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.replace_css",
    "itemloaders.itemloader.replace_jmes": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.replace_jmes",
    "itemloaders.itemloader.replace_value": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.replace_value",
    "itemloaders.itemloader.replace_xpath": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.replace_xpath",
    "itemloaders.itemloader.selector": "https://itemloaders.readthedocs.io/en/latest/api-reference.html#itemloaders.ItemLoader.selector",
    "itemloaders.processors": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html",
    "itemloaders.processors.compose": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.Compose",
    "itemloaders.processors.identity": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.Identity",
    "itemloaders.processors.join": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.Join",
    "itemloaders.processors.mapcompose": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.MapCompose",
    "itemloaders.processors.selectjmes": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.SelectJmes",
    "itemloaders.processors.takefirst": "https://itemloaders.readthedocs.io/en/latest/built-in-processors.html#itemloaders.processors.TakeFirst",
}
