VERSION = "6.6.2"

# fmt: off
MAPPING = {
    "multidict": "https://multidict.aio-libs.org/en/stable/",
    "multidict.cimultidict": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.CIMultiDict",
    "multidict.cimultidictproxy": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.CIMultiDictProxy",
    "multidict.getversion": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.getversion",
    "multidict.istr": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.istr",
    "multidict.multidict": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict",
    "multidict.multidict.add": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.add",
    "multidict.multidict.clear": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.clear",
    "multidict.multidict.copy": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.copy",
    "multidict.multidict.d": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.d",
    "multidict.multidict.extend": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.extend",
    "multidict.multidict.get": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.get",
    "multidict.multidict.getall": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.getall",
    "multidict.multidict.getone": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.getone",
    "multidict.multidict.items": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.items",
    "multidict.multidict.iter": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.iter",
    "multidict.multidict.keys": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.keys",
    "multidict.multidict.len": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.len",
    "multidict.multidict.merge": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.merge",
    "multidict.multidict.pop": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.pop",
    "multidict.multidict.popall": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.popall",
    "multidict.multidict.popitem": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.popitem",
    "multidict.multidict.popone": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.popone",
    "multidict.multidict.setdefault": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.setdefault",
    "multidict.multidict.update": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.update",
    "multidict.multidict.values": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDict.values",
    "multidict.multidictproxy": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy",
    "multidict.multidictproxy.copy": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.copy",
    "multidict.multidictproxy.d": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.d",
    "multidict.multidictproxy.get": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.get",
    "multidict.multidictproxy.getall": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.getall",
    "multidict.multidictproxy.getone": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.getone",
    "multidict.multidictproxy.items": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.items",
    "multidict.multidictproxy.iter": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.iter",
    "multidict.multidictproxy.keys": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.keys",
    "multidict.multidictproxy.len": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.len",
    "multidict.multidictproxy.values": "https://multidict.aio-libs.org/en/stable/multidict/#multidict.MultiDictProxy.values",
}
