VERSION = "5.10.4"

# fmt: off
MAPPING = {
    "nbformat": "https://nbformat.readthedocs.io/en/latest/",
    "nbformat.convert": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.convert",
    "nbformat.current_nbformat": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.current_nbformat",
    "nbformat.current_nbformat_minor": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.current_nbformat_minor",
    "nbformat.from_dict": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.from_dict",
    "nbformat.no_convert": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.NO_CONVERT",
    "nbformat.notebooknode": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.NotebookNode",
    "nbformat.read": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.read",
    "nbformat.reads": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.reads",
    "nbformat.sign": "https://nbformat.readthedocs.io/en/latest/api.html#module-nbformat.sign",
    "nbformat.sign.memorysignaturestore": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.MemorySignatureStore",
    "nbformat.sign.notebooknotary": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary",
    "nbformat.sign.notebooknotary.check_cells": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary.check_cells",
    "nbformat.sign.notebooknotary.check_signature": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary.check_signature",
    "nbformat.sign.notebooknotary.mark_cells": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary.mark_cells",
    "nbformat.sign.notebooknotary.sign": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary.sign",
    "nbformat.sign.notebooknotary.unsign": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.NotebookNotary.unsign",
    "nbformat.sign.signaturestore": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SignatureStore",
    "nbformat.sign.signaturestore.check_signature": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SignatureStore.check_signature",
    "nbformat.sign.signaturestore.close": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SignatureStore.close",
    "nbformat.sign.signaturestore.remove_signature": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SignatureStore.remove_signature",
    "nbformat.sign.signaturestore.store_signature": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SignatureStore.store_signature",
    "nbformat.sign.sqlitesignaturestore": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.SQLiteSignatureStore",
    "nbformat.v4": "https://nbformat.readthedocs.io/en/latest/api.html#module-nbformat.v4",
    "nbformat.v4.new_code_cell": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.new_code_cell",
    "nbformat.v4.new_markdown_cell": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.new_markdown_cell",
    "nbformat.v4.new_notebook": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.new_notebook",
    "nbformat.v4.new_output": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.new_output",
    "nbformat.v4.new_raw_cell": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.new_raw_cell",
    "nbformat.v4.output_from_msg": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.v4.output_from_msg",
    "nbformat.validate": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.validate",
    "nbformat.validationerror": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.ValidationError",
    "nbformat.write": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.write",
    "nbformat.writes": "https://nbformat.readthedocs.io/en/latest/api.html#nbformat.writes",
}
