VERSION = "23.1.0"

# fmt: off
MAPPING = {
    "pem": "https://pem.readthedocs.io/en/stable/",
    "pem.abstractpemobject": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject",
    "pem.abstractpemobject.__str__": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.__str__",
    "pem.abstractpemobject.as_bytes": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.as_bytes",
    "pem.abstractpemobject.as_text": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.as_text",
    "pem.abstractpemobject.bytes_payload": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.bytes_payload",
    "pem.abstractpemobject.decoded_payload": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.decoded_payload",
    "pem.abstractpemobject.meta_headers": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.meta_headers",
    "pem.abstractpemobject.sha1_hexdigest": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.sha1_hexdigest",
    "pem.abstractpemobject.text_payload": "https://pem.readthedocs.io/en/stable/api.html#pem.AbstractPEMObject.text_payload",
    "pem.certificate": "https://pem.readthedocs.io/en/stable/api.html#pem.Certificate",
    "pem.certificaterequest": "https://pem.readthedocs.io/en/stable/api.html#pem.CertificateRequest",
    "pem.certificaterevocationlist": "https://pem.readthedocs.io/en/stable/api.html#pem.CertificateRevocationList",
    "pem.dhparameters": "https://pem.readthedocs.io/en/stable/api.html#pem.DHParameters",
    "pem.dsaprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.DSAPrivateKey",
    "pem.ecprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.ECPrivateKey",
    "pem.key": "https://pem.readthedocs.io/en/stable/api.html#pem.Key",
    "pem.openpgpprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.OpenPGPPrivateKey",
    "pem.openpgppublickey": "https://pem.readthedocs.io/en/stable/api.html#pem.OpenPGPPublicKey",
    "pem.opensshprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.OpenSSHPrivateKey",
    "pem.openssltrustedcertificate": "https://pem.readthedocs.io/en/stable/api.html#pem.OpenSSLTrustedCertificate",
    "pem.parse": "https://pem.readthedocs.io/en/stable/api.html#pem.parse",
    "pem.parse_file": "https://pem.readthedocs.io/en/stable/api.html#pem.parse_file",
    "pem.privatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.PrivateKey",
    "pem.publickey": "https://pem.readthedocs.io/en/stable/api.html#pem.PublicKey",
    "pem.rsaprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.RSAPrivateKey",
    "pem.rsapublickey": "https://pem.readthedocs.io/en/stable/api.html#pem.RSAPublicKey",
    "pem.sshcomprivatekey": "https://pem.readthedocs.io/en/stable/api.html#pem.SSHCOMPrivateKey",
    "pem.sshpublickey": "https://pem.readthedocs.io/en/stable/api.html#pem.SSHPublicKey",
    "pem.twisted": "https://pem.readthedocs.io/en/stable/api.html",
    "pem.twisted.certificateoptionsfromfiles": "https://pem.readthedocs.io/en/stable/api.html#pem.twisted.certificateOptionsFromFiles",
    "pem.twisted.certificateoptionsfrompems": "https://pem.readthedocs.io/en/stable/api.html#pem.twisted.certificateOptionsFromPEMs",
}
