VERSION = "1.0"

# fmt: off
MAPPING = {
    "postmarker": "https://postmarker.readthedocs.io/en/latest/",
    "postmarker.models.bounces": "https://postmarker.readthedocs.io/en/latest/bounces.html",
    "postmarker.models.bounces.bounce": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.Bounce",
    "postmarker.models.bounces.bounce.activate": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.Bounce.activate",
    "postmarker.models.bounces.bounce.dump": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.Bounce.dump",
    "postmarker.models.bounces.bouncemanager": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager",
    "postmarker.models.bounces.bouncemanager.activate": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.activate",
    "postmarker.models.bounces.bouncemanager.all": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.all",
    "postmarker.models.bounces.bouncemanager.bounce": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.Bounce",
    "postmarker.models.bounces.bouncemanager.deliverystats": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.deliverystats",
    "postmarker.models.bounces.bouncemanager.get": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.get",
    "postmarker.models.bounces.bouncemanager.get_dump": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.get_dump",
    "postmarker.models.bounces.bouncemanager.model": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.model",
    "postmarker.models.bounces.bouncemanager.tags": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.bounces.BounceManager.tags",
    "postmarker.models.emails": "https://postmarker.readthedocs.io/en/latest/emails.html",
    "postmarker.models.emails.email": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.Email",
    "postmarker.models.emails.email.attach": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.Email.attach",
    "postmarker.models.emails.emailmanager": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager",
    "postmarker.models.emails.emailmanager.email": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.Email",
    "postmarker.models.emails.emailmanager.emailbatch": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.EmailBatch",
    "postmarker.models.emails.emailmanager.emailtemplate": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.EmailTemplate",
    "postmarker.models.emails.emailmanager.emailtemplatebatch": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.EmailTemplateBatch",
    "postmarker.models.emails.emailmanager.send": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.send",
    "postmarker.models.emails.emailmanager.send_batch": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.send_batch",
    "postmarker.models.emails.emailmanager.send_template_batch": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.emails.EmailManager.send_template_batch",
    "postmarker.models.server": "https://postmarker.readthedocs.io/en/latest/reference.html",
    "postmarker.models.server.server": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.server.Server",
    "postmarker.models.server.servermanager": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.server.ServerManager",
    "postmarker.models.server.servermanager.model": "https://postmarker.readthedocs.io/en/latest/reference.html#postmarker.models.server.ServerManager.model",
}
