VERSION = "13.0.0"

# fmt: off
MAPPING = {
    "pyee": "https://pyee.readthedocs.io/en/latest/",
    "pyee.asyncio": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio",
    "pyee.asyncio.asyncioeventemitter": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio.AsyncIOEventEmitter",
    "pyee.asyncio.asyncioeventemitter.cancel": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio.AsyncIOEventEmitter.cancel",
    "pyee.asyncio.asyncioeventemitter.complete": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio.AsyncIOEventEmitter.complete",
    "pyee.asyncio.asyncioeventemitter.emit": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio.AsyncIOEventEmitter.emit",
    "pyee.asyncio.asyncioeventemitter.wait_for_complete": "https://pyee.readthedocs.io/en/latest/api/#pyee.asyncio.AsyncIOEventEmitter.wait_for_complete",
    "pyee.cls": "https://pyee.readthedocs.io/en/latest/api/#pyee.cls",
    "pyee.cls.evented": "https://pyee.readthedocs.io/en/latest/api/#pyee.cls.evented",
    "pyee.cls.on": "https://pyee.readthedocs.io/en/latest/api/#pyee.cls.on",
    "pyee.eventemitter": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter",
    "pyee.eventemitter.add_listener": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.add_listener",
    "pyee.eventemitter.emit": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.emit",
    "pyee.eventemitter.event_names": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.event_names",
    "pyee.eventemitter.listeners": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.listeners",
    "pyee.eventemitter.listens_to": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.listens_to",
    "pyee.eventemitter.on": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.on",
    "pyee.eventemitter.once": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.once",
    "pyee.eventemitter.remove_all_listeners": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.remove_all_listeners",
    "pyee.eventemitter.remove_listener": "https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.remove_listener",
    "pyee.executor": "https://pyee.readthedocs.io/en/latest/api/#pyee.executor",
    "pyee.executor.executoreventemitter": "https://pyee.readthedocs.io/en/latest/api/#pyee.executor.ExecutorEventEmitter",
    "pyee.executor.executoreventemitter.shutdown": "https://pyee.readthedocs.io/en/latest/api/#pyee.executor.ExecutorEventEmitter.shutdown",
    "pyee.pyeeexception": "https://pyee.readthedocs.io/en/latest/api/#pyee.PyeeException",
    "pyee.trio": "https://pyee.readthedocs.io/en/latest/api/#pyee.trio",
    "pyee.trio.trioeventemitter": "https://pyee.readthedocs.io/en/latest/api/#pyee.trio.TrioEventEmitter",
    "pyee.trio.trioeventemitter.context": "https://pyee.readthedocs.io/en/latest/api/#pyee.trio.TrioEventEmitter.context",
    "pyee.twisted": "https://pyee.readthedocs.io/en/latest/api/#pyee.twisted",
    "pyee.twisted.twistedeventemitter": "https://pyee.readthedocs.io/en/latest/api/#pyee.twisted.TwistedEventEmitter",
    "pyee.uplift": "https://pyee.readthedocs.io/en/latest/api/#pyee.uplift",
    "pyee.uplift.unwrap": "https://pyee.readthedocs.io/en/latest/api/#pyee.uplift.unwrap",
    "pyee.uplift.uplift": "https://pyee.readthedocs.io/en/latest/api/#pyee.uplift.uplift",
}
