VERSION = "2.10.1"

# fmt: off
MAPPING = {
    "jwt": "https://pyjwt.readthedocs.io/en/stable/",
    "jwt.api_jwt": "https://pyjwt.readthedocs.io/en/stable/api.html",
    "jwt.api_jwt.decode_complete": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.api_jwt.decode_complete",
    "jwt.decode": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.decode",
    "jwt.encode": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.encode",
    "jwt.exceptions": "https://pyjwt.readthedocs.io/en/stable/api.html",
    "jwt.exceptions.decodeerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.DecodeError",
    "jwt.exceptions.expiredsignatureerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.ExpiredSignatureError",
    "jwt.exceptions.immaturesignatureerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.ImmatureSignatureError",
    "jwt.exceptions.invalidalgorithmerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidAlgorithmError",
    "jwt.exceptions.invalidaudienceerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidAudienceError",
    "jwt.exceptions.invalidissuedaterror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidIssuedAtError",
    "jwt.exceptions.invalidissuererror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidIssuerError",
    "jwt.exceptions.invalidkeyerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidKeyError",
    "jwt.exceptions.invalidsignatureerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidSignatureError",
    "jwt.exceptions.invalidtokenerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.InvalidTokenError",
    "jwt.exceptions.missingrequiredclaimerror": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.MissingRequiredClaimError",
    "jwt.pyjwk": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK",
    "jwt.pyjwk.__init__": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.__init__",
    "jwt.pyjwk.algorithm": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.Algorithm",
    "jwt.pyjwk.algorithm_name": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.algorithm_name",
    "jwt.pyjwk.from_json": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.from_json",
    "jwt.pyjwk.key_id": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.key_id",
    "jwt.pyjwk.key_type": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.key_type",
    "jwt.pyjwk.public_key_use": "https://pyjwt.readthedocs.io/en/stable/api.html#jwt.PyJWK.public_key_use",
}
