VERSION = "0.1.55"

# fmt: off
MAPPING = {
    "pylabel": "https://pylabel.readthedocs.io/en/latest/",
    "pylabel.analyze": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.analyze",
    "pylabel.analyze.analyze": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze",
    "pylabel.analyze.analyze.class_counts": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.class_counts",
    "pylabel.analyze.analyze.class_ids": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.class_ids",
    "pylabel.analyze.analyze.class_name_id_map": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.class_name_id_map",
    "pylabel.analyze.analyze.classes": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.classes",
    "pylabel.analyze.analyze.num_classes": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.num_classes",
    "pylabel.analyze.analyze.num_images": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.num_images",
    "pylabel.analyze.analyze.showclasssplits": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.analyze.Analyze.ShowClassSplits",
    "pylabel.dataset": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.dataset",
    "pylabel.dataset.dataset": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset",
    "pylabel.dataset.dataset.analyze": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.analyze",
    "pylabel.dataset.dataset.df": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.df",
    "pylabel.dataset.dataset.export": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.export",
    "pylabel.dataset.dataset.labeler": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.labeler",
    "pylabel.dataset.dataset.name": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.name",
    "pylabel.dataset.dataset.path_to_annotations": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.path_to_annotations",
    "pylabel.dataset.dataset.reindexcatids": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.ReindexCatIds",
    "pylabel.dataset.dataset.splitter": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.splitter",
    "pylabel.dataset.dataset.visualize": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.visualize",
    "pylabel.exporter": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.exporter",
    "pylabel.exporter.export": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.exporter.Export",
    "pylabel.exporter.export.exporttococo": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.exporter.Export.ExportToCoco",
    "pylabel.exporter.export.exporttovoc": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.exporter.Export.ExportToVoc",
    "pylabel.exporter.export.exporttoyolov5": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.exporter.Export.ExportToYoloV5",
    "pylabel.importer": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.importer",
    "pylabel.importer.importcoco": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.importer.ImportCoco",
    "pylabel.importer.importimagesonly": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.importer.ImportImagesOnly",
    "pylabel.importer.importvoc": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.importer.ImportVOC",
    "pylabel.importer.importyolov5": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.importer.ImportYoloV5",
    "pylabel.importer.importyolov5withyaml": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.importer.ImportYoloV5WithYaml",
    "pylabel.labeler": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.labeler",
    "pylabel.labeler.labeler": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.labeler.Labeler",
    "pylabel.labeler.labeler.startpylaber": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.labeler.Labeler.StartPyLaber",
    "pylabel.shared": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.shared",
    "pylabel.splitter": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.splitter",
    "pylabel.splitter.split": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.splitter.Split",
    "pylabel.splitter.split.groupshufflesplit": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.splitter.Split.GroupShuffleSplit",
    "pylabel.splitter.split.stratifiedgroupshufflesplit": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.splitter.Split.StratifiedGroupShuffleSplit",
    "pylabel.splitter.split.unsplit": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.splitter.Split.UnSplit",
    "pylabel.visualize": "https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.visualize",
    "pylabel.visualize.visualize": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.visualize.Visualize",
    "pylabel.visualize.visualize.showboundingboxes": "https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.visualize.Visualize.ShowBoundingBoxes",
}
