VERSION = "1.1.1"

# fmt: off
MAPPING = {
    "pymysql": "https://pymysql.readthedocs.io/en/latest/",
    "pymysql.connections": "https://pymysql.readthedocs.io/en/latest/modules/connections.html",
    "pymysql.connections.connection": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection",
    "pymysql.connections.connection.begin": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.begin",
    "pymysql.connections.connection.close": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.close",
    "pymysql.connections.connection.commit": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.commit",
    "pymysql.connections.connection.cursor": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.cursor",
    "pymysql.connections.connection.open": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.open",
    "pymysql.connections.connection.ping": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.ping",
    "pymysql.connections.connection.rollback": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.rollback",
    "pymysql.connections.connection.select_db": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.select_db",
    "pymysql.connections.connection.set_character_set": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.set_character_set",
    "pymysql.connections.connection.set_charset": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.set_charset",
    "pymysql.connections.connection.show_warnings": "https://pymysql.readthedocs.io/en/latest/modules/connections.html#pymysql.connections.Connection.show_warnings",
    "pymysql.cursors": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html",
    "pymysql.cursors.cursor": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor",
    "pymysql.cursors.cursor.callproc": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.callproc",
    "pymysql.cursors.cursor.close": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.close",
    "pymysql.cursors.cursor.execute": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.execute",
    "pymysql.cursors.cursor.executemany": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.executemany",
    "pymysql.cursors.cursor.fetchall": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.fetchall",
    "pymysql.cursors.cursor.fetchmany": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.fetchmany",
    "pymysql.cursors.cursor.fetchone": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.fetchone",
    "pymysql.cursors.cursor.max_stmt_length": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.max_stmt_length",
    "pymysql.cursors.cursor.mogrify": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.mogrify",
    "pymysql.cursors.cursor.setinputsizes": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.setinputsizes",
    "pymysql.cursors.cursor.setoutputsizes": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.Cursor.setoutputsizes",
    "pymysql.cursors.dictcursor": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.DictCursor",
    "pymysql.cursors.sscursor": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor",
    "pymysql.cursors.sscursor.close": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.close",
    "pymysql.cursors.sscursor.fetchall": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.fetchall",
    "pymysql.cursors.sscursor.fetchall_unbuffered": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.fetchall_unbuffered",
    "pymysql.cursors.sscursor.fetchmany": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.fetchmany",
    "pymysql.cursors.sscursor.fetchone": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.fetchone",
    "pymysql.cursors.sscursor.read_next": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.read_next",
    "pymysql.cursors.ssdictcursor": "https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSDictCursor",
}
