VERSION = "0.16.1"

# fmt: off
MAPPING = {
    "barcode": "https://python-barcode.readthedocs.io/en/stable/",
    "barcode.codex": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html",
    "barcode.codex.code128": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code128",
    "barcode.codex.code128.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code128.get_fullcode",
    "barcode.codex.code128.render": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code128.render",
    "barcode.codex.code39": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code39",
    "barcode.codex.code39.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code39.get_fullcode",
    "barcode.codex.code39.render": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Code39.render",
    "barcode.codex.gs1_128": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Gs1_128",
    "barcode.codex.gs1_128.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.Gs1_128.get_fullcode",
    "barcode.codex.pzn7": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.PZN7",
    "barcode.codex.pzn7.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.codex.PZN7.get_fullcode",
    "barcode.ean": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html",
    "barcode.ean.europeanarticlenumber13": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13",
    "barcode.ean.europeanarticlenumber13.build": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13.build",
    "barcode.ean.europeanarticlenumber13.calculate_checksum": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13.calculate_checksum",
    "barcode.ean.europeanarticlenumber13.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13.get_fullcode",
    "barcode.ean.europeanarticlenumber13.render": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13.render",
    "barcode.ean.europeanarticlenumber13.to_ascii": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber13.to_ascii",
    "barcode.ean.europeanarticlenumber14": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber14",
    "barcode.ean.europeanarticlenumber14.calculate_checksum": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber14.calculate_checksum",
    "barcode.ean.europeanarticlenumber8": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber8",
    "barcode.ean.europeanarticlenumber8.build": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber8.build",
    "barcode.ean.europeanarticlenumber8.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.EuropeanArticleNumber8.get_fullcode",
    "barcode.ean.japanarticlenumber": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.ean.JapanArticleNumber",
    "barcode.isxn": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html",
    "barcode.isxn.internationalstandardbooknumber10": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.isxn.InternationalStandardBookNumber10",
    "barcode.isxn.internationalstandardbooknumber13": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.isxn.InternationalStandardBookNumber13",
    "barcode.isxn.internationalstandardserialnumber": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.isxn.InternationalStandardSerialNumber",
    "barcode.upc": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html",
    "barcode.upc.universalproductcodea": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA",
    "barcode.upc.universalproductcodea.build": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA.build",
    "barcode.upc.universalproductcodea.calculate_checksum": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA.calculate_checksum",
    "barcode.upc.universalproductcodea.get_fullcode": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA.get_fullcode",
    "barcode.upc.universalproductcodea.render": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA.render",
    "barcode.upc.universalproductcodea.to_ascii": "https://python-barcode.readthedocs.io/en/stable/supported-formats.html#barcode.upc.UniversalProductCodeA.to_ascii",
}
