VERSION = "3.8.0"

# fmt: off
MAPPING = {
    "tablib": "https://tablib.readthedocs.io/en/stable/",
    "tablib.databook": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook",
    "tablib.databook.add_sheet": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook.add_sheet",
    "tablib.databook.export": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook.export",
    "tablib.databook.load": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook.load",
    "tablib.databook.size": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook.size",
    "tablib.databook.wipe": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Databook.wipe",
    "tablib.dataset": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset",
    "tablib.dataset.add_formatter": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.add_formatter",
    "tablib.dataset.append": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.append",
    "tablib.dataset.append_col": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.append_col",
    "tablib.dataset.append_separator": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.append_separator",
    "tablib.dataset.dict": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.dict",
    "tablib.dataset.export": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.export",
    "tablib.dataset.extend": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.extend",
    "tablib.dataset.filter": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.filter",
    "tablib.dataset.get": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.get",
    "tablib.dataset.get_col": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.get_col",
    "tablib.dataset.headers": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.headers",
    "tablib.dataset.height": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.height",
    "tablib.dataset.insert": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.insert",
    "tablib.dataset.insert_col": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.insert_col",
    "tablib.dataset.insert_separator": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.insert_separator",
    "tablib.dataset.load": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.load",
    "tablib.dataset.lpop": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.lpop",
    "tablib.dataset.lpush": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.lpush",
    "tablib.dataset.lpush_col": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.lpush_col",
    "tablib.dataset.pop": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.pop",
    "tablib.dataset.remove_duplicates": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.remove_duplicates",
    "tablib.dataset.rpop": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.rpop",
    "tablib.dataset.rpush": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.rpush",
    "tablib.dataset.rpush_col": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.rpush_col",
    "tablib.dataset.sort": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.sort",
    "tablib.dataset.stack": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.stack",
    "tablib.dataset.stack_cols": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.stack_cols",
    "tablib.dataset.subset": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.subset",
    "tablib.dataset.transpose": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.transpose",
    "tablib.dataset.width": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.width",
    "tablib.dataset.wipe": "https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.wipe",
    "tablib.detect_format": "https://tablib.readthedocs.io/en/stable/api.html#tablib.detect_format",
    "tablib.exceptions": "https://tablib.readthedocs.io/en/stable/api.html",
    "tablib.exceptions.headersneeded": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.HeadersNeeded",
    "tablib.exceptions.invaliddatasetindex": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.InvalidDatasetIndex",
    "tablib.exceptions.invaliddatasettype": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.InvalidDatasetType",
    "tablib.exceptions.invaliddimensions": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.InvalidDimensions",
    "tablib.exceptions.tablibexception": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.TablibException",
    "tablib.exceptions.unsupportedformat": "https://tablib.readthedocs.io/en/stable/api.html#tablib.exceptions.UnsupportedFormat",
    "tablib.import_set": "https://tablib.readthedocs.io/en/stable/api.html#tablib.import_set",
}
