VERSION = "25.6.1"

# fmt: off
MAPPING = {
    "txaio": "https://txaio.readthedocs.io/en/latest/",
    "txaio.add_callbacks": "https://txaio.readthedocs.io/en/latest/api.html#txaio.add_callbacks",
    "txaio.as_future": "https://txaio.readthedocs.io/en/latest/api.html#txaio.as_future",
    "txaio.call_later": "https://txaio.readthedocs.io/en/latest/api.html#txaio.call_later",
    "txaio.cancel": "https://txaio.readthedocs.io/en/latest/api.html#txaio.cancel",
    "txaio.create_future": "https://txaio.readthedocs.io/en/latest/api.html#txaio.create_future",
    "txaio.failure_message": "https://txaio.readthedocs.io/en/latest/api.html#txaio.failure_message",
    "txaio.failure_traceback": "https://txaio.readthedocs.io/en/latest/api.html#txaio.failure_traceback",
    "txaio.gather": "https://txaio.readthedocs.io/en/latest/api.html#txaio.gather",
    "txaio.interfaces": "https://txaio.readthedocs.io/en/latest/api.html",
    "txaio.interfaces.ifailedfuture": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.IFailedFuture",
    "txaio.interfaces.ifailedfuture.value": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.IFailedFuture.value",
    "txaio.interfaces.ilogger": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger",
    "txaio.interfaces.ilogger.critical": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.critical",
    "txaio.interfaces.ilogger.debug": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.debug",
    "txaio.interfaces.ilogger.error": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.error",
    "txaio.interfaces.ilogger.info": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.info",
    "txaio.interfaces.ilogger.trace": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.trace",
    "txaio.interfaces.ilogger.warn": "https://txaio.readthedocs.io/en/latest/api.html#txaio.interfaces.ILogger.warn",
    "txaio.make_batched_timer": "https://txaio.readthedocs.io/en/latest/api.html#txaio.make_batched_timer",
    "txaio.make_logger": "https://txaio.readthedocs.io/en/latest/api.html#txaio.make_logger",
    "txaio.reject": "https://txaio.readthedocs.io/en/latest/api.html#txaio.reject",
    "txaio.resolve": "https://txaio.readthedocs.io/en/latest/api.html#txaio.resolve",
    "txaio.testutil": "https://txaio.readthedocs.io/en/latest/api.html",
    "txaio.testutil.replace_loop": "https://txaio.readthedocs.io/en/latest/api.html#txaio.testutil.replace_loop",
    "txaio.use_asyncio": "https://txaio.readthedocs.io/en/latest/api.html#txaio.use_asyncio",
    "txaio.use_twisted": "https://txaio.readthedocs.io/en/latest/api.html#txaio.use_twisted",
    "txaio.using_asyncio": "https://txaio.readthedocs.io/en/latest/api.html#txaio.using_asyncio",
    "txaio.using_twisted": "https://txaio.readthedocs.io/en/latest/api.html#txaio.using_twisted",
}
