VERSION = "4.4.4"

# fmt: off
MAPPING = {
    "typeguard": "https://typeguard.readthedocs.io/en/stable/",
    "typeguard.check_type": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.check_type",
    "typeguard.check_type_internal": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.check_type_internal",
    "typeguard.checker_lookup_functions": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.checker_lookup_functions",
    "typeguard.collectioncheckstrategy": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.CollectionCheckStrategy",
    "typeguard.config": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.config",
    "typeguard.forwardrefpolicy": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.ForwardRefPolicy",
    "typeguard.importhookmanager": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.ImportHookManager",
    "typeguard.importhookmanager.uninstall": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.ImportHookManager.uninstall",
    "typeguard.install_import_hook": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.install_import_hook",
    "typeguard.instrumentationwarning": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.InstrumentationWarning",
    "typeguard.load_plugins": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.load_plugins",
    "typeguard.suppress_type_checks": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.suppress_type_checks",
    "typeguard.typecheckconfiguration": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckConfiguration",
    "typeguard.typecheckconfiguration.collection_check_strategy": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckConfiguration.collection_check_strategy",
    "typeguard.typecheckconfiguration.debug_instrumentation": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckConfiguration.debug_instrumentation",
    "typeguard.typecheckconfiguration.forward_ref_policy": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckConfiguration.forward_ref_policy",
    "typeguard.typecheckconfiguration.typecheck_fail_callback": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckConfiguration.typecheck_fail_callback",
    "typeguard.typechecked": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.typechecked",
    "typeguard.typecheckerror": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckError",
    "typeguard.typecheckmemo": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckMemo",
    "typeguard.typecheckmemo.config": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckMemo.config",
    "typeguard.typecheckmemo.globals": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckMemo.globals",
    "typeguard.typecheckmemo.locals": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckMemo.locals",
    "typeguard.typecheckmemo.self_type": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckMemo.self_type",
    "typeguard.typecheckwarning": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeCheckWarning",
    "typeguard.typeguard_ignore": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.typeguard_ignore",
    "typeguard.typeguardfinder": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeguardFinder",
    "typeguard.typeguardfinder.should_instrument": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeguardFinder.should_instrument",
    "typeguard.typehintwarning": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.TypeHintWarning",
    "typeguard.unset": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.Unset",
    "typeguard.warn_on_error": "https://typeguard.readthedocs.io/en/stable/api.html#typeguard.warn_on_error",
}
