VERSION = "5.0.0"

# fmt: off
MAPPING = {
    "uritools": "https://uritools.readthedocs.io/en/stable/",
    "uritools.defragresult": "https://uritools.readthedocs.io/en/stable/index.html#uritools.DefragResult",
    "uritools.defragresult.getfragment": "https://uritools.readthedocs.io/en/stable/index.html#uritools.DefragResult.getfragment",
    "uritools.defragresult.geturi": "https://uritools.readthedocs.io/en/stable/index.html#uritools.DefragResult.geturi",
    "uritools.gen_delims": "https://uritools.readthedocs.io/en/stable/index.html#uritools.GEN_DELIMS",
    "uritools.isabspath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.isabspath",
    "uritools.isabsuri": "https://uritools.readthedocs.io/en/stable/index.html#uritools.isabsuri",
    "uritools.isnetpath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.isnetpath",
    "uritools.isrelpath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.isrelpath",
    "uritools.issamedoc": "https://uritools.readthedocs.io/en/stable/index.html#uritools.issamedoc",
    "uritools.isuri": "https://uritools.readthedocs.io/en/stable/index.html#uritools.isuri",
    "uritools.reserved": "https://uritools.readthedocs.io/en/stable/index.html#uritools.RESERVED",
    "uritools.splitresult": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult",
    "uritools.splitresult.getauthority": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getauthority",
    "uritools.splitresult.getfragment": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getfragment",
    "uritools.splitresult.gethost": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.gethost",
    "uritools.splitresult.getpath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getpath",
    "uritools.splitresult.getport": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getport",
    "uritools.splitresult.getquery": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getquery",
    "uritools.splitresult.getquerydict": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getquerydict",
    "uritools.splitresult.getquerylist": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getquerylist",
    "uritools.splitresult.getscheme": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getscheme",
    "uritools.splitresult.geturi": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.geturi",
    "uritools.splitresult.getuserinfo": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.getuserinfo",
    "uritools.splitresult.isabspath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.isabspath",
    "uritools.splitresult.isabsuri": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.isabsuri",
    "uritools.splitresult.isnetpath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.isnetpath",
    "uritools.splitresult.isrelpath": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.isrelpath",
    "uritools.splitresult.issamedoc": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.issamedoc",
    "uritools.splitresult.isuri": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.isuri",
    "uritools.splitresult.transform": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SplitResult.transform",
    "uritools.sub_delims": "https://uritools.readthedocs.io/en/stable/index.html#uritools.SUB_DELIMS",
    "uritools.unreserved": "https://uritools.readthedocs.io/en/stable/index.html#uritools.UNRESERVED",
    "uritools.uricompose": "https://uritools.readthedocs.io/en/stable/index.html#uritools.uricompose",
    "uritools.uridecode": "https://uritools.readthedocs.io/en/stable/index.html#uritools.uridecode",
    "uritools.uridefrag": "https://uritools.readthedocs.io/en/stable/index.html#uritools.uridefrag",
    "uritools.uriencode": "https://uritools.readthedocs.io/en/stable/index.html#uritools.uriencode",
    "uritools.urijoin": "https://uritools.readthedocs.io/en/stable/index.html#uritools.urijoin",
    "uritools.urisplit": "https://uritools.readthedocs.io/en/stable/index.html#uritools.urisplit",
    "uritools.uriunsplit": "https://uritools.readthedocs.io/en/stable/index.html#uritools.uriunsplit",
}
