VERSION = "3.3.0"

# fmt: off
MAPPING = {
    "versioningit": "https://versioningit.readthedocs.io/en/stable/",
    "versioningit.configerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.ConfigError",
    "versioningit.error": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Error",
    "versioningit.fallbackreport": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.FallbackReport",
    "versioningit.fallbackreport.version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.FallbackReport.version",
    "versioningit.get_cmdclasses": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.get_cmdclasses",
    "versioningit.get_next_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.get_next_version",
    "versioningit.get_template_fields_from_distribution": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.get_template_fields_from_distribution",
    "versioningit.get_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.get_version",
    "versioningit.get_version_from_pkg_info": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.get_version_from_pkg_info",
    "versioningit.invalidtagerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.InvalidTagError",
    "versioningit.invalidversionerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.InvalidVersionError",
    "versioningit.methoderror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.MethodError",
    "versioningit.noconfigfileerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NoConfigFileError",
    "versioningit.noconfigfileerror.project_dir": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NoConfigFileError.project_dir",
    "versioningit.noconfigsectionerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NoConfigSectionError",
    "versioningit.noconfigsectionerror.config_path": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NoConfigSectionError.config_path",
    "versioningit.notagerror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NoTagError",
    "versioningit.notsdisterror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NotSdistError",
    "versioningit.notvcserror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NotVCSError",
    "versioningit.notversioningiterror": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.NotVersioningitError",
    "versioningit.onbuildfile": "https://versioningit.readthedocs.io/en/stable/writing-methods.html#versioningit.OnbuildFile",
    "versioningit.onbuildfile.open": "https://versioningit.readthedocs.io/en/stable/writing-methods.html#versioningit.OnbuildFile.open",
    "versioningit.onbuildfileprovider": "https://versioningit.readthedocs.io/en/stable/writing-methods.html#versioningit.OnbuildFileProvider",
    "versioningit.onbuildfileprovider.get_file": "https://versioningit.readthedocs.io/en/stable/writing-methods.html#versioningit.OnbuildFileProvider.get_file",
    "versioningit.report": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report",
    "versioningit.report.base_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.base_version",
    "versioningit.report.description": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.description",
    "versioningit.report.next_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.next_version",
    "versioningit.report.template_fields": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.template_fields",
    "versioningit.report.using_default_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.using_default_version",
    "versioningit.report.version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Report.version",
    "versioningit.run_onbuild": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.run_onbuild",
    "versioningit.vcsdescription": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.VCSDescription",
    "versioningit.vcsdescription.branch": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.VCSDescription.branch",
    "versioningit.vcsdescription.fields": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.VCSDescription.fields",
    "versioningit.vcsdescription.state": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.VCSDescription.state",
    "versioningit.vcsdescription.tag": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.VCSDescription.tag",
    "versioningit.versioningit": "https://versioningit.readthedocs.io/en/stable/api.html",
    "versioningit.Versioningit": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit",
    "versioningit.versioningit.cmdclass": "https://versioningit.readthedocs.io/en/stable/api.html",
    "versioningit.versioningit.cmdclass.build_py": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.versioningit.cmdclass.build_py",
    "versioningit.versioningit.cmdclass.sdist": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.versioningit.cmdclass.sdist",
    "versioningit.versioningit.do_format": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_format",
    "versioningit.versioningit.do_next_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_next_version",
    "versioningit.versioningit.do_onbuild": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_onbuild",
    "versioningit.versioningit.do_tag2version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_tag2version",
    "versioningit.versioningit.do_template_fields": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_template_fields",
    "versioningit.versioningit.do_vcs": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_vcs",
    "versioningit.versioningit.do_write": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_write",
    "versioningit.versioningit.from_project_dir": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.from_project_dir",
    "versioningit.versioningit.get_version": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.get_version",
    "versioningit.versioningit.run": "https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.run",
}
