VERSION = "5.1.0"

# fmt: off
MAPPING = {
    "vine": "https://vine.readthedocs.io/en/latest/",
    "vine.abstract": "https://vine.readthedocs.io/en/latest/reference/vine.abstract.html",
    "vine.abstract.thenable": "https://vine.readthedocs.io/en/latest/reference/vine.abstract.html#vine.abstract.Thenable",
    "vine.abstract.thenable.cancel": "https://vine.readthedocs.io/en/latest/reference/vine.abstract.html#vine.abstract.Thenable.cancel",
    "vine.abstract.thenable.then": "https://vine.readthedocs.io/en/latest/reference/vine.abstract.html#vine.abstract.Thenable.then",
    "vine.abstract.thenable.throw": "https://vine.readthedocs.io/en/latest/reference/vine.abstract.html#vine.abstract.Thenable.throw",
    "vine.five": "https://vine.readthedocs.io/en/latest/reference/vine.five.html",
    "vine.five.items": "https://vine.readthedocs.io/en/latest/reference/vine.five.html#vine.five.items",
    "vine.five.with_metaclass": "https://vine.readthedocs.io/en/latest/reference/vine.five.html#vine.five.with_metaclass",
    "vine.funtools": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html",
    "vine.funtools.ensure_promise": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.ensure_promise",
    "vine.funtools.maybe_promise": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.maybe_promise",
    "vine.funtools.ppartial": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.ppartial",
    "vine.funtools.preplace": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.preplace",
    "vine.funtools.ready_promise": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.ready_promise",
    "vine.funtools.starpromise": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.starpromise",
    "vine.funtools.transform": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.transform",
    "vine.funtools.wrap": "https://vine.readthedocs.io/en/latest/reference/vine.funtools.html#vine.funtools.wrap",
    "vine.promises": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html",
    "vine.promises.promise": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise",
    "vine.promises.promise.args": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.args",
    "vine.promises.promise.cancel": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.cancel",
    "vine.promises.promise.cancelled": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.cancelled",
    "vine.promises.promise.failed": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.failed",
    "vine.promises.promise.fun": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.fun",
    "vine.promises.promise.kwargs": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.kwargs",
    "vine.promises.promise.listeners": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.listeners",
    "vine.promises.promise.on_error": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.on_error",
    "vine.promises.promise.ready": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.ready",
    "vine.promises.promise.reason": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.reason",
    "vine.promises.promise.set_error_state": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.set_error_state",
    "vine.promises.promise.then": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.then",
    "vine.promises.promise.throw": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.throw",
    "vine.promises.promise.throw1": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.throw1",
    "vine.promises.promise.value": "https://vine.readthedocs.io/en/latest/reference/vine.promises.html#vine.promises.promise.value",
    "vine.synchronization": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html",
    "vine.synchronization.barrier": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier",
    "vine.synchronization.barrier.add": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.add",
    "vine.synchronization.barrier.add_noincr": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.add_noincr",
    "vine.synchronization.barrier.cancel": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.cancel",
    "vine.synchronization.barrier.finalize": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.finalize",
    "vine.synchronization.barrier.then": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.then",
    "vine.synchronization.barrier.throw": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.throw",
    "vine.synchronization.barrier.throw1": "https://vine.readthedocs.io/en/latest/reference/vine.synchronization.html#vine.synchronization.barrier.throw1",
}
