VERSION = "2.3.1"

# fmt: off
MAPPING = {
    "w3lib": "https://w3lib.readthedocs.io/en/latest/",
    "w3lib.encoding": "https://w3lib.readthedocs.io/en/latest/w3lib.html#module-w3lib.encoding",
    "w3lib.encoding.html_body_declared_encoding": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.html_body_declared_encoding",
    "w3lib.encoding.html_to_unicode": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.html_to_unicode",
    "w3lib.encoding.http_content_type_encoding": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.http_content_type_encoding",
    "w3lib.encoding.read_bom": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.read_bom",
    "w3lib.encoding.resolve_encoding": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.resolve_encoding",
    "w3lib.encoding.to_unicode": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.encoding.to_unicode",
    "w3lib.html": "https://w3lib.readthedocs.io/en/latest/w3lib.html#module-w3lib.html",
    "w3lib.html.get_base_url": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.get_base_url",
    "w3lib.html.get_meta_refresh": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.get_meta_refresh",
    "w3lib.html.remove_comments": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.remove_comments",
    "w3lib.html.remove_tags": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.remove_tags",
    "w3lib.html.remove_tags_with_content": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.remove_tags_with_content",
    "w3lib.html.replace_entities": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.replace_entities",
    "w3lib.html.replace_escape_chars": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.replace_escape_chars",
    "w3lib.html.replace_tags": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.replace_tags",
    "w3lib.html.strip_html5_whitespace": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.strip_html5_whitespace",
    "w3lib.html.unquote_markup": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.html.unquote_markup",
    "w3lib.http": "https://w3lib.readthedocs.io/en/latest/w3lib.html#module-w3lib.http",
    "w3lib.http.basic_auth_header": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.http.basic_auth_header",
    "w3lib.http.headers_dict_to_raw": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.http.headers_dict_to_raw",
    "w3lib.http.headers_raw_to_dict": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.http.headers_raw_to_dict",
    "w3lib.url": "https://w3lib.readthedocs.io/en/latest/w3lib.html#module-w3lib.url",
    "w3lib.url.add_or_replace_parameter": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.add_or_replace_parameter",
    "w3lib.url.add_or_replace_parameters": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.add_or_replace_parameters",
    "w3lib.url.any_to_uri": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.any_to_uri",
    "w3lib.url.canonicalize_url": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.canonicalize_url",
    "w3lib.url.file_uri_to_path": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.file_uri_to_path",
    "w3lib.url.parse_data_uri": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.parse_data_uri",
    "w3lib.url.parsedatauriresult": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.ParseDataURIResult",
    "w3lib.url.parsedatauriresult.data": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.ParseDataURIResult.data",
    "w3lib.url.parsedatauriresult.media_type": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.ParseDataURIResult.media_type",
    "w3lib.url.parsedatauriresult.media_type_parameters": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.ParseDataURIResult.media_type_parameters",
    "w3lib.url.path_to_file_uri": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.path_to_file_uri",
    "w3lib.url.safe_download_url": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.safe_download_url",
    "w3lib.url.safe_url_string": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.safe_url_string",
    "w3lib.url.url_query_cleaner": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.url_query_cleaner",
    "w3lib.url.url_query_parameter": "https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.url_query_parameter",
}
