VERSION = "24.11.1"

# fmt: off
MAPPING = {
    "webcolors": "https://webcolors.readthedocs.io/en/latest/",
    "webcolors.css2": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.CSS2",
    "webcolors.css21": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.CSS21",
    "webcolors.css3": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.CSS3",
    "webcolors.hex_to_name": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.hex_to_name",
    "webcolors.hex_to_rgb": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.hex_to_rgb",
    "webcolors.hex_to_rgb_percent": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.hex_to_rgb_percent",
    "webcolors.html4": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.HTML4",
    "webcolors.html5_parse_legacy_color": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.html5_parse_legacy_color",
    "webcolors.html5_parse_simple_color": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.html5_parse_simple_color",
    "webcolors.html5_serialize_simple_color": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.html5_serialize_simple_color",
    "webcolors.html5simplecolor": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.HTML5SimpleColor",
    "webcolors.html5simplecolor.blue": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.HTML5SimpleColor.blue",
    "webcolors.html5simplecolor.green": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.HTML5SimpleColor.green",
    "webcolors.html5simplecolor.red": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.HTML5SimpleColor.red",
    "webcolors.integerrgb": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.IntegerRGB",
    "webcolors.integerrgb.blue": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.IntegerRGB.blue",
    "webcolors.integerrgb.green": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.IntegerRGB.green",
    "webcolors.integerrgb.red": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.IntegerRGB.red",
    "webcolors.inttuple": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.IntTuple",
    "webcolors.name_to_hex": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.name_to_hex",
    "webcolors.name_to_rgb": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.name_to_rgb",
    "webcolors.name_to_rgb_percent": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.name_to_rgb_percent",
    "webcolors.names": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.names",
    "webcolors.normalize_hex": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.normalize_hex",
    "webcolors.normalize_integer_triplet": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.normalize_integer_triplet",
    "webcolors.normalize_percent_triplet": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.normalize_percent_triplet",
    "webcolors.percentrgb": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.PercentRGB",
    "webcolors.percentrgb.blue": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.PercentRGB.blue",
    "webcolors.percentrgb.green": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.PercentRGB.green",
    "webcolors.percentrgb.red": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.PercentRGB.red",
    "webcolors.percenttuple": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.PercentTuple",
    "webcolors.rgb_percent_to_hex": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_percent_to_hex",
    "webcolors.rgb_percent_to_name": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_percent_to_name",
    "webcolors.rgb_percent_to_rgb": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_percent_to_rgb",
    "webcolors.rgb_to_hex": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_to_hex",
    "webcolors.rgb_to_name": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_to_name",
    "webcolors.rgb_to_rgb_percent": "https://webcolors.readthedocs.io/en/latest/contents.html#webcolors.rgb_to_rgb_percent",
}
