VERSION = "3.0.0"

# fmt: off
MAPPING = {
    "zict": "https://zict.readthedocs.io/en/latest/",
    "zict.asyncbuffer": "https://zict.readthedocs.io/en/latest/index.html#zict.AsyncBuffer",
    "zict.asyncbuffer.async_evict_until_below_target": "https://zict.readthedocs.io/en/latest/index.html#zict.AsyncBuffer.async_evict_until_below_target",
    "zict.asyncbuffer.async_get": "https://zict.readthedocs.io/en/latest/index.html#zict.AsyncBuffer.async_get",
    "zict.asyncbuffer.close": "https://zict.readthedocs.io/en/latest/index.html#zict.AsyncBuffer.close",
    "zict.buffer": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer",
    "zict.buffer.close": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.close",
    "zict.buffer.evict_until_below_target": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.evict_until_below_target",
    "zict.buffer.items": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.items",
    "zict.buffer.n": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.n",
    "zict.buffer.offset": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.offset",
    "zict.buffer.set_noevict": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.set_noevict",
    "zict.buffer.values": "https://zict.readthedocs.io/en/latest/index.html#zict.Buffer.values",
    "zict.cache": "https://zict.readthedocs.io/en/latest/index.html#zict.Cache",
    "zict.cache.close": "https://zict.readthedocs.io/en/latest/index.html#zict.Cache.close",
    "zict.file": "https://zict.readthedocs.io/en/latest/index.html#zict.File",
    "zict.func": "https://zict.readthedocs.io/en/latest/index.html#zict.Func",
    "zict.func.close": "https://zict.readthedocs.io/en/latest/index.html#zict.Func.close",
    "zict.insertionsortedset": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet",
    "zict.insertionsortedset.add": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.add",
    "zict.insertionsortedset.clear": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.clear",
    "zict.insertionsortedset.discard": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.discard",
    "zict.insertionsortedset.pop": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.pop",
    "zict.insertionsortedset.popleft": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.popleft",
    "zict.insertionsortedset.popright": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.popright",
    "zict.insertionsortedset.remove": "https://zict.readthedocs.io/en/latest/index.html#zict.InsertionSortedSet.remove",
    "zict.keymap": "https://zict.readthedocs.io/en/latest/index.html#zict.KeyMap",
    "zict.keymap.close": "https://zict.readthedocs.io/en/latest/index.html#zict.KeyMap.close",
    "zict.lmdb": "https://zict.readthedocs.io/en/latest/index.html#zict.LMDB",
    "zict.lmdb.close": "https://zict.readthedocs.io/en/latest/index.html#zict.LMDB.close",
    "zict.lmdb.items": "https://zict.readthedocs.io/en/latest/index.html#zict.LMDB.items",
    "zict.lmdb.values": "https://zict.readthedocs.io/en/latest/index.html#zict.LMDB.values",
    "zict.lru": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU",
    "zict.lru.close": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.close",
    "zict.lru.evict": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.evict",
    "zict.lru.evict_until_below_target": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.evict_until_below_target",
    "zict.lru.get_all_or_nothing": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.get_all_or_nothing",
    "zict.lru.items": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.items",
    "zict.lru.keys": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.keys",
    "zict.lru.n": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.n",
    "zict.lru.offset": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.offset",
    "zict.lru.set_noevict": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.set_noevict",
    "zict.lru.values": "https://zict.readthedocs.io/en/latest/index.html#zict.LRU.values",
    "zict.sieve": "https://zict.readthedocs.io/en/latest/index.html#zict.Sieve",
    "zict.sieve.close": "https://zict.readthedocs.io/en/latest/index.html#zict.Sieve.close",
    "zict.weakvaluemapping": "https://zict.readthedocs.io/en/latest/index.html#zict.WeakValueMapping",
    "zict.zip": "https://zict.readthedocs.io/en/latest/index.html#zict.Zip",
}
