"""FlaskIt Project Templates"""
from .project_templates import *

__all__ = [
    'TEMPLATE_APP',
    'TEMPLATE_CONFIG',
    'TEMPLATE_DATABASE_INIT',
    'TEMPLATE_MODEL_EXAMPLE',
    'TEMPLATE_SERVICE_EXAMPLE',
    'TEMPLATE_LOGIC_EXAMPLE',
    'TEMPLATE_ROUTES',
    'TEMPLATE_HOME_ROUTES',
    'TEMPLATE_LAYOUT',
    'TEMPLATE_NAVBAR',
    'TEMPLATE_FOOTER',
    'TEMPLATE_HOME_PAGE',
    'TEMPLATE_ABOUT_PAGE',
    'TEMPLATE_404_PAGE',
    'TEMPLATE_500_PAGE',
    'TEMPLATE_403_PAGE',
    'TEMPLATE_CSS',
    'TEMPLATE_JS',
    'TEMPLATE_REQUIREMENTS',
    'TEMPLATE_ENV',
    'TEMPLATE_DATA_JSON',
    'TEMPLATE_GITIGNORE',
    'TEMPLATE_README',
]
