# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['hrflow_connectors',
 'hrflow_connectors.connectors.bullhorn.utils',
 'hrflow_connectors.connectors.hrflow',
 'hrflow_connectors.core',
 'hrflow_connectors.core.backend',
 'hrflow_connectors.v1',
 'hrflow_connectors.v1.connectors.adzuna',
 'hrflow_connectors.v1.connectors.breezyhr',
 'hrflow_connectors.v1.connectors.breezyhr.utils',
 'hrflow_connectors.v1.connectors.bullhorn',
 'hrflow_connectors.v1.connectors.bullhorn.utils',
 'hrflow_connectors.v1.connectors.carrevolutis',
 'hrflow_connectors.v1.connectors.ceridian',
 'hrflow_connectors.v1.connectors.digitalrecruiters',
 'hrflow_connectors.v1.connectors.greenhouse',
 'hrflow_connectors.v1.connectors.hrflow',
 'hrflow_connectors.v1.connectors.hrflow.warehouse',
 'hrflow_connectors.v1.connectors.hubspot',
 'hrflow_connectors.v1.connectors.jobology',
 'hrflow_connectors.v1.connectors.lever',
 'hrflow_connectors.v1.connectors.meteojob',
 'hrflow_connectors.v1.connectors.poleemploi',
 'hrflow_connectors.v1.connectors.recruitee',
 'hrflow_connectors.v1.connectors.salesforce',
 'hrflow_connectors.v1.connectors.sapsuccessfactors',
 'hrflow_connectors.v1.connectors.sapsuccessfactors.utils',
 'hrflow_connectors.v1.connectors.smartrecruiters',
 'hrflow_connectors.v1.connectors.taleez',
 'hrflow_connectors.v1.connectors.talentsoft',
 'hrflow_connectors.v1.connectors.talentsoft.utils',
 'hrflow_connectors.v1.connectors.teamtailor',
 'hrflow_connectors.v1.connectors.waalaxy',
 'hrflow_connectors.v1.connectors.workable',
 'hrflow_connectors.v1.core',
 'hrflow_connectors.v1.core.templates',
 'hrflow_connectors.v1.utils',
 'hrflow_connectors.v2',
 'hrflow_connectors.v2.connectors.admen',
 'hrflow_connectors.v2.connectors.admen.utils',
 'hrflow_connectors.v2.connectors.adzuna',
 'hrflow_connectors.v2.connectors.breezyhr',
 'hrflow_connectors.v2.connectors.bullhorn',
 'hrflow_connectors.v2.connectors.bullhorn.utils',
 'hrflow_connectors.v2.connectors.ceipal',
 'hrflow_connectors.v2.connectors.flatchr',
 'hrflow_connectors.v2.connectors.francetravail',
 'hrflow_connectors.v2.connectors.greenhouse',
 'hrflow_connectors.v2.connectors.hubspot',
 'hrflow_connectors.v2.connectors.jazzhr',
 'hrflow_connectors.v2.connectors.recruitee',
 'hrflow_connectors.v2.connectors.smartrecruiters',
 'hrflow_connectors.v2.connectors.taleez',
 'hrflow_connectors.v2.connectors.teamtailor',
 'hrflow_connectors.v2.connectors.waalaxy',
 'hrflow_connectors.v2.connectors.workable',
 'hrflow_connectors.v2.connectors.zohorecruit',
 'hrflow_connectors.v2.core',
 'hrflow_connectors.v2.core.hrflow',
 'hrflow_connectors.v2.core.hrflow.aisles',
 'hrflow_connectors.v2.core.templates']

package_data = \
{'': ['*'],
 'hrflow_connectors.v1': ['connectors/abacusumantis/*',
                          'connectors/adpworkforcenow/*',
                          'connectors/afas/*',
                          'connectors/agefiph/*',
                          'connectors/apec/*',
                          'connectors/applicantstack/*',
                          'connectors/ashby/*',
                          'connectors/avature/*',
                          'connectors/bamboohr/*',
                          'connectors/beetween/*',
                          'connectors/bite/*',
                          'connectors/broadbean/*',
                          'connectors/cadreemploi/*',
                          'connectors/carerix/*',
                          'connectors/cats/*',
                          'connectors/ceipal/*',
                          'connectors/clayhr/*',
                          'connectors/clockwork/*',
                          'connectors/comeet/*',
                          'connectors/concludis/*',
                          'connectors/connexys/*',
                          'connectors/cornerjob/*',
                          'connectors/cornerstoneondemand/*',
                          'connectors/cornerstonetalentlink/*',
                          'connectors/crosstalent/*',
                          'connectors/distrijob/*',
                          'connectors/dvinci/*',
                          'connectors/engageats/*',
                          'connectors/engagementjeunes/*',
                          'connectors/eolia/*',
                          'connectors/eploy/*',
                          'connectors/erecruiter/*',
                          'connectors/factorial/*',
                          'connectors/fashionjobs/*',
                          'connectors/fieldglasssap/*',
                          'connectors/figaroclassifieds/*',
                          'connectors/flatchr/*',
                          'connectors/fountain/*',
                          'connectors/freework/*',
                          'connectors/freshteam/*',
                          'connectors/glassdoor/*',
                          'connectors/goldenbees/*',
                          'connectors/guidecom/*',
                          'connectors/handicapjob/*',
                          'connectors/harbourats/*',
                          'connectors/hellowork/*',
                          'connectors/heyrecruit/*',
                          'connectors/homerun/*',
                          'connectors/hrcloud/*',
                          'connectors/hroffice/*',
                          'connectors/hrworks/*',
                          'connectors/icims/*',
                          'connectors/indeed/*',
                          'connectors/infinitebrassring/*',
                          'connectors/inrecruiting/*',
                          'connectors/inzojob/*',
                          'connectors/jazzhr/*',
                          'connectors/jobadder/*',
                          'connectors/jobaffinity/*',
                          'connectors/jobdiva/*',
                          'connectors/jobijoba/*',
                          'connectors/jobrapido/*',
                          'connectors/jobscore/*',
                          'connectors/jobsoid/*',
                          'connectors/jobteaser/*',
                          'connectors/jobtransport/*',
                          'connectors/jobvitae/*',
                          'connectors/jobvite/*',
                          'connectors/jobylon/*',
                          'connectors/join/*',
                          'connectors/jooble/*',
                          'connectors/keljob/*',
                          'connectors/lano/*',
                          'connectors/laponi/*',
                          'connectors/leboncoin/*',
                          'connectors/lesjeudis/*',
                          'connectors/linkedin/*',
                          'connectors/lucca/*',
                          'connectors/mailchimp/*',
                          'connectors/meta4/*',
                          'connectors/microsoftdynamics/*',
                          'connectors/monster/*',
                          'connectors/mysolution/*',
                          'connectors/neuvoo/*',
                          'connectors/occupop/*',
                          'connectors/onlyfy/*',
                          'connectors/optioncarriere/*',
                          'connectors/oracle/*',
                          'connectors/oraclefusion/*',
                          'connectors/oraclerecruiting/*',
                          'connectors/oracletaleo/*',
                          'connectors/otys/*',
                          'connectors/personio/*',
                          'connectors/personiorecruiting/*',
                          'connectors/piloga/*',
                          'connectors/pinpoint/*',
                          'connectors/polymer/*',
                          'connectors/radancy/*',
                          'connectors/reachmee/*',
                          'connectors/recruhr/*',
                          'connectors/recruiterflow/*',
                          'connectors/recruitive/*',
                          'connectors/rexx/*',
                          'connectors/sagehr/*',
                          'connectors/softgarden/*',
                          'connectors/staffme/*',
                          'connectors/staffsante/*',
                          'connectors/talentadore/*',
                          'connectors/talentclue/*',
                          'connectors/talentlink/*',
                          'connectors/talentlyft/*',
                          'connectors/talentreef/*',
                          'connectors/tekkit/*',
                          'connectors/tellent/*',
                          'connectors/traffit/*',
                          'connectors/trakstar/*',
                          'connectors/tribepad/*',
                          'connectors/twilio/*',
                          'connectors/ubeeo/*',
                          'connectors/ukgreadyrecruiting/*',
                          'connectors/umantis/*',
                          'connectors/welcometothejungle/*',
                          'connectors/welcometothejungleats/*',
                          'connectors/wizbii/*',
                          'connectors/workday/*',
                          'connectors/zohorecruit/*',
                          'data/*'],
 'hrflow_connectors.v1.connectors.adzuna': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v1.connectors.breezyhr': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v1.connectors.bullhorn': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v1.connectors.carrevolutis': ['docs/*',
                                                  'mappings/format/*',
                                                  'notebooks/*'],
 'hrflow_connectors.v1.connectors.ceridian': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v1.connectors.digitalrecruiters': ['docs/*',
                                                       'mappings/format/*',
                                                       'notebooks/*'],
 'hrflow_connectors.v1.connectors.greenhouse': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v1.connectors.hubspot': ['docs/*',
                                             'mappings/format/*',
                                             'notebooks/*'],
 'hrflow_connectors.v1.connectors.jobology': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v1.connectors.lever': ['docs/*',
                                           'mappings/format/*',
                                           'notebooks/*'],
 'hrflow_connectors.v1.connectors.meteojob': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v1.connectors.poleemploi': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v1.connectors.recruitee': ['docs/*',
                                               'mappings/format/*',
                                               'notebooks/*'],
 'hrflow_connectors.v1.connectors.salesforce': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v1.connectors.sapsuccessfactors': ['docs/*',
                                                       'mappings/format/*',
                                                       'notebooks/*'],
 'hrflow_connectors.v1.connectors.smartrecruiters': ['docs/*',
                                                     'mappings/format/*',
                                                     'notebooks/*'],
 'hrflow_connectors.v1.connectors.taleez': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v1.connectors.talentsoft': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v1.connectors.teamtailor': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v1.connectors.waalaxy': ['docs/*',
                                             'mappings/format/*',
                                             'notebooks/*'],
 'hrflow_connectors.v1.connectors.workable': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v2.connectors.admen': ['docs/*',
                                           'mappings/format/*',
                                           'notebooks/*'],
 'hrflow_connectors.v2.connectors.adzuna': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v2.connectors.breezyhr': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v2.connectors.bullhorn': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v2.connectors.ceipal': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v2.connectors.flatchr': ['docs/*',
                                             'mappings/format/*',
                                             'notebooks/*'],
 'hrflow_connectors.v2.connectors.francetravail': ['docs/*',
                                                   'mappings/format/*',
                                                   'notebooks/*'],
 'hrflow_connectors.v2.connectors.greenhouse': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v2.connectors.hubspot': ['docs/*',
                                             'mappings/format/*',
                                             'notebooks/*'],
 'hrflow_connectors.v2.connectors.jazzhr': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v2.connectors.recruitee': ['docs/*',
                                               'mappings/format/*',
                                               'notebooks/*'],
 'hrflow_connectors.v2.connectors.smartrecruiters': ['docs/*',
                                                     'mappings/format/*',
                                                     'notebooks/*'],
 'hrflow_connectors.v2.connectors.taleez': ['docs/*',
                                            'mappings/format/*',
                                            'notebooks/*'],
 'hrflow_connectors.v2.connectors.teamtailor': ['docs/*',
                                                'mappings/format/*',
                                                'notebooks/*'],
 'hrflow_connectors.v2.connectors.waalaxy': ['docs/*',
                                             'mappings/format/*',
                                             'notebooks/*'],
 'hrflow_connectors.v2.connectors.workable': ['docs/*',
                                              'mappings/format/*',
                                              'notebooks/*'],
 'hrflow_connectors.v2.connectors.zohorecruit': ['docs/*',
                                                 'mappings/format/*',
                                                 'notebooks/*']}

install_requires = \
['Jinja2>=3.0.3,<4.0.0',
 'beautifulsoup4==4.10.0',
 'hrflow>=4.2.0,<5.0.0',
 'msgspec>=0.18.6,<0.19.0',
 'mysql-connector-python>=9.1.0,<10.0.0',
 'puremagic>=1.27,<2.0',
 'pydantic==1.10.8',
 'requests>=2.27.1,<3.0.0',
 'simple-salesforce>=1.12.4,<2.0.0',
 'smbprotocol>=1.15.0,<2.0.0',
 'typing-extensions>=4.7.1,<5.0.0']

extras_require = \
{'s3': ['boto3>=1.24.66,<2.0.0']}

setup_kwargs = {
    'name': 'hrflow-connectors',
    'version': '4.27.4',
    'description': 'hrflow-connectors is an open source project created by HrFlow.ai to allow developers to connect easily HR ecosystem component.',
    'long_description': '<p align="center">\n  <a href="https://hrflow.ai">\n    <img alt="hrflow" src="https://img.riminder.net/logo-hrflow.svg" width="240" />\n  </a>\n</p>\n<h1 align="center">\n  HrFlow.ai connectors\n</h1>\n\n![GitHub Repo stars](https://img.shields.io/github/stars/Riminder/hrflow-connectors?style=social) ![](https://img.shields.io/github/v/release/Riminder/hrflow-connectors) ![](https://img.shields.io/github/license/Riminder/hrflow-connectors)\n\n# 💼 About HrFlow.ai\n\n**[HrFlow.ai](https://hrflow.ai/) is on a mission to make AI and data integration pipelines a commodity in the HR Industry:**\n\n  1. **Unify**: Link your Talent Data channels with a few clicks, so they can share data.\n  2. **Understand**: Leverage our AI solutions to process your Talent Data.\n  3. **Automate**: Sync data between your tools and build workflows that meet your business logic.\n\n<p align="center">\n  <a href="https://hrflow.ai">\n    <img alt="hrflow" src="https://hrflow-ai.imgix.net/corporate.svg"/>\n  </a>\n</p>\n\n<br/>\n\n# 💻 About **HrFlow-Connectors**\n\n**HrFlow-Connectors** is an open-source project created by HrFlow.ai to democratize Talent Data integration within the HR Tech landscape.\n\nWe invite developers to join us in our mission to bring AI and data integration to the HR industr, as a developper you can:\n\n- Create new connectors quickly and easily with our low-code connector approach and abstracted concepts\n- Contribute to the Connectors\' framework with your own code\n- Leverage our AI solutions to process your Talent Data\n- Sync data between your tools and build workflows that meet your business logic\n- Link your Talent Data channels with a few clicks, so they can share data\n\n<p align="center">\n<image src=https://user-images.githubusercontent.com/57711045/215884679-33f754e2-2a21-4aad-97c8-181f6d75235e.png width=90% height=100% >\n</p>\n\n📃 **More instructions are available in the Documentation section below**\n\n# :book: Open Source Connectors\n\n## 🤝 List of ATS, CRM and HCM\n\n| Name                                                                                                                                      | Type                 | Status             | Release date   | Last update     |\n|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------|--------------------|----------------|-----------------|\n| [**AD-MEN**](./src/hrflow_connectors/v2/connectors/admen/README.md) | CRM | :book: Open source | ** | ** |\n| [**Breezy HR**](./src/hrflow_connectors/v2/connectors/breezyhr/README.md) | ATS | :book: Open source | *19/01/2022* | *31/10/2024* |\n| [**Bullhorn**](./src/hrflow_connectors/v2/connectors/bullhorn/README.md) | ATS | :book: Open source | *26/01/2022* | *23/10/2024* |\n| [**Ceipal**](./src/hrflow_connectors/v2/connectors/ceipal/README.md) | ATS | :book: Open source | ** | ** |\n| [**Ceridian**](./src/hrflow_connectors/v1/connectors/ceridian/README.md) | HCM | :book: Open source | *19/01/2022* | *05/09/2024* |\n| [**Digitalrecruiters**](./src/hrflow_connectors/v1/connectors/digitalrecruiters/README.md) | ATS | :book: Open source | *17/08/2023* | *24/10/2024* |\n| [**Flatchr**](./src/hrflow_connectors/v2/connectors/flatchr/README.md) | ATS | :book: Open source | *21/04/2022* | ** |\n| [**Greenhouse**](./src/hrflow_connectors/v2/connectors/greenhouse/README.md) | ATS | :book: Open source | *19/01/2022* | *05/09/2024* |\n| [**Hubspot**](./src/hrflow_connectors/v2/connectors/hubspot/README.md) | CRM | :book: Open source | *27/10/2022* | *05/09/2024* |\n| [**JazzHR**](./src/hrflow_connectors/v2/connectors/jazzhr/README.md) | ATS | :book: Open source | ** | ** |\n| [**Lever**](./src/hrflow_connectors/v1/connectors/lever/README.md) | ATS | :book: Open source | *18/08/2023* | *23/10/2024* |\n| [**Recruitee**](./src/hrflow_connectors/v2/connectors/recruitee/README.md) | ATS | :book: Open source | *30/10/2022* | *23/10/2024* |\n| [**Salesforce**](./src/hrflow_connectors/v1/connectors/salesforce/README.md) | CRM | :book: Open source | *03/08/2023* | *05/09/2024* |\n| [**SAP SuccessFactors**](./src/hrflow_connectors/v1/connectors/sapsuccessfactors/README.md) | ATS | :book: Open source | *19/01/2022* | *23/10/2024* |\n| [**SmartRecruiters**](./src/hrflow_connectors/v2/connectors/smartrecruiters/README.md) | ATS | :book: Open source | *21/03/2022* | *05/09/2024* |\n| [**Taleez**](./src/hrflow_connectors/v2/connectors/taleez/README.md) | ATS | :book: Open source | *19/01/2022* | *23/10/2024* |\n| [**TalentSoft**](./src/hrflow_connectors/v1/connectors/talentsoft/README.md) | HCM | :book: Open source | *19/04/2022* | ** |\n| [**Teamtailor**](./src/hrflow_connectors/v2/connectors/teamtailor/README.md) | ATS | :book: Open source | *06/10/2022* | *05/09/2024* |\n| [**Waalaxy**](./src/hrflow_connectors/v2/connectors/waalaxy/README.md) | Automation | :book: Open source | *18/11/2022* | *05/09/2024* |\n| [**Workable**](./src/hrflow_connectors/v2/connectors/workable/README.md) | HCM | :book: Open source | *27/09/2022* | *05/09/2024* |\n| [**Zoho Recruit**](./src/hrflow_connectors/v2/connectors/zohorecruit/README.md) | ATS | :book: Open source | ** | ** |\n\n## 🤝 List of Job Boards\n\n| Name                                                                                                                                      | Type                 | Status             | Release date   | Last update     |\n|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------|--------------------|----------------|-----------------|\n| [**Adzuna**](./src/hrflow_connectors/v2/connectors/adzuna/README.md) | Job Board | :book: Open source | *08/09/2022* | *05/09/2024* |\n| [**Carrevolutis**](./src/hrflow_connectors/v1/connectors/carrevolutis/README.md) | Job Board | :book: Open source | *20/03/2024* | *05/09/2024* |\n| [**France Travail (ex: Pole Emploi)**](./src/hrflow_connectors/v2/connectors/francetravail/README.md) | Job Board | :book: Open source | *15/07/2022* | *24/10/2024* |\n| [**Jobology**](./src/hrflow_connectors/v1/connectors/jobology/README.md) | Job Board | :book: Open source | *21/12/2022* | *05/09/2024* |\n| [**Meteojob**](./src/hrflow_connectors/v1/connectors/meteojob/README.md) | Job Board | :book: Open source | *15/02/2024* | *05/09/2024* |\n\n# :lock: Premium Connectors\n\n## 🤝 List of ATS, CRM and HCM\n\n| Name                                                                                                                                      | Type                 | Status             | Release date   | Last update     |\n|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------|--------------------|----------------|-----------------|\n| [**Abacus Umantis**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**ADP Workforce Now**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**AFAS Software**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Applicantstack**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Ashby**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Avature**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**BambooHR**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Beetween**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**BITE**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Broadbean**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Carerix**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**CATS**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Cegid (Meta4)**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**ClayHR**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**ClockWork**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Comeet**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**concludis**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Connexys By Bullhorn**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Cornerstone OnDemand**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Cornerstone TalentLink**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Crosstalent**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**d.vinci**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**EngageATS**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**EOLIA Software**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Eploy**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**eRecruiter**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Factorial**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Fieldglass SAP**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Fountain**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Freshteam**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**GuideCom**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Harbour ATS**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Haufe Umantis**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Heyrecruit**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Homerun**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**HR Cloud**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**HR Office**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**HRworks**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**iCIMS**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Infinite BrassRing**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**InRecruiting**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**JobAdder**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Jobaffinity**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**JobDiva**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**JobScore**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Jobsoid**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Jobvite**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Jobylon**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**JOIN**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Lano**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Lucca**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**Mailchimp**](https://forms.gle/pokoE9pAjSVSFtCe7) | Automation | :lock: Premium |  |  |\n| [**Microsoft Dynamics**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**Mysolution**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Occupop**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Onlyfy**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Oracle**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**Oracle Fusion - Recruiting Cloud**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Oracle Recruiting Cloud**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Oracle Taleo**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**OTYS**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**P&I Loga**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Personio**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**Personio Recruiting**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Pinpoint**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Polymer**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Radancy**](https://forms.gle/pokoE9pAjSVSFtCe7) | HCM | :lock: Premium |  |  |\n| [**ReachMee**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**RECRU**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Recruiterflow**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Recruitive**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**rexx systems**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Sage HR**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Softgarden**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Talent Clue**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**TalentAdore**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Talentlink**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**TalentLyft**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**TalentReef**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Tellent**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**TRAFFIT**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Trakstar**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Tribepad**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Twilio**](https://forms.gle/pokoE9pAjSVSFtCe7) | Automation | :lock: Premium |  |  |\n| [**Ubeeo**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**UKG Ready Recruiting**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n| [**Workday**](https://forms.gle/pokoE9pAjSVSFtCe7) | ATS | :lock: Premium |  |  |\n\n## 🤝 List of Job Boards\n\n| Name                                                                                                                                      | Type                 | Status             | Release date   | Last update     |\n|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------|--------------------|----------------|-----------------|\n| [**Agefiph**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**APEC**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Cadreemploi**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Cornerjob**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Distrijob**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Engagement Jeunes**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**FashionJobs**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Figaro Classifieds**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**freework**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Glassdoor**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**GoldenBees**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Handicap-Job**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**HelloWork**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Indeed**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Inzojob**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Jobijoba**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Jobrapido**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**JobTeaser**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Jobtransport**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Jobvitae**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Jooble**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Keljob**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Laponi**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Leboncoin**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**LesJeudis**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**LinkedIn**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Monster**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Neuvoo**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Optioncarriere**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Staffme**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Staffsante**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Tekkit**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Welcome To The Jungle**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n| [**Wizbii**](https://forms.gle/pokoE9pAjSVSFtCe7) | Job Board | :lock: Premium |  |  |\n\n# 🪄 Quickstart\n\n## What I can do?\n\nWith HrFlow-Connectors, you can **synchronize** and **process** multiple **HR data streams** in just a few lines of code.\n\nYou can do any kind of data transfer between HrFlow.ai and external destinations :\n\n- Pull jobs : `External Job flow` :arrow_right: ***`HrFlow.ai Board`***\n- Pull profiles : `External Profile flow` :arrow_right: ***`HrFlow.ai Source`***\n- Push job : ***`HrFlow.ai Board`*** :arrow_right: `External destination`\n- Push profile : ***`HrFlow.ai Source`*** :arrow_right: `External destination`\n\nThe features offered by this package:\n\n- **Synchronize an entire data** stream with a ready-to-use solution\n- **Synchronize only certain data** in a stream meeting a condition defined by you : [`logics`](DOCUMENTATION.md#logics)\n- **Format the data as you wish** or use the default formatting that we propose adapted to each connector : [`format`](DOCUMENTATION.md#format)\n- **Leverage the provider *HrFlow.ai\'s* Job and Profile Warehouse** with a many available options like [`hydrate_with_parsing`](src/hrflow_connectors/connectors/hrflow/warehouse.py#L42) or [`update_content`](src/hrflow_connectors/connectors/hrflow/warehouse.py#L39)\n\n## ❓ How to use a connector ?\n\n**Prerequisites**\n\n- [✨ Create a Workspace](https://hrflow.ai/signup/)\n- [🔑 Get your API Key](https://developers.hrflow.ai/docs/api-authentification)\n\n1. Spin of a terminal shell\n2. **`pip install hrflow-connectors`**\n3. Pick the connector you would like to use. Let\'s say it\'s **SAPSuccessFactors**\n\n🏁 **TADA! You have just used your first connector.**\n\n## 📖 Documentation\n\nTo find out **more about the HrFlow.ai Connectors framework** take a look at the [📖 documentation](DOCUMENTATION.md).\n\n## 💡 Contributions\n\nPlease feel free to contribute to the quality of this content by\nsubmitting PRs for improvements to code, architecture, etc.\n\nAny contributions you make to this effort are of course greatly\nappreciated.\n\n👉 **To find out more about how to proceed, the rules and conventions to follow, read carefully [`CONTRIBUTING.md`](CONTRIBUTING.md).**\n\n# 🔗 Resources\n\n- Our Developers documentation : <https://developers.hrflow.ai/>\n\n- Our API list (Parsing, Revealing, Embedding, Searching, Scoring, Reasoning) : <https://www.hrflow.ai/api>\n- Our cool demos labs : <https://labs.hrflow.ai>\n\n# 🚀 Upcoming Steps and Future Improvements\n\nThe project is now in a stable state, however there are still some features and modifications that can be added to further improve the project.\n\n**Next features** :\n\n- Add base classes for connectors actions to inherit from when developping new connectors  🚧\n\nThe development team is always open to feedback and new ideas from users, so if you have any suggestions or ideas on how to improve the project, feel free to contact us!\n\n# 📃 License\n\nSee the [`LICENSE`](LICENSE) file for licensing information.',
    'author': 'HrFlow.ai',
    'author_email': 'support+hrflow_connectors@hrflow.ai',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/Riminder/hrflow-connectors',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'python_requires': '>=3.9,<4.0',
}


setup(**setup_kwargs)
