from .client_repositories.address_repository import AddressRepository
from .client_repositories.client_type_repository import ClientTypeRepository
from .client_repositories.education_repository import EducationRepository
from .client_repositories.gender_repository import GenderRepository
from .client_repositories.marriage_status_repository import MarriageStatusRepository
from .client_repositories.pet_repository import PetRepository
from .client_repositories.profession_repository import ProfessionRepository
from .client_repositories.px_repository import PxRepository
from .client_repositories.emergency_contact_repository import EmergencyContactRepository
from .client_repositories.nationality_repository import NationalityRepository
from .client_repositories.pathological_history_repository import PathologicalHistoryRepository

from .collaborator_repositories.collaborator_repository import CollaboratorRepository
from .collaborator_repositories.collaborator_type_repository import CollaboratorTypeRepository
from .collaborator_repositories.speciality_repository import SpecialityRepository

from .infraestructure_repositories.area_repository import AreaRepository
from .infraestructure_repositories.branch_repository import BranchRepository
from .infraestructure_repositories.bridge_repository import BridgeAreaFloorBranchRepository
from .infraestructure_repositories.floor_repository import FloorRepository
from .infraestructure_repositories.room_repository import RoomRepository
from .infraestructure_repositories.system_repository import SystemRepository

from .lab_repositories.measure_lab_repository import MeasureLabRepository
from .lab_repositories.medical_lab_repository import MedicalLabRepository

from .medical_visit_repositories.medical_diagnosis_repository import MedicalDiagnosisRepository
from .medical_visit_repositories.medical_diagnosis_visit_repository import MedicalDiagnosisVisitRepository
from .medical_visit_repositories.medical_drug_recipe_repository import MedicalDrugRecipeRepository
from .medical_visit_repositories.medical_drug_repository import MedicalDrugRepository
from .medical_visit_repositories.medical_recipe_visit_repository import MedicalRecipeVisitRepository
from .medical_visit_repositories.medical_visit_repository import MedicalVisitRepository
from .medical_visit_repositories.organ_system_review_repository import OrganSystemReviewRepository
from .medical_visit_repositories.physical_exam_repository import PhysicalExamRepository
from .medical_visit_repositories.visit_triage_repository import VisitTriageRepository

from .user_repositories.permission_repository import PermissionRepository
from .user_repositories.role_repository import RoleRepository
from .user_repositories.user_repository import UserRepository

