from typing import Any

__all__: Any

def __getattr__(name: str) -> Any: ...

ALL_OPERATOR_NAMES: Any
CANONICAL_OPERATOR_NAMES: Any
COHERENCE: Any
CONTRACTION: Any
COUPLING: Any
DISSONANCE: Any
EMISSION: Any
ENGLISH_OPERATOR_NAMES: Any
EXPANSION: Any
INTERMEDIATE_OPERATORS: Any
MUTATION: Any
RECEPTION: Any
RECURSIVITY: Any
RESONANCE: Any
SELF_ORGANIZATION: Any
SELF_ORGANIZATION_CLOSURES: Any
SILENCE: Any
TRANSITION: Any
VALID_END_OPERATORS: Any
VALID_START_OPERATORS: Any
canonical_operator_name: Any
operator_display_name: Any
