# Generated by Django 4.2.10 on 2024-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuree", "0020_alter_insuree_card_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insureephoto",
            name="chf_id",
            field=models.CharField(
                blank=True, db_column="CHFID", max_length=50, null=True
            ),
        ),
    ]
