# Generated by Django 4.2.10 on 2024-09-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insuree", "0022_alter_insureephoto_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="head_insuree",
            field=models.ForeignKey(
                db_column="InsureeID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="head_of",
                to="insuree.insuree",
            ),
        ),
    ]
