from tests.fixtures.profiles import (
    custom_profile_factory,
    custom_profile_obj,
    custom_profile_obj_with_paths,
    mobileconfig_content,
    mobileconfig_content_factory,
    mobileconfig_data,
    mobileconfig_data_factory,
    mobileconfig_file,
    profile_directory,
    profile_directory_factory,
    profile_info_content_factory,
    profile_info_data_factory,
    profiles_list,
    profiles_repo,
    profiles_repo_obj,
    profiles_repo_obj_without_paths,
)
