from enum import Enum


class CommandBeginColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    SESSION = 8
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    REQUEST_PARAMETERS = 44
    REQUEST_PROPERTIES = 45
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class CommandEndColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    SESSION = 8
    INTEGER_DATA = 10
    SEVERITY = 22
    SUCCESS = 23
    ERROR = 24
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    ERROR_TYPE = 49
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55
