from enum import Enum


class VertipaqSeQueryBeginColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    JOB_ID = 7
    SESSION_TYPE = 8
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    OBJECT_REFERENCE = 15
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class VertipaqSeQueryEndColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    JOB_ID = 7
    SESSION_TYPE = 8
    PROGRESS_TOTAL = 9
    INTEGER_DATA = 10
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    OBJECT_REFERENCE = 15
    SEVERITY = 22
    SUCCESS = 23
    ERROR = 24
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    ERROR_TYPE = 49
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class VertipaqSeQueryCacheMissColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    JOB_ID = 7
    SESSION_TYPE = 8
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    OBJECT_REFERENCE = 15
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class VertipaqSeQueryCacheMatchColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    JOB_ID = 7
    SESSION_TYPE = 8
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    OBJECT_REFERENCE = 15
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class CalculationEvaluationColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    INTEGER_DATA = 10
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    CLIENT_HOST_NAME = 35
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    APPLICATION_CONTEXT = 52


class CalculationEvaluationDetailedInformationColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    INTEGER_DATA = 10
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    CLIENT_HOST_NAME = 35
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    APPLICATION_CONTEXT = 52


class DaxQueryPlanColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    INTEGER_DATA = 10
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    CLIENT_HOST_NAME = 35
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    APPLICATION_CONTEXT = 52


class DaxExtensionExecutionBeginColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    INTEGER_DATA = 10
    DATABASE_NAME = 28
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    FUNCTION_NAME = 50
    APPLICATION_CONTEXT = 52


class DaxExtensionExecutionEndColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    INTEGER_DATA = 10
    SEVERITY = 22
    SUCCESS = 23
    ERROR = 24
    DATABASE_NAME = 28
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    ERROR_TYPE = 49
    FUNCTION_NAME = 50
    APPLICATION_CONTEXT = 52


class DaxExtensionTraceErrorColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    INTEGER_DATA = 10
    DATABASE_NAME = 28
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    FUNCTION_NAME = 50
    APPLICATION_CONTEXT = 52


class DaxExtensionTraceInfoColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    INTEGER_DATA = 10
    DATABASE_NAME = 28
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    FUNCTION_NAME = 50
    APPLICATION_CONTEXT = 52


class DaxExtensionTraceVerboseColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    INTEGER_DATA = 10
    DATABASE_NAME = 28
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    FUNCTION_NAME = 50
    APPLICATION_CONTEXT = 52


class AggregateTableRewriteQueryColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    INTEGER_DATA = 10
    SUCCESS = 23
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USERNAME = 32
    NT_DOMAIN_NAME = 33
    CLIENT_HOST_NAME = 35
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    USER_OBJECT_ID = 51
    APPLICATION_CONTEXT = 52


class AggregateTableRewriteInfoColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    START_TIME = 3
    SEVERITY = 22
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    NT_DOMAIN_NAME = 33
    CLIENT_HOST_NAME = 35
    CLIENT_PROCESS_ID = 36
    APPLICATION_NAME = 37
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    APPLICATION_CONTEXT = 52


class QuerySubcubeColumns(Enum):
    EVENT_CLASS = 0
    EVENT_SUBCLASS = 1
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    OBJECT_PATH = 14
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    SESSION_ID = 39
    NT_CANONICAL_USER_NAME = 40
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_DATA = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class DirectQueryBeginColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    JOB_ID = 7
    SESSION_TYPE = 8
    INTEGER_DATA = 10
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    SEVERITY = 22
    SUCCESS = 23
    ERROR = 24
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    CLIENT_PROCESS_ID = 36
    SESSION_ID = 39
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    ERROR_TYPE = 49
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class DirectQueryEndColumns(Enum):
    EVENT_CLASS = 0
    CURRENT_TIME = 2
    START_TIME = 3
    END_TIME = 4
    DURATION = 5
    CPU_TIME = 6
    JOB_ID = 7
    SESSION_TYPE = 8
    INTEGER_DATA = 10
    OBJECT_ID = 11
    OBJECT_TYPE = 12
    OBJECT_NAME = 13
    OBJECT_PATH = 14
    SEVERITY = 22
    SUCCESS = 23
    ERROR = 24
    CONNECTION_ID = 25
    DATABASE_NAME = 28
    NT_USER_NAME = 32
    CLIENT_PROCESS_ID = 36
    SESSION_ID = 39
    SP_ID = 41
    TEXT_DATA = 42
    SERVER_NAME = 43
    ACTIVITY_ID = 46
    REQUEST_ID = 47
    ERROR_TYPE = 49
    APPLICATION_CONTEXT = 52
    DATABASE_FRIENDLY_NAME = 54
    IDENTITY = 55


class ExecutionMetricsColumns(Enum):
    EVENT_CLASS = 0
    DATABASE_NAME = 28
    APPLICATION_NAME = 37
    SP_ID = 41
    TEXT_DATA = 42
    ACTIVITY_ID = 46
    REQUEST_ID = 47
