"""Type stubs for lazy-loaded components."""

from .components import (
    animated_image as animated_image,
    animation as animation,
    avatar as avatar,
    badge as badge,
    breadcrumb as breadcrumb,
    breadcrumb_item as breadcrumb_item,
    button as button,
    button_group as button_group,
    callout as callout,
    card as card,
    carousel as carousel,
    carousel_item as carousel_item,
    checkbox as checkbox,
    color_picker as color_picker,
    comparison as comparison,
    copy_button as copy_button,
    details as details,
    dialog as dialog,
    divider as divider,
    drawer as drawer,
    dropdown as dropdown,
    dropdown_item as dropdown_item,
    format_bytes as format_bytes,
    format_date as format_date,
    format_number as format_number,
    icon as icon,
    include as include,
    input as input,
    intersection_observer as intersection_observer,
    mutation_observer as mutation_observer,
    option as option,
    popover as popover,
    popup as popup,
    progress_bar as progress_bar,
    progress_ring as progress_ring,
    qr_code as qr_code,
    radio as radio,
    radio_group as radio_group,
    rating as rating,
    relative_time as relative_time,
    resize_observer as resize_observer,
    scroller as scroller,
    select as select,
    skeleton as skeleton,
    slider as slider,
    spinner as spinner,
    split_panel as split_panel,
    switch as switch,
    tab as tab,
    tab_group as tab_group,
    tab_panel as tab_panel,
    tag as tag,
    textarea as textarea,
    tooltip as tooltip,
    tree as tree,
    tree_item as tree_item,
    zoomable_frame as zoomable_frame,
)

__all__: list[str]