{
 "title": "Current Assets",
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  {
   "title": "Total Assets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Stablecoins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ETH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"ETH\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BTC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"BTC\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Breakdown",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}