"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import StructureDataTypeTest_pb2
import abc
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class StructureDataTypeTestStub:
    """Provides commands and properties to set or respectively get SiLA Structure Data Type values via command parameters or property responses respectively."""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    EchoStructureValue: grpc.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.EchoStructureValue_Parameters,
        StructureDataTypeTest_pb2.EchoStructureValue_Responses,
    ]
    """Receives a structure value and returns the structure that has been received (binary value is expected to be an embedded value, any typer value is expected to be a Basic type)."""

    EchoDeepStructureValue: grpc.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.EchoDeepStructureValue_Parameters,
        StructureDataTypeTest_pb2.EchoDeepStructureValue_Responses,
    ]
    """Receives a multilevel structure value and returns the structure that has been received."""

    Get_StructureValue: grpc.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.Get_StructureValue_Parameters,
        StructureDataTypeTest_pb2.Get_StructureValue_Responses,
    ]
    """
    Returns a structure with the following elements values:
    - String value = 'SiLA2_Test_String_Value'
    - Integer value = 5124
    - Real value = 3.1415926
    - Boolean value = true
    - Binary value = embedded string 'SiLA2_Binary_String_Value'
    - Date value = 05.08.2022 respective 08/05/2022
    - Time value = 12:34:56.789
    - Timestamp value = 2022-08-05 12:34:56.789
    - Any type value = string 'SiLA2_Any_Type_String_Value'.
    """

    Get_DeepStructureValue: grpc.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.Get_DeepStructureValue_Parameters,
        StructureDataTypeTest_pb2.Get_DeepStructureValue_Responses,
    ]
    """
    Returns a multilevel structure with the following values:
    - string value = 'Outer_Test_String'
    - integer value = 1111
    - middle structure value =
    - string value = 'Middle_Test_String'
    - integer value = 2222
    - inner structure value =
    - string value = 'Inner_Test_String'
    - integer value = 3333.
    """

class StructureDataTypeTestAsyncStub:
    """Provides commands and properties to set or respectively get SiLA Structure Data Type values via command parameters or property responses respectively."""

    EchoStructureValue: grpc.aio.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.EchoStructureValue_Parameters,
        StructureDataTypeTest_pb2.EchoStructureValue_Responses,
    ]
    """Receives a structure value and returns the structure that has been received (binary value is expected to be an embedded value, any typer value is expected to be a Basic type)."""

    EchoDeepStructureValue: grpc.aio.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.EchoDeepStructureValue_Parameters,
        StructureDataTypeTest_pb2.EchoDeepStructureValue_Responses,
    ]
    """Receives a multilevel structure value and returns the structure that has been received."""

    Get_StructureValue: grpc.aio.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.Get_StructureValue_Parameters,
        StructureDataTypeTest_pb2.Get_StructureValue_Responses,
    ]
    """
    Returns a structure with the following elements values:
    - String value = 'SiLA2_Test_String_Value'
    - Integer value = 5124
    - Real value = 3.1415926
    - Boolean value = true
    - Binary value = embedded string 'SiLA2_Binary_String_Value'
    - Date value = 05.08.2022 respective 08/05/2022
    - Time value = 12:34:56.789
    - Timestamp value = 2022-08-05 12:34:56.789
    - Any type value = string 'SiLA2_Any_Type_String_Value'.
    """

    Get_DeepStructureValue: grpc.aio.UnaryUnaryMultiCallable[
        StructureDataTypeTest_pb2.Get_DeepStructureValue_Parameters,
        StructureDataTypeTest_pb2.Get_DeepStructureValue_Responses,
    ]
    """
    Returns a multilevel structure with the following values:
    - string value = 'Outer_Test_String'
    - integer value = 1111
    - middle structure value =
    - string value = 'Middle_Test_String'
    - integer value = 2222
    - inner structure value =
    - string value = 'Inner_Test_String'
    - integer value = 3333.
    """

class StructureDataTypeTestServicer(metaclass=abc.ABCMeta):
    """Provides commands and properties to set or respectively get SiLA Structure Data Type values via command parameters or property responses respectively."""

    @abc.abstractmethod
    def EchoStructureValue(
        self,
        request: StructureDataTypeTest_pb2.EchoStructureValue_Parameters,
        context: _ServicerContext,
    ) -> typing.Union[StructureDataTypeTest_pb2.EchoStructureValue_Responses, collections.abc.Awaitable[StructureDataTypeTest_pb2.EchoStructureValue_Responses]]:
        """Receives a structure value and returns the structure that has been received (binary value is expected to be an embedded value, any typer value is expected to be a Basic type)."""

    @abc.abstractmethod
    def EchoDeepStructureValue(
        self,
        request: StructureDataTypeTest_pb2.EchoDeepStructureValue_Parameters,
        context: _ServicerContext,
    ) -> typing.Union[StructureDataTypeTest_pb2.EchoDeepStructureValue_Responses, collections.abc.Awaitable[StructureDataTypeTest_pb2.EchoDeepStructureValue_Responses]]:
        """Receives a multilevel structure value and returns the structure that has been received."""

    @abc.abstractmethod
    def Get_StructureValue(
        self,
        request: StructureDataTypeTest_pb2.Get_StructureValue_Parameters,
        context: _ServicerContext,
    ) -> typing.Union[StructureDataTypeTest_pb2.Get_StructureValue_Responses, collections.abc.Awaitable[StructureDataTypeTest_pb2.Get_StructureValue_Responses]]:
        """
        Returns a structure with the following elements values:
        - String value = 'SiLA2_Test_String_Value'
        - Integer value = 5124
        - Real value = 3.1415926
        - Boolean value = true
        - Binary value = embedded string 'SiLA2_Binary_String_Value'
        - Date value = 05.08.2022 respective 08/05/2022
        - Time value = 12:34:56.789
        - Timestamp value = 2022-08-05 12:34:56.789
        - Any type value = string 'SiLA2_Any_Type_String_Value'.
        """

    @abc.abstractmethod
    def Get_DeepStructureValue(
        self,
        request: StructureDataTypeTest_pb2.Get_DeepStructureValue_Parameters,
        context: _ServicerContext,
    ) -> typing.Union[StructureDataTypeTest_pb2.Get_DeepStructureValue_Responses, collections.abc.Awaitable[StructureDataTypeTest_pb2.Get_DeepStructureValue_Responses]]:
        """
        Returns a multilevel structure with the following values:
        - string value = 'Outer_Test_String'
        - integer value = 1111
        - middle structure value =
        - string value = 'Middle_Test_String'
        - integer value = 2222
        - inner structure value =
        - string value = 'Inner_Test_String'
        - integer value = 3333.
        """

def add_StructureDataTypeTestServicer_to_server(servicer: StructureDataTypeTestServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
