# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper
from payrix.models.apple_domains_mass_enablement_data_preview_item import AppleDomainsMassEnablementDataPreviewItem


class ApplePayForMerchantListPostRequest(object):

    """Implementation of the 'applePayForMerchantListPostRequest' model.

    Attributes:
        merchant_id_domain_pairs
            (List[AppleDomainsMassEnablementDataPreviewItem]): The model
            property of type List[AppleDomainsMassEnablementDataPreviewItem].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_id_domain_pairs": 'merchantIdDomainPairs'
    }

    _optionals = [
        'merchant_id_domain_pairs',
    ]

    def __init__(self,
                 merchant_id_domain_pairs=APIHelper.SKIP):
        """Constructor for the ApplePayForMerchantListPostRequest class"""

        # Initialize members of the class
        if merchant_id_domain_pairs is not APIHelper.SKIP:
            self.merchant_id_domain_pairs = merchant_id_domain_pairs 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_id_domain_pairs = None
        if dictionary.get('merchantIdDomainPairs') is not None:
            merchant_id_domain_pairs = [AppleDomainsMassEnablementDataPreviewItem.from_dictionary(x) for x in dictionary.get('merchantIdDomainPairs')]
        else:
            merchant_id_domain_pairs = APIHelper.SKIP
        # Return an object of this model
        return cls(merchant_id_domain_pairs)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'merchant_id_domain_pairs={(self.merchant_id_domain_pairs if hasattr(self, "merchant_id_domain_pairs") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'merchant_id_domain_pairs={(self.merchant_id_domain_pairs if hasattr(self, "merchant_id_domain_pairs") else None)!s})')
