# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BatchStatusEnum(object):

    """Implementation of the 'batchStatus' enum.

    Attributes:
        OPEN: This Batch can accept more Transactions.
        CLOSED: This Batch is closed to new Transactions and is ready to be
            sent to the processor.

    """
    _all_values = ['open', 'closed']
    OPEN = 'open'

    CLOSED = 'closed'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   