# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ChargebackDocumentStatusEnum(object):

    """Implementation of the 'chargebackDocumentStatus' enum.

    Attributes:
        CREATED: The ChargebackDocument has been created.
        PROCESSED: The ChargebackDocument integration has been successful.
        FAILED: The ChargebackDocument integration has failed.

    """
    _all_values = ['created', 'processed', 'failed']
    CREATED = 'created'

    PROCESSED = 'processed'

    FAILED = 'failed'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   