# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DebtRepaymentStrEnum(object):

    """Implementation of the 'debtRepaymentStr' enum.

    Attributes:
        OFF: Transaction not for debt repayment.
        ON: Transaction for debt repayment.

    """
    _all_values = ['0', '1']
    OFF = '0'

    ON = '1'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   