# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper
from payrix.models.aggregations_response import AggregationsResponse
from payrix.models.billing_modifiers_response import BillingModifiersResponse
from payrix.models.billings_response import BillingsResponse
from payrix.models.configurations_response import ConfigurationsResponse
from payrix.models.currency_rates_response import CurrencyRatesResponse
from payrix.models.decisions_response import DecisionsResponse
from payrix.models.embedded_finance_response import EmbeddedFinanceResponse
from payrix.models.entity_routes_response import EntityRoutesResponse
from payrix.models.fee_modifiers_response import FeeModifiersResponse
from payrix.models.funding_parameters_response import FundingParametersResponse
from payrix.models.hosts_response import HostsResponse
from payrix.models.invoice_parameters_response import InvoiceParametersResponse
from payrix.models.mccs_response import MccsResponse
from payrix.models.omni_tokens_response import OmniTokensResponse
from payrix.models.org_flows_response import OrgFlowsResponse
from payrix.models.parameters_response import ParametersResponse
from payrix.models.payout_flows_response import PayoutFlowsResponse
from payrix.models.pinless_debit_conversions_response import PinlessDebitConversionsResponse
from payrix.models.profit_shares_response import ProfitSharesResponse
from payrix.models.reserves_response import ReservesResponse
from payrix.models.revenue_boosts_response import RevenueBoostsResponse
from payrix.models.safer_payments_response import SaferPaymentsResponse
from payrix.models.secrets_response import SecretsResponse
from payrix.models.vendors_response import VendorsResponse


class DivisionsResponse(object):

    """Implementation of the 'divisionsResponse' model.

    Attributes:
        id (str): The ID of this resource.
        created (str): The date and time at which this resource was created.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        modified (str): The date and time at which this resource was modified.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        creator (str | LoginsResponse | None): The model property of type str
            | LoginsResponse | None.
        modifier (str): The identifier of the Login that last modified this
            resource.
        login (str | LoginsResponse | None): The model property of type str |
            LoginsResponse | None.
        name (str): The name of the division, which may be used for some
            white-label purposes
        email (str): The white-labeled outgoing email for all automated emails
            generated throughout this division
        change_management_enabled (ChangeManagementEnabledEnum): Whether
            change request management is enabled <details> <summary>Valid
            Values</summary> - `0` - **Disabled.** - `1` - **Enabled.**
            </details>
        min_password_length (int): Minimum password length
        min_password_complexity (MinPasswordComplexityEnum): Password
            Complexity <details> <summary>Valid Values</summary> - `1` -
            **Needs to include one type.** - `2` - **Needs to include two
            types.** - `3` - **Needs to include three types.** - `4` - **Needs
            to include the four types.** </details>
        can_use_plaid_wrapper_microservice
            (CanUsePlaidWrapperMicroserviceEnum): Describes if the user can
            use the Plaid Wrapper Microservice or not <details> <summary>Valid
            Values</summary>    - `0` - **No.**   - `1` - **Yes.** </details>
        simplified_deposit_enabled (SimplifiedDepositEnabledEnum): Allows
            automatic enablement of simplified deposits for new boardings and
            allows enablement of existing boardings. Restricted to admin.
            Valid Values :  - `1` - **Enabled**
        aggregations (List[AggregationsResponse]): The model property of type
            List[AggregationsResponse].
        billing_modifiers (List[BillingModifiersResponse]): The model property
            of type List[BillingModifiersResponse].
        billings (List[BillingsResponse]): The model property of type
            List[BillingsResponse].
        configurations (List[ConfigurationsResponse]): The model property of
            type List[ConfigurationsResponse].
        currency_rates (List[CurrencyRatesResponse]): The model property of
            type List[CurrencyRatesResponse].
        decisions (List[DecisionsResponse]): The model property of type
            List[DecisionsResponse].
        embedded_finance (List[EmbeddedFinanceResponse]): The model property
            of type List[EmbeddedFinanceResponse].
        entity_routes (List[EntityRoutesResponse]): The model property of type
            List[EntityRoutesResponse].
        fee_modifiers (List[FeeModifiersResponse]): The model property of type
            List[FeeModifiersResponse].
        funding_parameters (List[FundingParametersResponse]): The model
            property of type List[FundingParametersResponse].
        hosts (List[HostsResponse]): The model property of type
            List[HostsResponse].
        invoice_parameters (List[InvoiceParametersResponse]): The model
            property of type List[InvoiceParametersResponse].
        logins (List[LoginsResponse]): The model property of type
            List[LoginsResponse].
        mccs (List[MccsResponse]): The model property of type
            List[MccsResponse].
        org_flows (List[OrgFlowsResponse]): The model property of type
            List[OrgFlowsResponse].
        omni_tokens (List[OmniTokensResponse]): The model property of type
            List[OmniTokensResponse].
        parameters (List[ParametersResponse]): The model property of type
            List[ParametersResponse].
        payout_flows (List[PayoutFlowsResponse]): The model property of type
            List[PayoutFlowsResponse].
        pinless_debit_conversions (List[PinlessDebitConversionsResponse]): The
            model property of type List[PinlessDebitConversionsResponse].
        profit_shares (List[ProfitSharesResponse]): The model property of type
            List[ProfitSharesResponse].
        reserves (List[ReservesResponse]): The model property of type
            List[ReservesResponse].
        revenue_boosts (List[RevenueBoostsResponse]): The model property of
            type List[RevenueBoostsResponse].
        safer_payments (List[SaferPaymentsResponse]): The model property of
            type List[SaferPaymentsResponse].
        secrets (List[SecretsResponse]): The model property of type
            List[SecretsResponse].
        vendors (List[VendorsResponse]): The model property of type
            List[VendorsResponse].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "created": 'created',
        "modified": 'modified',
        "creator": 'creator',
        "modifier": 'modifier',
        "login": 'login',
        "name": 'name',
        "email": 'email',
        "change_management_enabled": 'changeManagementEnabled',
        "min_password_length": 'minPasswordLength',
        "min_password_complexity": 'minPasswordComplexity',
        "can_use_plaid_wrapper_microservice": 'canUsePlaidWrapperMicroservice',
        "simplified_deposit_enabled": 'simplifiedDepositEnabled',
        "aggregations": 'aggregations',
        "billing_modifiers": 'billingModifiers',
        "billings": 'billings',
        "configurations": 'configurations',
        "currency_rates": 'currencyRates',
        "decisions": 'decisions',
        "embedded_finance": 'embeddedFinance',
        "entity_routes": 'entityRoutes',
        "fee_modifiers": 'feeModifiers',
        "funding_parameters": 'fundingParameters',
        "hosts": 'hosts',
        "invoice_parameters": 'invoiceParameters',
        "logins": 'logins',
        "mccs": 'mccs',
        "org_flows": 'orgFlows',
        "omni_tokens": 'omniTokens',
        "parameters": 'parameters',
        "payout_flows": 'payoutFlows',
        "pinless_debit_conversions": 'pinlessDebitConversions',
        "profit_shares": 'profitShares',
        "reserves": 'reserves',
        "revenue_boosts": 'revenueBoosts',
        "safer_payments": 'saferPayments',
        "secrets": 'secrets',
        "vendors": 'vendors'
    }

    _optionals = [
        'id',
        'created',
        'modified',
        'creator',
        'modifier',
        'login',
        'name',
        'email',
        'change_management_enabled',
        'min_password_length',
        'min_password_complexity',
        'can_use_plaid_wrapper_microservice',
        'simplified_deposit_enabled',
        'aggregations',
        'billing_modifiers',
        'billings',
        'configurations',
        'currency_rates',
        'decisions',
        'embedded_finance',
        'entity_routes',
        'fee_modifiers',
        'funding_parameters',
        'hosts',
        'invoice_parameters',
        'logins',
        'mccs',
        'org_flows',
        'omni_tokens',
        'parameters',
        'payout_flows',
        'pinless_debit_conversions',
        'profit_shares',
        'reserves',
        'revenue_boosts',
        'safer_payments',
        'secrets',
        'vendors',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 created=APIHelper.SKIP,
                 modified=APIHelper.SKIP,
                 creator=APIHelper.SKIP,
                 modifier=APIHelper.SKIP,
                 login=APIHelper.SKIP,
                 name=APIHelper.SKIP,
                 email=APIHelper.SKIP,
                 change_management_enabled=APIHelper.SKIP,
                 min_password_length=APIHelper.SKIP,
                 min_password_complexity=APIHelper.SKIP,
                 can_use_plaid_wrapper_microservice=APIHelper.SKIP,
                 simplified_deposit_enabled=APIHelper.SKIP,
                 aggregations=APIHelper.SKIP,
                 billing_modifiers=APIHelper.SKIP,
                 billings=APIHelper.SKIP,
                 configurations=APIHelper.SKIP,
                 currency_rates=APIHelper.SKIP,
                 decisions=APIHelper.SKIP,
                 embedded_finance=APIHelper.SKIP,
                 entity_routes=APIHelper.SKIP,
                 fee_modifiers=APIHelper.SKIP,
                 funding_parameters=APIHelper.SKIP,
                 hosts=APIHelper.SKIP,
                 invoice_parameters=APIHelper.SKIP,
                 logins=APIHelper.SKIP,
                 mccs=APIHelper.SKIP,
                 org_flows=APIHelper.SKIP,
                 omni_tokens=APIHelper.SKIP,
                 parameters=APIHelper.SKIP,
                 payout_flows=APIHelper.SKIP,
                 pinless_debit_conversions=APIHelper.SKIP,
                 profit_shares=APIHelper.SKIP,
                 reserves=APIHelper.SKIP,
                 revenue_boosts=APIHelper.SKIP,
                 safer_payments=APIHelper.SKIP,
                 secrets=APIHelper.SKIP,
                 vendors=APIHelper.SKIP):
        """Constructor for the DivisionsResponse class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if created is not APIHelper.SKIP:
            self.created = created 
        if modified is not APIHelper.SKIP:
            self.modified = modified 
        if creator is not APIHelper.SKIP:
            self.creator = creator 
        if modifier is not APIHelper.SKIP:
            self.modifier = modifier 
        if login is not APIHelper.SKIP:
            self.login = login 
        if name is not APIHelper.SKIP:
            self.name = name 
        if email is not APIHelper.SKIP:
            self.email = email 
        if change_management_enabled is not APIHelper.SKIP:
            self.change_management_enabled = change_management_enabled 
        if min_password_length is not APIHelper.SKIP:
            self.min_password_length = min_password_length 
        if min_password_complexity is not APIHelper.SKIP:
            self.min_password_complexity = min_password_complexity 
        if can_use_plaid_wrapper_microservice is not APIHelper.SKIP:
            self.can_use_plaid_wrapper_microservice = can_use_plaid_wrapper_microservice 
        if simplified_deposit_enabled is not APIHelper.SKIP:
            self.simplified_deposit_enabled = simplified_deposit_enabled 
        if aggregations is not APIHelper.SKIP:
            self.aggregations = aggregations 
        if billing_modifiers is not APIHelper.SKIP:
            self.billing_modifiers = billing_modifiers 
        if billings is not APIHelper.SKIP:
            self.billings = billings 
        if configurations is not APIHelper.SKIP:
            self.configurations = configurations 
        if currency_rates is not APIHelper.SKIP:
            self.currency_rates = currency_rates 
        if decisions is not APIHelper.SKIP:
            self.decisions = decisions 
        if embedded_finance is not APIHelper.SKIP:
            self.embedded_finance = embedded_finance 
        if entity_routes is not APIHelper.SKIP:
            self.entity_routes = entity_routes 
        if fee_modifiers is not APIHelper.SKIP:
            self.fee_modifiers = fee_modifiers 
        if funding_parameters is not APIHelper.SKIP:
            self.funding_parameters = funding_parameters 
        if hosts is not APIHelper.SKIP:
            self.hosts = hosts 
        if invoice_parameters is not APIHelper.SKIP:
            self.invoice_parameters = invoice_parameters 
        if logins is not APIHelper.SKIP:
            self.logins = logins 
        if mccs is not APIHelper.SKIP:
            self.mccs = mccs 
        if org_flows is not APIHelper.SKIP:
            self.org_flows = org_flows 
        if omni_tokens is not APIHelper.SKIP:
            self.omni_tokens = omni_tokens 
        if parameters is not APIHelper.SKIP:
            self.parameters = parameters 
        if payout_flows is not APIHelper.SKIP:
            self.payout_flows = payout_flows 
        if pinless_debit_conversions is not APIHelper.SKIP:
            self.pinless_debit_conversions = pinless_debit_conversions 
        if profit_shares is not APIHelper.SKIP:
            self.profit_shares = profit_shares 
        if reserves is not APIHelper.SKIP:
            self.reserves = reserves 
        if revenue_boosts is not APIHelper.SKIP:
            self.revenue_boosts = revenue_boosts 
        if safer_payments is not APIHelper.SKIP:
            self.safer_payments = safer_payments 
        if secrets is not APIHelper.SKIP:
            self.secrets = secrets 
        if vendors is not APIHelper.SKIP:
            self.vendors = vendors 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from payrix.utilities.union_type_lookup import UnionTypeLookUp
        from payrix.models.logins_response import LoginsResponse

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        created = dictionary.get("created") if dictionary.get("created") else APIHelper.SKIP
        modified = dictionary.get("modified") if dictionary.get("modified") else APIHelper.SKIP
        creator = APIHelper.deserialize_union_type(UnionTypeLookUp.get('DivisionsResponseCreator'), dictionary.get('creator'), False) if dictionary.get('creator') is not None else APIHelper.SKIP
        modifier = dictionary.get("modifier") if dictionary.get("modifier") else APIHelper.SKIP
        login = APIHelper.deserialize_union_type(UnionTypeLookUp.get('DivisionsResponseLogin'), dictionary.get('login'), False) if dictionary.get('login') is not None else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        email = dictionary.get("email") if dictionary.get("email") else APIHelper.SKIP
        change_management_enabled = dictionary.get("changeManagementEnabled") if dictionary.get("changeManagementEnabled") else APIHelper.SKIP
        min_password_length = dictionary.get("minPasswordLength") if dictionary.get("minPasswordLength") else APIHelper.SKIP
        min_password_complexity = dictionary.get("minPasswordComplexity") if dictionary.get("minPasswordComplexity") else APIHelper.SKIP
        can_use_plaid_wrapper_microservice = dictionary.get("canUsePlaidWrapperMicroservice") if dictionary.get("canUsePlaidWrapperMicroservice") else APIHelper.SKIP
        simplified_deposit_enabled = dictionary.get("simplifiedDepositEnabled") if dictionary.get("simplifiedDepositEnabled") else APIHelper.SKIP
        aggregations = None
        if dictionary.get('aggregations') is not None:
            aggregations = [AggregationsResponse.from_dictionary(x) for x in dictionary.get('aggregations')]
        else:
            aggregations = APIHelper.SKIP
        billing_modifiers = None
        if dictionary.get('billingModifiers') is not None:
            billing_modifiers = [BillingModifiersResponse.from_dictionary(x) for x in dictionary.get('billingModifiers')]
        else:
            billing_modifiers = APIHelper.SKIP
        billings = None
        if dictionary.get('billings') is not None:
            billings = [BillingsResponse.from_dictionary(x) for x in dictionary.get('billings')]
        else:
            billings = APIHelper.SKIP
        configurations = None
        if dictionary.get('configurations') is not None:
            configurations = [ConfigurationsResponse.from_dictionary(x) for x in dictionary.get('configurations')]
        else:
            configurations = APIHelper.SKIP
        currency_rates = None
        if dictionary.get('currencyRates') is not None:
            currency_rates = [CurrencyRatesResponse.from_dictionary(x) for x in dictionary.get('currencyRates')]
        else:
            currency_rates = APIHelper.SKIP
        decisions = None
        if dictionary.get('decisions') is not None:
            decisions = [DecisionsResponse.from_dictionary(x) for x in dictionary.get('decisions')]
        else:
            decisions = APIHelper.SKIP
        embedded_finance = None
        if dictionary.get('embeddedFinance') is not None:
            embedded_finance = [EmbeddedFinanceResponse.from_dictionary(x) for x in dictionary.get('embeddedFinance')]
        else:
            embedded_finance = APIHelper.SKIP
        entity_routes = None
        if dictionary.get('entityRoutes') is not None:
            entity_routes = [EntityRoutesResponse.from_dictionary(x) for x in dictionary.get('entityRoutes')]
        else:
            entity_routes = APIHelper.SKIP
        fee_modifiers = None
        if dictionary.get('feeModifiers') is not None:
            fee_modifiers = [FeeModifiersResponse.from_dictionary(x) for x in dictionary.get('feeModifiers')]
        else:
            fee_modifiers = APIHelper.SKIP
        funding_parameters = None
        if dictionary.get('fundingParameters') is not None:
            funding_parameters = [FundingParametersResponse.from_dictionary(x) for x in dictionary.get('fundingParameters')]
        else:
            funding_parameters = APIHelper.SKIP
        hosts = None
        if dictionary.get('hosts') is not None:
            hosts = [HostsResponse.from_dictionary(x) for x in dictionary.get('hosts')]
        else:
            hosts = APIHelper.SKIP
        invoice_parameters = None
        if dictionary.get('invoiceParameters') is not None:
            invoice_parameters = [InvoiceParametersResponse.from_dictionary(x) for x in dictionary.get('invoiceParameters')]
        else:
            invoice_parameters = APIHelper.SKIP
        logins = None
        if dictionary.get('logins') is not None:
            logins = [LoginsResponse.from_dictionary(x) for x in dictionary.get('logins')]
        else:
            logins = APIHelper.SKIP
        mccs = None
        if dictionary.get('mccs') is not None:
            mccs = [MccsResponse.from_dictionary(x) for x in dictionary.get('mccs')]
        else:
            mccs = APIHelper.SKIP
        org_flows = None
        if dictionary.get('orgFlows') is not None:
            org_flows = [OrgFlowsResponse.from_dictionary(x) for x in dictionary.get('orgFlows')]
        else:
            org_flows = APIHelper.SKIP
        omni_tokens = None
        if dictionary.get('omniTokens') is not None:
            omni_tokens = [OmniTokensResponse.from_dictionary(x) for x in dictionary.get('omniTokens')]
        else:
            omni_tokens = APIHelper.SKIP
        parameters = None
        if dictionary.get('parameters') is not None:
            parameters = [ParametersResponse.from_dictionary(x) for x in dictionary.get('parameters')]
        else:
            parameters = APIHelper.SKIP
        payout_flows = None
        if dictionary.get('payoutFlows') is not None:
            payout_flows = [PayoutFlowsResponse.from_dictionary(x) for x in dictionary.get('payoutFlows')]
        else:
            payout_flows = APIHelper.SKIP
        pinless_debit_conversions = None
        if dictionary.get('pinlessDebitConversions') is not None:
            pinless_debit_conversions = [PinlessDebitConversionsResponse.from_dictionary(x) for x in dictionary.get('pinlessDebitConversions')]
        else:
            pinless_debit_conversions = APIHelper.SKIP
        profit_shares = None
        if dictionary.get('profitShares') is not None:
            profit_shares = [ProfitSharesResponse.from_dictionary(x) for x in dictionary.get('profitShares')]
        else:
            profit_shares = APIHelper.SKIP
        reserves = None
        if dictionary.get('reserves') is not None:
            reserves = [ReservesResponse.from_dictionary(x) for x in dictionary.get('reserves')]
        else:
            reserves = APIHelper.SKIP
        revenue_boosts = None
        if dictionary.get('revenueBoosts') is not None:
            revenue_boosts = [RevenueBoostsResponse.from_dictionary(x) for x in dictionary.get('revenueBoosts')]
        else:
            revenue_boosts = APIHelper.SKIP
        safer_payments = None
        if dictionary.get('saferPayments') is not None:
            safer_payments = [SaferPaymentsResponse.from_dictionary(x) for x in dictionary.get('saferPayments')]
        else:
            safer_payments = APIHelper.SKIP
        secrets = None
        if dictionary.get('secrets') is not None:
            secrets = [SecretsResponse.from_dictionary(x) for x in dictionary.get('secrets')]
        else:
            secrets = APIHelper.SKIP
        vendors = None
        if dictionary.get('vendors') is not None:
            vendors = [VendorsResponse.from_dictionary(x) for x in dictionary.get('vendors')]
        else:
            vendors = APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   created,
                   modified,
                   creator,
                   modifier,
                   login,
                   name,
                   email,
                   change_management_enabled,
                   min_password_length,
                   min_password_complexity,
                   can_use_plaid_wrapper_microservice,
                   simplified_deposit_enabled,
                   aggregations,
                   billing_modifiers,
                   billings,
                   configurations,
                   currency_rates,
                   decisions,
                   embedded_finance,
                   entity_routes,
                   fee_modifiers,
                   funding_parameters,
                   hosts,
                   invoice_parameters,
                   logins,
                   mccs,
                   org_flows,
                   omni_tokens,
                   parameters,
                   payout_flows,
                   pinless_debit_conversions,
                   profit_shares,
                   reserves,
                   revenue_boosts,
                   safer_payments,
                   secrets,
                   vendors)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from payrix.models.logins_response import LoginsResponse

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'created={(self.created if hasattr(self, "created") else None)!r}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!r}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!r}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!r}, '
                f'login={(self.login if hasattr(self, "login") else None)!r}, '
                f'name={(self.name if hasattr(self, "name") else None)!r}, '
                f'email={(self.email if hasattr(self, "email") else None)!r}, '
                f'change_management_enabled={(self.change_management_enabled if hasattr(self, "change_management_enabled") else None)!r}, '
                f'min_password_length={(self.min_password_length if hasattr(self, "min_password_length") else None)!r}, '
                f'min_password_complexity={(self.min_password_complexity if hasattr(self, "min_password_complexity") else None)!r}, '
                f'can_use_plaid_wrapper_microservice={(self.can_use_plaid_wrapper_microservice if hasattr(self, "can_use_plaid_wrapper_microservice") else None)!r}, '
                f'simplified_deposit_enabled={(self.simplified_deposit_enabled if hasattr(self, "simplified_deposit_enabled") else None)!r}, '
                f'aggregations={(self.aggregations if hasattr(self, "aggregations") else None)!r}, '
                f'billing_modifiers={(self.billing_modifiers if hasattr(self, "billing_modifiers") else None)!r}, '
                f'billings={(self.billings if hasattr(self, "billings") else None)!r}, '
                f'configurations={(self.configurations if hasattr(self, "configurations") else None)!r}, '
                f'currency_rates={(self.currency_rates if hasattr(self, "currency_rates") else None)!r}, '
                f'decisions={(self.decisions if hasattr(self, "decisions") else None)!r}, '
                f'embedded_finance={(self.embedded_finance if hasattr(self, "embedded_finance") else None)!r}, '
                f'entity_routes={(self.entity_routes if hasattr(self, "entity_routes") else None)!r}, '
                f'fee_modifiers={(self.fee_modifiers if hasattr(self, "fee_modifiers") else None)!r}, '
                f'funding_parameters={(self.funding_parameters if hasattr(self, "funding_parameters") else None)!r}, '
                f'hosts={(self.hosts if hasattr(self, "hosts") else None)!r}, '
                f'invoice_parameters={(self.invoice_parameters if hasattr(self, "invoice_parameters") else None)!r}, '
                f'logins={(self.logins if hasattr(self, "logins") else None)!r}, '
                f'mccs={(self.mccs if hasattr(self, "mccs") else None)!r}, '
                f'org_flows={(self.org_flows if hasattr(self, "org_flows") else None)!r}, '
                f'omni_tokens={(self.omni_tokens if hasattr(self, "omni_tokens") else None)!r}, '
                f'parameters={(self.parameters if hasattr(self, "parameters") else None)!r}, '
                f'payout_flows={(self.payout_flows if hasattr(self, "payout_flows") else None)!r}, '
                f'pinless_debit_conversions={(self.pinless_debit_conversions if hasattr(self, "pinless_debit_conversions") else None)!r}, '
                f'profit_shares={(self.profit_shares if hasattr(self, "profit_shares") else None)!r}, '
                f'reserves={(self.reserves if hasattr(self, "reserves") else None)!r}, '
                f'revenue_boosts={(self.revenue_boosts if hasattr(self, "revenue_boosts") else None)!r}, '
                f'safer_payments={(self.safer_payments if hasattr(self, "safer_payments") else None)!r}, '
                f'secrets={(self.secrets if hasattr(self, "secrets") else None)!r}, '
                f'vendors={(self.vendors if hasattr(self, "vendors") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'created={(self.created if hasattr(self, "created") else None)!s}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!s}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!s}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!s}, '
                f'login={(self.login if hasattr(self, "login") else None)!s}, '
                f'name={(self.name if hasattr(self, "name") else None)!s}, '
                f'email={(self.email if hasattr(self, "email") else None)!s}, '
                f'change_management_enabled={(self.change_management_enabled if hasattr(self, "change_management_enabled") else None)!s}, '
                f'min_password_length={(self.min_password_length if hasattr(self, "min_password_length") else None)!s}, '
                f'min_password_complexity={(self.min_password_complexity if hasattr(self, "min_password_complexity") else None)!s}, '
                f'can_use_plaid_wrapper_microservice={(self.can_use_plaid_wrapper_microservice if hasattr(self, "can_use_plaid_wrapper_microservice") else None)!s}, '
                f'simplified_deposit_enabled={(self.simplified_deposit_enabled if hasattr(self, "simplified_deposit_enabled") else None)!s}, '
                f'aggregations={(self.aggregations if hasattr(self, "aggregations") else None)!s}, '
                f'billing_modifiers={(self.billing_modifiers if hasattr(self, "billing_modifiers") else None)!s}, '
                f'billings={(self.billings if hasattr(self, "billings") else None)!s}, '
                f'configurations={(self.configurations if hasattr(self, "configurations") else None)!s}, '
                f'currency_rates={(self.currency_rates if hasattr(self, "currency_rates") else None)!s}, '
                f'decisions={(self.decisions if hasattr(self, "decisions") else None)!s}, '
                f'embedded_finance={(self.embedded_finance if hasattr(self, "embedded_finance") else None)!s}, '
                f'entity_routes={(self.entity_routes if hasattr(self, "entity_routes") else None)!s}, '
                f'fee_modifiers={(self.fee_modifiers if hasattr(self, "fee_modifiers") else None)!s}, '
                f'funding_parameters={(self.funding_parameters if hasattr(self, "funding_parameters") else None)!s}, '
                f'hosts={(self.hosts if hasattr(self, "hosts") else None)!s}, '
                f'invoice_parameters={(self.invoice_parameters if hasattr(self, "invoice_parameters") else None)!s}, '
                f'logins={(self.logins if hasattr(self, "logins") else None)!s}, '
                f'mccs={(self.mccs if hasattr(self, "mccs") else None)!s}, '
                f'org_flows={(self.org_flows if hasattr(self, "org_flows") else None)!s}, '
                f'omni_tokens={(self.omni_tokens if hasattr(self, "omni_tokens") else None)!s}, '
                f'parameters={(self.parameters if hasattr(self, "parameters") else None)!s}, '
                f'payout_flows={(self.payout_flows if hasattr(self, "payout_flows") else None)!s}, '
                f'pinless_debit_conversions={(self.pinless_debit_conversions if hasattr(self, "pinless_debit_conversions") else None)!s}, '
                f'profit_shares={(self.profit_shares if hasattr(self, "profit_shares") else None)!s}, '
                f'reserves={(self.reserves if hasattr(self, "reserves") else None)!s}, '
                f'revenue_boosts={(self.revenue_boosts if hasattr(self, "revenue_boosts") else None)!s}, '
                f'safer_payments={(self.safer_payments if hasattr(self, "safer_payments") else None)!s}, '
                f'secrets={(self.secrets if hasattr(self, "secrets") else None)!s}, '
                f'vendors={(self.vendors if hasattr(self, "vendors") else None)!s})')
