# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrgsVASFraudSightEnablementsPostRequest(object):

    """Implementation of the 'orgsVASFraudSightEnablementsPostRequest' model.

    Attributes:
        org (str): The identifier of the Org (group) that
            OrgsVASFraudSightEnablements is associated to.
        group_name (GroupNameEnum): The name of the group for this FraudSight
            enablement.  <details> <summary>Valid Values</summary>  - `PIECPA`
            - Post Network -Decision Non EMV CP & Inform remaining CP. -
            `PICNP` - Post Network - Decision CNP only & Inform CP. - `PACPA`
            - Post Network - Decision All CP Authorizations. - `INCNP` - Pre
            Network -Decision Non-Recurring CNP & Inform CP. - `PIKCPA` - Post
            Network -Decision Key Entered CP & Inform remaining CP. - `IECNP`
            - Pre Network -Decision CNP and Non EMV CP & Inform remaining CP.
            - `ACPA` - Pre Network - Decision All CP Authorizations. - `PACNP`
            - Post Network - Decision All Authorizations (CNP & CP). -
            `PIECNP` - Post Network -Decision CNP and Non EMV CP & Inform
            remaining CP. - `IKCPA` - Pre Network -Decision Key Entered CP &
            Inform remaining CP. - `ACNP` - Pre Network - Decision All
            Authorizations (CNP & CP). - `PINCNP` - Post Network -Decision
            Non-Recurring CNP & Inform CP. - `IECPA` - Pre Network -Decision
            Non EMV CP & Inform remaining CP. - `ICNP` - Pre Network -
            Decision CNP only & Inform CP.  </details>
        description (str): The description of the Group Name.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "org": 'org',
        "group_name": 'groupName',
        "description": 'description'
    }

    def __init__(self,
                 org=None,
                 group_name=None,
                 description=None):
        """Constructor for the OrgsVASFraudSightEnablementsPostRequest class"""

        # Initialize members of the class
        self.org = org 
        self.group_name = group_name 
        self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        org = dictionary.get("org") if dictionary.get("org") else None
        group_name = dictionary.get("groupName") if dictionary.get("groupName") else None
        description = dictionary.get("description") if dictionary.get("description") else None
        # Return an object of this model
        return cls(org,
                   group_name,
                   description)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'org={self.org!r}, '
                f'group_name={self.group_name!r}, '
                f'description={self.description!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'org={self.org!s}, '
                f'group_name={self.group_name!s}, '
                f'description={self.description!s})')
