# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentMethodsEnum(object):

    """Implementation of the 'PaymentMethods' enum.

    Attributes:
        AMEX: American Express.
        VISA: Visa.
        MASTERCARD: MasterCard.
        DINERS: Diners Club.
        DISCOVER: Discover.
        PAYPAL: PayPal.
        DEBIT: Debit.
        CHECKING: Personal checking.
        SAVINGS: Personal savings.
        CORPCHECKING: Corporate checking.
        CORPSAVINGS: Corporate savings.
        GIFT: Gift card.
        EBT: EBT (Electronic Benefits Transfer).
        WIC: WIC (Women, Infants and Children).
        ACCEL: Accel network.
        ATH: ATH network.
        AFFN: AFFN network.
        CULIANCE: Culiance network.
        INTERLINK: Interlink network.
        JEANIE: Jeanie network.
        MAESTRO: Maestro network.
        NYCE: NYCE network.
        PULSE: Pulse network.
        SHAZAM: Shazam network.
        STAR: Star network.
        INTERAC: Interac network.
        OMNITOKEN: Omnitoken.

    """
    _all_values = ['amex', 'visa', 'masterCard', 'diners', 'discover', 'paypal', 'debit', 'checking', 'savings', 'corpChecking', 'corpSavings', 'gift', 'ebt', 'wic', 'Accel', 'ATH', 'AFFN', 'Culiance', 'Interlink', 'Jeanie', 'Maestro', 'NYCE', 'Pulse', 'Shazam', 'Star', 'Interac', 'Omnitoken']
    AMEX = 'amex'

    VISA = 'visa'

    MASTERCARD = 'masterCard'

    DINERS = 'diners'

    DISCOVER = 'discover'

    PAYPAL = 'paypal'

    DEBIT = 'debit'

    CHECKING = 'checking'

    SAVINGS = 'savings'

    CORPCHECKING = 'corpChecking'

    CORPSAVINGS = 'corpSavings'

    GIFT = 'gift'

    EBT = 'ebt'

    WIC = 'wic'

    ACCEL = 'Accel'

    ATH = 'ATH'

    AFFN = 'AFFN'

    CULIANCE = 'Culiance'

    INTERLINK = 'Interlink'

    JEANIE = 'Jeanie'

    MAESTRO = 'Maestro'

    NYCE = 'NYCE'

    PULSE = 'Pulse'

    SHAZAM = 'Shazam'

    STAR = 'Star'

    INTERAC = 'Interac'

    OMNITOKEN = 'Omnitoken'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   