# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PayoutDelayIncludeOffDaysEnum(object):

    """Implementation of the 'PayoutDelayIncludeOffDays' enum.

    Attributes:
        NO: Weekends and holidays are not counted in the payout delay.
        YES: Weekends and holidays are counted in the payout delay.

    """
    _all_values = [0, 1]
    NO = 0

    YES = 1

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   