# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TaxFormEnablementsPostRequest(object):

    """Implementation of the 'taxFormEnablementsPostRequest' model.

    Attributes:
        entity (str): The identifier of the Entity that is enabled for tax
            forms.
        mtype (str): The tax document type. <details> <summary>Valid
            Values</summary>  - `1099k` - **1099k Tax Document**  </details>

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "entity": 'entity',
        "mtype": 'type'
    }

    def __init__(self,
                 entity=None):
        """Constructor for the TaxFormEnablementsPostRequest class"""

        # Initialize members of the class
        self.entity = entity 
        self.mtype = '1099k' 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        entity = dictionary.get("entity") if dictionary.get("entity") else None
        # Return an object of this model
        return cls(entity)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'entity={self.entity!r}, '
                f'mtype={self.mtype!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'entity={self.entity!s}, '
                f'mtype={self.mtype!s})')
