from enum import Enum


class HubspotObject(Enum):
    ACCOUNT = "account"
    CALL = "call"
    COMMUNICATION = "communication"
    COMPANY = "company"
    CONTACT = "contact"
    DEAL = "deal"
    EMAIL = "email"
    MEETING = "meeting"
    NOTE = "note"
    TASK = "task"

    @property
    def plural(self) -> str:
        if self.value == "company":
            return "companies"
        return f"{self.value}s"


class HubspotIndustryType(str, Enum):
    ACCOUNTING = "ACCOUNTING"
    AIRLINES_AVIATION = "AIRLINES_AVIATION"
    ALTERNATIVE_DISPUTE_RESOLUTION = "ALTERNATIVE_DISPUTE_RESOLUTION"
    ALTERNATIVE_MEDICINE = "ALTERNATIVE_MEDICINE"
    ANIMATION = "ANIMATION"
    APPAREL_FASHION = "APPAREL_FASHION"
    ARCHITECTURE_PLANNING = "ARCHITECTURE_PLANNING"
    ARTS_AND_CRAFTS = "ARTS_AND_CRAFTS"
    AUTOMOTIVE = "AUTOMOTIVE"
    AVIATION_AEROSPACE = "AVIATION_AEROSPACE"
    BANKING = "BANKING"
    BIOTECHNOLOGY = "BIOTECHNOLOGY"
    BROADCAST_MEDIA = "BROADCAST_MEDIA"
    BUILDING_MATERIALS = "BUILDING_MATERIALS"
    BUSINESS_SUPPLIES_AND_EQUIPMENT = "BUSINESS_SUPPLIES_AND_EQUIPMENT"
    CAPITAL_MARKETS = "CAPITAL_MARKETS"
    CHEMICALS = "CHEMICALS"
    CIVIC_SOCIAL_ORGANIZATION = "CIVIC_SOCIAL_ORGANIZATION"
    CIVIL_ENGINEERING = "CIVIL_ENGINEERING"
    COMMERCIAL_REAL_ESTATE = "COMMERCIAL_REAL_ESTATE"
    COMPUTER_NETWORK_SECURITY = "COMPUTER_NETWORK_SECURITY"
    COMPUTER_GAMES = "COMPUTER_GAMES"
    COMPUTER_HARDWARE = "COMPUTER_HARDWARE"
    COMPUTER_NETWORKING = "COMPUTER_NETWORKING"
    COMPUTER_SOFTWARE = "COMPUTER_SOFTWARE"
    INTERNET = "INTERNET"
    CONSTRUCTION = "CONSTRUCTION"
    CONSUMER_ELECTRONICS = "CONSUMER_ELECTRONICS"
    CONSUMER_GOODS = "CONSUMER_GOODS"
    CONSUMER_SERVICES = "CONSUMER_SERVICES"
    COSMETICS = "COSMETICS"
    DAIRY = "DAIRY"
    DEFENSE_SPACE = "DEFENSE_SPACE"
    DESIGN = "DESIGN"
    EDUCATION_MANAGEMENT = "EDUCATION_MANAGEMENT"
    E_LEARNING = "E_LEARNING"
    ELECTRICAL_ELECTRONIC_MANUFACTURING = "ELECTRICAL_ELECTRONIC_MANUFACTURING"
    ENTERTAINMENT = "ENTERTAINMENT"
    ENVIRONMENTAL_SERVICES = "ENVIRONMENTAL_SERVICES"
    EVENTS_SERVICES = "EVENTS_SERVICES"
    EXECUTIVE_OFFICE = "EXECUTIVE_OFFICE"
    FACILITIES_SERVICES = "FACILITIES_SERVICES"
    FARMING = "FARMING"
    FINANCIAL_SERVICES = "FINANCIAL_SERVICES"
    FINE_ART = "FINE_ART"
    FISHERY = "FISHERY"
    FOOD_BEVERAGES = "FOOD_BEVERAGES"
    FOOD_PRODUCTION = "FOOD_PRODUCTION"
    FUND_RAISING = "FUND_RAISING"
    FURNITURE = "FURNITURE"
    GAMBLING_CASINOS = "GAMBLING_CASINOS"
    GLASS_CERAMICS_CONCRETE = "GLASS_CERAMICS_CONCRETE"
    GOVERNMENT_ADMINISTRATION = "GOVERNMENT_ADMINISTRATION"
    GOVERNMENT_RELATIONS = "GOVERNMENT_RELATIONS"
    GRAPHIC_DESIGN = "GRAPHIC_DESIGN"
    HEALTH_WELLNESS_AND_FITNESS = "HEALTH_WELLNESS_AND_FITNESS"
    HIGHER_EDUCATION = "HIGHER_EDUCATION"
    HOSPITAL_HEALTH_CARE = "HOSPITAL_HEALTH_CARE"
    HOSPITALITY = "HOSPITALITY"
    HUMAN_RESOURCES = "HUMAN_RESOURCES"
    IMPORT_AND_EXPORT = "IMPORT_AND_EXPORT"
    INDIVIDUAL_FAMILY_SERVICES = "INDIVIDUAL_FAMILY_SERVICES"
    INDUSTRIAL_AUTOMATION = "INDUSTRIAL_AUTOMATION"
    INFORMATION_SERVICES = "INFORMATION_SERVICES"
    INFORMATION_TECHNOLOGY_AND_SERVICES = "INFORMATION_TECHNOLOGY_AND_SERVICES"
    INSURANCE = "INSURANCE"
    INTERNATIONAL_AFFAIRS = "INTERNATIONAL_AFFAIRS"
    INTERNATIONAL_TRADE_AND_DEVELOPMENT = "INTERNATIONAL_TRADE_AND_DEVELOPMENT"
    INVESTMENT_BANKING = "INVESTMENT_BANKING"
    INVESTMENT_MANAGEMENT = "INVESTMENT_MANAGEMENT"
    JUDICIARY = "JUDICIARY"
    LAW_ENFORCEMENT = "LAW_ENFORCEMENT"
    LAW_PRACTICE = "LAW_PRACTICE"
    LEGAL_SERVICES = "LEGAL_SERVICES"
    LEGISLATIVE_OFFICE = "LEGISLATIVE_OFFICE"
    LEISURE_TRAVEL_TOURISM = "LEISURE_TRAVEL_TOURISM"
    LIBRARIES = "LIBRARIES"
    LOGISTICS_AND_SUPPLY_CHAIN = "LOGISTICS_AND_SUPPLY_CHAIN"
    LUXURY_GOODS_JEWELRY = "LUXURY_GOODS_JEWELRY"
    MACHINERY = "MACHINERY"
    MANAGEMENT_CONSULTING = "MANAGEMENT_CONSULTING"
    MARITIME = "MARITIME"
    MARKET_RESEARCH = "MARKET_RESEARCH"
    MARKETING_AND_ADVERTISING = "MARKETING_AND_ADVERTISING"
    MECHANICAL_OR_INDUSTRIAL_ENGINEERING = "MECHANICAL_OR_INDUSTRIAL_ENGINEERING"
    MEDIA_PRODUCTION = "MEDIA_PRODUCTION"
    MEDICAL_DEVICES = "MEDICAL_DEVICES"
    MEDICAL_PRACTICE = "MEDICAL_PRACTICE"
    MENTAL_HEALTH_CARE = "MENTAL_HEALTH_CARE"
    MILITARY = "MILITARY"
    MINING_METALS = "MINING_METALS"
    MOTION_PICTURES_AND_FILM = "MOTION_PICTURES_AND_FILM"
    MUSEUMS_AND_INSTITUTIONS = "MUSEUMS_AND_INSTITUTIONS"
    MUSIC = "MUSIC"
    NANOTECHNOLOGY = "NANOTECHNOLOGY"
    NEWSPAPERS = "NEWSPAPERS"
    NON_PROFIT_ORGANIZATION_MANAGEMENT = "NON_PROFIT_ORGANIZATION_MANAGEMENT"
    OIL_ENERGY = "OIL_ENERGY"
    ONLINE_MEDIA = "ONLINE_MEDIA"
    OUTSOURCING_OFFSHORING = "OUTSOURCING_OFFSHORING"
    PACKAGE_FREIGHT_DELIVERY = "PACKAGE_FREIGHT_DELIVERY"
    PACKAGING_AND_CONTAINERS = "PACKAGING_AND_CONTAINERS"
    PAPER_FOREST_PRODUCTS = "PAPER_FOREST_PRODUCTS"
    PERFORMING_ARTS = "PERFORMING_ARTS"
    PHARMACEUTICALS = "PHARMACEUTICALS"
    PHILANTHROPY = "PHILANTHROPY"
    PHOTOGRAPHY = "PHOTOGRAPHY"
    PLASTICS = "PLASTICS"
    POLITICAL_ORGANIZATION = "POLITICAL_ORGANIZATION"
    PRIMARY_SECONDARY_EDUCATION = "PRIMARY_SECONDARY_EDUCATION"
    PRINTING = "PRINTING"
    PROFESSIONAL_TRAINING_COACHING = "PROFESSIONAL_TRAINING_COACHING"
    PROGRAM_DEVELOPMENT = "PROGRAM_DEVELOPMENT"
    PUBLIC_POLICY = "PUBLIC_POLICY"
    PUBLIC_RELATIONS_AND_COMMUNICATIONS = "PUBLIC_RELATIONS_AND_COMMUNICATIONS"
    PUBLIC_SAFETY = "PUBLIC_SAFETY"
    PUBLISHING = "PUBLISHING"
    RAILROAD_MANUFACTURE = "RAILROAD_MANUFACTURE"
    RANCHING = "RANCHING"
    REAL_ESTATE = "REAL_ESTATE"
    RECREATIONAL_FACILITIES_AND_SERVICES = "RECREATIONAL_FACILITIES_AND_SERVICES"
    RELIGIOUS_INSTITUTIONS = "RELIGIOUS_INSTITUTIONS"
    RENEWABLES_ENVIRONMENT = "RENEWABLES_ENVIRONMENT"
    RESEARCH = "RESEARCH"
    RESTAURANTS = "RESTAURANTS"
    RETAIL = "RETAIL"
    SECURITY_AND_INVESTIGATIONS = "SECURITY_AND_INVESTIGATIONS"
    SEMICONDUCTORS = "SEMICONDUCTORS"
    SHIPBUILDING = "SHIPBUILDING"
    SPORTING_GOODS = "SPORTING_GOODS"
    SPORTS = "SPORTS"
    STAFFING_AND_RECRUITING = "STAFFING_AND_RECRUITING"
    SUPERMARKETS = "SUPERMARKETS"
    TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
    TEXTILES = "TEXTILES"
    THINK_TANKS = "THINK_TANKS"
    TOBACCO = "TOBACCO"
    TRANSLATION_AND_LOCALIZATION = "TRANSLATION_AND_LOCALIZATION"
    TRANSPORTATION_TRUCKING_RAILROAD = "TRANSPORTATION_TRUCKING_RAILROAD"
    UTILITIES = "UTILITIES"
    VENTURE_CAPITAL_PRIVATE_EQUITY = "VENTURE_CAPITAL_PRIVATE_EQUITY"
    VETERINARY = "VETERINARY"
    WAREHOUSING = "WAREHOUSING"
    WHOLESALE = "WHOLESALE"
    WINE_AND_SPIRITS = "WINE_AND_SPIRITS"
    WIRELESS = "WIRELESS"
    WRITING_AND_EDITING = "WRITING_AND_EDITING"
    MOBILE_GAMES = "MOBILE_GAMES"


class HubspotDealType(str, Enum):
    NEW_BUSINESS = "newbusiness"
    EXISTING_BUSINESS = "existingbusiness"


class HubspotDealPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class HubspotDefaultDealStage(str, Enum):
    APPOINTMENT_SCHEDULED = "appointmentscheduled"
    QUALIFIED_TO_BUY = "qualifiedtobuy"
    PRESENTATION_SCHEDULED = "presentationscheduled"
    DECISION_MAKER_BOUGHT_IN = "decisionmakerboughtin"
    CONTRACT_SENT = "contractsent"
    CLOSED_WON = "closedwon"
    CLOSED_LOST = "closedlost"


class HubspotActivityType(str, Enum):
    NOTE = "note"
    CALL = "call"
    EMAIL = "email"
    MEETING = "meeting"
    TASK = "task"
    COMMUNICATION = "communication"


class HubspotCallDirection(str, Enum):
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"


class HubspotEmailStatus(str, Enum):
    BOUNCED = "BOUNCED"
    FAILED = "FAILED"
    SCHEDULED = "SCHEDULED"
    SENDING = "SENDING"
    SENT = "SENT"


class HubspotEmailDirection(str, Enum):
    EMAIL = "EMAIL"
    INCOMING_EMAIL = "INCOMING_EMAIL"
    FORWARDED_EMAIL = "FORWARDED_EMAIL"


class HubspotMeetingOutcome(str, Enum):
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    RESCHEDULED = "RESCHEDULED"
    NO_SHOW = "NO_SHOW"
    CANCELED = "CANCELED"


class HubspotCommunicationChannel(str, Enum):
    SMS = "SMS"
    WHATS_APP = "WHATS_APP"
    LINKEDIN_MESSAGE = "LINKEDIN_MESSAGE"
    PHYSICAL_MAIL = "PHYSICAL_MAIL"
    CUSTOM_CHANNEL_CONVERSATION = "CUSTOM_CHANNEL_CONVERSATION"


class HubspotCommunicationLoggedFrom(str, Enum):
    CRM = "CRM"
    CONVERSATIONS = "CONVERSATIONS"


class HubspotSortOrder(str, Enum):
    LATEST_MODIFIED = "LATEST_MODIFIED"
    OLDEST_MODIFIED = "OLDEST_MODIFIED"
    ALPHABETICAL = "ALPHABETICAL"


class HubspotAssociationType(int, Enum):
    """HubSpot-defined association type IDs for activities and CRM objects."""

    # Standard CRM object associations (bidirectional)
    CONTACT_TO_COMPANY = 1
    COMPANY_TO_CONTACT = 2
    DEAL_TO_CONTACT = 3
    CONTACT_TO_DEAL = 4
    DEAL_TO_COMPANY = 5
    COMPANY_TO_DEAL = 6

    # Activity to Contact associations
    NOTE_TO_CONTACT = 202
    CALL_TO_CONTACT = 194
    EMAIL_TO_CONTACT = 198
    MEETING_TO_CONTACT = 200

    # Standard engagement/activity associations (HubSpot-defined)
    ENGAGEMENT_TO_CONTACT = 10  # Any activity → contact
    ENGAGEMENT_TO_COMPANY = 8  # Any activity → company
    ENGAGEMENT_TO_DEAL = 12  # Any activity → deal

    # Legacy specific activity associations (kept for compatibility)
    COMMUNICATION_TO_CONTACT = 10
    COMMUNICATION_TO_COMPANY = 8
    COMMUNICATION_TO_DEAL = 12

    # Activity to Company associations
    NOTE_TO_COMPANY = 190
    CALL_TO_COMPANY = 182
    EMAIL_TO_COMPANY = 186
    MEETING_TO_COMPANY = 188

    # Activity to Deal associations
    NOTE_TO_DEAL = 214
    CALL_TO_DEAL = 206
    EMAIL_TO_DEAL = 210
    MEETING_TO_DEAL = 212
