from .Prime import *
from .rest.rest_func import *
from .rest.statistics import *
from .digits import *
from .core import *
from .rest.Checking import *
from .Closeness import *
from .ratio import *
from .hard_math import *
from .machine_computing import *