"""ACP Protocol implementation."""

from .jsonrpc import (
    JSONRPCRequest,
    JSONRPCNotification,
    JSONRPCResponse,
    JSONRPCError,
    JSONRPCMessage,
    parse_message,
    create_request,
    create_notification,
    create_response,
    create_error_response,
    RequestId,
)
from .constants import (
    METHOD_INITIALIZE,
    METHOD_AUTHENTICATE,
    METHOD_SESSION_NEW,
    METHOD_SESSION_LOAD,
    METHOD_SESSION_PROMPT,
    METHOD_SESSION_UPDATE,
    METHOD_SESSION_SET_MODE,
    METHOD_SESSION_CANCEL,
    METHOD_SESSION_REQUEST_PERMISSION,
    METHOD_FS_READ_TEXT_FILE,
    METHOD_FS_WRITE_TEXT_FILE,
    METHOD_TERMINAL_CREATE,
    METHOD_TERMINAL_OUTPUT,
    METHOD_TERMINAL_RELEASE,
    METHOD_TERMINAL_WAIT_FOR_EXIT,
    METHOD_TERMINAL_KILL,
)

__all__ = [
    # JSON-RPC
    "JSONRPCRequest",
    "JSONRPCNotification",
    "JSONRPCResponse",
    "JSONRPCError",
    "JSONRPCMessage",
    "parse_message",
    "create_request",
    "create_notification",
    "create_response",
    "create_error_response",
    "RequestId",
    # Method constants
    "METHOD_INITIALIZE",
    "METHOD_AUTHENTICATE",
    "METHOD_SESSION_NEW",
    "METHOD_SESSION_LOAD",
    "METHOD_SESSION_PROMPT",
    "METHOD_SESSION_UPDATE",
    "METHOD_SESSION_SET_MODE",
    "METHOD_SESSION_CANCEL",
    "METHOD_SESSION_REQUEST_PERMISSION",
    "METHOD_FS_READ_TEXT_FILE",
    "METHOD_FS_WRITE_TEXT_FILE",
    "METHOD_TERMINAL_CREATE",
    "METHOD_TERMINAL_OUTPUT",
    "METHOD_TERMINAL_RELEASE",
    "METHOD_TERMINAL_WAIT_FOR_EXIT",
    "METHOD_TERMINAL_KILL",
]
