def test_placeholder():
    from plugins.module_utils.defaults.main import \
        OPN_MOD_ARGS, BUILTIN_ALIASES, BUILTIN_INTERFACE_ALIASES_REG, STATE_ONLY_MOD_ARG, \
        EN_ONLY_MOD_ARG, STATE_MOD_ARG, RELOAD_MOD_ARG, RELOAD_MOD_ARG_DEF_FALSE, DEBUG_CONFIG, \
        CONNECTION_TEST_TIMEOUT
