class EnvNames:
    IS_REST_SERVICE_ENABLED = 'IS_EMBEDDING_STORE_REST_SERVICE_ENABLED'
    HOST = 'EMBEDDING_STORE_SERVICE_HOST'
    PORT = 'EMBEDDING_STORE_SERVICE_PORT'
    LOCAL_CACHE_PATH = 'EMBEDDING_STORE_LOCAL_CACHE_PATH'
